.TH "ADCSCAN" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCSCAN
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBADCSCAN::DAO54SH\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBADCSCAN::DAO32SH\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBADCSCAN::DAO10SH\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBADCSCAN::ENADCBUF\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBADCSCAN::ENSCAN\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBADCSCAN::__pad0__\fP: 3"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 404 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
