.TH "pac_foc/pac55xx/board/board.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/board/board.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config_board\&.h'\fP
.br
\fC#include 'board_pac5523evk1\&.h'\fP
.br
\fC#include 'device_5523\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAMPGAIN_AIO6\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AMPGAIN_AIO6   0"

.PP
Definition at line 73 of file board\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
