.TH "pac_foc/pac55xx/board/board_pac5556evk1.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/board/board_pac5556evk1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'pac5xxx_tile_signal_manager\&.h'\fP
.br
\fC#include 'pac5xxx_driver_tile\&.h'\fP
.br
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br
\fC#include 'pac5xxx_driver_timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_diff_amp_gain\fP (void)"
.br
.ti -1c
.RI "void \fBconfig_seq_foc\fP (void)"
.br
.ti -1c
.RI "void \fBinit_emux\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void config_seq_foc (void)"

.PP
Definition at line 55 of file board_pac5556evk1\&.c\&.
.PP
.nf
56 {
57     Struct_Motor* motor_ptr = &motor;
58     unsigned char value;
59 
60     // Configure ADC input pin PG7(AD0) to read analog input from AFE and PF6(AD6) to read VBUS
61     pac5xxx_adc_config_io(0x01 | 0x40);                 // PG7 | PF6
62 
63     PAC55XX_ADC->DTSETRIGENT8TO11\&.FORCE8 = 0;            // Reset to 0
64     PAC55XX_ADC->DTSETRIGENT8TO11\&.TRIG8CFGIDX = 0;       // DTSE Trigger 0 Sequence Configuration Entry Index
65     PAC55XX_ADC->DTSETRIGENT8TO11\&.TRIG8EDGE = 2;         // Trigger falling edge
66 
67     // Dummy conversions are added to each sequence to work around a bug in the DTSE
68     pac5xxx_dtse_seq_config(0, ADC6, EMUX_AIO10 | DIFFAMPS_HOLD, 0,           0);    // Convert Vout, then change CAFE MUX to M1-Iu
69     pac5xxx_dtse_seq_config(1, ADC0, EMUX_AIO10 | DIFFAMPS_HOLD, 0,           0);    // Dummy Conversion, then change CAFE MUX to M1-Iu
70     pac5xxx_dtse_seq_config(2, ADC0, EMUX_AIO32 | DIFFAMPS_HOLD, 0,           0);    // Convert M1-Iu, then change CAFE MUX to M1-Iv
71     pac5xxx_dtse_seq_config(3, ADC0, EMUX_AIO32 | DIFFAMPS_HOLD, 0,           0);    // Dummy Conversion, then change CAFE MUX to M1-Iv
72     pac5xxx_dtse_seq_config(4, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0,           0);    // Convert M1-Iv, then change CAFE MUX to M1-Iv
73     pac5xxx_dtse_seq_config(5, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0,           0);    // Dummy Conversion, then change CAFE MUX to M1-Iw
74     pac5xxx_dtse_seq_config(6, ADC0, EMUX_AB11, ADC_IRQ0_EN, 0);                     // Convert M1-Iw, then change CAFE MUX to M1-Iu, generate ADC interrupt
75 
76     pac5xxx_dtse_seq_config(7, ADC0, EMUX_AB11,                  0,           0);    // Dummy Conversion, then change CAFE MUX to VMS AB11
77     pac5xxx_dtse_seq_config(8, ADC0, EMUX_AB11,                  0,           0);    // Convert VMS, then change CAFE MUX to VMS AB11
78 
79     pac5xxx_dtse_seq_config(9, ADC6, EMUX_AIO10,                 0,           0);    // Dummy conversion, then change CAFE MUX to M1-Iu
80     pac5xxx_dtse_seq_config(10, ADC6, EMUX_AIO10,                0,     SEQ_END);    // Convert VM BUS, then change CAFE MUX to M1-Iu
81 
82     // Configure Power Mux so AB11 = Vout(Vbus)
83     value = pac5xxx_tile_register_read(ADDR_PWRCTL);
84     value = (value & 0xC7) | (0x07 << 3);
85     pac5xxx_tile_register_write(ADDR_PWRCTL, value);     // Select PWRMON Mux = Vbus
86 }
.fi
.PP
References ADC0, ADC6, ADC_IRQ0_EN, ADDR_PWRCTL, DIFFAMPS_HOLD, EMUX_AB11, EMUX_AIO10, EMUX_AIO32, EMUX_AIO54, PAC55XX_ADC, pac5xxx_adc_config_io(), pac5xxx_dtse_seq_config(), pac5xxx_tile_register_read(), pac5xxx_tile_register_write(), and SEQ_END\&.
.SS "void init_diff_amp_gain (void)"

.PP
Definition at line 22 of file board_pac5556evk1\&.c\&.
.PP
.nf
23 {
24     Struct_Motor* motor_ptr = &motor;
25     
26     pac5xxx_tile_register_write(ADDR_CFGAIO0, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app\&.iphase_amp_gain << 3)));
27 #ifdef ENABLE_CBC_CURRENT_LIMIT
28     pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
29 #else
30     pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
31 #endif    
32 
33     pac5xxx_tile_register_write(ADDR_CFGAIO2, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app\&.iphase_amp_gain << 3)));
34 #ifdef ENABLE_CBC_CURRENT_LIMIT    
35     pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
36 #else    
37     pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
38 #endif    
39 
40     pac5xxx_tile_register_write(ADDR_CFGAIO4, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app\&.iphase_amp_gain << 3)));
41 #ifdef ENABLE_CBC_CURRENT_LIMIT     
42     pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
43 #else    
44     pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
45 #endif    
46 
47     pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_IO << 6) | (AIO6789_OPT_INPUT << 4) | (AIO6789_POL_AH << 3) | AIO6789_MUX_DEFAULT));    // IO Mode
48 //    pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT));                          // Gain Mode
49 
50     pac5xxx_tile_register_write(ADDR_CFGAIO7, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app\&.vphase_amp_gain << 3)));
51     pac5xxx_tile_register_write(ADDR_CFGAIO8, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app\&.vphase_amp_gain << 3)));
52     pac5xxx_tile_register_write(ADDR_CFGAIO9, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app\&.vphase_amp_gain << 3)));
53 }
.fi
.PP
References ADDR_CFGAIO0, ADDR_CFGAIO1, ADDR_CFGAIO2, ADDR_CFGAIO3, ADDR_CFGAIO4, ADDR_CFGAIO5, ADDR_CFGAIO6, ADDR_CFGAIO7, ADDR_CFGAIO8, ADDR_CFGAIO9, AIO50_GAIN_X1, AIO50_HPCOMP_1US, AIO50_HPROT_PR, AIO50_LPCOMP_2US, AIO50_LPROT_PR, AIO50_LPROT_PR1PR2, AIO50_MODE_DIFFAMP, AIO50_OFFSET_ENABLED, AIO6789_GAIN_X1, AIO6789_MODE_GAIN, AIO6789_MODE_IO, AIO6789_MUX_DEFAULT, AIO6789_OPT_INPUT, AIO6789_POL_AH, and pac5xxx_tile_register_write()\&.
.SS "void init_emux (void)"

.PP
Definition at line 176 of file board_pac5556evk1\&.c\&.
.PP
.nf
177 {
178 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
