pac_foc/pac55xx/board/board_pac5556evk1_1shunt.c
NAME
pac_foc/pac55xx/board/board_pac5556evk1_1shunt.c
SYNOPSIS
#include 'motor_struct.h'
#include 'pac5xxx_tile_signal_manager.h'
#include 'pac5xxx_driver_tile.h'
#include 'pac5xxx_driver_adc.h'
#include 'pac5xxx_driver_timer.h'
Functions
void init_diff_amp_gain (void)
void config_seq_foc (void)
void init_emux (void)
Function Documentation
void config_seq_foc (void)
Definition at line 55 of file board_pac5556evk1_1shunt.c.
{
    unsigned char value;
    // Configure ADC input pin PG7(AD0) to read analog input from AFE and PF6(AD6) to read VBUS
    pac5xxx_adc_config_io(0x01 | 0x40); // PG7 | PF6
    PAC55XX_ADC->DTSETRIGENT8TO11.FORCE8 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG8CFGIDX = 0; // DTSE Trigger 0 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG8EDGE = 2; // Trigger falling edge
    // Dummy conversions are added to each sequence to work around a bug in the DTSE
    pac5xxx_dtse_seq_config(0, ADC0, EMUX_AIO32, 0, 0); // Convert M1_Iu, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(1, ADC0, EMUX_AIO32, 0, SEQ_END); // Dummy Conversion, then change CAFE MUX to M1-I
#if (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_1) || !defined(ENABLE_POWERMEASURE)
    #ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    PAC55XX_ADC->DTSETRIGENT8TO11.FORCE9 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG9CFGIDX = 3; // DTSE Trigger 1 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG9EDGE = 2; // Trigger falling edge
    pac5xxx_dtse_seq_config(3, ADC0, EMUX_AIO32, 0, 0); // Convert M1-I, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(4, ADC0, EMUX_AIO32, ADC_IRQ0_EN, 0); // Dummy Conversion, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(5, ADC6, EMUX_AIO32, 0, 0); // Dummy Conversion, read vbus, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(6, ADC6, EMUX_AB11, 0, 0); // Dummy Conversion, read vbus, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(7, ADC0, EMUX_AB11, 0, 0); // Dummy Conversion, read vms, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(8, ADC0, EMUX_AB11, 0, 0); // Dummy Conversion, read vms, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(9, ADC0, EMUX_AIO32, 0, SEQ_END); // Dummy Conversion, then change CAFE MUX to M1-I
    #else //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    // AS1 configuration
    PAC55XX_ADC->DTSETRIGENT8TO11.FORCE9 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG9CFGIDX = 3; // DTSE Trigger 1 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT8TO11.TRIG9EDGE = 1; // Trigger rising edge
    pac5xxx_dtse_seq_config(3, ADC0, EMUX_AIO32, 0, 0); // Convert M1-I, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(4, ADC0, EMUX_AIO32, ADC_IRQ0_EN, 0); // Dummy Conversion, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(5, ADC6, EMUX_AIO32, 0, 0); // Dummy Conversion, read vbus, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(6, ADC6, EMUX_AB11, 0, 0); // Convert vbs, read vbus, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(7, ADC0, EMUX_AB11, 0, 0); // Dummy Conversion, read vms, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(8, ADC0, EMUX_AB11, 0, 0); // Convert vms, read vms, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(9, ADC0, EMUX_AIO32, 0, SEQ_END); // Dummy Conversion, then change CAFE MUX to M1-I
    #endif //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
#elif (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_2)
#error: POWER_MEASURE_METHOD_2 not supported BOARD_EP5223LVM1_1_1SHUNT
#endif
    // Configure Power Mux so AB11 = Vout(Vbus)
    value = pac5xxx_tile_register_read(ADDR_PWRCTL);
    value = (value & 0xC7) | (0x07 << 3);
    pac5xxx_tile_register_write(ADDR_PWRCTL, value); // Select PWRMON Mux = Vbus
}
References ADC0, ADC6, ADC_IRQ0_EN, ADDR_PWRCTL, EMUX_AB11, EMUX_AIO32, PAC55XX_ADC, pac5xxx_adc_config_io(), pac5xxx_dtse_seq_config(), pac5xxx_tile_register_read(), pac5xxx_tile_register_write(), and SEQ_END.
void init_diff_amp_gain (void)
Definition at line 22 of file board_pac5556evk1_1shunt.c.
{
    Struct_Motor* motor_ptr = &motor;
    
    pac5xxx_tile_register_write(ADDR_CFGAIO0, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO2, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO4, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_HPROT_PR << 5) | (AIO50_LPROT_PR << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_IO << 6) | (AIO6789_OPT_INPUT << 4) | (AIO6789_POL_AH << 3) | AIO6789_MUX_DEFAULT)); // IO Mode
// pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT)); // Gain Mode
    pac5xxx_tile_register_write(ADDR_CFGAIO7, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO8, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO9, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
}
References ADDR_CFGAIO0, ADDR_CFGAIO1, ADDR_CFGAIO2, ADDR_CFGAIO3, ADDR_CFGAIO4, ADDR_CFGAIO5, ADDR_CFGAIO6, ADDR_CFGAIO7, ADDR_CFGAIO8, ADDR_CFGAIO9, AIO50_GAIN_X1, AIO50_HPCOMP_1US, AIO50_HPROT_PR, AIO50_LPCOMP_2US, AIO50_LPROT_PR, AIO50_LPROT_PR1PR2, AIO50_MODE_DIFFAMP, AIO50_OFFSET_ENABLED, AIO6789_GAIN_X1, AIO6789_MODE_GAIN, AIO6789_MODE_IO, AIO6789_MUX_DEFAULT, AIO6789_OPT_INPUT, AIO6789_POL_AH, and pac5xxx_tile_register_write().
void init_emux (void)
Definition at line 180 of file board_pac5556evk1_1shunt.c.
{
}
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.