pac_foc/pac55xx/board/board_pac5526evk1.c
NAME
pac_foc/pac55xx/board/board_pac5526evk1.c
SYNOPSIS
#include 'motor_struct.h'
#include 'pac5xxx_tile_signal_manager.h'
#include 'pac5xxx_driver_tile.h'
#include 'pac5xxx_driver_adc.h'
#include 'pac5xxx_driver_timer.h'
Functions
void init_diff_amp_gain (void)
void config_seq_foc (void)
void init_emux (void)
Function Documentation
void config_seq_foc (void)
Definition at line 46 of file board_pac5526evk1.c.
{
    // Configure ADC input pin PG7(AD0) to read analog input from AFE and PF6(AD6) to read VBUS
    pac5xxx_adc_config_io(0x01 | 0x40); // PG7 | PF6
    PAC55XX_ADC->DTSETRIGENT0TO3.FORCE0 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG0CFGIDX = 0; // DTSE Trigger 0 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG0EDGE = 2; // Trigger falling edge
    
    // Dummy conversions are added to each sequence to work around a bug in the DTSE
    pac5xxx_dtse_seq_config(0, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0, 0); // Convert M1_Iu, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(1, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0, 0); // Dummy Conversion, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(2, ADC0, EMUX_AIO54, 0, SEQ_END); // Dummy Conversion, then change CAFE MUX to M1-I
    
#if (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_1) || !defined(ENABLE_POWERMEASURE)
    #ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    PAC55XX_ADC->DTSETRIGENT0TO3.FORCE1 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG1CFGIDX = 3; // DTSE Trigger 1 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG1EDGE = 2; // Trigger falling edge
    pac5xxx_dtse_seq_config(3, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0, 0); // Convert M1-I, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(4, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, ADC_IRQ0_EN, 0); // Dummy Conversion, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(5, ADC6, EMUX_AIO54, 0, 0); // Convert Iw, then change CAFE MUX vms, generate ADC interrupt
    pac5xxx_dtse_seq_config(6, ADC6, EMUX_AB13, 0, 0); // Dummy Conversion, change CAFE MUX to vms
    pac5xxx_dtse_seq_config(7, ADC0, EMUX_AB13, 0, 0); // Dummy Conversion, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(8, ADC0, EMUX_AB13, 0, 0); // Convert vms
    pac5xxx_dtse_seq_config(9, ADC0, EMUX_AIO54, 0, SEQ_END); // Convert vms, then change CAFE MUX to M1-Iu
    #else //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    // AS1 configuration
    PAC55XX_ADC->DTSETRIGENT0TO3.FORCE1 = 0; // Reset to 0
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG1CFGIDX = 3; // DTSE Trigger 1 Sequence Configuration Entry Index
    PAC55XX_ADC->DTSETRIGENT0TO3.TRIG1EDGE = 1; // Trigger rising edge
    pac5xxx_dtse_seq_config(3, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, 0, 0); // Convert M1-I, then change CAFE MUX to M1-I
    pac5xxx_dtse_seq_config(4, ADC0, EMUX_AIO54 | DIFFAMPS_HOLD, ADC_IRQ0_EN, 0); // Dummy Conversion, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(5, ADC6, EMUX_AIO54, 0, 0); // Convert Iw, then change CAFE MUX vms, generate ADC interrupt
    pac5xxx_dtse_seq_config(6, ADC6, EMUX_AB13, 0, 0); // Dummy Conversion, change CAFE MUX to vms
    pac5xxx_dtse_seq_config(7, ADC0, EMUX_AB13, 0, 0); // Dummy Conversion, then change CAFE MUX to vms
    pac5xxx_dtse_seq_config(8, ADC0, EMUX_AB13, 0, 0); // Convert vms
    pac5xxx_dtse_seq_config(9, ADC0, EMUX_AIO54, 0, SEQ_END); // Convert vms, then change CAFE MUX to M1-Iu
    #endif //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
#elif (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_2)
#error: POWER_MEASURE_METHOD_2 not supported BOARD_EP5223LVM1_1_1SHUNT
#endif
}
References ADC0, ADC6, ADC_IRQ0_EN, DIFFAMPS_HOLD, EMUX_AIO54, PAC55XX_ADC, pac5xxx_adc_config_io(), pac5xxx_dtse_seq_config(), and SEQ_END.
void init_diff_amp_gain (void)
Definition at line 22 of file board_pac5526evk1.c.
{
    Struct_Motor* motor_ptr = &motor;
    
    pac5xxx_tile_register_write(ADDR_CFGAIO0, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3)) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)) & (~AIO50_LPCOMP_DISABLE));
    // Disable HPROT
    pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_LPROT_PR1PR2 << 4)| (AIO50_OFFSET_ENABLED << 3)) & (~0x03));
    pac5xxx_tile_register_write(ADDR_CFGAIO2, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3)) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)) & (~AIO50_LPCOMP_DISABLE));
    // Disable HPROT
    pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)) & (~0x03));
    pac5xxx_tile_register_write(ADDR_CFGAIO4, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
    // Disable HPROT
    pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_LPROT_PR1PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)) & (~0x03));
    pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_IO << 6) | (AIO6789_OPT_INPUT << 4) | (AIO6789_POL_AH << 3) | AIO6789_MUX_DEFAULT)); // IO Mode
// pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT)); // Gain Mode
    pac5xxx_tile_register_write(ADDR_CFGAIO7, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO8, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO9, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
}
References ADDR_CFGAIO0, ADDR_CFGAIO1, ADDR_CFGAIO2, ADDR_CFGAIO3, ADDR_CFGAIO4, ADDR_CFGAIO5, ADDR_CFGAIO6, ADDR_CFGAIO7, ADDR_CFGAIO8, ADDR_CFGAIO9, AIO50_GAIN_X1, AIO50_LPCOMP_2US, AIO50_LPCOMP_DISABLE, AIO50_LPROT_PR1PR2, AIO50_MODE_DIFFAMP, AIO50_OFFSET_ENABLED, AIO6789_GAIN_X1, AIO6789_MODE_GAIN, AIO6789_MODE_IO, AIO6789_MUX_DEFAULT, AIO6789_OPT_INPUT, AIO6789_POL_AH, and pac5xxx_tile_register_write().
void init_emux (void)
Definition at line 164 of file board_pac5526evk1.c.
{
}
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.