.TH "pac_foc/pac55xx/pac55xx_sdk Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBboot_gcc\fP"
.br
.ti -1c
.RI "directory \fBboot_keil\fP"
.br
.ti -1c
.RI "directory \fBdevice\fP"
.br
.ti -1c
.RI "directory \fBdriver\fP"
.br
.ti -1c
.RI "directory \fBperipheral\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpac5xxx_sdk_version\&.h\fP"
.br
.in -1c
