.TH "CCTL_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCTL_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_timers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCMODE\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCINTEN\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCINTEDGE\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCOUTINV\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCLATCH\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCFORCE\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCCINTSKIP\fP: 4"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 20"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 133 of file pac5xxx_timers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t CCTL_TYPEDEF::__pad0__"

.PP
Definition at line 144 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCFORCE"

.PP
Definition at line 142 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCINTEDGE"

.PP
Definition at line 139 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCINTEN"

.PP
Definition at line 138 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCINTSKIP"

.PP
Definition at line 143 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCLATCH"

.PP
Definition at line 141 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCMODE"

.PP
Definition at line 137 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::CCOUTINV"

.PP
Definition at line 140 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTL_TYPEDEF::w"

.PP
Definition at line 134 of file pac5xxx_timers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
