.TH "CCTR_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCTR_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_timers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCAP1\fP: 16"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCAP2\fP: 16"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBCTR\fP: 16"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBDELAY\fP: 16"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file pac5xxx_timers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "struct { \&.\&.\&. } "

.SS "\fB__IO\fP uint32_t CCTR_TYPEDEF::CAP1"

.PP
Definition at line 158 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTR_TYPEDEF::CAP2"

.PP
Definition at line 163 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTR_TYPEDEF::CTR"

.PP
Definition at line 174 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTR_TYPEDEF::DELAY"

.PP
Definition at line 180 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t CCTR_TYPEDEF::w"

.PP
Definition at line 150 of file pac5xxx_timers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
