.TH "CFGAIO8" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFGAIO8
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBCFGAIO8::MUX8\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBCFGAIO8::POL8\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBCFGAIO8::OPT8\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBCFGAIO8::MODE8\fP: 2"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 354 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
