.TH "CMSIS_core_register" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_register \- Defines and Type Definitions
.PP
 \- Type definitions and defines for Cortex-M processor based devices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStatus and Control Registers\fP"
.br
.RI "Core Register type definitions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type definitions and defines for Cortex-M processor based devices\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
