.TH "CMSIS_TPI" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_TPI \- Trace Port Interface (TPI)
.PP
 \- Type definitions for the Trace Port Interface (TPI)  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCore Debug Registers (CoreDebug)\fP"
.br
.RI "Type definitions for the Core Debug Registers\&. "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTPI_Type\fP"
.br
.RI "Structure type to access the Trace Port Interface Register (TPI)\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL << \fBTPI_ACPR_PRESCALER_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL << \fBTPI_SPPR_TXMODE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL << \fBTPI_FFSR_FlInProg_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL << \fBTPI_TRIGGER_TRIGGER_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM0_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY_Msk\fP   (0x1UL << \fBTPI_ITATBCTR2_ATREADY_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM0_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY_Msk\fP   (0x1UL << \fBTPI_ITATBCTR0_ATREADY_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x1UL << \fBTPI_ITCTRL_Mode_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL << \fBTPI_DEVID_NrTraceInput_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_SubType_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   4"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Trace Port Interface (TPI) 


.SH "Macro Definition Documentation"
.PP 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL << \fBTPI_ACPR_PRESCALER_Pos\fP)"
TPI ACPR: PRESCALER Mask 
.PP
Definition at line 934 of file core_cm4\&.h\&.
.SS "#define TPI_ACPR_PRESCALER_Pos   0"
TPI ACPR: PRESCALER Position 
.PP
Definition at line 933 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_AsynClkIn_Msk   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
TPI DEVID: AsynClkIn Mask 
.PP
Definition at line 1034 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_AsynClkIn_Pos   5"
TPI DEVID: AsynClkIn Position 
.PP
Definition at line 1033 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.PP
Definition at line 1025 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_MANCVALID_Pos   10"
TPI DEVID: MANCVALID Position 
.PP
Definition at line 1024 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_MinBufSz_Msk   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
TPI DEVID: MinBufSz Mask 
.PP
Definition at line 1031 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_MinBufSz_Pos   6"
TPI DEVID: MinBufSz Position 
.PP
Definition at line 1030 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x1FUL << \fBTPI_DEVID_NrTraceInput_Pos\fP)"
TPI DEVID: NrTraceInput Mask 
.PP
Definition at line 1037 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_NrTraceInput_Pos   0"
TPI DEVID: NrTraceInput Position 
.PP
Definition at line 1036 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.PP
Definition at line 1022 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_NRZVALID_Pos   11"
TPI DEVID: NRZVALID Position 
.PP
Definition at line 1021 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.PP
Definition at line 1028 of file core_cm4\&.h\&.
.SS "#define TPI_DEVID_PTINVALID_Pos   9"
TPI DEVID: PTINVALID Position 
.PP
Definition at line 1027 of file core_cm4\&.h\&.
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.PP
Definition at line 1044 of file core_cm4\&.h\&.
.SS "#define TPI_DEVTYPE_MajorType_Pos   4"
TPI DEVTYPE: MajorType Position 
.PP
Definition at line 1043 of file core_cm4\&.h\&.
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL << \fBTPI_DEVTYPE_SubType_Pos\fP)"
TPI DEVTYPE: SubType Mask 
.PP
Definition at line 1041 of file core_cm4\&.h\&.
.SS "#define TPI_DEVTYPE_SubType_Pos   0"
TPI DEVTYPE: SubType Position 
.PP
Definition at line 1040 of file core_cm4\&.h\&.
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.PP
Definition at line 958 of file core_cm4\&.h\&.
.SS "#define TPI_FFCR_EnFCont_Pos   1"
TPI FFCR: EnFCont Position 
.PP
Definition at line 957 of file core_cm4\&.h\&.
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.PP
Definition at line 955 of file core_cm4\&.h\&.
.SS "#define TPI_FFCR_TrigIn_Pos   8"
TPI FFCR: TrigIn Position 
.PP
Definition at line 954 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL << \fBTPI_FFSR_FlInProg_Pos\fP)"
TPI FFSR: FlInProg Mask 
.PP
Definition at line 951 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FlInProg_Pos   0"
TPI FFSR: FlInProg Position 
.PP
Definition at line 950 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.PP
Definition at line 942 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FtNonStop_Pos   3"
TPI FFSR: FtNonStop Position 
.PP
Definition at line 941 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.PP
Definition at line 948 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_FtStopped_Pos   1"
TPI FFSR: FtStopped Position 
.PP
Definition at line 947 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.PP
Definition at line 945 of file core_cm4\&.h\&.
.SS "#define TPI_FFSR_TCPresent_Pos   2"
TPI FFSR: TCPresent Position 
.PP
Definition at line 944 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM0_Msk   (0xFFUL << \fBTPI_FIFO0_ETM0_Pos\fP)"
TPI FIFO0: ETM0 Mask 
.PP
Definition at line 984 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM0_Pos   0"
TPI FIFO0: ETM0 Position 
.PP
Definition at line 983 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM1_Msk   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
TPI FIFO0: ETM1 Mask 
.PP
Definition at line 981 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM1_Pos   8"
TPI FIFO0: ETM1 Position 
.PP
Definition at line 980 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM2_Msk   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
TPI FIFO0: ETM2 Mask 
.PP
Definition at line 978 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM2_Pos   16"
TPI FIFO0: ETM2 Position 
.PP
Definition at line 977 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
TPI FIFO0: ETM_ATVALID Mask 
.PP
Definition at line 972 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM_ATVALID_Pos   26"
TPI FIFO0: ETM_ATVALID Position 
.PP
Definition at line 971 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
TPI FIFO0: ETM_bytecount Mask 
.PP
Definition at line 975 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ETM_bytecount_Pos   24"
TPI FIFO0: ETM_bytecount Position 
.PP
Definition at line 974 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
TPI FIFO0: ITM_ATVALID Mask 
.PP
Definition at line 966 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ITM_ATVALID_Pos   29"
TPI FIFO0: ITM_ATVALID Position 
.PP
Definition at line 965 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
TPI FIFO0: ITM_bytecount Mask 
.PP
Definition at line 969 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO0_ITM_bytecount_Pos   27"
TPI FIFO0: ITM_bytecount Position 
.PP
Definition at line 968 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
TPI FIFO1: ETM_ATVALID Mask 
.PP
Definition at line 998 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ETM_ATVALID_Pos   26"
TPI FIFO1: ETM_ATVALID Position 
.PP
Definition at line 997 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
TPI FIFO1: ETM_bytecount Mask 
.PP
Definition at line 1001 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ETM_bytecount_Pos   24"
TPI FIFO1: ETM_bytecount Position 
.PP
Definition at line 1000 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM0_Msk   (0xFFUL << \fBTPI_FIFO1_ITM0_Pos\fP)"
TPI FIFO1: ITM0 Mask 
.PP
Definition at line 1010 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM0_Pos   0"
TPI FIFO1: ITM0 Position 
.PP
Definition at line 1009 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM1_Msk   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
TPI FIFO1: ITM1 Mask 
.PP
Definition at line 1007 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM1_Pos   8"
TPI FIFO1: ITM1 Position 
.PP
Definition at line 1006 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM2_Msk   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
TPI FIFO1: ITM2 Mask 
.PP
Definition at line 1004 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM2_Pos   16"
TPI FIFO1: ITM2 Position 
.PP
Definition at line 1003 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
TPI FIFO1: ITM_ATVALID Mask 
.PP
Definition at line 992 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM_ATVALID_Pos   29"
TPI FIFO1: ITM_ATVALID Position 
.PP
Definition at line 991 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
TPI FIFO1: ITM_bytecount Mask 
.PP
Definition at line 995 of file core_cm4\&.h\&.
.SS "#define TPI_FIFO1_ITM_bytecount_Pos   27"
TPI FIFO1: ITM_bytecount Position 
.PP
Definition at line 994 of file core_cm4\&.h\&.
.SS "#define TPI_ITATBCTR0_ATREADY_Msk   (0x1UL << \fBTPI_ITATBCTR0_ATREADY_Pos\fP)"
TPI ITATBCTR0: ATREADY Mask 
.PP
Definition at line 1014 of file core_cm4\&.h\&.
.SS "#define TPI_ITATBCTR0_ATREADY_Pos   0"
TPI ITATBCTR0: ATREADY Position 
.PP
Definition at line 1013 of file core_cm4\&.h\&.
.SS "#define TPI_ITATBCTR2_ATREADY_Msk   (0x1UL << \fBTPI_ITATBCTR2_ATREADY_Pos\fP)"
TPI ITATBCTR2: ATREADY Mask 
.PP
Definition at line 988 of file core_cm4\&.h\&.
.SS "#define TPI_ITATBCTR2_ATREADY_Pos   0"
TPI ITATBCTR2: ATREADY Position 
.PP
Definition at line 987 of file core_cm4\&.h\&.
.SS "#define TPI_ITCTRL_Mode_Msk   (0x1UL << \fBTPI_ITCTRL_Mode_Pos\fP)"
TPI ITCTRL: Mode Mask 
.PP
Definition at line 1018 of file core_cm4\&.h\&.
.SS "#define TPI_ITCTRL_Mode_Pos   0"
TPI ITCTRL: Mode Position 
.PP
Definition at line 1017 of file core_cm4\&.h\&.
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL << \fBTPI_SPPR_TXMODE_Pos\fP)"
TPI SPPR: TXMODE Mask 
.PP
Definition at line 938 of file core_cm4\&.h\&.
.SS "#define TPI_SPPR_TXMODE_Pos   0"
TPI SPPR: TXMODE Position 
.PP
Definition at line 937 of file core_cm4\&.h\&.
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL << \fBTPI_TRIGGER_TRIGGER_Pos\fP)"
TPI TRIGGER: TRIGGER Mask 
.PP
Definition at line 962 of file core_cm4\&.h\&.
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0"
TPI TRIGGER: TRIGGER Position 
.PP
Definition at line 961 of file core_cm4\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
