CMSIS_Core_NVICFunctions
NAME
CMSIS_Core_NVICFunctions - NVIC Functions
 - Functions that manage interrupts and exceptions via the NVIC.
SYNOPSIS
Modules
SysTick Functions
Functions that configure the System.
__STATIC_INLINE void NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Set Priority Grouping.
__STATIC_INLINE uint32_t NVIC_GetPriorityGrouping (void)
Get Priority Grouping.
__STATIC_INLINE void NVIC_EnableIRQ (IRQn_Type IRQn)
Enable External Interrupt.
__STATIC_INLINE void NVIC_DisableIRQ (IRQn_Type IRQn)
Disable External Interrupt.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt.
__STATIC_INLINE void NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt.
__STATIC_INLINE void NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt.
__STATIC_INLINE uint32_t NVIC_GetActive (IRQn_Type IRQn)
Get Active Interrupt.
__STATIC_INLINE void NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
__STATIC_INLINE uint32_t NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority.
__STATIC_INLINE uint32_t NVIC_EncodePriority (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)
Encode Priority.
__STATIC_INLINE void NVIC_DecodePriority (uint32_t Priority, uint32_t PriorityGroup, uint32_t *pPreemptPriority, uint32_t *pSubPriority)
Decode Priority.
__STATIC_INLINE void NVIC_SystemReset (void)
System Reset.
Detailed Description
Functions that manage interrupts and exceptions via the NVIC.
Function Documentation
__STATIC_INLINE void NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt. The function clears the pending bit of an external interrupt.
Parameters
IRQn External interrupt number. Value cannot be negative.
Definition at line 1505 of file core_cm4.h.
{
  NVIC->ICPR[((uint32_t)(IRQn) >> 5)] = (1 << ((uint32_t)(IRQn) & 0x1F)); /* Clear pending interrupt */
}
References NVIC.
Referenced by pac5xxx_socbridge_config().
__STATIC_INLINE void NVIC_DecodePriority (uint32_t Priority, uint32_t PriorityGroup, uint32_t * pPreemptPriority, uint32_t * pSubPriority)
Decode Priority. The function decodes an interrupt priority value with a given priority group to preemptive priority value and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS) the samllest possible priority group is set.
Parameters
Priority Priority value, which can be retrieved with the function NVIC_GetPriority().
PriorityGroup Used priority group.
pPreemptPriority Preemptive priority value (starting from 0).
pSubPriority Subpriority value (starting from 0).
Definition at line 1605 of file core_cm4.h.
{
  uint32_t PriorityGroupTmp = (PriorityGroup & 0x07); /* only values 0..7 are used */
  uint32_t PreemptPriorityBits;
  uint32_t SubPriorityBits;
  PreemptPriorityBits = ((7 - PriorityGroupTmp) > __NVIC_PRIO_BITS) ? __NVIC_PRIO_BITS : 7 - PriorityGroupTmp;
  SubPriorityBits = ((PriorityGroupTmp + __NVIC_PRIO_BITS) < 7) ? 0 : PriorityGroupTmp - 7 + __NVIC_PRIO_BITS;
  *pPreemptPriority = (Priority >> SubPriorityBits) & ((1 << (PreemptPriorityBits)) - 1);
  *pSubPriority = (Priority ) & ((1 << (SubPriorityBits )) - 1);
}
References __NVIC_PRIO_BITS.
__STATIC_INLINE void NVIC_DisableIRQ (IRQn_Type IRQn)
Disable External Interrupt. The function disables a device-specific interrupt in the NVIC interrupt controller.
Parameters
IRQn External interrupt number. Value cannot be negative.
Definition at line 1465 of file core_cm4.h.
{
  NVIC->ICER[((uint32_t)(IRQn) >> 5)] = (1 << ((uint32_t)(IRQn) & 0x1F)); /* disable interrupt */
}
References NVIC.
__STATIC_INLINE void NVIC_EnableIRQ (IRQn_Type IRQn)
Enable External Interrupt. The function enables a device-specific interrupt in the NVIC interrupt controller.
Parameters
IRQn External interrupt number. Value cannot be negative.
Definition at line 1452 of file core_cm4.h.
{
/* NVIC->ISER[((uint32_t)(IRQn) >> 5)] = (1 << ((uint32_t)(IRQn) & 0x1F)); enable interrupt */
  NVIC->ISER[(uint32_t)((int32_t)IRQn) >> 5] = (uint32_t)(1 << ((uint32_t)((int32_t)IRQn) & (uint32_t)0x1F)); /* enable interrupt */
}
References NVIC.
Referenced by pac5xxx_gpio_configure_interrupt_a(), pac5xxx_gpio_configure_interrupt_b(), pac5xxx_gpio_configure_interrupt_c(), pac5xxx_gpio_configure_interrupt_d(), pac5xxx_gpio_configure_interrupt_e(), pac5xxx_gpio_configure_interrupt_f(), pac5xxx_gpio_configure_interrupt_g(), and pac5xxx_socbridge_config().
__STATIC_INLINE uint32_t NVIC_EncodePriority (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)
Encode Priority. The function encodes the priority for an interrupt with the given priority group, preemptive priority value, and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the samllest possible priority group is set.
Parameters
PriorityGroup Used priority group.
PreemptPriority Preemptive priority value (starting from 0).
SubPriority Subpriority value (starting from 0).
Returns
Encoded priority. Value can be used in the function NVIC_SetPriority().
Definition at line 1577 of file core_cm4.h.
{
  uint32_t PriorityGroupTmp = (PriorityGroup & 0x07); /* only values 0..7 are used */
  uint32_t PreemptPriorityBits;
  uint32_t SubPriorityBits;
  PreemptPriorityBits = ((7 - PriorityGroupTmp) > __NVIC_PRIO_BITS) ? __NVIC_PRIO_BITS : 7 - PriorityGroupTmp;
  SubPriorityBits = ((PriorityGroupTmp + __NVIC_PRIO_BITS) < 7) ? 0 : PriorityGroupTmp - 7 + __NVIC_PRIO_BITS;
  return (
           ((PreemptPriority & ((1 << (PreemptPriorityBits)) - 1)) << SubPriorityBits) |
           ((SubPriority & ((1 << (SubPriorityBits )) - 1)))
         );
}
References __NVIC_PRIO_BITS.
__STATIC_INLINE uint32_t NVIC_GetActive (IRQn_Type IRQn)
Get Active Interrupt. The function reads the active register in NVIC and returns the active bit.
Parameters
IRQn Interrupt number.
Returns
0 Interrupt status is not active.
1 Interrupt status is active.
Definition at line 1520 of file core_cm4.h.
{
  return((uint32_t)((NVIC->IABR[(uint32_t)(IRQn) >> 5] & (1 << ((uint32_t)(IRQn) & 0x1F)))?1:0)); /* Return 1 if active else 0 */
}
References NVIC.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt. The function reads the pending register in the NVIC and returns the pending bit for the specified interrupt.
Parameters
IRQn Interrupt number.
Returns
0 Interrupt status is not pending.
1 Interrupt status is pending.
Definition at line 1481 of file core_cm4.h.
{
  return((uint32_t) ((NVIC->ISPR[(uint32_t)(IRQn) >> 5] & (1 << ((uint32_t)(IRQn) & 0x1F)))?1:0)); /* Return 1 if pending else 0 */
}
References NVIC.
__STATIC_INLINE uint32_t NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority. The function reads the priority of an interrupt. The interrupt number can be positive to specify an external (device specific) interrupt, or negative to specify an internal (core) interrupt.
Parameters
IRQn Interrupt number.
Returns
Interrupt Priority. Value is aligned automatically to the implemented priority bits of the microcontroller.
Definition at line 1555 of file core_cm4.h.
{
  if(IRQn < 0) {
    return((uint32_t)(SCB->SHP[((uint32_t)(IRQn) & 0xF)-4] >> (8 - __NVIC_PRIO_BITS))); } /* get priority for Cortex-M system interrupts */
  else {
    return((uint32_t)(NVIC->IP[(uint32_t)(IRQn)] >> (8 - __NVIC_PRIO_BITS))); } /* get priority for device specific interrupts */
}
References __NVIC_PRIO_BITS, NVIC, and SCB.
__STATIC_INLINE uint32_t NVIC_GetPriorityGrouping (void)
Get Priority Grouping. The function reads the priority grouping field from the NVIC Interrupt Controller.
Returns
Priority grouping field (SCB->AIRCR [10:8] PRIGROUP field).
Definition at line 1440 of file core_cm4.h.
{
  return ((SCB->AIRCR & SCB_AIRCR_PRIGROUP_Msk) >> SCB_AIRCR_PRIGROUP_Pos); /* read priority grouping field */
}
References SCB, SCB_AIRCR_PRIGROUP_Msk, and SCB_AIRCR_PRIGROUP_Pos.
__STATIC_INLINE void NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt. The function sets the pending bit of an external interrupt.
Parameters
IRQn Interrupt number. Value cannot be negative.
Definition at line 1493 of file core_cm4.h.
{
  NVIC->ISPR[((uint32_t)(IRQn) >> 5)] = (1 << ((uint32_t)(IRQn) & 0x1F)); /* set interrupt pending */
}
References NVIC.
__STATIC_INLINE void NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority. The function sets the priority of an interrupt.
Note
The priority cannot be set for every core interrupt.
Parameters
IRQn Interrupt number.
priority Priority to set.
Definition at line 1535 of file core_cm4.h.
{
  if(IRQn < 0) {
    SCB->SHP[((uint32_t)(IRQn) & 0xF)-4] = ((priority << (8 - __NVIC_PRIO_BITS)) & 0xff); } /* set Priority for Cortex-M System Interrupts */
  else {
    NVIC->IP[(uint32_t)(IRQn)] = ((priority << (8 - __NVIC_PRIO_BITS)) & 0xff); } /* set Priority for device specific Interrupts */
}
References __NVIC_PRIO_BITS, NVIC, and SCB.
Referenced by config_systick_timer(), configure_cafe_fault_interrupt(), and SysTick_Config().
__STATIC_INLINE void NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Set Priority Grouping. The function sets the priority grouping field using the required unlock sequence. The parameter PriorityGroup is assigned to the field SCB->AIRCR [10:8] PRIGROUP field. Only values from 0..7 are used. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set.
Parameters
PriorityGroup Priority grouping field.
Definition at line 1420 of file core_cm4.h.
{
  uint32_t reg_value;
  uint32_t PriorityGroupTmp = (PriorityGroup & (uint32_t)0x07); /* only values 0..7 are used */
  reg_value = SCB->AIRCR; /* read old register configuration */
  reg_value &= ~(SCB_AIRCR_VECTKEY_Msk | SCB_AIRCR_PRIGROUP_Msk); /* clear bits to change */
  reg_value = (reg_value |
                ((uint32_t)0x5FA << SCB_AIRCR_VECTKEY_Pos) |
                (PriorityGroupTmp << 8)); /* Insert write key and priorty group */
  SCB->AIRCR = reg_value;
}
References SCB, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_VECTKEY_Msk, and SCB_AIRCR_VECTKEY_Pos.
__STATIC_INLINE void NVIC_SystemReset (void)
System Reset. The function initiates a system reset request to reset the MCU.
Definition at line 1623 of file core_cm4.h.
{
  __DSB(); /* Ensure all outstanding memory accesses included
                                                                  buffered write are completed before reset */
  SCB->AIRCR = ((0x5FA << SCB_AIRCR_VECTKEY_Pos) |
                 (SCB->AIRCR & SCB_AIRCR_PRIGROUP_Msk) |
                 SCB_AIRCR_SYSRESETREQ_Msk); /* Keep priority group unchanged */
  __DSB(); /* Ensure completion of memory access */
  while(1); /* wait until reset */
}
References SCB, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_SYSRESETREQ_Msk, and SCB_AIRCR_VECTKEY_Pos.
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.