.TH "CMSIS_Core_FunctionInterface" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_FunctionInterface \- Functions and Instructions Reference
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBNVIC Functions\fP"
.br
.RI "Functions that manage interrupts and exceptions via the NVIC\&. "
.ti -1c
.RI "\fBCMSIS Core Register Access Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
