.TH "pac_foc/pac55xx/board/config_board.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/board/config_board.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOARD_CUSTOM_1\fP   1"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5523EVK1\fP   10"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5524EVK1\fP   11"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5527EVK1\fP   12"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5532EVK1\fP   13"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5556EVK1\fP   14"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5526EVK1\fP   32"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5523EVK1_1_1SHUNT\fP   20"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5524EVK1_1_1SHUNT\fP   21"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5532EVK1_1SHUNT\fP   22"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5556EVK1_1SHUNT\fP   23"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5523EVK1_1_1SHUNT_PWR2\fP   30"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5524EVK1_1_1SHUNT_PWR2\fP   31"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5527HCRD1_ENG\fP   1000"
.br
.ti -1c
.RI "#define \fBBOARD_PAC5524RDPS_ENG\fP   1001"
.br
.ti -1c
.RI "#define \fBBOARD_SELECT\fP   \fBBOARD_PAC5523EVK1\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOARD_CUSTOM_1   1"

.PP
Definition at line 28 of file config_board\&.h\&.
.SS "#define BOARD_PAC5523EVK1   10"

.PP
Definition at line 29 of file config_board\&.h\&.
.SS "#define BOARD_PAC5523EVK1_1_1SHUNT   20"

.PP
Definition at line 38 of file config_board\&.h\&.
.SS "#define BOARD_PAC5523EVK1_1_1SHUNT_PWR2   30"

.PP
Definition at line 45 of file config_board\&.h\&.
.SS "#define BOARD_PAC5524EVK1   11"

.PP
Definition at line 30 of file config_board\&.h\&.
.SS "#define BOARD_PAC5524EVK1_1_1SHUNT   21"

.PP
Definition at line 39 of file config_board\&.h\&.
.SS "#define BOARD_PAC5524EVK1_1_1SHUNT_PWR2   31"

.PP
Definition at line 46 of file config_board\&.h\&.
.SS "#define BOARD_PAC5524RDPS_ENG   1001"

.PP
Definition at line 51 of file config_board\&.h\&.
.SS "#define BOARD_PAC5526EVK1   32"

.PP
Definition at line 34 of file config_board\&.h\&.
.SS "#define BOARD_PAC5527EVK1   12"

.PP
Definition at line 31 of file config_board\&.h\&.
.SS "#define BOARD_PAC5527HCRD1_ENG   1000"

.PP
Definition at line 50 of file config_board\&.h\&.
.SS "#define BOARD_PAC5532EVK1   13"

.PP
Definition at line 32 of file config_board\&.h\&.
.SS "#define BOARD_PAC5532EVK1_1SHUNT   22"

.PP
Definition at line 40 of file config_board\&.h\&.
.SS "#define BOARD_PAC5556EVK1   14"

.PP
Definition at line 33 of file config_board\&.h\&.
.SS "#define BOARD_PAC5556EVK1_1SHUNT   23"

.PP
Definition at line 41 of file config_board\&.h\&.
.SS "#define BOARD_SELECT   \fBBOARD_PAC5523EVK1\fP"

.PP
Definition at line 58 of file config_board\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
