.TH "CONTROL_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONTROL_Type \- Union type to access the Control Registers (CONTROL)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBCONTROL_Type::nPRIV\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBCONTROL_Type::SPSEL\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBCONTROL_Type::FPCA\fP:1"
.br
.ti -1c
.RI "   uint32_t \fBCONTROL_Type::_reserved0\fP:29"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Control Registers (CONTROL)\&. 
.PP
Definition at line 298 of file core_cm4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
