.TH "pac_foc/pac55xx/cmsis_core/core_cm4_simd.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/cmsis_core/core_cm4_simd.h \- CMSIS Cortex-M4 SIMD Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CORE_CM4_SIMD_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M4 SIMD Header File\&. 


.PP
\fBVersion\fP
.RS 4
V3\&.01 
.RE
.PP
\fBDate\fP
.RS 4
06\&. March 2012
.RE
.PP
\fBNote\fP
.RS 4
Copyright (C) 2010-2012 ARM Limited\&. All rights reserved\&.
.RE
.PP
\fB\fP
.RS 4
ARM Limited (ARM) is supplying this software for use with Cortex-M processor based microcontrollers\&. This file can be freely distributed within development tools that are supporting such ARM based processors\&.
.RE
.PP
\fB\fP
.RS 4
THIS SOFTWARE IS PROVIDED 'AS IS'\&. NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE\&. ARM SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER\&. 
.RE
.PP

.PP
Definition in file \fBcore_cm4_simd\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define __CORE_CM4_SIMD_H"

.PP
Definition at line 29 of file core_cm4_simd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
