.TH "pac_foc/pac55xx/device/device_5527.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/device/device_5527.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5527\&.h'\fP
.br
\fC#include 'pac5xxx\&.h'\fP
.br
\fC#include 'family_55xx\&.h'\fP
.br
\fC#include 'pac5xxx_driver_tile\&.h'\fP
.br
\fC#include 'pac5xxx_driver_timer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFOC_PWM_Timer\fP   \fBTimerA\fP"
.br
.ti -1c
.RI "#define \fBFOC_PWM_Timer_Ptr\fP   \fBPAC55XX_TIMERA\fP"
.br
.ti -1c
.RI "#define \fBFOC_PWM_Timer_IRQn\fP   \fBTimerA_IRQn\fP"
.br
.ti -1c
.RI "#define \fBFOC_DAC_Timer\fP   \fBTimerB\fP"
.br
.ti -1c
.RI "#define \fBADC_IRQn\fP   \fBADC0_IRQn\fP"
.br
.ti -1c
.RI "#define \fBDEBUG_DAC_SUPPORT_PORT_A_DRL\fP   FALSE"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_IRQn   \fBADC0_IRQn\fP"

.PP
Definition at line 30 of file device_5527\&.h\&.
.SS "#define DEBUG_DAC_SUPPORT_PORT_A_DRL   FALSE"

.PP
Definition at line 34 of file device_5527\&.h\&.
.SS "#define FOC_DAC_Timer   \fBTimerB\fP"

.PP
Definition at line 29 of file device_5527\&.h\&.
.SS "#define FOC_PWM_Timer   \fBTimerA\fP"

.PP
Definition at line 26 of file device_5527\&.h\&.
.SS "#define FOC_PWM_Timer_IRQn   \fBTimerA_IRQn\fP"

.PP
Definition at line 28 of file device_5527\&.h\&.
.SS "#define FOC_PWM_Timer_Ptr   \fBPAC55XX_TIMERA\fP"

.PP
Definition at line 27 of file device_5527\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
