.TH "DINSIG1" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DINSIG1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDINSIG1::DIN6\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDINSIG1::DIN7\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDINSIG1::DIN8\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDINSIG1::DIN9\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBDINSIG1::__pad0__\fP: 4"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 503 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
