.TH "DOUTSIG0" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DOUTSIG0
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT0\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT1\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT2\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT3\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT4\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBDOUTSIG0::DOUT5\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBDOUTSIG0::__pad0__\fP: 2"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 460 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
