.TH "DTGCTL_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTGCTL_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_timers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBRED\fP: 12"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 4"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBFED\fP: 12"
.br
.ti -1c
.RI "   uint32_t \fB__pad1__\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBDTEN\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file pac5xxx_timers\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t DTGCTL_TYPEDEF::__pad0__"

.PP
Definition at line 191 of file pac5xxx_timers\&.h\&.
.SS "uint32_t DTGCTL_TYPEDEF::__pad1__"

.PP
Definition at line 193 of file pac5xxx_timers\&.h\&.
.SS "\fB__IO\fP uint32_t DTGCTL_TYPEDEF::DTEN"

.PP
Definition at line 194 of file pac5xxx_timers\&.h\&.
.PP
Referenced by pac5xxx_dtg_config2()\&.
.SS "\fB__IO\fP uint32_t DTGCTL_TYPEDEF::FED"

.PP
Definition at line 192 of file pac5xxx_timers\&.h\&.
.PP
Referenced by pac5xxx_dtg_config2()\&.
.SS "\fB__IO\fP uint32_t DTGCTL_TYPEDEF::RED"

.PP
Definition at line 190 of file pac5xxx_timers\&.h\&.
.PP
Referenced by pac5xxx_dtg_config2()\&.
.SS "\fB__IO\fP uint32_t DTGCTL_TYPEDEF::w"

.PP
Definition at line 187 of file pac5xxx_timers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
