.TH "DWT_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DWT_Type \- Structure type to access the Data Watchpoint and Trace Register (DWT)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCYCCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCPICNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXCCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSLEEPCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLSUCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFOLDCNT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBPCSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCOMP0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFUNCTION0\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [1]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCOMP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFUNCTION1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [1]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCOMP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFUNCTION2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [1]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCOMP3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMASK3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFUNCTION3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Data Watchpoint and Trace Register (DWT)\&. 
.PP
Definition at line 759 of file core_cm4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
