pac_foc/pac55xx/device/family_55xx.h
NAME
pac_foc/pac55xx/device/family_55xx.h
SYNOPSIS
#include 'pac5xxx.h'
#include 'config_debug.h'
#include 'pac5xxx_driver_timer.h'
Macros
#define FAMILY_55XX
#define VMS100_ADDRESS 0x00100410
#define VMS200_ADDRESS 0x00100412
#define ADC_OFFSET_ADDRESS 0x00100414
#define ADC_GAIN_ADDRESS 0x00100418
#define ADC_CHANNEL_MASK (1L << ADCCTL_CHANNEL_ADC0)
Functions
void init_system (void)
void configure_cafe_fault_interrupt (void)
void configure_foc_timer (void)
void configure_adc_emux_engine (void)
void configure_pwm_dac (void)
void uart_scratch_write (int32_t value)
int32_t uart_scratch_read (void)
void sim_update_seq_trigger_point (int32_t value)
Macro Definition Documentation
#define ADC_CHANNEL_MASK (1L << ADCCTL_CHANNEL_ADC0)
Definition at line 31 of file family_55xx.h.
#define ADC_GAIN_ADDRESS 0x00100418
Definition at line 28 of file family_55xx.h.
#define ADC_OFFSET_ADDRESS 0x00100414
Definition at line 27 of file family_55xx.h.
#define FAMILY_55XX
Definition at line 18 of file family_55xx.h.
#define VMS100_ADDRESS 0x00100410
Definition at line 25 of file family_55xx.h.
#define VMS200_ADDRESS 0x00100412
Definition at line 26 of file family_55xx.h.
Function Documentation
void configure_adc_emux_engine (void)
Definition at line 147 of file family_55xx.c.
{
    // EMUX configuration
    pac5xxx_adc_config_emux_io();
    pac5xxx_adc_emux_config(ADCEMUXCTL_DTSE_SEQ, ADCEMUXCTL_EMUXDIV_DIV16);
    pac5xxx_adc_config(ADCCTL_MODE_DTSE, ADCCTL_CLKDIV_DIV8, 0);
}
References ADCCTL_CLKDIV_DIV8, ADCCTL_MODE_DTSE, ADCEMUXCTL_DTSE_SEQ, ADCEMUXCTL_EMUXDIV_DIV16, pac5xxx_adc_config(), pac5xxx_adc_config_emux_io(), and pac5xxx_adc_emux_config().
void configure_cafe_fault_interrupt (void)
Definition at line 94 of file family_55xx.c.
{
    // Configure nIRQ1, CAFE fault interrupt, as digital input - active low
    PAC55XX_SCC->PAMUXSEL.w &= 0x0FFFFFFF; // PA7 as input for n1RQ1, over current interrupt
// PAC55XX_GPIOA->CLKSYNC.P7 = 1;
    pac5xxx_gpio_configure_interrupt_a(NIRQ1_PIN_MASK, 0);
    #ifdef ENABLE_CBC_CURRENT_LIMIT
        NVIC_SetPriority(GpioA_IRQn,0);
    #else
        NVIC_SetPriority(GpioA_IRQn,3);
    #endif
}
References GpioA_IRQn, NIRQ1_PIN_MASK, NVIC_SetPriority(), PAC55XX_SCC, and pac5xxx_gpio_configure_interrupt_a().
void configure_foc_timer (void)
Definition at line 109 of file family_55xx.c.
{
    // Configure Timer A Controls
    pac5xxx_timer_clock_config(FOC_PWM_Timer, TXCTL_CS_ACLK, TXCTL_PS_DIV1); // Configure timer clock input for ACLK, /1 divider
    pac5xxx_timer_base_config(FOC_PWM_Timer, motor.control.motor_period_ticks, 0, TxCTL_MODE_UPDOWN, 0); // Enable base timer
    // Update duty cycle when TACTR counts from 1 to 0
    FOC_PWM_Timer_Ptr->CTL.PRDLATCH = 0;
    // Configure Dead time generators
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL0), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA0 for phase U
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL1), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA1 for phase V
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL2), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA2 for phase W
}
References FOC_PWM_Timer, FOC_PWM_Timer_Ptr, pac5xxx_dtg_config2(), pac5xxx_timer_base_config(), pac5xxx_timer_clock_config(), TXCTL_CS_ACLK, TxCTL_MODE_UPDOWN, and TXCTL_PS_DIV1.
void configure_pwm_dac (void)
Definition at line 123 of file family_55xx.c.
{
#ifdef ENABLE_DEBUG_PWMDAC
    pac5xxx_timer_clock_config(FOC_DAC_Timer, TXCTL_CS_ACLK, TXCTL_PS_DIV1); // Configure timer clock input for ACLK, /1 divider
    pac5xxx_timer_base_config(FOC_DAC_Timer, PWMDAC_PERIOD_TICKS, 0, TxCTL_MODE_UPDOWN, 0); // Enable base timer
    switch (FOC_DAC_Timer)
    {
        case TimerB:
            pac5xxx_timer_b_ccctr0_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_b_ccctr1_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_b_ccctr2_value_set(PWMDAC_PERIOD_TICKS >> 1);
            break;
        case TimerC:
            pac5xxx_timer_c_ccctr4_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_c_ccctr5_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_c_ccctr6_value_set(PWMDAC_PERIOD_TICKS >> 1);
            break;
        default:
            break;
    }
#endif
}
References FOC_DAC_Timer, pac5xxx_timer_base_config(), pac5xxx_timer_clock_config(), TimerB, TXCTL_CS_ACLK, TxCTL_MODE_UPDOWN, and TXCTL_PS_DIV1.
void init_system (void)
Definition at line 49 of file family_55xx.c.
{
    // Set Flash Lock to allow write access to MEMCTL register for configuring clocks
    PAC55XX_MEMCTL->FLASHLOCK = FLASH_LOCK_ALLOW_WRITE_MEMCTL;
    // Set safe clock defaults
    PAC55XX_SCC->CCSCTL.FRCLKMUXSEL = CCSCTL_CLKIN_ROSC;
    PAC55XX_SCC->CCSCTL.SCLKMUXSEL = CCSCTL_SCLK_FRCLK;
    PAC55XX_MEMCTL->MEMCTL.MCLKSEL = MEMCTL_MCLK_ROSCCLK;
    // Turn on Flache Cache
    PAC55XX_MEMCTL->MEMCTL.CACHEDIS = 0; // enable Flash CACHE
    // Select 4 MHz CLKREF for Free Running Clock FRCLK
    PAC55XX_SCC->CCSCTL.FRCLKMUXSEL = CCSCTL_CLKIN_CLKREF;
 
    pac5xxx_sys_pll_config_enable(4, 300, 0); // PLLCLK = 300 MHz = (4/4 * 300) /1
    // Configure SCLK=PLLCLK=300 MHz, HCLK=150 MHz, PCLK=150 MHz, ACLK=50 MHz and WaitStates; Use default PCLKDIV=1
    PAC55XX_SCC->CCSCTL.HCLKDIV = CCSCTL_HCLKDIV_DIV2; // HCLK = 150 MHz = SCLK/2; when SCLK = PLLCLK
    PAC55XX_SCC->CCSCTL.ACLKDIV = CCSCTL_ACLKDIV_DIV6; // ACLK = 50 MHz = SCLK/6; when SCLK = PLLCLK
    PAC55XX_MEMCTL->MEMCTL.WSTATE = 5 + 1; // Flash = 150/25 = 6 clocks = 5 WS; So, need 5 + 1 Extra WS
    PAC55XX_SCC->CCSCTL.SCLKMUXSEL = CCSCTL_SCLK_PLLCLK; // SCLK = PLLCLK
    // Set MCLK for Flash write & erase in addition to read
    PAC55XX_MEMCTL->MEMCTL.MCLKDIV = MEMCTL_MCLK_DIV5; // MCLK will = HCLK/5 when MCLKSEL = MEMCTL_MCLK_HCLKDIV
    PAC55XX_MEMCTL->MEMCTL.MCLKSEL = MEMCTL_MCLK_HCLKDIV; // MCLK = HCLK/5 = 30 MHz; allows reading and writing of Flash
    PAC55XX_MEMCTL->FLASHLOCK = 0; // Disallow write access to MEMCTL
    // Enable GPIO Input clock synchronization; should always be enabled, especially when using GPIO edge based interrupts
    PAC55XX_GPIOA->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOB->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOC->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOD->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOE->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOF->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOG->CLKSYNC.w = 0xFF;
#ifdef ENABLE_FLASH_CRC_TEST
    // Set USARTC to UART mode for scratch pad
    PAC55XX_SCC->CCSCTL.USCMODE = 1; // UART mode
#endif
}
References CCSCTL_ACLKDIV_DIV6, CCSCTL_CLKIN_CLKREF, CCSCTL_CLKIN_ROSC, CCSCTL_HCLKDIV_DIV2, CCSCTL_SCLK_FRCLK, CCSCTL_SCLK_PLLCLK, FLASH_LOCK_ALLOW_WRITE_MEMCTL, MEMCTL_MCLK_DIV5, MEMCTL_MCLK_HCLKDIV, MEMCTL_MCLK_ROSCCLK, PAC55XX_GPIOA, PAC55XX_GPIOB, PAC55XX_GPIOC, PAC55XX_GPIOD, PAC55XX_GPIOE, PAC55XX_GPIOF, PAC55XX_GPIOG, PAC55XX_MEMCTL, PAC55XX_SCC, and pac5xxx_sys_pll_config_enable().
void sim_update_seq_trigger_point (int32_t value)
int32_t uart_scratch_read (void)
Definition at line 249 of file family_55xx.c.
{
    // Return the value stored in the UART Scratch Pad Register
    return PAC55XX_UARTC->SCR.PAD;
}
References PAC55XX_UARTC.
void uart_scratch_write (int32_t value)
Definition at line 243 of file family_55xx.c.
{
    // Set the UART Scratch Pad Register value
    PAC55XX_UARTC->SCR.PAD = value;
}
References PAC55XX_UARTC.
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.