pac_foc/pac55xx/device/family_55xx.c
NAME
pac_foc/pac55xx/device/family_55xx.c
SYNOPSIS
#include 'motor_struct.h'
#include 'pac_init.h'
#include 'driver_funcs.h'
#include 'param.h'
#include 'sim_funcs.h'
#include 'parameter_process.h'
#include 'comm.h'
#include 'fault.h'
#include 'pac5xxx_driver_adc.h'
#include 'pac5xxx_driver_timer.h'
#include 'pac5xxx_driver_socbridge.h'
#include 'pac5xxx_driver_tile.h'
#include 'pac5xxx_driver_system.h'
#include 'pac5xxx_driver_memory.h'
#include 'pac5xxx_driver_uart.h'
#include 'pac5xxx_driver_gpio.h'
#include 'debug_dac.h'
#include 'watchdog.h'
#include 'stack_check.h'
Macros
#define NIRQ1_PIN 7
#define NIRQ1_PIN_MASK (1 << NIRQ1_PIN)
Functions
void init_system ()
void configure_cafe_fault_interrupt (void)
void configure_foc_timer (void)
void configure_pwm_dac (void)
void configure_adc_emux_engine (void)
void config_systick_timer (void)
void USARTC_IRQHandler (void)
void config_uart (void)
void uart_scratch_write (int32_t value)
int32_t uart_scratch_read (void)
Macro Definition Documentation
#define NIRQ1_PIN 7
Definition at line 46 of file family_55xx.c.
#define NIRQ1_PIN_MASK (1 << NIRQ1_PIN)
Definition at line 47 of file family_55xx.c.
Function Documentation
void config_systick_timer (void)
Definition at line 156 of file family_55xx.c.
{
    SysTick_Config(SYSTICK_TICKS);
    NVIC_SetPriority(SysTick_IRQn, 2);
    SysTick->VAL = SYSTICK_TICKS;
}
References NVIC_SetPriority(), SysTick, SysTick_Config(), and SysTick_IRQn.
void config_uart (void)
Definition at line 218 of file family_55xx.c.
{
    // Configure UART C (Depends on pclk input, Expects 150MHz PCLK)
    PAC55XX_SCC->CCSCTL.USCMODE = 1; // UART mode
    pac5xxx_uart_config_LCR2(PAC55XX_UARTC,
                             UARTLCR_WL_BPC_8,
                             UART_STOP_BITS_1,
                             UART_PEN_DISABLE,
                             UART_PARITY_FORCE_STICK_1,
                             UART_BRKCTL_DISABLE);
    pac5xxx_uart_config_divisor_latch2(PAC55XX_UARTC, 81); // 115kbps = PCLK / (16 * DLR)
    pac5xxx_uart_fifo_enable2(PAC55XX_UARTC, 1);
    pac5xxx_uart_rx_fifo_reset2(PAC55XX_UARTC);
    pac5xxx_uart_rx_fifo_threshold2(PAC55XX_UARTC, UARTFCR_TL_1B);
    pac5xxx_uart_tx_fifo_threshold2(PAC55XX_UARTC, UARTFCR_TL_1B);
    pac5xxx_uart_int_enable_RDAI2(PAC55XX_UARTC, 1);
    pac5xxx_uart_int_enable_THREI2(PAC55XX_UARTC, 1);
    pac5xxx_uart_io_config2();
    NVIC_ClearPendingIRQ(USARTC_IRQn);
    NVIC_SetPriority(USARTC_IRQn,3);
    NVIC_EnableIRQ(USARTC_IRQn);
}
References PAC55XX_SCC, PAC55XX_UARTC, pac5xxx_uart_config_divisor_latch2(), pac5xxx_uart_config_LCR2(), UART_BRKCTL_DISABLE, UART_PARITY_FORCE_STICK_1, UART_PEN_DISABLE, UART_STOP_BITS_1, and UARTLCR_WL_BPC_8.
void configure_adc_emux_engine (void)
Definition at line 147 of file family_55xx.c.
{
    // EMUX configuration
    pac5xxx_adc_config_emux_io();
    pac5xxx_adc_emux_config(ADCEMUXCTL_DTSE_SEQ, ADCEMUXCTL_EMUXDIV_DIV16);
    pac5xxx_adc_config(ADCCTL_MODE_DTSE, ADCCTL_CLKDIV_DIV8, 0);
}
References ADCCTL_CLKDIV_DIV8, ADCCTL_MODE_DTSE, ADCEMUXCTL_DTSE_SEQ, ADCEMUXCTL_EMUXDIV_DIV16, pac5xxx_adc_config(), pac5xxx_adc_config_emux_io(), and pac5xxx_adc_emux_config().
void configure_cafe_fault_interrupt (void)
Definition at line 94 of file family_55xx.c.
{
    // Configure nIRQ1, CAFE fault interrupt, as digital input - active low
    PAC55XX_SCC->PAMUXSEL.w &= 0x0FFFFFFF; // PA7 as input for n1RQ1, over current interrupt
// PAC55XX_GPIOA->CLKSYNC.P7 = 1;
    pac5xxx_gpio_configure_interrupt_a(NIRQ1_PIN_MASK, 0);
    #ifdef ENABLE_CBC_CURRENT_LIMIT
        NVIC_SetPriority(GpioA_IRQn,0);
    #else
        NVIC_SetPriority(GpioA_IRQn,3);
    #endif
}
References GpioA_IRQn, NIRQ1_PIN_MASK, NVIC_SetPriority(), PAC55XX_SCC, and pac5xxx_gpio_configure_interrupt_a().
void configure_foc_timer (void)
Definition at line 109 of file family_55xx.c.
{
    // Configure Timer A Controls
    pac5xxx_timer_clock_config(FOC_PWM_Timer, TXCTL_CS_ACLK, TXCTL_PS_DIV1); // Configure timer clock input for ACLK, /1 divider
    pac5xxx_timer_base_config(FOC_PWM_Timer, motor.control.motor_period_ticks, 0, TxCTL_MODE_UPDOWN, 0); // Enable base timer
    // Update duty cycle when TACTR counts from 1 to 0
    FOC_PWM_Timer_Ptr->CTL.PRDLATCH = 0;
    // Configure Dead time generators
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL0), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA0 for phase U
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL1), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA1 for phase V
    pac5xxx_dtg_config2(&(FOC_PWM_Timer_Ptr->DTGCTL2), MOTOR1_LED_TICKS, MOTOR1_TED_TICKS); // Configure DTGA2 for phase W
}
References FOC_PWM_Timer, FOC_PWM_Timer_Ptr, pac5xxx_dtg_config2(), pac5xxx_timer_base_config(), pac5xxx_timer_clock_config(), TXCTL_CS_ACLK, TxCTL_MODE_UPDOWN, and TXCTL_PS_DIV1.
void configure_pwm_dac (void)
Definition at line 123 of file family_55xx.c.
{
#ifdef ENABLE_DEBUG_PWMDAC
    pac5xxx_timer_clock_config(FOC_DAC_Timer, TXCTL_CS_ACLK, TXCTL_PS_DIV1); // Configure timer clock input for ACLK, /1 divider
    pac5xxx_timer_base_config(FOC_DAC_Timer, PWMDAC_PERIOD_TICKS, 0, TxCTL_MODE_UPDOWN, 0); // Enable base timer
    switch (FOC_DAC_Timer)
    {
        case TimerB:
            pac5xxx_timer_b_ccctr0_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_b_ccctr1_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_b_ccctr2_value_set(PWMDAC_PERIOD_TICKS >> 1);
            break;
        case TimerC:
            pac5xxx_timer_c_ccctr4_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_c_ccctr5_value_set(PWMDAC_PERIOD_TICKS >> 1);
            pac5xxx_timer_c_ccctr6_value_set(PWMDAC_PERIOD_TICKS >> 1);
            break;
        default:
            break;
    }
#endif
}
References FOC_DAC_Timer, pac5xxx_timer_base_config(), pac5xxx_timer_clock_config(), TimerB, TXCTL_CS_ACLK, TxCTL_MODE_UPDOWN, and TXCTL_PS_DIV1.
void init_system (void)
Definition at line 49 of file family_55xx.c.
{
    // Set Flash Lock to allow write access to MEMCTL register for configuring clocks
    PAC55XX_MEMCTL->FLASHLOCK = FLASH_LOCK_ALLOW_WRITE_MEMCTL;
    // Set safe clock defaults
    PAC55XX_SCC->CCSCTL.FRCLKMUXSEL = CCSCTL_CLKIN_ROSC;
    PAC55XX_SCC->CCSCTL.SCLKMUXSEL = CCSCTL_SCLK_FRCLK;
    PAC55XX_MEMCTL->MEMCTL.MCLKSEL = MEMCTL_MCLK_ROSCCLK;
    // Turn on Flache Cache
    PAC55XX_MEMCTL->MEMCTL.CACHEDIS = 0; // enable Flash CACHE
    // Select 4 MHz CLKREF for Free Running Clock FRCLK
    PAC55XX_SCC->CCSCTL.FRCLKMUXSEL = CCSCTL_CLKIN_CLKREF;
 
    pac5xxx_sys_pll_config_enable(4, 300, 0); // PLLCLK = 300 MHz = (4/4 * 300) /1
    // Configure SCLK=PLLCLK=300 MHz, HCLK=150 MHz, PCLK=150 MHz, ACLK=50 MHz and WaitStates; Use default PCLKDIV=1
    PAC55XX_SCC->CCSCTL.HCLKDIV = CCSCTL_HCLKDIV_DIV2; // HCLK = 150 MHz = SCLK/2; when SCLK = PLLCLK
    PAC55XX_SCC->CCSCTL.ACLKDIV = CCSCTL_ACLKDIV_DIV6; // ACLK = 50 MHz = SCLK/6; when SCLK = PLLCLK
    PAC55XX_MEMCTL->MEMCTL.WSTATE = 5 + 1; // Flash = 150/25 = 6 clocks = 5 WS; So, need 5 + 1 Extra WS
    PAC55XX_SCC->CCSCTL.SCLKMUXSEL = CCSCTL_SCLK_PLLCLK; // SCLK = PLLCLK
    // Set MCLK for Flash write & erase in addition to read
    PAC55XX_MEMCTL->MEMCTL.MCLKDIV = MEMCTL_MCLK_DIV5; // MCLK will = HCLK/5 when MCLKSEL = MEMCTL_MCLK_HCLKDIV
    PAC55XX_MEMCTL->MEMCTL.MCLKSEL = MEMCTL_MCLK_HCLKDIV; // MCLK = HCLK/5 = 30 MHz; allows reading and writing of Flash
    PAC55XX_MEMCTL->FLASHLOCK = 0; // Disallow write access to MEMCTL
    // Enable GPIO Input clock synchronization; should always be enabled, especially when using GPIO edge based interrupts
    PAC55XX_GPIOA->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOB->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOC->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOD->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOE->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOF->CLKSYNC.w = 0xFF;
    PAC55XX_GPIOG->CLKSYNC.w = 0xFF;
#ifdef ENABLE_FLASH_CRC_TEST
    // Set USARTC to UART mode for scratch pad
    PAC55XX_SCC->CCSCTL.USCMODE = 1; // UART mode
#endif
}
References CCSCTL_ACLKDIV_DIV6, CCSCTL_CLKIN_CLKREF, CCSCTL_CLKIN_ROSC, CCSCTL_HCLKDIV_DIV2, CCSCTL_SCLK_FRCLK, CCSCTL_SCLK_PLLCLK, FLASH_LOCK_ALLOW_WRITE_MEMCTL, MEMCTL_MCLK_DIV5, MEMCTL_MCLK_HCLKDIV, MEMCTL_MCLK_ROSCCLK, PAC55XX_GPIOA, PAC55XX_GPIOB, PAC55XX_GPIOC, PAC55XX_GPIOD, PAC55XX_GPIOE, PAC55XX_GPIOF, PAC55XX_GPIOG, PAC55XX_MEMCTL, PAC55XX_SCC, and pac5xxx_sys_pll_config_enable().
int32_t uart_scratch_read (void)
Definition at line 249 of file family_55xx.c.
{
    // Return the value stored in the UART Scratch Pad Register
    return PAC55XX_UARTC->SCR.PAD;
}
References PAC55XX_UARTC.
void uart_scratch_write (int32_t value)
Definition at line 243 of file family_55xx.c.
{
    // Set the UART Scratch Pad Register value
    PAC55XX_UARTC->SCR.PAD = value;
}
References PAC55XX_UARTC.
void USARTC_IRQHandler (void)
Definition at line 168 of file family_55xx.c.
{
    uint8_t int_type;
    uint8_t data;
    volatile int32_t var;
    for (var = 0; var < 6; ++var)
    {
        __NOP();
    }
    int_type = pac5xxx_uart_interrupt_identification2(PAC55XX_UARTC);
    if (int_type == UARTIIR_INTID_TX_HOLD_EMPTY)
    {
        pac5xxx_uart_write2(PAC55XX_UARTC, uart_tx_buffer[uart_tx_byte_count++]);
        if (uart_tx_byte_count == UART_MESSAGE_SIZE) // Last byte of message to transmit
        {
            pac5xxx_uart_int_enable_THREI2(PAC55XX_UARTC, 0); // Disable transmit interrupt
            pac5xxx_uart_int_enable_RDAI2(PAC55XX_UARTC, 1); // Enable receive data interrupt for next incoming message
            uart_tx_byte_count = 0;
        }
    }
    else
    {
        data = pac5xxx_uart_read2(PAC55XX_UARTC);
        if (uart_rx_byte_count == 0) // For the first byte received, the start byte must be 0x89
        {
            if (data != 0x89)
                return;
        }
        uart_rx_buffer[uart_rx_byte_count++] = data; // Store data in buffer and increment index
        if (uart_rx_byte_count == UART_MESSAGE_SIZE) // Received all bytes of message
        {
            uart_message_process(); // Process incoming message in uart_rx_buffer and put response in uart_tx_buffer
            uart_rx_byte_count = 0;
            uart_tx_byte_count = 0;
            pac5xxx_uart_int_enable_RDAI2(PAC55XX_UARTC, 0); // Disable receive data interrupt
            pac5xxx_uart_rx_fifo_reset2(PAC55XX_UARTC); // Reset RX FIFO, to clear RDAI interrupt
            pac5xxx_uart_int_enable_THREI2(PAC55XX_UARTC, 1); // Enable transmit intrerrupt to send reponse to host
        }
    }
}
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.