.TH "I2CADR_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2CADR_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_i2c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBGC\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBADDRESS\fP: 7"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 24"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file pac5xxx_i2c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t I2CADR_TYPEDEF::__pad0__"

.PP
Definition at line 34 of file pac5xxx_i2c\&.h\&.
.SS "\fB__IO\fP uint32_t I2CADR_TYPEDEF::ADDRESS"

.PP
Definition at line 33 of file pac5xxx_i2c\&.h\&.
.SS "\fB__IO\fP uint32_t I2CADR_TYPEDEF::GC"

.PP
Definition at line 32 of file pac5xxx_i2c\&.h\&.
.SS "\fB__IO\fP uint32_t I2CADR_TYPEDEF::w"

.PP
Definition at line 30 of file pac5xxx_i2c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
