.TH "I2CADR_MASK_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2CADR_MASK_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_i2c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBMASK\fP: 7"
.br
.ti -1c
.RI "   uint32_t \fB__pad1__\fP: 24"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file pac5xxx_i2c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t I2CADR_MASK_TYPEDEF::__pad0__"

.PP
Definition at line 42 of file pac5xxx_i2c\&.h\&.
.SS "uint32_t I2CADR_MASK_TYPEDEF::__pad1__"

.PP
Definition at line 44 of file pac5xxx_i2c\&.h\&.
.SS "\fB__IO\fP uint32_t I2CADR_MASK_TYPEDEF::MASK"

.PP
Definition at line 43 of file pac5xxx_i2c\&.h\&.
.SS "\fB__IO\fP uint32_t I2CADR_MASK_TYPEDEF::w"

.PP
Definition at line 40 of file pac5xxx_i2c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
