.TH "IO_DS_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO_DS_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_scc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP0DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP0ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP1DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP1ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP2DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP2ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP3DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP3ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP4DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP4ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP5DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP5ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP6DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP6ST\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP7DS\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP7ST\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file pac5xxx_scc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P0DS"

.PP
Definition at line 150 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P0ST"

.PP
Definition at line 151 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P1DS"

.PP
Definition at line 152 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P1ST"

.PP
Definition at line 153 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P2DS"

.PP
Definition at line 154 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P2ST"

.PP
Definition at line 155 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P3DS"

.PP
Definition at line 156 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P3ST"

.PP
Definition at line 157 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P4DS"

.PP
Definition at line 158 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P4ST"

.PP
Definition at line 159 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P5DS"

.PP
Definition at line 160 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P5ST"

.PP
Definition at line 161 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P6DS"

.PP
Definition at line 162 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P6ST"

.PP
Definition at line 163 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P7DS"

.PP
Definition at line 164 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::P7ST"

.PP
Definition at line 165 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_DS_TYPEDEF::w"

.PP
Definition at line 148 of file pac5xxx_scc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
