.TH "IO_MODE_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO_MODE_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_gpio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP0\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP1\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP2\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP3\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP4\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP5\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP6\fP: 2"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP7\fP: 2"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 16"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file pac5xxx_gpio\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t IO_MODE_TYPEDEF::__pad0__"

.PP
Definition at line 42 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P0"

.PP
Definition at line 34 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P1"

.PP
Definition at line 35 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P2"

.PP
Definition at line 36 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P3"

.PP
Definition at line 37 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P4"

.PP
Definition at line 38 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P5"

.PP
Definition at line 39 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P6"

.PP
Definition at line 40 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::P7"

.PP
Definition at line 41 of file pac5xxx_gpio\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MODE_TYPEDEF::w"

.PP
Definition at line 32 of file pac5xxx_gpio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
