.TH "IO_MUXSEL_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO_MUXSEL_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_scc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP0\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad0__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP1\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad1__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP2\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad2__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP3\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad3__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP4\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad4__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP5\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad5__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP6\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad6__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint32_t \fBP7\fP: 3"
.br
.ti -1c
.RI "   uint32_t \fB__pad7__\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file pac5xxx_scc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad0__"

.PP
Definition at line 107 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad1__"

.PP
Definition at line 109 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad2__"

.PP
Definition at line 111 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad3__"

.PP
Definition at line 113 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad4__"

.PP
Definition at line 115 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad5__"

.PP
Definition at line 117 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad6__"

.PP
Definition at line 119 of file pac5xxx_scc\&.h\&.
.SS "uint32_t IO_MUXSEL_TYPEDEF::__pad7__"

.PP
Definition at line 121 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P0"

.PP
Definition at line 106 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P1"

.PP
Definition at line 108 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P2"

.PP
Definition at line 110 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P3"

.PP
Definition at line 112 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P4"

.PP
Definition at line 114 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P5"

.PP
Definition at line 116 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P6"

.PP
Definition at line 118 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::P7"

.PP
Definition at line 120 of file pac5xxx_scc\&.h\&.
.SS "\fB__IO\fP uint32_t IO_MUXSEL_TYPEDEF::w"

.PP
Definition at line 104 of file pac5xxx_scc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
