.TH "IPSR_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPSR_Type \- Union type to access the Interrupt Program Status Register (IPSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBIPSR_Type::ISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fBIPSR_Type::_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Interrupt Program Status Register (IPSR)\&. 
.PP
Definition at line 259 of file core_cm4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
