.TH "PAC55XX_INFO3_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC55XX_INFO3_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRMASK\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWMASK\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [4]"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIMASK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBSECLEVEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 200 of file pac5xxx_memory\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint8_t PAC55XX_INFO3_TYPEDEF::IMASK"

.PP
Definition at line 206 of file pac5xxx_memory\&.h\&.
.SS "uint32_t PAC55XX_INFO3_TYPEDEF::RESERVED1[4]"

.PP
Definition at line 203 of file pac5xxx_memory\&.h\&.
.SS "uint32_t PAC55XX_INFO3_TYPEDEF::RESERVED2[4]"

.PP
Definition at line 205 of file pac5xxx_memory\&.h\&.
.SS "\fB__IO\fP uint32_t PAC55XX_INFO3_TYPEDEF::RMASK[4]"

.PP
Definition at line 202 of file pac5xxx_memory\&.h\&.
.SS "\fB__IO\fP uint8_t PAC55XX_INFO3_TYPEDEF::SECLEVEL"

.PP
Definition at line 207 of file pac5xxx_memory\&.h\&.
.SS "\fB__IO\fP uint32_t PAC55XX_INFO3_TYPEDEF::WMASK[4]"

.PP
Definition at line 204 of file pac5xxx_memory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
