.TH "pac_foc/pac55xx/pac55xx_sdk/device/pac5532.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/device/pac5532.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx\&.h'\fP
.br
\fC#include 'pac5xxx_tile_driver_manager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_power_manager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_signal_manager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_system_manager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPAC5532\fP"
.br
.ti -1c
.RI "#define \fBCAFE_ARCH2\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAFE_ARCH2"

.PP
Definition at line 18 of file pac5532\&.h\&.
.SS "#define PAC5532"

.PP
Definition at line 17 of file pac5532\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
