.TH "pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_system.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_system.h \- Firmware driver for the PAC5XXX system and clock controllers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx\&.h'\fP
.br
\fC#include 'pac5xxx_driver_config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAMFUNC_SYSTEM\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_SYSTEM\fP void \fBpac5xxx_sys_pll_config_enable\fP (uint32_t pllindiv, uint32_t pllfbdiv, uint32_t plloutdiv)"
.br
.RI "This function configures and enables the PLL with the given frequency output using CLKREF\&. "
.ti -1c
.RI "void \fBpac_recovery\fP (void)"
.br
.RI "When PAC_RECOVERY is defined, this function will insert a 3-second delay on startup if PE3 is low\&. "
.ti -1c
.RI "void \fBpac_delay_asm\fP (uint32_t counts)"
.br
.RI "Implements a delay in assembly\&. "
.ti -1c
.RI "\fBPAC5XXX_RAMFUNC\fP void \fBpac_delay_asm_ramfunc\fP (uint32_t counts)"
.br
.RI "Implementes a delay executing from SRAM\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX system and clock controllers\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2020, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_system\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
