.TH "PAC55XX_INFO1_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC55XX_INFO1_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_memory\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBUNIQUEID\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file pac5xxx_memory\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t PAC55XX_INFO1_TYPEDEF::UNIQUEID[3]"

.PP
Definition at line 165 of file pac5xxx_memory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
