.TH "pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_uart.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_uart.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_uart\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_LCR2\fP (\fBPAC55XX_UART_TYPEDEF\fP *uart_ptr, \fBUARTLCR_WL_TYPE\fP bpc, \fBUART_STOPBITS_TYPE\fP stop_bits, \fBUART_PEN_TYPE\fP parity_enabled, \fBUART_PARITY_TYPE\fP parity, \fBUART_BREAKCONTROL_TYPE\fP break_control)"
.br
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_divisor_latch2\fP (\fBPAC55XX_UART_TYPEDEF\fP *uart_ptr, uint32_t latch_value)"
.br
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_io_config2\fP ()"
.br
.RI "This function configures IO for use with the UART peripheral\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
