.TH "pac_foc/pac55xx/pac55xx_sdk/peripheral/pac5xxx_gp_timers.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/peripheral/pac5xxx_gp_timers.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPAC55XX_GPTTIMER_TYPEDEF\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGPTCTL_PS_TYPE\fP { \fBGPTCTL_PS_DIV1\fP = 0, \fBGPTCTL_PS_DIV2\fP = 1, \fBGPTCTL_PS_DIV4\fP = 2, \fBGPTCTL_PS_DIV8\fP = 3, \fBGPTCTL_PS_DIV16\fP = 4, \fBGPTCTL_PS_DIV32\fP = 5, \fBGPTCTL_PS_DIV64\fP = 6, \fBGPTCTL_PS_DIV128\fP = 7, \fBGPTCTL_PS_DIV256\fP = 8, \fBGPTCTL_PS_DIV512\fP = 9, \fBGPTCTL_PS_DIV1024\fP = 10, \fBGPTCTL_PS_DIV2018\fP = 11, \fBGPTCTL_PS_DIV4096\fP = 12, \fBGPTCTL_PS_DIV8192\fP = 13, \fBGPTCTL_PS_DIV16384\fP = 14, \fBGPTCTL_PS_DIV32768\fP = 15 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGPTCTL_PS_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGPTCTL_PS_DIV1 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV2 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV4 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV8 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV16 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV32 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV64 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV128 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV256 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV512 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV1024 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV2018 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV4096 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV8192 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV16384 \fP\fP
.TP
\fB\fIGPTCTL_PS_DIV32768 \fP\fP
.PP
Definition at line 21 of file pac5xxx_gp_timers\&.h\&.
.PP
.nf
21              {
22     GPTCTL_PS_DIV1             = 0,                // GPTimer pre-scaler: /1
23     GPTCTL_PS_DIV2             = 1,                // GPTimer pre-scaler: /2
24     GPTCTL_PS_DIV4             = 2,                // GPTimer pre-scaler: /4
25     GPTCTL_PS_DIV8             = 3,                // GPTimer pre-scaler: /8
26     GPTCTL_PS_DIV16            = 4,                // GPTimer pre-scaler: /16
27     GPTCTL_PS_DIV32            = 5,                // GPTimer pre-scaler: /32
28     GPTCTL_PS_DIV64            = 6,                // GPTimer pre-scaler: /64
29     GPTCTL_PS_DIV128           = 7,                // GPTimer pre-scaler: /128   
30     GPTCTL_PS_DIV256           = 8,                // GPTimer pre-scaler: /256   
31     GPTCTL_PS_DIV512           = 9,                // GPTimer pre-scaler: /512
32     GPTCTL_PS_DIV1024          = 10,               // GPTimer pre-scaler: /1024
33     GPTCTL_PS_DIV2018          = 11,               // GPTimer pre-scaler: /2018
34     GPTCTL_PS_DIV4096          = 12,               // GPTimer pre-scaler: /4096
35     GPTCTL_PS_DIV8192          = 13,               // GPTimer pre-scaler: /18192
36     GPTCTL_PS_DIV16384         = 14,               // GPTimer pre-scaler: /16384
37     GPTCTL_PS_DIV32768         = 15,               // GPTimer pre-scaler: /32768
38 } GPTCTL_PS_TYPE;
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
