.TH "pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_gpio.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_gpio.c \- Firmware driver for the PAC5XXX GPIOs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_gpio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_a\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.RI "This function configures interrupts for the given pins on the given port and enables them\&. "
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_b\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_c\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_d\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_e\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_f\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.ti -1c
.RI "\fBRAMFUNC_GPIO\fP void \fBpac5xxx_gpio_configure_interrupt_g\fP (uint8_t port_mask, uint8_t active_high_mask)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX GPIOs\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_gpio\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
