.TH "PAC55XX_GPIO_TYPEDEF" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC55XX_GPIO_TYPEDEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_gpio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIO_MODE_TYPEDEF\fP \fBMODE\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBOUTMASK\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBOUT\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBIN\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTEN\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTFLAG\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTCLEAR\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTTYPE\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTCFG\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBINTEDGEBOTH\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBCLKSYNC\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBDOSET\fP"
.br
.ti -1c
.RI "\fBIO_PINS_TYPEDEF\fP \fBDOCLEAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file pac5xxx_gpio\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::CLKSYNC"

.PP
Definition at line 79 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::DOCLEAR"

.PP
Definition at line 81 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::DOSET"

.PP
Definition at line 80 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::IN"

.PP
Definition at line 71 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTCFG"

.PP
Definition at line 77 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTCLEAR"

.PP
Definition at line 75 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTEDGEBOTH"

.PP
Definition at line 78 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTEN"

.PP
Definition at line 72 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTFLAG"

.PP
Definition at line 73 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::INTTYPE"

.PP
Definition at line 76 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_MODE_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::MODE"

.PP
Definition at line 68 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::OUT"

.PP
Definition at line 70 of file pac5xxx_gpio\&.h\&.
.SS "\fBIO_PINS_TYPEDEF\fP PAC55XX_GPIO_TYPEDEF::OUTMASK"

.PP
Definition at line 69 of file pac5xxx_gpio\&.h\&.
.SS "uint32_t PAC55XX_GPIO_TYPEDEF::RESERVED"

.PP
Definition at line 74 of file pac5xxx_gpio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
