.TH "pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_socbridge.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_socbridge.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_socbridge\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config\fP (int enable, int int_enable)"
.br
.RI "This function configures and enables the SOC bridge\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config_io\fP (void)"
.br
.RI "This function configures the IO ports on the device for SOC bridge operation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
