.TH "pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_socbridge.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/driver/pac5xxx_driver_socbridge.h \- Firmware driver for the PAC5XXX SOC Bridge\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5XXX\&.h'\fP
.br
\fC#include 'pac5xxx_driver_config\&.h'\fP
.br
\fC#include 'pac5xxx_driver_gpio\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAMFUNC_SOCBRIDGE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config\fP (int enable, int int_enable)"
.br
.RI "This function configures and enables the SOC bridge\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config_io\fP (void)"
.br
.RI "This function configures the IO ports on the device for SOC bridge operation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX SOC Bridge\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2020, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_socbridge\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
