.TH "pac_foc/pac55xx/pac55xx_sdk/pac5xxx_sdk_version.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/pac55xx_sdk/pac5xxx_sdk_version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDK_VERSION_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_MINOR\fP   6"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_BUGFIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_RELEASE_STATE\fP   \fBPAC5XXX_RELEASED\fP"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_RELEASE_NUM\fP   0"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_STR\fP   'v1\&.6\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SDK_VERSION_BUGFIX   1"

.PP
Definition at line 21 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_MAJOR   1"

.PP
\fBNote\fP
.RS 4
Copyright (C) 2017-2020, Qorvo, Inc\&.
.RE
.PP
\fB\fP
.RS 4
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.RE
.PP

.PP
Definition at line 19 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_MINOR   6"

.PP
Definition at line 20 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_RELEASE_NUM   0"

.PP
Definition at line 23 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_RELEASE_STATE   \fBPAC5XXX_RELEASED\fP"

.PP
Definition at line 22 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_STR   'v1\&.6\&.1'"

.PP
Definition at line 24 of file pac5xxx_sdk_version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
