PAC5XXX_Driver_Timer
NAME
PAC5XXX_Driver_Timer - PAC5XXX Analog Timer and DTG Driver
SYNOPSIS
Macros
#define RAMFUNC_TIMER
Enumerations
enum TimerInstance { TimerA, TimerB, TimerC, TimerD }
Functions
RAMFUNC_TIMER void pac5xxx_timer_base_config (TimerInstance timer, uint16_t period, int single_shot, TXCTRL_MODE_Type mode, int sync)
This function configures the base timer period, mode and single-use mode for the given timer.
RAMFUNC_TIMER void pac5xxx_dtg_config2 (DTGCTL_TYPEDEF *p_dtg, uint16_t red, uint16_t fed)
This function configures and enables the given Dead-Time Generator (DTG)
RAMFUNC_TIMER void pac5xxx_timer_clock_config (TimerInstance timer, TXCTRL_CLKIN_Type source, TXCTRL_PS_Type prescale)
This function configures the clock source and pre-scaler for the given timer.
Detailed Description
Macro Definition Documentation
#define RAMFUNC_TIMER
Definition at line 32 of file pac5xxx_driver_timer.h.
Enumeration Type Documentation
enum TimerInstance
Timer Instance for Timer Driver Configuration
Enumerator
TimerA
TimerB
TimerC
TimerD
Definition at line 36 of file pac5xxx_driver_timer.h.
             {
    TimerA,
    TimerB,
    TimerC,
    TimerD
} TimerInstance;
Function Documentation
RAMFUNC_TIMER void pac5xxx_dtg_config2 (DTGCTL_TYPEDEF * p_dtg, uint16_t red, uint16_t fed)
This function configures and enables the given Dead-Time Generator (DTG)
Parameters
p_dtg DTG Instance
red Risigin Edge Delay
fed Trailing Edge Delay
Returns
none
Definition at line 20 of file pac5xxx_driver_timer.c.
{
    p_dtg->RED = red;
    p_dtg->FED = fed;
    p_dtg->DTEN = 1;
}
References DTGCTL_TYPEDEF::DTEN, DTGCTL_TYPEDEF::FED, and DTGCTL_TYPEDEF::RED.
Referenced by configure_foc_timer().
RAMFUNC_TIMER void pac5xxx_timer_base_config (TimerInstance timer, uint16_t period, int single_shot, TXCTRL_MODE_Type mode, int sync)
This function configures the base timer period, mode and single-use mode for the given timer.
Parameters
timer Timer Instance
period Timer Period in clock ticks
single_shot Set to 1 for single-use timer mode, 0 for auto-reload
mode Timer Mode (up, up/down, etc.)
sync Timer slave synchronize (set for slave sync) if set to 1
Returns
none
Definition at line 51 of file pac5xxx_driver_timer.c.
{
    PAC55XX_TIMER_TYPEDEF * p_timer = PAC55XX_TIMERD;
    
    switch (timer)
    {
        case TimerA:
            p_timer = PAC55XX_TIMERA;
            break;
        case TimerB:
            p_timer = PAC55XX_TIMERB;
            break;
        case TimerC:
            p_timer = PAC55XX_TIMERC;
            break;
        case TimerD:
            p_timer = PAC55XX_TIMERD;
            break;
    }
        
    p_timer->CTL.SSYNC = slave_sync; // Be sure to set sync bit first
    p_timer->PRD.w = period;
    p_timer->CTL.MODE = mode;
    p_timer->CTL.SINGLE = single_shot;
 
}
References PAC55XX_TIMER_TYPEDEF::CTL, TIMER_CTL_TYPEDEF::MODE, PAC55XX_TIMERA, PAC55XX_TIMERB, PAC55XX_TIMERC, PAC55XX_TIMERD, PAC55XX_TIMER_TYPEDEF::PRD, TIMER_CTL_TYPEDEF::SINGLE, TIMER_CTL_TYPEDEF::SSYNC, TimerA, TimerB, TimerC, TimerD, and PAC55XX_TIMER_TYPEDEF::w.
Referenced by configure_foc_timer(), and configure_pwm_dac().
RAMFUNC_TIMER void pac5xxx_timer_clock_config (TimerInstance timer, TXCTRL_CLKIN_Type source, TXCTRL_PS_Type prescale)
This function configures the clock source and pre-scaler for the given timer.
Parameters
timer Timer Instance
source Timer clock input source
prescale Timer pre-scaler
Returns
none
Definition at line 27 of file pac5xxx_driver_timer.c.
{
    PAC55XX_TIMER_TYPEDEF * p_timer = PAC55XX_TIMERD;;
    
    switch (timer)
    {
        case TimerA:
            p_timer = PAC55XX_TIMERA;
            break;
        case TimerB:
            p_timer = PAC55XX_TIMERB;
            break;
        case TimerC:
            p_timer = PAC55XX_TIMERC;
            break;
        case TimerD:
            p_timer = PAC55XX_TIMERD;
            break;
    }
    
    p_timer->CTL.CLKSRC = source;
    p_timer->CTL.CLKDIV = prescale;
}
References TIMER_CTL_TYPEDEF::CLKDIV, TIMER_CTL_TYPEDEF::CLKSRC, PAC55XX_TIMER_TYPEDEF::CTL, PAC55XX_TIMERA, PAC55XX_TIMERB, PAC55XX_TIMERC, PAC55XX_TIMERD, TimerA, TimerB, TimerC, and TimerD.
Referenced by configure_foc_timer(), and configure_pwm_dac().
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC55XX from the source code.