.TH "pac_foc/pac55xx/iar_proj/project_build_info_iar.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac55xx/iar_proj/project_build_info_iar.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROJECT_BUILD_STR\fP   '20200814\&.180740'"
.br
.ti -1c
.RI "#define \fBPROJECT_BUILD_DATE_STR\fP   '20200814'"
.br
.ti -1c
.RI "#define \fBPROJECT_BUILD_DATE_NUM\fP   20200814"
.br
.ti -1c
.RI "#define \fBPROJECT_BUILD_TIME_STR\fP   '180740'"
.br
.ti -1c
.RI "#define \fBPROJECT_BUILD_TIME_NUM\fP   180740"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROJECT_BUILD_DATE_NUM   20200814"

.PP
Definition at line 13 of file project_build_info_iar\&.h\&.
.SS "#define PROJECT_BUILD_DATE_STR   '20200814'"

.PP
Definition at line 12 of file project_build_info_iar\&.h\&.
.SS "#define PROJECT_BUILD_STR   '20200814\&.180740'"

.PP
Definition at line 11 of file project_build_info_iar\&.h\&.
.SS "#define PROJECT_BUILD_TIME_NUM   180740"

.PP
Definition at line 15 of file project_build_info_iar\&.h\&.
.SS "#define PROJECT_BUILD_TIME_STR   '180740'"

.PP
Definition at line 14 of file project_build_info_iar\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
