.TH "PROTSTAT" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PROTSTAT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::LPROT10\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::LPROT32\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::LPROT54\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBPROTSTAT::__pad0__\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::HPROT10\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::HPROT32\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPROTSTAT::HPROT54\fP: 1"
.br
.ti -1c
.RI "   uint8_t \fBPROTSTAT::__pad1__\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 444 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
