.TH "PWRCTL" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWRCTL
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_power_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPWRCTL::WUTIMER\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPWRCTL::PWRMON\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPWRCTL::MCUALIVE\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBPWRCTL::HIB\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
< Power Manager Tile Registers
.PP
< \fBPWRCTL\fP: Address: 0x10 Power Manager Control Register 
.PP
Definition at line 152 of file pac5xxx_tile_power_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
