.TH "SCFG" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCFG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_power_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::DMAX\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::FSWM\fP: 3"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::FMODE\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::VCLAMPSEL\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::DIGCTL\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSCFG::SRST\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 197 of file pac5xxx_tile_power_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
