.TH "SIGSTAT" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SIGSTAT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_tile_signal_manager\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint8_t \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::HPDACAB2\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::LPDACAB3\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::LPROTHYS\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::HPROTHYS\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::AIO6HYS\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::AIO7HYS\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::AIO8HYS\fP: 1"
.br
.ti -1c
.RI "   \fB__IO\fP uint8_t \fBSIGSTAT::AIO9HYS\fP: 1"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 378 of file pac5xxx_tile_signal_manager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
