.TH "TPI_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC55XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPI_Type \- Structure type to access the Trace Port Interface Register (TPI)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm4\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSSPSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSPSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBACPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [55]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [131]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFFSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFFCR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [759]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBTRIGGER\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFIFO0\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBITATBCTR2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [1]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBITATBCTR0\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBFIFO1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBITCTRL\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [39]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLAIMSET\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCLAIMCLR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED7\fP [8]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBDEVID\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBDEVTYPE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Trace Port Interface Register (TPI)\&. 
.PP
Definition at line 904 of file core_cm4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC55XX from the source code\&.
