
/**
 * @file param_calc.h
 * @brief Use for parameter processing
 */

//=============================================================================
// Copyright (C) 2020 - 2022, Qorvo, Inc.
//
// THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES,
// AMONG OTHER THINGS:  (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S
// APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC.;
// (ii) THAT  IT IS PROVIDED "AS IS" WITHOUT WARRANTY;  (iii) THAT
// QORVO, INC. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT
// DAMAGES EXCEEDING US$1,500;  AND (iv) THAT IT CAN BE DISCLOSED TO AND USED
// ONLY BY CERTAIN AUTHORIZED PERSONS.
//
//=============================================================================

#ifndef PARAMCALC_H
#define PARAMCALC_H

#include "maths.h"
#include "config_app.h"
#include "param.h"

#define LPDAC 0
#define HPDAC 1

#define CURRENT_SCALE_FACTOR_FLT                            (float)(1.25f / (PCB_RSENSE_IUVW_OHMS * (float)PUSER_VALUE_DIFFAMP_GAIN_FINAL))
#define CURRENT_SCALE_FACTOR_Q16                            QCONST(CURRENT_SCALE_FACTOR_FLT, Q16)
#define CURRENT_SCALE_FACTOR_X1_FLT                         (float)(1.25f / PCB_RSENSE_IUVW_OHMS)
#define CURRENT_SCALE_FACTOR_X1_Q16                         QCONST(CURRENT_SCALE_FACTOR_X1_FLT, Q16)

// Control Config
#define MOTOR1_PERIOD_TICKS                                 QCONST(((TIMERCLK_FREQ_HZ / (float)PUSER_VALUE_PWM_FREQ_HZ) + 0.5f), Q00)
#define FOC_DIVIDER                                         PUSER_VALUE_CONTROL_FREQ_DIV
#define CONTROLFREQ_HZ_FLT                                  (float)((float)PUSER_VALUE_PWM_FREQ_HZ / (float)PUSER_VALUE_CONTROL_FREQ_DIV)
#define FOC_DT_FLT                                          (float)(1.0f / CONTROLFREQ_HZ_FLT)
#define FOC_DT_Q26                                          QCONST(FOC_DT_FLT, Q26)

// Hardware Config
#if (PUSER_VALUE_DIFFAMP_GAIN == 0)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              0
#elif (PUSER_VALUE_DIFFAMP_GAIN == 1)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              1
#elif (PUSER_VALUE_DIFFAMP_GAIN == 2)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              2
#elif (PUSER_VALUE_DIFFAMP_GAIN == 4)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              3
#elif (PUSER_VALUE_DIFFAMP_GAIN == 8)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              4
#elif (PUSER_VALUE_DIFFAMP_GAIN == 16)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              5
#elif (PUSER_VALUE_DIFFAMP_GAIN == 32)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              6
#elif (PUSER_VALUE_DIFFAMP_GAIN == 48)
    #define UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE              7
#else
    #error: Invalid value for PUSER_VALUE_DIFFAMP_GAIN.
#endif

// Motor Config
#define FOC_LD_DEFAULT_VALUE                                QCONST(PUSER_VALUE_LD_UH / 1000000.0f, Q26)
#define FOC_LQ_DEFAULT_VALUE                                QCONST(PUSER_VALUE_LQ_UH / 1000000.0f, Q26)
#define FOC_RALPHA_DEFAULT_VALUE                            QCONST(PUSER_VALUE_R_OHMS, Q16)
#define FOC_NUM_POLE_PAIRS_DEFAULT_VALUE                    PUSER_VALUE_POLE_PAIRS
#define NOMINAL_SPEED_DEFAULT_VALUE                         QCONST((PUSER_VALUE_NOMINAL_SPEED * FLT_2PI), Q16)

// Application Config
#define CLOSE_LOOP_MIN_SPEED_LIMIT_DEFAULT_VALUE            QCONST((PUSER_VALUE_SPEED_SETPOINT_OL_HZ * FLT_PI), Q16)
#define CLOSE_LOOP_MAX_SPEED_LIMIT_DEFAULT_VALUE            QCONST((PUSER_VALUE_SPEED_MAX_HZ * FLT_2PI), Q16)
#define CLOSE_LOOP_MAX_POWER_LIMIT_DEFAULT_VALUE            QCONST((PUSER_VALUE_POWER_MAX_W), Q16)
#define SPEED_PID_MIN_DEFAULT_VALUE                         QCONST((PUSER_VALUE_IQ_MIN_A / CURRENT_SCALE_FACTOR_FLT), Q16)
#define SPEED_PID_MAX_DEFAULT_VALUE                         QCONST((PUSER_VALUE_IQ_MAX_A / CURRENT_SCALE_FACTOR_FLT), Q16)
#if (PUSER_VALUE_OC_DAC == LPDAC)
    #define MOTOR_CURRENT_LIMIT_LPDAC                       (float)((((PUSER_VALUE_OC_LIMIT_A * PCB_RSENSE_IUVW_OHMS * PUSER_VALUE_DIFFAMP_GAIN) + 1.25f) / 2.5f) * 1023)
    #define MOTOR_CURRENT_LIMIT_DEFAULT_VALUE               QCONST((MOTOR_CURRENT_LIMIT_LPDAC + 0.5f), Q00)
#else
    #define MOTOR_CURRENT_LIMIT_HPDAC                       (float)(((PUSER_VALUE_OC_LIMIT_A * PCB_RSENSE_OC_OHMS) / 2.5f) * 255)
    #define MOTOR_CURRENT_LIMIT_DEFAULT_VALUE               QCONST((MOTOR_CURRENT_LIMIT_HPDAC + 0.5f), Q00)
#endif
#define COAST_TIMEOUT_DEFAULT_VALUE                         QCONST(((PUSER_VALUE_CL_COAST_TIMEOUT_SEC / DT_DIVSYSTICK_FLT) + 0.5f), Q00)

// Startup Config (Align and Go)
#define FOC_OPEN_LOOP_SS_ALIGN_COUNT_DEFAULT_VALUE          QCONST(((PUSER_VALUE_ALIGN_TIME_SEC * CONTROLFREQ_HZ_FLT) + 0.5f), Q00)
#define ID_REF_SP_DEFAULT_VALUE                             QCONST((PUSER_VALUE_ID_REF_OL_A / CURRENT_SCALE_FACTOR_FLT), Q16)
#define IQ_REF_SP_DEFAULT_VALUE                             QCONST((PUSER_VALUE_ITOTAL_REF_OL_A / CURRENT_SCALE_FACTOR_FLT), Q16)
#define FOC_CUR_CTRL_OPEN_LOOP_SLEW_RATE_DEFAULT_VALUE_Q26  QCONST((PUSER_VALUE_SPEED_RAMP_OL_HZPSEC * FLT_2PI * FOC_DT_FLT * FOC_DT_FLT), Q26)
#define FOC_OPEN_LOOP_SPEED_SET_POINT_DEFAULT_VALUE_Q26     QCONST((PUSER_VALUE_SPEED_SETPOINT_OL_HZ * FLT_2PI * FOC_DT_FLT), Q26)
#define AUTO_CLOSE_LOOP_DEFAULT_VALUE                       PUSER_VALUE_AUTO_CLOSE_LOOP

// Control Config
#define ID_PID_KP_REF_DEFAULT_VALUE                         QCONST(PUSER_VALUE_PI_ID_KP, Q16)
#define ID_PID_KI_REF_DEFAULT_VALUE                         QCONST(PUSER_VALUE_PI_ID_KI, Q16)
#define ID_PID_MIN_DEFAULT_VALUE                            QCONST(PUSER_VALUE_PI_ID_MIN, Q16)
#define ID_PID_MAX_DEFAULT_VALUE                            QCONST(PUSER_VALUE_PI_ID_MAX, Q16)
#define ID_FILTER_GAIN_DEFAULT_VALUE                        QCONST((FOC_DT_FLT / (FOC_DT_FLT + (1 / (FLT_2PI * PUSER_VALUE_FC_ID_HZ)))), Q16)
#define IQ_PID_KP_REF_DEFAULT_VALUE                         QCONST(PUSER_VALUE_PI_IQ_KP, Q16)
#define IQ_PID_KI_REF_DEFAULT_VALUE                         QCONST(PUSER_VALUE_PI_IQ_KI, Q16)
#define IQ_PID_MIN_DEFAULT_VALUE                            QCONST(PUSER_VALUE_PI_IQ_MIN, Q16)
#define IQ_PID_MAX_DEFAULT_VALUE                            QCONST(PUSER_VALUE_PI_IQ_MAX, Q16)
#define IQ_FILTER_GAIN_DEFAULT_VALUE                        QCONST((FOC_DT_FLT / (FOC_DT_FLT + (1 / (FLT_2PI * PUSER_VALUE_FC_IQ_HZ)))), Q16)
#define IDIQ_RAMP_RATE_DEFAULT_VALUE                        QCONST((PUSER_VALUE_IDIQ_RAMP_APSEC / CURRENT_SCALE_FACTOR_FLT * FOC_DT_FLT), Q16)

// Speed Control
#define SPEED_PID_KP_REF_DEFAULT_VALUE                      QCONST(PUSER_VALUE_PI_SPEED_KP, Q16)
#define SPEED_PID_KI_REF_DEFAULT_VALUE                      QCONST(PUSER_VALUE_PI_SPEED_KI, Q16)
#define FOC_CLOSE_LOOP_SPEED_SLEW_RATE_DEFAULT_VALUE        QCONST((PUSER_VALUE_SPEED_RAMP_HZPSEC * FLT_2PI * FOC_DT_FLT), Q16)

// Power Control
#define POWER_PID_KP_REF_DEFAULT_VALUE                      QCONST(PUSER_VALUE_PI_POWER_KP, Q16)
#define POWER_PID_KI_REF_DEFAULT_VALUE                      QCONST(PUSER_VALUE_PI_POWER_KI, Q16)
#define FOC_CLOSE_LOOP_POWER_SLEW_RATE_DEFAULT_VALUE        QCONST((PUSER_VALUE_POWER_RAMP_WPSEC * FOC_DT_FLT), Q16)

// Operation
#define CLOSE_LOOP_SPEED_MODE_DEFAULT_VALUE                 PUSER_VALUE_CL_MODE
#define MOTOR_DIRECTION_REVERSE_FLAG_DEFAULT_VALUE          PUSER_VALUE_REVERSE
#define FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE         QCONST((PUSER_VALUE_SPEED_SETPOINT_CL_HZ * FLT_2PI), Q16)
#define FOC_CLOSE_LOOP_POWER_SETPOINT_DEFAULT_VALUE         QCONST((PUSER_VALUE_POWER_SETPOINT_CL_W), Q16)
#define ID_REF_CLOSE_LOOP_REF_DEFAULT_VALUE                 QCONST((PUSER_VALUE_ID_REF_CL_A / CURRENT_SCALE_FACTOR_FLT), Q16)
#define IQ_REF_CLOSE_LOOP_REF_DEFAULT_VALUE                 QCONST((PUSER_VALUE_IQ_REF_CL_A / CURRENT_SCALE_FACTOR_FLT), Q16)

// LBG1 Estimator
#define EST_LBG1_BANDWIDTH_DEFAULT_VALUE                    QCONST(PUSER_VALUE_LBG1_BANDWIDTH, Q16)
#define EST_LBG1_DAMPINGFACTOR_DEFAULT_VALUE                QCONST(PUSER_VALUE_LBG1_DAMPINGFACTOR, Q16)
#define EST_LBG1_KSPEED_DEFAULT_VALUE                       QCONST(PUSER_VALUE_LBG1_FC_SPEED_HZ, Q16)
#define EST_LBG1_ANGLE_OFFSET_DEFAULT_VALUE                 QCONST((PUSER_VALUE_LBG1_ANGLE_OFFSET_DEG * FLT_PI / 180.0f), Q16)
#define EST_LBG1_ANGLE_FACTOR_DEFAULT_VALUE                 QCONST((PUSER_VALUE_LBG1_ANGLE_FACTOR_DEGPHZ / 360.0f * 16.0f), Q16)
#define EST_LBG1_FC_BEMF_MAGNITUDE_DEFAULT_VALUE            QCONST(PUSER_VALUE_LBG1_FC_BEMF_MAG_HZ, Q16)

// SIM
#define SIM_BRAKING_ALIGN_TIME_DEFAULT_VALUE                QCONST(((PUSER_VALUE_SIM_ALIGN_SEC * CONTROLFREQ_HZ_FLT) + 0.5f), Q00)
#define SIM_BRAKING_ID_REF_MUL_DEFAULT_VALUE                QCONST(PUSER_VALUE_SIM_IDIQ_GAIN, Q16)
#define SIM_BRAKING_IQ_REF_MUL_DEFAULT_VALUE                QCONST(PUSER_VALUE_SIM_IDIQ_GAIN, Q16)
#define SIM_BEMF_BRAKING_TIMEOUT_COUNT_DEFAULT_VALUE        QCONST(((PUSER_VALUE_SIM_BTO_SEC * CONTROLFREQ_HZ_FLT) + 0.5f), Q00)
#if (PUSER_VALUE_SIM_AMP_GAIN == 0)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 0
#elif (PUSER_VALUE_SIM_AMP_GAIN == 1)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 1
#elif (PUSER_VALUE_SIM_AMP_GAIN == 2)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 2
#elif (PUSER_VALUE_SIM_AMP_GAIN == 4)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 3
#elif (PUSER_VALUE_SIM_AMP_GAIN == 8)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 4
#elif (PUSER_VALUE_SIM_AMP_GAIN == 16)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 5
#elif (PUSER_VALUE_SIM_AMP_GAIN == 32)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 6
#elif (PUSER_VALUE_SIM_AMP_GAIN == 48)
    #define SIM_BEMF_AMP_GAIN_DEFAULT_VALUE                 7
#endif
#define SIM_CURRENT_TRACK_GAIN_DEFAULT_VALUE                QCONST(PUSER_VALUE_SIM_CURRENT_TRACK_GAIN, Q16)

// Stall Detection
#define STALL_BEMF_CONSTANT_DEFAULT_VALUE                   QCONST((PUSER_VALUE_STALL_KE / FLT_2PI), Q16)
#define STALL_DETECT_TIME_DEFAULT_VALUE                     QCONST(((PUSER_VALUE_STALL_WINDOW_SEC / DT_DIVSYSTICK_FLT) + 0.5f), Q00)

// IPD
#define IPD_CHARGE_TICKS_DEFAULT_VALUE                      PUSER_VALUE_IPD_CHARGE
#define IPD_DISCHARGE_PERCENT_DEFAULT_VALUE                 PUSER_VALUE_IPD_DISCHARGE
#define IPD_PERIODS_PER_PULSE_DEFAULT_VALUE                 PUSER_VALUE_IPD_PERIODS
#define IPD_ANGLE_FORWARD_OFFSET_DEFAULT_VALUE              QCONST(PUSER_VALUE_IPD_OFFSET_FORWARD_DEG, Q16)
#define IPD_ANGLE_REVERSE_OFFSET_DEFAULT_VALUE              QCONST(PUSER_VALUE_IPD_OFFSET_REVERSE_DEG, Q16)

// Field Weakening
#define FIELD_WEAKENING_SPEED_THRESHOLD_VALUE               QCONST((PUSER_VALUE_FW_SPEED * FLT_2PI), Q16)
#define FIELD_WEAKENING_ID_REF_VALUE                        QCONST((PUSER_VALUE_FW_ID / CURRENT_SCALE_FACTOR_FLT), Q16)
#define FIELD_WEAKENING_VDRIVE_THRESHOLD_VALUE              QCONST((PUSER_VALUE_FW_VDRIVE / 100.0f), Q16)
#define FIELD_WEAKENING_PID_KP_REF_DEFAULT_VALUE            QCONST(PUSER_VALUE_FW_PID_KP, Q16)
#define FIELD_WEAKENING_PID_KI_REF_DEFAULT_VALUE            QCONST(PUSER_VALUE_FW_PID_KI, Q16)
#define FIELD_WEAKENING_VMAX_SCL_FACTOR_DEFAULT_VALUE       QCONST(PUSER_VALUE_FW_VMAX_SCL_FACTOR, Q16)

// MTPA
#define MTPA_DEGPAMP_DEFAULT_VALUE                          QCONST(PUSER_VALUE_MTPA_DEGPAMP_FIX16, Q16)

//// Misc (not part of parameter_process)
//#define MISC_FIX16_VAR1_DEFAULT_VALUE                       QCONST(PUSER_VALUE_MISC_FIX16_1, Q16)
//#define MISC_FIX16_VAR2_DEFAULT_VALUE                       QCONST(PUSER_VALUE_MISC_FIX16_2, Q16)
//#define MISC_FIX16_VAR3_DEFAULT_VALUE                       QCONST(PUSER_VALUE_MISC_FIX16_3, Q16)
//#define MISC_UINT32_VAR1_DEFAULT_VALUE                      PUSER_VALUE_MISC_UINT32_1
//#define MISC_UINT32_VAR2_DEFAULT_VALUE                      PUSER_VALUE_MISC_UINT32_2
//#define MISC_UINT32_VAR3_DEFAULT_VALUE                      PUSER_VALUE_MISC_UINT32_3

// Motor Configuration
#define AUTOTUNE_KE_DEFAULT_VALUE                           QCONST(PUSER_VALUE_AUTOTUNE_KE, Q26)
#define AUTOTUNE_J_DEFAULT_VALUE                            QCONST(PUSER_VALUE_AUTOTUNE_J, Q26)

// Hall Mode
#define DEFAULT_VALUE_HALL_ISTART_Q16                       QCONST((PUSER_VALUE_HALL_ISTART_AMPS / CURRENT_SCALE_FACTOR_FLT), Q16)
#define DEFAULT_VALUE_HALL_ANGCORR_GAIN_FWD_Q20             QCONST((PUSER_VALUE_HALL_ANGCORR_GAIN_FWD_DEGPHZ / 360.0f * 16.0f), Q16)
#define DEFAULT_VALUE_HALL_ANGCORR_GAIN_REV_Q20             QCONST((PUSER_VALUE_HALL_ANGCORR_GAIN_REV_DEGPHZ / 360.0f * 16.0f), Q16)
#define DEFAULT_VALUE_HALL_ANGCORR_OFFSET_FWD_Q16           QCONST((PUSER_VALUE_HALL_ANGCORR_OFFSET_FWD_DEG * FLT_PI / 180.0f), Q16)
#define DEFAULT_VALUE_HALL_ANGCORR_OFFSET_REV_Q16           QCONST((PUSER_VALUE_HALL_ANGCORR_OFFSET_REV_DEG * FLT_PI / 180.0f), Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_1_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_1_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_1_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_1_REV_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_2_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_2_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_2_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_2_REV_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_3_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_3_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_3_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_3_REV_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_4_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_4_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_4_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_4_REV_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_5_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_5_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_5_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_5_REV_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_6_FWD_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_6_FWD_RAD, Q16)
#define DEFAULT_VALUE_HALL_SNAPANGLE_6_REV_Q16              QCONST(PUSER_VALUE_HALL_SNAPANGLE_6_REV_RAD, Q16)

// Hall+Estimator Mode
#define DEFAULT_VALUE_HALL_HALL2EST_SWITCH_SPEED_Q16        QCONST((PUSER_VALUE_HALL_HALL2EST_SWITCH_SPEED_HZ * FLT_2PI), Q16)

// Hall Tuning
#define DEFAULT_VALUE_HALLTUNE_ISTART_Q16                   QCONST((PUSER_VALUE_HALLTUNE_ISTART_AMPS / CURRENT_SCALE_FACTOR_FLT), Q16)
#define DEFAULT_VALUE_HALLTUNE_RAMPRATE_Q26                 QCONST((PUSER_VALUE_HALLTUNE_RAMPRATE_HZPSEC * FLT_2PI * FOC_DT_FLT * FOC_DT_FLT), Q26)
#define DEFAULT_VALUE_HALLTUNE_SPEED_Q26                    QCONST((PUSER_VALUE_HALLTUNE_SPEED_HZ * FLT_2PI * FOC_DT_FLT), Q26)

#define DEFAULT_VALUE_HALL_MECH_ANGLE_OFFSET_DEG_Q16        QCONST(PUSER_VALUE_HALL_MECH_ANGLE_OFFSET_DEG, Q16)
#define DEFAULT_VALUE_HALL_EDGE_POL_SKEW_TIME_Q16           QCONST(PUSER_VALUE_HALL_EDGE_POL_SKEW_TIME, Q16)

// QEP Mode
#define DEFAULT_VALUE_QEP_RESOLUTION_Q00                    QCONST(PUSER_VALUE_QEP_RESOLUTION, Q00)
#define DEFAULT_VALUE_QEP_ANGCORR_OFFSET_FWD_Q16            QCONST((PUSER_VALUE_QEP_ANGCORR_OFFSET_FWD_DEG * FLT_PI / 180.0f), Q16)
#define DEFAULT_VALUE_QEP_ANGCORR_OFFSET_REV_Q16            QCONST((PUSER_VALUE_QEP_ANGCORR_OFFSET_REV_DEG * FLT_PI / 180.0f), Q16)
#define DEFAULT_VALUE_QEP_FC_SPEED_HZ_Q16                   QCONST(PUSER_VALUE_QEP_FC_HZ, Q16)
#define DEFAULT_VALUE_QEP_ALIGNOFFSET_DEG                   QCONST(PUSER_VALUE_QEP_ALIGNOFFSET_DEG, Q16)
//#define DEFAULT_VALUE_QEP_ALIGNGO_ALIGN_STEPS_Q0            QCONST(((PUSER_VALUE_QEP_ALIGN_TIME_SEC * CONTROLFREQ_HZ_FLT) + 0.5f), Q00)
//#define DEFAULT_VALUE_QEP_ALIGNGO_ISTART_Q16                QCONST((PUSER_VALUE_QEP_ALIGNGO_ISTART_AMPS / CURRENT_SCALE_FACTOR_FLT), Q16)
//#define DEFAULT_VALUE_QEP_ALIGNGO_SPDRAMP_Q26               QCONST((PUSER_VALUE_QEP_ALIGNGO_SPDRAMP_HZPSEC * FLT_2PI * FOC_DT_FLT * FOC_DT_FLT), Q26)
//#define DEFAULT_VALUE_QEP_ALIGNGO_SPDTARGET_Q26             QCONST((PUSER_VALUE_QEP_ALIGNGO_SPDTARGET_HZ * FLT_2PI * FOC_DT_FLT), Q26)

#define DEFAULT_VALUE_POWER_IPHASE_OFSFET_Q16               QCONST(PUSER_VALUE_POWER_IPHASE_OFSFET, Q16)
#define DEFAULT_VALUE_POWER_IPHASE_FACTOR_Q16               QCONST(PUSER_VALUE_POWER_IPHASE_FACTOR, Q16)
    
#endif  //#ifndef PARAMCALC_H
