pac_foc/src/mpos/estimator/anglediff.c
NAME
pac_foc/src/mpos/estimator/anglediff.c - Use to check for angle difference between open loop and est angle and est speed.
SYNOPSIS
#include 'anglediff.h'
#include 'fault.h'
Functions
void est_anglediff_check (Struct_Motor *motor_ptr, int32_t ref_angle, int32_t check_angle, int32_t ref_speed_radps, int32_t check_speed_radps)
Use to do angle and speed difference check of est and open loop angle.
Detailed Description
Use to check for angle difference between open loop and est angle and est speed.
Definition in file anglediff.c.
Function Documentation
void est_anglediff_check (Struct_Motor * motor_ptr, int32_t ref_angle, int32_t check_angle, int32_t ref_speed_radps, int32_t check_speed_radps)
Use to do angle and speed difference check of est and open loop angle.
Parameters
Struct_Motor* motor_ptr
int32_t ref_angle
int32_t check_angle
int32_t ref_speed_radps
int32_t check_speed_radps
Definition at line 35 of file anglediff.c.
{
#ifdef ENABLE_ANGLEDIFF_SPEED_CHECK
    fix16_t ol_cl_speed_difference;
    static unsigned long int angle_speed_error_last_sample_time_value = 0;
    int32_t angle_diff_abs_q12;
    // Check for overflow
    if (motor_ptr->app.systick_div_counter < angle_speed_error_last_sample_time_value)
        angle_speed_error_last_sample_time_value = motor_ptr->app.systick_div_counter;
    if ((motor_ptr->app.systick_div_counter - angle_speed_error_last_sample_time_value) >= 1)
    {
        angle_speed_error_last_sample_time_value = motor_ptr->app.systick_div_counter;
        // Check speed difference between open loop speed and close loop feedback speed
        ol_cl_speed_difference = ref_speed_radps - check_speed_radps;
        // If difference is negative convert it to positive
        if (ol_cl_speed_difference < 0)
            ol_cl_speed_difference = -ol_cl_speed_difference;
        // Open loop frequency ramp finish
        fix16_t temp_angle_diff_stall_q12 = (ref_angle - check_angle) >> 4;
        // Convert difference between ideal and estimated angle to q12 format
        if (temp_angle_diff_stall_q12 > (FIX16_PI >> 4))
            temp_angle_diff_stall_q12 -= (FIX16_2PI >> 4);
        else if (temp_angle_diff_stall_q12 < ((-FIX16_PI) >> 4))
            temp_angle_diff_stall_q12 += (FIX16_2PI >> 4);
#ifdef ENABLE_OLSPEED_ANGLEDIFF_TIMEOUT
       if (motor_ptr->app.auto_close_loop_cmd)
       {
            if (motor_ptr->mpos.est.angle_diff_timeout_counter++ >= ANGLEDIFF_TIMEOUT_COUNT)
            {
                set_fault(FAULT_SPDANGLDIF_TIMEOUT); // Set motor stall status
                motor_ptr->mpos.est.angle_diff_timeout_counter = 0;
            }
        }
        else
            motor_ptr->mpos.est.angle_diff_timeout_counter = 0;
#endif
        // If speed error between open loop speed and feedback speed is less then or equal 12.5 %
       if (ol_cl_speed_difference >= fix16_mul(ANGLEDIFF_SPEED_ERROR_PCT_Q16, motor_ptr->app.speedrefcl_max)) // q16
        {
            // This flag tells that it's a right time to switch from open loop to close loop by check angle difference and speed
            motor_ptr->mpos.est.switchover_check_pass = 0;
            set_warning(WARNING_SPDDIF); // Set motor stall status
        }
        else // Come here when open loop and estimated speed is in within error band
        {
            clear_warning(WARNING_SPDDIF); // Set motor stall status
            angle_diff_abs_q12 = temp_angle_diff_stall_q12;
            // Convert into positive number if it's a negative for compare purpose
            if (angle_diff_abs_q12 < 0)
                angle_diff_abs_q12 = -angle_diff_abs_q12;
            // If error difference between ideal and estimated angle is more then 22.5 degrees
            // Check angle error between ideal and estimated in q12 format, check is angle difference is +ve, Pi in rad converted into Q12 before compare
#ifdef ENABLE_ANGLEDIFF_AUTORANGE
            if ((angle_diff_abs_q12 <= ANGLEDIFF_ANGLE_ERROR_DEG_Q12) && (temp_angle_diff_stall_q12 < 0)) // 22.5 degrees
#else
            if (angle_diff_abs_q12 <= ANGLEDIFF_ANGLE_ERROR_DEG_Q12) // 22.5 degrees
#endif
            {
                clear_warning(WARNING_ANGLDIF); // Clear Set motor stall status
                motor_ptr->mpos.est.switchover_check_pass = 1;
            }
            else
            {
                set_warning(WARNING_ANGLDIF); // Set motor stall status
                motor_ptr->mpos.est.switchover_check_pass = 0;
                // Run auto angle difference calculation to calculate required Iq form given I_total current */
#ifdef ENABLE_ANGLEDIFF_AUTORANGE
                if (motor_ptr->app.auto_close_loop_cmd)
                {
#if (MODULE_MPOS_ALIGNGO == ENABLED)
                    minimize_anglediff((temp_angle_diff_stall_q12 << 4), &motor_ptr->startup.aligngo.idrefol_target_q16, motor_ptr->startup.aligngo.itotrefol_target_q16,
                    motor_ptr->startup.aligngo.itotrefol_target_q16, motor_ptr->foc.idref_ramp_f16, QCONST(ANGLEDIFF_AUTORANGE_INC_METHOD1_PCT, Q10));
#elif (MODULE_MPOS_HALL == ENABLED)
#endif
                }
#endif
            }
        }
    }
#else //#ifdef ENABLE_ANGLEDIFF_SPEED_CHECK
    motor_ptr->mpos.est.switchover_check_pass = 1;
#endif //#ifdef ENABLE_ANGLEDIFF_SPEED_CHECK
}
References Struct_StartupAlignGo::aligngo, Struct_Est::angle_diff_timeout_counter, ANGLEDIFF_ANGLE_ERROR_DEG_Q12, ANGLEDIFF_AUTORANGE_INC_METHOD1_PCT, ANGLEDIFF_SPEED_ERROR_PCT_Q16, ANGLEDIFF_TIMEOUT_COUNT, Struct_Motor::app, Struct_App::auto_close_loop_cmd, clear_warning(), Struct_MPos::est, FAULT_SPDANGLDIF_TIMEOUT, FIX16_2PI, fix16_mul(), FIX16_PI, Struct_Motor::foc, Struct_FOC::idref_ramp_f16, Struct_AlignGo::idrefol_target_q16, Struct_AlignGo::itotrefol_target_q16, minimize_anglediff(), Struct_Motor::mpos, Q10, QCONST, set_fault(), set_warning(), Struct_App::speedrefcl_max, Struct_Motor::startup, Struct_Est::switchover_check_pass, Struct_App::systick_div_counter, WARNING_ANGLDIF, and WARNING_SPDDIF.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.