.TH "pac_foc/src/app/app_control_sm.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/app/app_control_sm.h \- Application control state machine, use for ADC channel calibration, IPD, SIM, Motor Run\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'control_funcs\&.h'\fP
.br
\fC#include 'app_funcs\&.h'\fP
.br
\fC#include 'driver_funcs\&.h'\fP
.br
\fC#include 'foc\&.h'\fP
.br
\fC#include 'mpos_funcs\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'control_sm\&.h'\fP
.br
\fC#include 'app_control_sm\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Application control state machine, use for ADC channel calibration, IPD, SIM, Motor Run\&. 


.PP
Definition in file \fBapp_control_sm\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
