pac_foc/src/app/app_funcs.c
NAME
pac_foc/src/app/app_funcs.c - Use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
SYNOPSIS
#include 'motor_struct.h'
#include 'app_funcs.h'
#include 'foc.h'
#include 'mpos_funcs.h'
#include 'param.h'
#include 'fault.h'
#include 'control_funcs.h'
#include 'foc_funcs.h'
#include 'comm.h'
#include 'harmonic_inj_funcs.h'
Functions
void motor_reset (Struct_Motor *motor_ptr)
This function use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
void systemvar_init (Struct_Motor *motor_ptr)
This function use to initialize debug, application, hall and other system variables.
void app_param_process (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
This function use for copying peak value of vdrive and speed for app level processing.
Variables
Struct_Motor motor
Detailed Description
Use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
Definition in file app_funcs.c.
Function Documentation
void app_param_process (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
This function use for copying peak value of vdrive and speed for app level processing.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
This function use for copying OL target speed and CL max speed ref to app level variable
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 217 of file app_funcs.c.
{
    switch(param_code)
    {
#if (MPOS_SELECT == MPOS_LBG1_START_ALIGNGO)
    case open_loop_speed_setpoint:
        motor_ptr->app.speedrefcl_min = motor_ptr->startup.aligngo.speedrefol_target_radps >> 1;
#elif (MPOS_SELECT == MPOS_HALL_ONLY) || (MPOS_SELECT == MPOS_LBG1_START_HALL)
    case max_cl_speed_limit:
        motor_ptr->app.speedrefcl_min = 0;
#elif (MPOS_SELECT == MPOS_QEP_START_ALIGNGO)
    case max_cl_speed_limit:
        // Set speed fault minimum to -max/4
        motor_ptr->app.speedrefcl_min = -motor_ptr->app.speedrefcl_max >> 2;
#endif
        break;
    default:
        break;
    }
}
References Struct_StartupAlignGo::aligngo, Struct_Motor::app, max_cl_speed_limit, open_loop_speed_setpoint, Struct_App::speedrefcl_max, Struct_App::speedrefcl_min, Struct_AlignGo::speedrefol_target_radps, and Struct_Motor::startup.
void motor_reset (Struct_Motor * motor_ptr)
This function use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 74 of file app_funcs.c.
{
    foc_reset(motor_ptr);
    control_reset(motor_ptr);
    clear_fault(FAULT_MAIN_GRP_CLEARSTART);
    motor_ptr->app.direction_reverse_flag = motor_ptr->app.direction_reverse_cmd;
    if (motor_ptr->app.direction_reverse_flag)
        motor_ptr->status.motor |= STATUS_MOTOR_REVERSE;
    else
        motor_ptr->status.motor &= ~STATUS_MOTOR_REVERSE;
#if defined(ENABLE_STALL_DETECT)
    motor_ptr->app.vdrvsq_q14_peak_stored = 0;
    motor_ptr->app.vdrvsq_q14_peak = 0;
#endif
#ifdef ENABLE_STALL_DETECT
    stalldet_reset(motor_ptr);
#endif
#ifdef ENABLE_OPDOL
    init_opdol(motor_ptr);
#endif
#if (COMMSEL_PPM == TRUE)
    ppm_init(motor_ptr);
#endif
#ifdef ENABLE_IPD
    motor_ptr->ipd.ipd_state = IPD_DONE;
#endif
#if defined(ENABLE_POWERMEASURE)
    power_reset(motor_ptr);
#endif
#if defined(ENABLE_AUTOTUNE_PI)
    at_reset_state(motor_ptr);
#endif
#if defined(ENABLE_OPD_CL)
    opdcl_reset(motor_ptr);
#endif
#ifdef ENABLE_MTPA
    mtpa_reset(motor_ptr);
#endif
}
References Struct_Motor::app, clear_fault(), control_reset(), Struct_App::direction_reverse_cmd, Struct_App::direction_reverse_flag, FAULT_MAIN_GRP_CLEARSTART, foc_reset(), init_opdol(), IPD_DONE, Struct_Status::motor, mtpa_reset(), ppm_init(), stalldet_reset(), Struct_Motor::status, STATUS_MOTOR_REVERSE, Struct_App::vdrvsq_q14_peak, and Struct_App::vdrvsq_q14_peak_stored.
Referenced by sm_mainsub_prestart().
void systemvar_init (Struct_Motor * motor_ptr)
This function use to initialize debug, application, hall and other system variables.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 129 of file app_funcs.c.
{
#ifdef ENABLE_DEBUG_DISPLAY
    test_ptr1 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
    test_ptr2 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
    test_ptr3 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
#endif
#if defined (ENABLE_DEBUG_PWMDAC) || defined (ENABLE_DEBUG_DAS)
    motor_ptr->debug.debug_buffer_command1 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command2 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command3 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command4 = 0; // make sure index never exceed array length
    dac_ptr1 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr2 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr3 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr4 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
#endif
    motor_ptr->state.main = STATE_MAIN_RESET;
    motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
    motor_ptr->app.current_limit = MOTOR_CURRENT_LIMIT_DEFAULT_VALUE;
#if defined(CAFE_ARCH3) && (DEVICE_SELECT == DEVICE_5285)
    motor_ptr->app.iphase_amp_gain = UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE_5285;
#else
    motor_ptr->app.iphase_amp_gain = UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE;
#endif
    motor_ptr->app.systick_counter = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.systick_div_counter = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.systick_divider_cnt = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.motor_led_ticks = MOTOR1_LED_TICKS; // Timer ticks in LED for this motor (for SVM)
    motor_ptr->app.motor_ted_ticks = MOTOR1_TED_TICKS; // Timer ticks in TED for this motor (for SVM)
    motor_ptr->app.motor_enable_cmd = 0;
    motor_ptr->status.motor = (eStatusMotor) 0;
    motor_ptr->fault.fault_stop_flag = FALSE;
    motor_ptr->control.ctrl_counter = 0;
    foc_systemvar_init(motor_ptr);
#ifdef ENABLE_CLSPEED_LIMIT_CHANGE_CHECK
    motor_ptr->debug.cl_speed_test_enable = FALSE;
    motor_ptr->debug.cl_speed_test_limit1 = FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE;
    motor_ptr->debug.cl_speed_test_limit2 = FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE;
#endif
#if (COMMSEL_PPM == TRUE)
    // Set power up flag, so we know system just power up, motor will not start until throttle will move back to minimum position
    motor_ptr->ppm.motor_powerup_flag = 1;
#endif
#ifdef ENABLE_FLASH_CRC_TEST
    // Get the results of the Reset Handler CRC Test; Passed = 0, Failed = 1
    // !!!!! Actions taken due to a Flash CRC Test failure are application specific; please modify accordingly !!!!!
    // In this case, the status is set so the FOC GUI can display the CRC failure
    if (uart_scratch_read() != 0)
        set_fault(FAULT_FLASH_CRC_TEST);
#endif
}
References Struct_Motor::app, Struct_State::appcontrol, Struct_Motor::control, Struct_Control::ctrl_counter, Struct_App::current_limit, FALSE, Struct_Motor::fault, FAULT_FLASH_CRC_TEST, Struct_Fault::fault_stop_flag, FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE, foc_systemvar_init(), GUI_Debug_Var_Q14, Struct_App::iphase_amp_gain, Struct_State::main, Struct_Status::motor, MOTOR1_LED_TICKS, MOTOR1_TED_TICKS, MOTOR_CURRENT_LIMIT_DEFAULT_VALUE, Struct_App::motor_enable_cmd, Struct_App::motor_led_ticks, Struct_PPM::motor_powerup_flag, Struct_App::motor_ted_ticks, Struct_Motor::ppm, set_fault(), Struct_Motor::state, STATE_APPCONTROL_IDLE, STATE_MAIN_RESET, Struct_Motor::status, Struct_App::systick_counter, Struct_App::systick_div_counter, Struct_App::systick_divider_cnt, test_ptr1, test_ptr2, test_ptr3, and UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE.
Referenced by main().
Variable Documentation
Struct_Motor motor
Definition at line 72 of file app_funcs.c.
Referenced by ADC_IRQHandler(), clear_fault(), clear_warning(), GpioA_IRQHandler(), GpioB_IRQHandler(), hall_timer_isr(), init_over_current_limit(), m1_disable(), m1_enable(), main(), peripheral_init(), qep_isr(), set_fault(), set_warning(), sm_mainsub_prestart(), statemachine_appmain(), statemachine_buttoncontrol(), SysTick_Handler(), TimerA_IRQHandler(), TimerB_IRQHandler(), and uart_message_process().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.