pac_foc/src/app/app_funcs.h
NAME
pac_foc/src/app/app_funcs.h - Use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
SYNOPSIS
#include 'pac5xxx_driver_timer.h'
#include 'motor_struct.h'
#include 'fault.h'
#include 'control_funcs.h'
#include 'parameter_process.h'
#include 'harmonic_inj_funcs.h'
Functions
void motor_reset (Struct_Motor *motor_ptr)
This function use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
void systemvar_init (Struct_Motor *motor_ptr)
This function use to initialize debug, application, hall and other system variables.
void sm_mainsub_post (Struct_Motor *motor_ptr)
This function use to initialize FOC timing, ADC calibration.
void sm_mainsub_prestart (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
void statemachine_appmain (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
void store_peak_speed_vdrive_value (Struct_Motor *motor_ptr)
void app_param_process (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
This function use for copying peak value of vdrive and speed for app level processing.
Detailed Description
Use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
Definition in file app_funcs.h.
Function Documentation
void app_param_process (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
This function use for copying peak value of vdrive and speed for app level processing.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
This function use for copying OL target speed and CL max speed ref to app level variable
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 217 of file app_funcs.c.
{
    switch(param_code)
    {
#if (MPOS_SELECT == MPOS_LBG1_START_ALIGNGO)
    case open_loop_speed_setpoint:
        motor_ptr->app.speedrefcl_min = motor_ptr->startup.aligngo.speedrefol_target_radps >> 1;
#elif (MPOS_SELECT == MPOS_HALL_ONLY) || (MPOS_SELECT == MPOS_LBG1_START_HALL)
    case max_cl_speed_limit:
        motor_ptr->app.speedrefcl_min = 0;
#elif (MPOS_SELECT == MPOS_QEP_START_ALIGNGO)
    case max_cl_speed_limit:
        // Set speed fault minimum to -max/4
        motor_ptr->app.speedrefcl_min = -motor_ptr->app.speedrefcl_max >> 2;
#endif
        break;
    default:
        break;
    }
}
References Struct_StartupAlignGo::aligngo, Struct_Motor::app, max_cl_speed_limit, open_loop_speed_setpoint, Struct_App::speedrefcl_max, Struct_App::speedrefcl_min, Struct_AlignGo::speedrefol_target_radps, and Struct_Motor::startup.
void motor_reset (Struct_Motor * motor_ptr)
This function use to reset variables associated to FOC, Control, Faults, Stall, OPD, PPM.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 74 of file app_funcs.c.
{
    foc_reset(motor_ptr);
    control_reset(motor_ptr);
    clear_fault(FAULT_MAIN_GRP_CLEARSTART);
    motor_ptr->app.direction_reverse_flag = motor_ptr->app.direction_reverse_cmd;
    if (motor_ptr->app.direction_reverse_flag)
        motor_ptr->status.motor |= STATUS_MOTOR_REVERSE;
    else
        motor_ptr->status.motor &= ~STATUS_MOTOR_REVERSE;
#if defined(ENABLE_STALL_DETECT)
    motor_ptr->app.vdrvsq_q14_peak_stored = 0;
    motor_ptr->app.vdrvsq_q14_peak = 0;
#endif
#ifdef ENABLE_STALL_DETECT
    stalldet_reset(motor_ptr);
#endif
#ifdef ENABLE_OPDOL
    init_opdol(motor_ptr);
#endif
#if (COMMSEL_PPM == TRUE)
    ppm_init(motor_ptr);
#endif
#ifdef ENABLE_IPD
    motor_ptr->ipd.ipd_state = IPD_DONE;
#endif
#if defined(ENABLE_POWERMEASURE)
    power_reset(motor_ptr);
#endif
#if defined(ENABLE_AUTOTUNE_PI)
    at_reset_state(motor_ptr);
#endif
#if defined(ENABLE_OPD_CL)
    opdcl_reset(motor_ptr);
#endif
#ifdef ENABLE_MTPA
    mtpa_reset(motor_ptr);
#endif
}
References Struct_Motor::app, clear_fault(), control_reset(), Struct_App::direction_reverse_cmd, Struct_App::direction_reverse_flag, FAULT_MAIN_GRP_CLEARSTART, foc_reset(), init_opdol(), IPD_DONE, Struct_Status::motor, mtpa_reset(), ppm_init(), stalldet_reset(), Struct_Motor::status, STATUS_MOTOR_REVERSE, Struct_App::vdrvsq_q14_peak, and Struct_App::vdrvsq_q14_peak_stored.
Referenced by sm_mainsub_prestart().
void sm_mainsub_post (Struct_Motor * motor_ptr)
This function use to initialize FOC timing, ADC calibration.
Parameters
Struct_Motor* motor_ptr motor pointer
Definition at line 173 of file app_mainsub_sm.c.
{
    switch (motor_ptr->state.post)
    {
        case STATE_POST_RESET:
            // Configure control loop for FOC mode
            foc_config(motor_ptr);
            motor_ptr->state.post = STATE_POST_ADCCAL_START;
            break;
        case STATE_POST_ADCCAL_START:
#ifdef ENABLE_ADCCAL
            __disable_irq();
            motor_ptr->state.post = STATE_POST_ADCCAL_RUN;
            motor_ptr->state.adccal = STATE_ADCCAL_RESET;
            motor_ptr->state.appcontrol = STATE_APPCONTROL_ADCCAL;
            __enable_irq();
#else
            set_default_adc_offset(motor_ptr);
            read_adc_offsets(motor_ptr);
            motor_ptr->state.post = STATE_POST_COMPLETE;
#endif
            break;
#ifdef ENABLE_ADCCAL
        case STATE_POST_ADCCAL_RUN:
           // Check status of ADC Offset Calibration, is completed yet
           if (motor_ptr->state.adccal == STATE_ADCCAL_COMPLETE)
           {
               read_adc_offsets(motor_ptr);
               __disable_irq();
               motor_ptr->state.post = STATE_POST_COMPLETE;
               __enable_irq();
           }
           break;
#endif
        case STATE_POST_COMPLETE:
           break;
        default:
           break;
    }
}
References Struct_State::adccal, Struct_State::appcontrol, foc_config(), Struct_State::post, Struct_Motor::state, STATE_ADCCAL_RESET, STATE_APPCONTROL_ADCCAL, STATE_POST_ADCCAL_RUN, STATE_POST_ADCCAL_START, and STATE_POST_RESET.
void sm_mainsub_prestart (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
Definition at line 55 of file app_mainsub_sm.c.
{
    static Struct_Motor* motor_ptr = &motor;
    switch(motor_ptr->state.prestart)
    {
        case STATE_PRESTART_RESET:
            __disable_irq();
            motor_reset(motor_ptr);
            motor_ptr->status.prestart = STATUS_PRESTART_RUNNING;
#ifdef ENABLE_SIM
            sim_smstate_reset(motor_ptr);
            config_control_timing_sim();
            config_control_dt(motor_ptr, motor_ptr->sim.dt_control_q26, SIM_CONTROL_DIVIDER);
            motor_ptr->state.appcontrol = STATE_APPCONTROL_SIM_RUN;
            motor_ptr->state.prestart = STATE_PRESTART_SIM_RUN;
#else
            motor_ptr->state.prestart = STATE_PRESTART_IPD_INIT;
#endif
            __enable_irq();
            break;
        case STATE_PRESTART_SIM_RUN:
        {
#ifdef ENABLE_SIM
            if ((motor_ptr->sim.status_sim & STATUS_SIM_COMPLETE) && (!(motor_ptr->sim.status_sim & STATUS_SIM_SWITCH2CL)))
            {
                // SIM exit procedure
                sim_exit_main(motor_ptr);
                // Next state
                __disable_irq();
                motor_ptr->state.prestart = STATE_PRESTART_IPD_INIT;
                motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
                __enable_irq();
            }
            else if ((motor_ptr->sim.status_sim & STATUS_SIM_COMPLETE) && (motor_ptr->sim.status_sim & STATUS_SIM_SWITCH2CL))
            {
                sim_sim2cl_transition_main(motor_ptr);
                // Next state if transitions are complete
                if (motor_ptr->sim.transition_complete)
                {
                    if (!motor_ptr->app.speed_mode_flag)
                        motor_ptr->control.iqrefcl_target_f16 = motor_ptr->app.iqrefcl_cmd_f16;
                    motor_ptr->control.idrefcl_target_f16 = motor_ptr->app.idrefcl_cmd_f16;
                    __disable_irq();
                    motor_ptr->state.main = STATE_MAIN_RUN;
                    motor_ptr->state.control = STATE_CONTROL_TORQUE;
                    sim_sim2cl_transition_exit_main(motor_ptr);
                    __enable_irq();
                }
            }
#endif // ENABLE_SIM
        }
            break;
        case STATE_PRESTART_IPD_INIT:
        {
            __disable_irq();
#ifdef ENABLE_IPD
            motor_ptr->state.prestart = STATE_PRESTART_IPD_RUN;
            motor_ptr->state.appcontrol = STATE_APPCONTROL_IPD;
            motor_ptr->ipd.ipd_state = IPD_START;
            motor_ptr->funcptr1 = (void (*)(void *)) &ipd_empty_function;
#else
            motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
            motor_ptr->status.prestart = STATUS_PRESTART_COMPLETED;
#endif
            __enable_irq();
        }
                    break;
        case STATE_PRESTART_IPD_RUN:
        {
#ifdef ENABLE_IPD
            // If IPD Is done, then Start FOC with Angle from IPD
            if (motor_ptr->ipd.ipd_state == IPD_DONE)
            {
                __disable_irq();
#ifdef ENABLE_IPD_OPD
                // If IPD detected phase lost
                if (motor_ptr->ipd.status & IPD_PHASE_LOST_DETECTED)
                {
                    set_fault(FAULT_OPD);
                    motor_ptr->status.prestart = STATUS_PRESTART_FAILED;
                    motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
                }
                else
#endif
                {
                    // Set the angle for FOC to start from; angle value must be a fix16 number between -pi*1024 and +pi*1024
                    motor_ptr->startup.aligngo.forced_angle_q26 = motor_ptr->ipd.ipd_starting_angle;
                    motor_ptr->status.prestart = STATUS_PRESTART_COMPLETED;
                    motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
                }
                __enable_irq();
            }
#endif
        }
            break;
        case STATE_PRESTART_COMPLETE:
            break;
        default:
            break;
    }
}
References Struct_StartupAlignGo::aligngo, Struct_Motor::app, Struct_State::appcontrol, config_control_dt(), Struct_Motor::control, Struct_State::control, FAULT_OPD, Struct_AlignGo::forced_angle_q26, Struct_App::idrefcl_cmd_f16, Struct_Control::idrefcl_target_f16, IPD_DONE, ipd_empty_function(), IPD_PHASE_LOST_DETECTED, IPD_START, Struct_App::iqrefcl_cmd_f16, Struct_Control::iqrefcl_target_f16, Struct_State::main, motor, motor_reset(), Struct_State::prestart, Struct_Status::prestart, set_fault(), Struct_App::speed_mode_flag, Struct_Motor::startup, Struct_Motor::state, STATE_APPCONTROL_IDLE, STATE_APPCONTROL_IPD, STATE_APPCONTROL_SIM_RUN, STATE_CONTROL_TORQUE, STATE_MAIN_RUN, STATE_PRESTART_COMPLETE, STATE_PRESTART_IPD_INIT, STATE_PRESTART_IPD_RUN, STATE_PRESTART_RESET, STATE_PRESTART_SIM_RUN, Struct_Motor::status, STATUS_PRESTART_COMPLETED, STATUS_PRESTART_FAILED, STATUS_PRESTART_RUNNING, STATUS_SIM_COMPLETE, and STATUS_SIM_SWITCH2CL.
void statemachine_appmain (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
Definition at line 55 of file app_main_sm.c.
{
    static Struct_Motor* motor_ptr = &motor;
    // Handle terminal faults
    if (motor_ptr->fault.fault_terminal_flag)
    {
        // Clear flag
        motor_ptr->fault.fault_terminal_flag = 0;
        // Clear motor enable command
        motor_ptr->app.motor_enable_cmd = 0;
        // Send to terminal state
        __disable_irq();
        motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
        motor_ptr->state.main = STATE_MAIN_TERMINAL;
        __enable_irq();
        // Clear status
        motor_ptr->status.motor &= ~STATUS_MAIN_ALLSTATUS;
        // Disable motor and PWMDAC's
        m1_disable();
#ifdef ENABLE_DEBUG_PWMDAC
        pwmdac_disable();
#endif
    }
    // Handle state faults except when in terminal state
    if ((motor_ptr->fault.fault_state_flag) && (motor_ptr->state.main != STATE_MAIN_TERMINAL)
            // Wait until sm_main is not in one of the states below before processing fault so that power up sequence is not interrupted and bypassed
            && (motor_ptr->state.main != STATE_MAIN_RESET)
            && (motor_ptr->state.main != STATE_MAIN_POST)
            && (motor_ptr->state.main != STATE_MAIN_PRESTART)
            && (motor_ptr->state.main != STATE_MAIN_MID1))
    {
        // Clear flag
        motor_ptr->fault.fault_state_flag = 0;
        // Clear motor enable command
        motor_ptr->app.motor_enable_cmd = 0;
        // Send to FAULT state
        __disable_irq();
        motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
        motor_ptr->state.main = STATE_MAIN_FAULT;
        __enable_irq();
        // Clear status
        motor_ptr->status.motor &= ~STATUS_MAIN_ALLSTATUS;
        // Disable motor (Special handling for over-current fault)
        if (motor_ptr->fault.motor & FAULT_CAFE_OC)
            set_drivers_gpio();
        else
            m1_disable();
    }
    // Handle stop faults except when in terminal or fault states
    else if ((motor_ptr->fault.fault_stop_flag) && (motor_ptr->state.main != STATE_MAIN_TERMINAL) && (motor_ptr->state.main != STATE_MAIN_FAULT))
    {
        __disable_irq();
        // Clear flag
        motor_ptr->fault.fault_stop_flag = FALSE;
        // Clear motor enable command
        motor_ptr->app.motor_enable_cmd = 0;
        // Send to DISABLE state
        switch (motor_ptr->state.main)
        {
            case STATE_MAIN_STARTUP:
            case STATE_MAIN_RUN:
            case STATE_MAIN_COASTING:
                motor_ptr->state.main = STATE_MAIN_DISABLE;
                break;
            default:
                break;
        }
        __enable_irq();
    }
    switch (motor_ptr->state.main)
    {
        case STATE_MAIN_RESET:
            __disable_irq();
            // Initialize variables for operation
            init_default_parameters(motor_ptr);
            motor_init(motor_ptr);
#if (MODULE_MPOS_HALL == ENABLED)
            hall_init(motor_ptr);
#endif
#if (MODULE_MPOS_QEP == ENABLED)
            qep_init(motor_ptr);
#endif
#ifdef ENABLE_OPD_CL
            opdcl_init(motor_ptr);
#endif
#ifdef ENABLE_DEBUG_PWMDAC
            pwmdac_enable();
#endif
#if defined(ENABLE_POWERUP_AUTOSTART)
            motor_ptr->app.flag_first_start = 1;
#endif
            // Transition Main state machine to POST state
            motor_ptr->state.main = STATE_MAIN_POST;
            motor_ptr->state.post = STATE_POST_RESET;
            __enable_irq();
            break;
        case STATE_MAIN_POST:
            // Execute Power On Self Test until complete
            sm_mainsub_post(motor_ptr);
            // If POST is complete, transition to DISABLE state
            if (motor_ptr->state.post == STATE_POST_COMPLETE)
            {
                __disable_irq();
                motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
                motor_ptr->state.main = STATE_MAIN_DISABLE;
                __enable_irq();
            }
            break;
        case STATE_MAIN_DISABLE:
// debugio1_off();
            __disable_irq();
            // Disable the motor and PWM DACs
            m1_disable();
#if (MODULE_MPOS_HALL == ENABLED)
            // Hall disable routine
            hall_timer_disable();
            hall_int_hallport_disable();
#endif
#if defined(ENABLE_AUTOTUNE_PI)
            at_reset_state(motor_ptr);
#endif
            // Next state and status
            motor_ptr->fault.fault_stop_flag = FALSE;
            motor_ptr->mpos.state = STATE_MPOS_IDLE;
            motor_ptr->state.control = STATE_CONTROL_IDLE;
            motor_ptr->status.motor &= ~(STATUS_MAIN_ALLSTATUS);
            motor_ptr->state.main = STATE_MAIN_STOPPED;
            motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
            motor_ptr->status.motor |= STATUS_MOTOR_STOPPED;
            // Initialize sub-state machines
            motor_ptr->state.prestart = STATE_PRESTART_RESET;
            startup_reset_state(motor_ptr);
#if defined(TM_SIM_REVERSE)
            // Handle SIM_Reverse test mode
            if (motor_ptr->debug.testmode_enable != 0)
            {
                if (motor_ptr->app.direction_reverse_cmd)
                    motor_ptr->app.direction_reverse_cmd = 0;
                else
                    motor_ptr->app.direction_reverse_cmd = 1;
            }
#endif
            __enable_irq();
            break;
#ifdef ENABLE_SIMBRAKE_MOTORDISABLE
        case STATE_MAIN_BRAKE:
            // Exit brake state if SIM is complete
            if (motor_ptr->sim.status_sim & STATUS_SIM_COMPLETE)
            {
                motor_ptr->state.main = STATE_MAIN_DISABLE;
                config_control_dt(motor_ptr, motor_ptr->foc.dt_control_q26, motor_ptr->foc.ctrl_divider_foc);
                motor_ptr->status.motor &= ~STATUS_MOTOR_BRAKING;
            }
            break;
#endif
        case STATE_MAIN_STOPPED:
#if defined(ENABLE_TM) && defined(ENABLE_TM_SIM)
            // Handle testmode
            if (motor_ptr->debug.testmode_enable != 0)
            {
                motor_ptr->app.motor_enable_cmd = 1;
            }
#endif
            // Logic to reverse direction only when the motor is stopped
            if (motor_ptr->app.direction_reverse_flag != motor_ptr->app.direction_reverse_cmd)
            {
                motor_ptr->app.direction_reverse_flag = motor_ptr->app.direction_reverse_cmd;
                if (motor_ptr->app.direction_reverse_flag)
                    motor_ptr->status.motor |= STATUS_MOTOR_REVERSE;
                else
                    motor_ptr->status.motor &= ~STATUS_MOTOR_REVERSE;
            }
#if defined(ENABLE_HALL_TUNING)
            halltune_process_cmd_enable(motor_ptr);
#endif
#if defined(ENABLE_AUTOTUNE_MID)
            mid1_process_motor_enable(motor_ptr);
#endif
#if defined(ENABLE_POWERUP_AUTOSTART)
            if (motor_ptr->app.flag_first_start)
            {
                motor_ptr->app.motor_enable_cmd = 1;
                motor_ptr->app.flag_first_start = 0;
            }
#endif
            // Wait for the motor enable command and then transition to the STARTUP state
            if (motor_ptr->app.motor_enable_cmd)
            {
                __disable_irq();
                motor_ptr->state.main = STATE_MAIN_PRESTART;
                motor_ptr->status.motor |= STATUS_MOTOR_ENABLED;
                motor_ptr->status.motor &= ~STATUS_MOTOR_STOPPED;
                __enable_irq();
            }
            break;
        case STATE_MAIN_PRESTART:
            // Execute Startup state machine until complete
            sm_mainsub_prestart();
            // If startup is complete and no faults, then go to Open Loop; otherwise go to Disable state
            if (motor_ptr->state.prestart == STATE_PRESTART_COMPLETE)
            {
                if (motor_ptr->status.prestart == STATUS_PRESTART_COMPLETED)
                {
                    __disable_irq();
                    motor_ptr->state.main = STATE_MAIN_STARTUP;
                    __enable_irq();
                }
                else if (motor_ptr->status.prestart == STATUS_PRESTART_FAILED)
                {
                    motor_ptr->app.motor_enable_cmd = 0;
                    motor_ptr->state.main = STATE_MAIN_DISABLE;
                }
            }
            break;
        case STATE_MAIN_STARTUP:
            // Call run state machine
            startup_controller(motor_ptr);
            // Next state
            if (startup_complete(motor_ptr))
                motor_ptr->state.main = STATE_MAIN_RUN;
            else if (!motor_ptr->app.motor_enable_cmd)
                motor_ptr->state.main = STATE_MAIN_DISABLE;
            break;
        case STATE_MAIN_RUN:
            // If motor is no longer enabled, transition to the COASTING state
            if (!motor_ptr->app.motor_enable_cmd)
            {
                __disable_irq();
#ifdef ENABLE_SIM
                //JAGTAG: Move this to inside SIM
                if (motor_ptr->app.direction_reverse_flag)
                    motor_ptr->sim.sim_spd_scaled_q28 = -motor_ptr->mpos.mpos_spd_scaled_q28;
                else
                    motor_ptr->sim.sim_spd_scaled_q28 = motor_ptr->mpos.mpos_spd_scaled_q28;
#endif
#ifdef ENABLE_COASTING
                // Need to write ramp as well to bypass ramp, in case iqref was at ripple peak when stop is commanded
                motor_ptr->control.iqrefcl_target_f16 = motor_ptr->foc.iqref_ramp_q14 = motor_ptr->foc.iqref_ramp_f16 = 0;
                motor_ptr->app.coast_timeout_counter = 0;
                motor_ptr->status.motor |= STATUS_MOTOR_CL_RAMPDOWN;
                motor_ptr->state.main = STATE_MAIN_COASTING;
                motor_ptr->state.control = STATE_CONTROL_TORQUE;
#elif defined(ENABLE_SIMBRAKE_MOTORDISABLE)
                // Disable gate drivers
                m1_disable();
                // Reset sim state machine
                sim_smstate_reset(motor_ptr);
                // Initialize SIM speed
                motor_ptr->sim.sim_spd_scaled_q28 = 0;
                // Next state and configure sequencers and control divider for SIM mode
                motor_ptr->mpos.state = STATE_MPOS_IDLE;
                motor_ptr->state.control = STATE_CONTROL_IDLE;
                config_control_timing_sim();
                config_control_dt(motor_ptr, motor_ptr->sim.dt_control_q26, SIM_CONTROL_DIVIDER);
                motor_ptr->state.appcontrol = STATE_APPCONTROL_SIM_RUN;
                motor_ptr->state.main = STATE_MAIN_BRAKE;
                motor_ptr->status.motor |= STATUS_MOTOR_BRAKING;
#else
                // Next state
                motor_ptr->state.main = STATE_MAIN_DISABLE;
#endif
                __enable_irq();
            }
            else
            {
                // Switch to speed mode if motor is in torque mode and speed mode is commanded
                if ((motor_ptr->app.speed_mode_flag) && (motor_ptr->state.control != STATE_CONTROL_OUTERLOOP))
                {
                    __disable_irq();
                    // Initialize outer loop before switching to CL mode
                    init_pi(&motor_ptr->control.outerloop_pid, motor_ptr->foc.iqref_ramp_q14);
                    update_outerloop_ramp_sw(motor_ptr);
                    motor_ptr->state.control = STATE_CONTROL_OUTERLOOP;
                    __enable_irq();
                }
                // Switch to torque mode if motor is in speed mode and torque mode is commanded
                else if ((!motor_ptr->app.speed_mode_flag) && (motor_ptr->state.control != STATE_CONTROL_TORQUE))
                {
                    __disable_irq();
                    motor_ptr->foc.iqref_ramp_f16 = (motor_ptr->foc.iqref_ramp_q14 << 2);
                    motor_ptr->control.iqrefcl_target_f16 = motor_ptr->app.iqrefcl_cmd_f16;
                    motor_ptr->state.control = STATE_CONTROL_TORQUE;
                    __enable_irq();
                }
#if (MODULE_MPOS_HALL == ENABLED) && (MODULE_MPOS_LBG1 == ENABLED)
                hall_hall2est_controller(motor_ptr);
#endif
            }
            break;
#ifdef ENABLE_COASTING
        case STATE_MAIN_COASTING:
            // Update outer loop ramp and feedback (for stall detection and display)
            update_outerloop_ramp_sw(motor_ptr);
            update_outerloop_fdbk_scaled(motor_ptr);
            // Handle case when motor is re-enabled while coasting but direction was changed
#ifdef ENABLE_NEGATIVE_IQ_COASTING
            if ((motor_ptr->app.motor_enable_cmd) && (motor_ptr->app.direction_reverse_cmd != motor_ptr->app.direction_reverse_flag))
            {
                // Need to write ramp as well to bypass ramp, in case iqref was at ripple peak when stop is commanded
                motor_ptr->control.iqrefcl_target_f16 = fix16_mul((0 - motor_ptr->control.outerloop_pid.max_value), NEGATIVE_IQ_CURRENT_PER_FOR_COAST);
                // Check if iqrefcl_target is +ve than set it to 0
                if (motor_ptr->control.iqrefcl_target_f16 > 0)
                    motor_ptr->control.iqrefcl_target_f16 = 0;
                motor_ptr->control.idiqref_rate_f16 = fix16_mul(motor_ptr->idiqref_rate_gui_f16, IDIQ_RAMP_RATE_PER_FOR_COAST);
                // Check if idiqref_rate is 0 than set it to default
                if (motor_ptr->control.idiqref_rate_f16 <= 0)
                    motor_ptr->control.idiqref_rate_f16 = DEFAULT_IDIQ_RAMP_RATE_PER_FOR_COAST;
            }
            // Handle case when motor is re-enabled while coasting
            if ((motor_ptr->app.motor_enable_cmd) && (motor_ptr->app.direction_reverse_cmd == motor_ptr->app.direction_reverse_flag))
#else
            // Handle case when motor is re-enabled while coasting
            if (motor_ptr->app.motor_enable_cmd)
#endif
            {
                __disable_irq();
                if (motor_ptr->mpos.mpos_spd_radps >= conv_ol2cl_speed(motor_ptr->control.dt_control_1div_q6, motor_ptr->startup.aligngo.speedrefol_target))
                {
                    motor_ptr->status.motor &= ~STATUS_MOTOR_CL_RAMPDOWN;
                    motor_ptr->state.main = STATE_MAIN_RUN;
                    if (motor_ptr->app.speed_mode_flag)
                    {
                        update_outerloop_ramp_sw(motor_ptr);
                        motor_ptr->state.control = STATE_CONTROL_OUTERLOOP;
                    }
                    else
                    {
                        motor_ptr->control.iqrefcl_target_f16 = motor_ptr->app.iqrefcl_cmd_f16;
                        motor_ptr->state.control = STATE_CONTROL_TORQUE;
                    }
                }
                else
                    motor_ptr->state.main = STATE_MAIN_DISABLE;
#ifdef ENABLE_NEGATIVE_IQ_COASTING
                // Restore value because it is overwritten by coast mode
                motor_ptr->control.idiqref_rate_f16 = motor_ptr->idiqref_rate_gui_f16;
#endif
                __enable_irq();
            }
            // Check if estimated speed less than switchover speed then disable motor
            else if (motor_ptr->mpos.mpos_spd_radps < conv_ol2cl_speed(motor_ptr->control.dt_control_1div_q6, motor_ptr->startup.aligngo.speedrefol_target))
            {
                motor_ptr->state.main = STATE_MAIN_DISABLE;
            }
            // If coast has timed out, then go to DISABLE state
            else if (motor_ptr->app.coast_timeout_counter++ >= motor_ptr->app.coast_timeout_target)
            {
#ifdef ENABLE_NEGATIVE_IQ_COASTING
                if (!motor_ptr->app.motor_enable_cmd)
                    set_fault(FAULT_COAST_TIMEOUT);
#else
                set_fault(FAULT_COAST_TIMEOUT);
#endif
                motor_ptr->state.main = STATE_MAIN_DISABLE;
            }
            break;
#endif
        case STATE_MAIN_FAULT:
            // Exit fault state if all fault conditions are clear
            if ((motor_ptr->fault.motor & FAULT_MAIN_GRP_STATE) == 0)
            {
                __disable_irq();
                motor_ptr->state.main = STATE_MAIN_DISABLE;
                __enable_irq();
            }
            break;
        case STATE_MAIN_TERMINAL:
            break;
#if defined(ENABLE_HALL_TUNING)
        case STATE_MAIN_HALLTUNE:
            // Hall tuning controller
            halltune_controller(motor_ptr);
            // Next state
            halltune_process_cmd_disable(motor_ptr);
            break;
#endif
#if defined(ENABLE_AUTOTUNE_MID)
        case STATE_MAIN_MID1:
            // MID1 main state machine
            mid1_main_subsm(motor_ptr);
            // Next state
            if (motor_ptr->atune.state_mainsub_mid1 & STATE_MAINSUB_MID1_COMPLETE)
// if (motor_ptr->atune.status_atune & (STATUS_ATUNE_MID1_COMPLETE | STATUS_ATUNE_MID1_FAILED))
            {
                // Next state
                motor_ptr->state.main = STATE_MAIN_DISABLE;
            }
            break;
#endif
        default:
            // If the state is not one of the above, then it's an error, so go to DISABLE state
            if (motor_ptr->app.motor_enable_cmd)
            {
                __disable_irq();
                motor_ptr->app.motor_enable_cmd = 0;
                motor_ptr->state.main = STATE_MAIN_DISABLE;
                motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
                __enable_irq();
            }
            break;
    }
}
References Struct_Motor::app, Struct_State::appcontrol, FALSE, Struct_Motor::fault, FAULT_CAFE_OC, Struct_Fault::fault_state_flag, Struct_Fault::fault_stop_flag, Struct_Fault::fault_terminal_flag, init_default_parameters(), m1_disable(), Struct_State::main, motor, Struct_Fault::motor, Struct_Status::motor, Struct_App::motor_enable_cmd, set_drivers_gpio(), Struct_Motor::state, STATE_APPCONTROL_IDLE, STATE_MAIN_COASTING, STATE_MAIN_DISABLE, STATE_MAIN_FAULT, STATE_MAIN_MID1, STATE_MAIN_POST, STATE_MAIN_PRESTART, STATE_MAIN_RESET, STATE_MAIN_RUN, STATE_MAIN_STARTUP, STATE_MAIN_TERMINAL, Struct_Motor::status, and STATUS_MAIN_ALLSTATUS.
void store_peak_speed_vdrive_value (Struct_Motor * motor_ptr)
void systemvar_init (Struct_Motor * motor_ptr)
This function use to initialize debug, application, hall and other system variables.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 129 of file app_funcs.c.
{
#ifdef ENABLE_DEBUG_DISPLAY
    test_ptr1 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
    test_ptr2 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
    test_ptr3 = (My_GUI_Debug_Q14*) &GUI_Debug_Var_Q14[0].ptr_gui_debug_value_q14; // make sure pointer is pointing to array index 0 at power up
#endif
#if defined (ENABLE_DEBUG_PWMDAC) || defined (ENABLE_DEBUG_DAS)
    motor_ptr->debug.debug_buffer_command1 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command2 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command3 = 0; // make sure index never exceed array length
    motor_ptr->debug.debug_buffer_command4 = 0; // make sure index never exceed array length
    dac_ptr1 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr2 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr3 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
    dac_ptr4 = (int32_t*) &DAC_ARRAY_Q14[0]; // make sure pointer points to something
#endif
    motor_ptr->state.main = STATE_MAIN_RESET;
    motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
    motor_ptr->app.current_limit = MOTOR_CURRENT_LIMIT_DEFAULT_VALUE;
#if defined(CAFE_ARCH3) && (DEVICE_SELECT == DEVICE_5285)
    motor_ptr->app.iphase_amp_gain = UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE_5285;
#else
    motor_ptr->app.iphase_amp_gain = UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE;
#endif
    motor_ptr->app.systick_counter = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.systick_div_counter = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.systick_divider_cnt = 0; // this is the timer that starts as soon ADC ISR called
    motor_ptr->app.motor_led_ticks = MOTOR1_LED_TICKS; // Timer ticks in LED for this motor (for SVM)
    motor_ptr->app.motor_ted_ticks = MOTOR1_TED_TICKS; // Timer ticks in TED for this motor (for SVM)
    motor_ptr->app.motor_enable_cmd = 0;
    motor_ptr->status.motor = (eStatusMotor) 0;
    motor_ptr->fault.fault_stop_flag = FALSE;
    motor_ptr->control.ctrl_counter = 0;
    foc_systemvar_init(motor_ptr);
#ifdef ENABLE_CLSPEED_LIMIT_CHANGE_CHECK
    motor_ptr->debug.cl_speed_test_enable = FALSE;
    motor_ptr->debug.cl_speed_test_limit1 = FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE;
    motor_ptr->debug.cl_speed_test_limit2 = FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE;
#endif
#if (COMMSEL_PPM == TRUE)
    // Set power up flag, so we know system just power up, motor will not start until throttle will move back to minimum position
    motor_ptr->ppm.motor_powerup_flag = 1;
#endif
#ifdef ENABLE_FLASH_CRC_TEST
    // Get the results of the Reset Handler CRC Test; Passed = 0, Failed = 1
    // !!!!! Actions taken due to a Flash CRC Test failure are application specific; please modify accordingly !!!!!
    // In this case, the status is set so the FOC GUI can display the CRC failure
    if (uart_scratch_read() != 0)
        set_fault(FAULT_FLASH_CRC_TEST);
#endif
}
References Struct_Motor::app, Struct_State::appcontrol, Struct_Motor::control, Struct_Control::ctrl_counter, Struct_App::current_limit, FALSE, Struct_Motor::fault, FAULT_FLASH_CRC_TEST, Struct_Fault::fault_stop_flag, FOC_CLOSE_LOOP_SPEED_SETPOINT_DEFAULT_VALUE, foc_systemvar_init(), GUI_Debug_Var_Q14, Struct_App::iphase_amp_gain, Struct_State::main, Struct_Status::motor, MOTOR1_LED_TICKS, MOTOR1_TED_TICKS, MOTOR_CURRENT_LIMIT_DEFAULT_VALUE, Struct_App::motor_enable_cmd, Struct_App::motor_led_ticks, Struct_PPM::motor_powerup_flag, Struct_App::motor_ted_ticks, Struct_Motor::ppm, set_fault(), Struct_Motor::state, STATE_APPCONTROL_IDLE, STATE_MAIN_RESET, Struct_Motor::status, Struct_App::systick_counter, Struct_App::systick_div_counter, Struct_App::systick_divider_cnt, test_ptr1, test_ptr2, test_ptr3, and UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE.
Referenced by main().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.