pac_foc/src/app/app_mainsub_sm.c
NAME
pac_foc/src/app/app_mainsub_sm.c - App main sub state machine, use to control ADC Calibration, pre PRESTART_RESET, SIM, IPD states.
SYNOPSIS
#include 'motor_struct.h'
#include 'parameter_process.h'
#include 'app_funcs.h'
#include 'driver_funcs.h'
#include 'fault.h'
#include 'control_funcs.h'
#include 'mpos_funcs.h'
#include 'foc_funcs.h'
Functions
PAC5XXX_OPTIMIZE_SPEED_ON void sm_mainsub_prestart (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
PAC5XXX_OPTIMIZE_SPEED_OFF void sm_mainsub_post (Struct_Motor *motor_ptr)
This function use to initialize FOC timing, ADC calibration.
Detailed Description
App main sub state machine, use to control ADC Calibration, pre PRESTART_RESET, SIM, IPD states.
Definition in file app_mainsub_sm.c.
Function Documentation
PAC5XXX_OPTIMIZE_SPEED_OFF void sm_mainsub_post (Struct_Motor * motor_ptr)
This function use to initialize FOC timing, ADC calibration.
Parameters
Struct_Motor* motor_ptr motor pointer
Definition at line 173 of file app_mainsub_sm.c.
{
    switch (motor_ptr->state.post)
    {
        case STATE_POST_RESET:
            // Configure control loop for FOC mode
            foc_config(motor_ptr);
            motor_ptr->state.post = STATE_POST_ADCCAL_START;
            break;
        case STATE_POST_ADCCAL_START:
#ifdef ENABLE_ADCCAL
            __disable_irq();
            motor_ptr->state.post = STATE_POST_ADCCAL_RUN;
            motor_ptr->state.adccal = STATE_ADCCAL_RESET;
            motor_ptr->state.appcontrol = STATE_APPCONTROL_ADCCAL;
            __enable_irq();
#else
            set_default_adc_offset(motor_ptr);
            read_adc_offsets(motor_ptr);
            motor_ptr->state.post = STATE_POST_COMPLETE;
#endif
            break;
#ifdef ENABLE_ADCCAL
        case STATE_POST_ADCCAL_RUN:
           // Check status of ADC Offset Calibration, is completed yet
           if (motor_ptr->state.adccal == STATE_ADCCAL_COMPLETE)
           {
               read_adc_offsets(motor_ptr);
               __disable_irq();
               motor_ptr->state.post = STATE_POST_COMPLETE;
               __enable_irq();
           }
           break;
#endif
        case STATE_POST_COMPLETE:
           break;
        default:
           break;
    }
}
References Struct_State::adccal, Struct_State::appcontrol, foc_config(), Struct_State::post, Struct_Motor::state, STATE_ADCCAL_RESET, STATE_APPCONTROL_ADCCAL, STATE_POST_ADCCAL_RUN, STATE_POST_ADCCAL_START, and STATE_POST_RESET.
PAC5XXX_OPTIMIZE_SPEED_ON void sm_mainsub_prestart (void)
This function use to FOC motor control state flow, FAULT, RUN, START, STOP, RESET, COAST, DISABLE.
Definition at line 55 of file app_mainsub_sm.c.
{
    static Struct_Motor* motor_ptr = &motor;
    switch(motor_ptr->state.prestart)
    {
        case STATE_PRESTART_RESET:
            __disable_irq();
            motor_reset(motor_ptr);
            motor_ptr->status.prestart = STATUS_PRESTART_RUNNING;
#ifdef ENABLE_SIM
            sim_smstate_reset(motor_ptr);
            config_control_timing_sim();
            config_control_dt(motor_ptr, motor_ptr->sim.dt_control_q26, SIM_CONTROL_DIVIDER);
            motor_ptr->state.appcontrol = STATE_APPCONTROL_SIM_RUN;
            motor_ptr->state.prestart = STATE_PRESTART_SIM_RUN;
#else
            motor_ptr->state.prestart = STATE_PRESTART_IPD_INIT;
#endif
            __enable_irq();
            break;
        case STATE_PRESTART_SIM_RUN:
        {
#ifdef ENABLE_SIM
            if ((motor_ptr->sim.status_sim & STATUS_SIM_COMPLETE) && (!(motor_ptr->sim.status_sim & STATUS_SIM_SWITCH2CL)))
            {
                // SIM exit procedure
                sim_exit_main(motor_ptr);
                // Next state
                __disable_irq();
                motor_ptr->state.prestart = STATE_PRESTART_IPD_INIT;
                motor_ptr->state.appcontrol = STATE_APPCONTROL_IDLE;
                __enable_irq();
            }
            else if ((motor_ptr->sim.status_sim & STATUS_SIM_COMPLETE) && (motor_ptr->sim.status_sim & STATUS_SIM_SWITCH2CL))
            {
                sim_sim2cl_transition_main(motor_ptr);
                // Next state if transitions are complete
                if (motor_ptr->sim.transition_complete)
                {
                    if (!motor_ptr->app.speed_mode_flag)
                        motor_ptr->control.iqrefcl_target_f16 = motor_ptr->app.iqrefcl_cmd_f16;
                    motor_ptr->control.idrefcl_target_f16 = motor_ptr->app.idrefcl_cmd_f16;
                    __disable_irq();
                    motor_ptr->state.main = STATE_MAIN_RUN;
                    motor_ptr->state.control = STATE_CONTROL_TORQUE;
                    sim_sim2cl_transition_exit_main(motor_ptr);
                    __enable_irq();
                }
            }
#endif // ENABLE_SIM
        }
            break;
        case STATE_PRESTART_IPD_INIT:
        {
            __disable_irq();
#ifdef ENABLE_IPD
            motor_ptr->state.prestart = STATE_PRESTART_IPD_RUN;
            motor_ptr->state.appcontrol = STATE_APPCONTROL_IPD;
            motor_ptr->ipd.ipd_state = IPD_START;
            motor_ptr->funcptr1 = (void (*)(void *)) &ipd_empty_function;
#else
            motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
            motor_ptr->status.prestart = STATUS_PRESTART_COMPLETED;
#endif
            __enable_irq();
        }
                    break;
        case STATE_PRESTART_IPD_RUN:
        {
#ifdef ENABLE_IPD
            // If IPD Is done, then Start FOC with Angle from IPD
            if (motor_ptr->ipd.ipd_state == IPD_DONE)
            {
                __disable_irq();
#ifdef ENABLE_IPD_OPD
                // If IPD detected phase lost
                if (motor_ptr->ipd.status & IPD_PHASE_LOST_DETECTED)
                {
                    set_fault(FAULT_OPD);
                    motor_ptr->status.prestart = STATUS_PRESTART_FAILED;
                    motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
                }
                else
#endif
                {
                    // Set the angle for FOC to start from; angle value must be a fix16 number between -pi*1024 and +pi*1024
                    motor_ptr->startup.aligngo.forced_angle_q26 = motor_ptr->ipd.ipd_starting_angle;
                    motor_ptr->status.prestart = STATUS_PRESTART_COMPLETED;
                    motor_ptr->state.prestart = STATE_PRESTART_COMPLETE;
                }
                __enable_irq();
            }
#endif
        }
            break;
        case STATE_PRESTART_COMPLETE:
            break;
        default:
            break;
    }
}
References Struct_StartupAlignGo::aligngo, Struct_Motor::app, Struct_State::appcontrol, config_control_dt(), Struct_Motor::control, Struct_State::control, FAULT_OPD, Struct_AlignGo::forced_angle_q26, Struct_App::idrefcl_cmd_f16, Struct_Control::idrefcl_target_f16, IPD_DONE, ipd_empty_function(), IPD_PHASE_LOST_DETECTED, IPD_START, Struct_App::iqrefcl_cmd_f16, Struct_Control::iqrefcl_target_f16, Struct_State::main, motor, motor_reset(), Struct_State::prestart, Struct_Status::prestart, set_fault(), Struct_App::speed_mode_flag, Struct_Motor::startup, Struct_Motor::state, STATE_APPCONTROL_IDLE, STATE_APPCONTROL_IPD, STATE_APPCONTROL_SIM_RUN, STATE_CONTROL_TORQUE, STATE_MAIN_RUN, STATE_PRESTART_COMPLETE, STATE_PRESTART_IPD_INIT, STATE_PRESTART_IPD_RUN, STATE_PRESTART_RESET, STATE_PRESTART_SIM_RUN, Struct_Motor::status, STATUS_PRESTART_COMPLETED, STATUS_PRESTART_FAILED, STATUS_PRESTART_RUNNING, STATUS_SIM_COMPLETE, and STATUS_SIM_SWITCH2CL.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.