.TH "pac_foc/src/features/autotune/autotune_build_info_keil_m4.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/autotune/autotune_build_info_keil_m4.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAUTOTUNE_BUILD_STR\fP   '20200813\&.184951'"
.br
.ti -1c
.RI "#define \fBAUTOTUNE_BUILD_DATE_STR\fP   '20200813'"
.br
.ti -1c
.RI "#define \fBAUTOTUNE_BUILD_DATE_NUM\fP   20200813"
.br
.ti -1c
.RI "#define \fBAUTOTUNE_BUILD_TIME_STR\fP   '184951'"
.br
.ti -1c
.RI "#define \fBAUTOTUNE_BUILD_TIME_NUM\fP   184951"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUTOTUNE_BUILD_DATE_NUM   20200813"

.PP
Definition at line 13 of file autotune_build_info_keil_m4\&.h\&.
.SS "#define AUTOTUNE_BUILD_DATE_STR   '20200813'"

.PP
Definition at line 12 of file autotune_build_info_keil_m4\&.h\&.
.SS "#define AUTOTUNE_BUILD_STR   '20200813\&.184951'"

.PP
Definition at line 11 of file autotune_build_info_keil_m4\&.h\&.
.SS "#define AUTOTUNE_BUILD_TIME_NUM   184951"

.PP
Definition at line 15 of file autotune_build_info_keil_m4\&.h\&.
.SS "#define AUTOTUNE_BUILD_TIME_STR   '184951'"

.PP
Definition at line 14 of file autotune_build_info_keil_m4\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
