.TH "pac_foc/src/comm Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/comm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBppm\fP"
.br
.ti -1c
.RI "directory \fBpush_button\fP"
.br
.ti -1c
.RI "directory \fBuart_gui\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcomm\&.h\fP"
.br
.RI "Use for communication initialization UART, PPM, Push Button\&. "
.in -1c
