.TH "pac_foc/src/param Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/param Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBntc_table\&.c\fP"
.br
.RI "Use for temperature calculation\&. "
.ti -1c
.RI "file \fBparam\&.h\fP"
.br
.RI "Use for parameter processing\&. "
.ti -1c
.RI "file \fBparam_calc\&.h\fP"
.br
.RI "Use for parameter processing\&. "
.ti -1c
.RI "file \fBparam_default\&.h\fP"
.br
.RI "Use for parameter processing\&. "
.ti -1c
.RI "file \fBparam_user_1\&.h\fP"
.br
.RI "Use for parameter processing\&. "
.ti -1c
.RI "file \fBparameter_process\&.c\fP"
.br
.RI "Use for parameter processing\&. "
.ti -1c
.RI "file \fBparameter_process\&.h\fP"
.br
.RI "Use for parameter processing\&. "
.in -1c
