.TH "pac_foc/src/mpos/estimator Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/estimator Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanglediff\&.c\fP"
.br
.RI "Use to check for angle difference between open loop and est angle and est speed\&. "
.ti -1c
.RI "file \fBanglediff\&.h\fP"
.br
.RI "Use to check for angle difference between open loop and est angle and est speed thrd\&. "
.ti -1c
.RI "file \fBanglediff_lib\&.h\fP"
.br
.ti -1c
.RI "file \fBest_sim2est\&.h\fP"
.br
.RI "Use for making system variables ready for SIM to EST transition\&. "
.ti -1c
.RI "file \fBestimator_build_info_eclipse\&.h\fP"
.br
.ti -1c
.RI "file \fBestimator_build_info_eclipse_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBestimator_build_info_iar\&.h\fP"
.br
.ti -1c
.RI "file \fBestimator_build_info_iar_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBestimator_build_info_keil\&.h\fP"
.br
.ti -1c
.RI "file \fBestimator_build_info_keil_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBlbg1\&.h\fP"
.br
.RI "Estimator main functions\&. "
.ti -1c
.RI "file \fBlbg1_funcs\&.c\fP"
.br
.RI "Estimator utility functions\&. "
.ti -1c
.RI "file \fBlbg1_funcs\&.h\fP"
.br
.RI "Estimator utility functions\&. "
.ti -1c
.RI "file \fBlbg1_struct\&.h\fP"
.br
.RI "Estimator structure\&. "
.in -1c
