.TH "pac_foc/src/startup Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/startup Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstartup_aligngo2est_funcs\&.h\fP"
.br
.RI "Use for hall startup functions\&. "
.ti -1c
.RI "file \fBstartup_aligngo2est_struct\&.h\fP"
.br
.ti -1c
.RI "file \fBstartup_aligngo2qep_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBstartup_aligngo2qep_struct\&.h\fP"
.br
.ti -1c
.RI "file \fBstartup_hall_funcs\&.h\fP"
.br
.RI "Use for hall startup functions\&. "
.ti -1c
.RI "file \fBstartup_hall_struct\&.h\fP"
.br
.RI "Use for hallstartup enum and struct\&. "
.in -1c
