.TH "pac_foc/src/comm/push_button Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/comm/push_button Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpush_button\&.c\fP"
.br
.RI "Use to configure push button as GPIO input, button status and state initialization\&. "
.ti -1c
.RI "file \fBpush_button\&.h\fP"
.br
.RI "Use to configure push button as GPIO input, button status and state initialization\&. "
.in -1c
