.TH "pac_foc/src/math Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcalc_angle\&.h\fP"
.br
.RI "Definitions for angle calculation\&. "
.ti -1c
.RI "file \fBcalc_speed\&.h\fP"
.br
.RI "Definitions for speed calculation routines\&. "
.ti -1c
.RI "file \fBcircle_table\&.c\fP"
.br
.RI "Fixed-point circle table for the FOC controller\&. "
.ti -1c
.RI "file \fBfast_div\&.h\fP"
.br
.RI "Fast divider definitions\&. "
.ti -1c
.RI "file \fBfix16\&.c\fP"
.br
.RI "Fixed math library functions (fix16_t) "
.ti -1c
.RI "file \fBfix16\&.h\fP"
.br
.RI "Fixed math library declarations (fix16_t) "
.ti -1c
.RI "file \fBfix16_sqrt\&.c\fP"
.br
.RI "fix16_t square root functions "
.ti -1c
.RI "file \fBint64\&.h\fP"
.br
.RI "Definitions for 64-bit math functions\&. "
.ti -1c
.RI "file \fBmaths\&.c\fP"
.br
.RI "Math support functions\&. "
.ti -1c
.RI "file \fBmaths\&.h\fP"
.br
.RI "Math support function declarations\&. "
.ti -1c
.RI "file \fBpid\&.c\fP"
.br
.RI "PID functions\&. "
.ti -1c
.RI "file \fBpid\&.h\fP"
.br
.RI "PID function declarations\&. "
.ti -1c
.RI "file \fBsin_table\&.c\fP"
.br
.RI "Sine table\&. "
.ti -1c
.RI "file \fBsqrt\&.h\fP"
.br
.RI "Square root function declarations\&. "
.ti -1c
.RI "file \fBtrig\&.c\fP"
.br
.RI "Trigonometric support functions\&. "
.ti -1c
.RI "file \fBtrig\&.h\fP"
.br
.RI "Trigonometric support function declarations\&. "
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.RI "Utility function declarations\&. "
.in -1c
