.TH "pac_foc/src/features/sim Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsim_build_info_eclipse\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_build_info_eclipse_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_build_info_iar\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_build_info_iar_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_build_info_keil\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_build_info_keil_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_funcs\&.c\fP"
.br
.RI "Use for SIM sequencer and state initialization\&. "
.ti -1c
.RI "file \fBsim_funcs\&.h\fP"
.br
.RI "Contains generic SIM function definitions and includes all SIM functions for the selected SIM method\&. "
.ti -1c
.RI "file \fBsim_h_defs\&.h\fP"
.br
.RI "Use for SIM Hall States, SIM2CL States and Status definitions\&. "
.ti -1c
.RI "file \fBsim_h_funcs\&.c\fP"
.br
.RI "Use for SIM hall utility functions\&. "
.ti -1c
.RI "file \fBsim_h_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_h_funcs_ext\&.h\fP"
.br
.RI "Use to set Hall SIM flags\&. "
.ti -1c
.RI "file \fBsim_h_struct\&.h\fP"
.br
.RI "Use for Hall SIM structure\&. "
.ti -1c
.RI "file \fBsim_i_defs\&.h\fP"
.br
.RI "I-SIM State and status definitions\&. "
.ti -1c
.RI "file \fBsim_i_funcs\&.c\fP"
.br
.RI "I-SIM function definitions\&. "
.ti -1c
.RI "file \fBsim_i_funcs\&.h\fP"
.br
.RI "I-SIM function declarations\&. "
.ti -1c
.RI "file \fBsim_i_struct\&.h\fP"
.br
.RI "I-SIM structure definition\&. "
.ti -1c
.RI "file \fBsim_sm\&.c\fP"
.br
.RI "SIM state machine\&. "
.ti -1c
.RI "file \fBsim_struct\&.h\fP"
.br
.RI "Includes the structure definition for selected SIM method\&. "
.ti -1c
.RI "file \fBsim_v_defs\&.h\fP"
.br
.RI "V-SIM State and status definitions\&. "
.ti -1c
.RI "file \fBsim_v_funcs\&.c\fP"
.br
.RI "V-SIM function definitions\&. "
.ti -1c
.RI "file \fBsim_v_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBsim_v_struct\&.h\fP"
.br
.RI "V-SIM structure definition\&. "
.ti -1c
.RI "file \fBsim_version\&.h\fP"
.br
.in -1c
