.TH "pac_foc/src/mpos/hall Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/hall Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhall_funcs\&.c\fP"
.br
.RI "Use for hall FOC utility functions\&. "
.ti -1c
.RI "file \fBhall_funcs\&.h\fP"
.br
.RI "Use for hall FOC utility functions\&. "
.ti -1c
.RI "file \fBhall_hall2est\&.h\fP"
.br
.RI "Use for hall FOC utility functions\&. "
.ti -1c
.RI "file \fBhall_io_config\&.h\fP"
.br
.RI "Use for hall port and interrupt initialization and utility function\&. "
.ti -1c
.RI "file \fBhall_sim2hall\&.h\fP"
.br
.RI "Use for hall port and interrupt initialization and utility function\&. "
.ti -1c
.RI "file \fBhall_struct\&.h\fP"
.br
.RI "Use for hall structure definition\&. "
.ti -1c
.RI "file \fBhall_timer_config\&.h\fP"
.br
.RI "Use for hall timer initialization and utility function\&. "
.in -1c
