.TH "pac_foc/src/control Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontrol_1shunt_funcs\&.h\fP"
.br
.RI "Use for single shunt control functions\&. "
.ti -1c
.RI "file \fBcontrol_1shunt_struct\&.h\fP"
.br
.RI "Use for single shunt control functions and structures\&. "
.ti -1c
.RI "file \fBcontrol_3shunt_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_3shunt_struct\&.h\fP"
.br
.RI "Use for 3 shunt motor current structure\&. "
.ti -1c
.RI "file \fBcontrol_build_info_eclipse\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_build_info_eclipse_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_build_info_iar\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_build_info_iar_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_build_info_keil\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_build_info_keil_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_funcs\&.c\fP"
.br
.RI "Use for FOC control functions\&. "
.ti -1c
.RI "file \fBcontrol_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBcontrol_loop\&.h\fP"
.br
.RI "Use for FOC main control loop function\&. "
.ti -1c
.RI "file \fBcontrol_power1\&.h\fP"
.br
.RI "Use for control power functions\&. "
.ti -1c
.RI "file \fBcontrol_power1_funcs\&.h\fP"
.br
.RI "Use for control power calculation\&. "
.ti -1c
.RI "file \fBcontrol_power1_struct\&.h\fP"
.br
.RI "Use for control power measurement storage\&. "
.ti -1c
.RI "file \fBcontrol_power2_funcs\&.c\fP"
.br
.ti -1c
.RI "file \fBcontrol_power2_funcs\&.h\fP"
.br
.RI "Use for control power functions\&. "
.ti -1c
.RI "file \fBcontrol_power2_struct\&.h\fP"
.br
.RI "Use for control power measurement storage\&. "
.ti -1c
.RI "file \fBcontrol_power_funcs\&.h\fP"
.br
.RI "Use for control power calculation\&. "
.ti -1c
.RI "file \fBcontrol_sm\&.h\fP"
.br
.RI "Use for FOC control state machine\&. "
.ti -1c
.RI "file \fBcontrol_struct\&.h\fP"
.br
.RI "Use for FOC control related variables\&. "
.ti -1c
.RI "file \fBfoc\&.h\fP"
.br
.RI "Use for basic FOC process function\&. "
.ti -1c
.RI "file \fBfoc_funcs\&.c\fP"
.br
.RI "Use for FOC initialization\&. "
.ti -1c
.RI "file \fBfoc_funcs\&.h\fP"
.br
.RI "Use for FOC utility functions, IdIq current filter, Id & Iq PI, vqmax\&. "
.ti -1c
.RI "file \fBfoc_math\&.h\fP"
.br
.RI "Use for basic FOC math functions, like park, clarke, inverse park, SVM\&. "
.ti -1c
.RI "file \fBfoc_struct\&.h\fP"
.br
.RI "Use for basic FOC structure\&. "
.ti -1c
.RI "file \fBharmonic_inj_funcs\&.h\fP"
.br
.RI "Use for SVM harmonic injection\&. "
.ti -1c
.RI "file \fBharmonic_inj_libfuncs\&.h\fP"
.br
.ti -1c
.RI "file \fBharmonic_inj_struct\&.h\fP"
.br
.RI "Use for SVM harmonic injection\&. "
.ti -1c
.RI "file \fBmtpa\&.h\fP"
.br
.RI "Use for FOC mtpa functions\&. "
.ti -1c
.RI "file \fBmtpa_funcs\&.c\fP"
.br
.RI "Use for FOC MTPA function\&. "
.ti -1c
.RI "file \fBmtpa_funcs\&.h\fP"
.br
.RI "Use for FOC MTPA function\&. "
.ti -1c
.RI "file \fBmtpa_struct\&.h\fP"
.br
.RI "Use for FOC mtpa structure\&. "
.ti -1c
.RI "file \fBovermod\&.h\fP"
.br
.RI "Use for FOC over modulation functions\&. "
.ti -1c
.RI "file \fBovermod_funcs\&.c\fP"
.br
.RI "Use for FOC over modulation function\&. "
.ti -1c
.RI "file \fBovermod_funcs\&.h\fP"
.br
.RI "Use for FOC over modulation function\&. "
.ti -1c
.RI "file \fBovermod_struct\&.h\fP"
.br
.RI "Use for FOC over modulation structure\&. "
.in -1c
