.TH "pac_foc/src Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapp\fP"
.br
.ti -1c
.RI "directory \fBcomm\fP"
.br
.ti -1c
.RI "directory \fBcontrol\fP"
.br
.ti -1c
.RI "directory \fBdebug\fP"
.br
.ti -1c
.RI "directory \fBfeatures\fP"
.br
.ti -1c
.RI "directory \fBisr\fP"
.br
.ti -1c
.RI "directory \fBmath\fP"
.br
.ti -1c
.RI "directory \fBmpos\fP"
.br
.ti -1c
.RI "directory \fBparam\fP"
.br
.ti -1c
.RI "directory \fBstartup\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig_app\&.h\fP"
.br
.RI "Use for selecting different FOC firmware application features\&. "
.ti -1c
.RI "file \fBconfig_debug\&.h\fP"
.br
.RI "Use for different FOC firmware debug option selection\&. "
.ti -1c
.RI "file \fBconfig_features\&.h\fP"
.br
.RI "Use for different FOC firmware features selection\&. "
.ti -1c
.RI "file \fBconfig_options\&.h\fP"
.br
.RI "Use for different FOC hardware and firmware option selection\&. "
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Use for motor control hardware and software initialization\&. "
.in -1c
