.TH "pac_foc/src/features/opd Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/opd Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBopd_cl\&.h\fP"
.br
.RI "Use to process control functions in OPD\&. "
.ti -1c
.RI "file \fBopd_cl_config\&.h\fP"
.br
.RI "Configuration for closed-loop open phase detection\&. "
.ti -1c
.RI "file \fBopd_cl_funcs\&.c\fP"
.br
.RI "Use for control functions in OPD\&. "
.ti -1c
.RI "file \fBopd_cl_funcs\&.h\fP"
.br
.RI "Use for defining control functions in OPD\&. "
.ti -1c
.RI "file \fBopd_cl_struct\&.h\fP"
.br
.RI "Use for defining OPD structure\&. "
.ti -1c
.RI "file \fBopd_ol\&.h\fP"
.br
.RI "Use to process control functions in Open-loop OPD\&. "
.ti -1c
.RI "file \fBopd_ol_config\&.h\fP"
.br
.RI "Configuration for open-loop open phase detection\&. "
.ti -1c
.RI "file \fBopd_ol_funcs\&.c\fP"
.br
.RI "Use for control functions in OPD\&. "
.ti -1c
.RI "file \fBopd_ol_funcs\&.h\fP"
.br
.RI "Use for defining control functions in OPD\&. "
.ti -1c
.RI "file \fBopd_ol_struct\&.h\fP"
.br
.RI "Use for defining Open-loop OPD structure\&. "
.in -1c
