.TH "pac_foc/src/features Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBautotune\fP"
.br
.ti -1c
.RI "directory \fBflash_crc_test\fP"
.br
.ti -1c
.RI "directory \fBhalltune\fP"
.br
.ti -1c
.RI "directory \fBipd\fP"
.br
.ti -1c
.RI "directory \fBopd\fP"
.br
.ti -1c
.RI "directory \fBsim\fP"
.br
.ti -1c
.RI "directory \fBstalldet\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdcbus_check\&.c\fP"
.br
.RI "Use to check is DC bus is with-in min-max voltage range and post fault\&. "
.ti -1c
.RI "file \fBdcbus_check\&.h\fP"
.br
.ti -1c
.RI "file \fBfw_funcs\&.c\fP"
.br
.RI "Use for field weakening utility functions\&. "
.ti -1c
.RI "file \fBfw_funcs\&.h\fP"
.br
.RI "Use for field weakening utility functions\&. "
.ti -1c
.RI "file \fBfw_struct\&.h\fP"
.br
.ti -1c
.RI "file \fBsatmon\&.c\fP"
.br
.RI "Use for PWM_SATURATED check\&. "
.ti -1c
.RI "file \fBsatmon\&.h\fP"
.br
.RI "Use for PWM_SATURATED check\&. "
.ti -1c
.RI "file \fBspeed_check\&.c\fP"
.br
.RI "Use for check speed min - max limit and generate speed fault\&. "
.ti -1c
.RI "file \fBspeed_check\&.h\fP"
.br
.ti -1c
.RI "file \fBwatchdog\&.c\fP"
.br
.RI "Use to initialize watchdog timer\&. "
.ti -1c
.RI "file \fBwatchdog\&.h\fP"
.br
.RI "Use to initialize watchdog timer\&. "
.in -1c
