.TH "pac_foc/src/features/autotune Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/autotune Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatune_funcs\&.c\fP"
.br
.RI "Use for parameters update on the current and speed-loop PI gains\&. "
.ti -1c
.RI "file \fBatune_funcs\&.h\fP"
.br
.RI "Use for auto-tuning functions definition\&. "
.ti -1c
.RI "file \fBatune_libfuncs\&.h\fP"
.br
.RI "Use for atune lib function definition\&. "
.ti -1c
.RI "file \fBatune_struct\&.h\fP"
.br
.RI "Use for auto-tuning structure definition\&. "
.ti -1c
.RI "file \fBautotune_build_info_eclipse\&.h\fP"
.br
.ti -1c
.RI "file \fBautotune_build_info_eclipse_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBautotune_build_info_iar\&.h\fP"
.br
.ti -1c
.RI "file \fBautotune_build_info_iar_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBautotune_build_info_keil\&.h\fP"
.br
.ti -1c
.RI "file \fBautotune_build_info_keil_m4\&.h\fP"
.br
.ti -1c
.RI "file \fBmid1_funcs\&.c\fP"
.br
.RI "Use for auto-tuning function calls in motor identification 1\&. "
.ti -1c
.RI "file \fBmid1_funcs\&.h\fP"
.br
.RI "Use for auto-tuning function definition in motor identification 1\&. "
.ti -1c
.RI "file \fBmid2_funcs\&.c\fP"
.br
.RI "Use for the control functions in motor identification 2\&. "
.ti -1c
.RI "file \fBmid2_funcs\&.h\fP"
.br
.RI "Use for the function definitions in mid2\&. "
.in -1c
