.TH "pac_foc/src/mpos/qep Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/qep Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqep_funcs\&.c\fP"
.br
.ti -1c
.RI "file \fBqep_funcs\&.h\fP"
.br
.ti -1c
.RI "file \fBqep_io_config\&.h\fP"
.br
.ti -1c
.RI "file \fBqep_struct\&.h\fP"
.br
.ti -1c
.RI "file \fBqep_timer_config\&.h\fP"
.br
.in -1c
