.TH "pac_foc/src/isr Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/isr Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBisr_adc\&.c\fP"
.br
.RI "Use for ADC ISR\&. "
.ti -1c
.RI "file \fBisr_gpioA\&.c\fP"
.br
.RI "Use for PortA ISR\&. "
.ti -1c
.RI "file \fBisr_gpioB\&.c\fP"
.br
.RI "Use for PortB ISR\&. "
.ti -1c
.RI "file \fBisr_gpioC\&.c\fP"
.br
.ti -1c
.RI "file \fBisr_gpioD\&.c\fP"
.br
.RI "Use for PortD ISR\&. "
.ti -1c
.RI "file \fBisr_qepC\&.c\fP"
.br
.ti -1c
.RI "file \fBisr_qepD\&.c\fP"
.br
.ti -1c
.RI "file \fBisr_stubs\&.c\fP"
.br
.RI "Use for NMI, MemCtl, HardFault and Default ISR handlers\&. "
.ti -1c
.RI "file \fBisr_systick\&.c\fP"
.br
.ti -1c
.RI "file \fBisr_timerA\&.c\fP"
.br
.RI "Use for timerA timer interrupt handler to run critical FOC functions\&. "
.ti -1c
.RI "file \fBisr_timerB\&.c\fP"
.br
.RI "Use for timerB timer interrupt handler to run critical FOC functions\&. "
.ti -1c
.RI "file \fBisr_timerC\&.c\fP"
.br
.RI "Use for timerC timer interrupt handler to run critical FOC functions\&. "
.ti -1c
.RI "file \fBisr_timerD\&.c\fP"
.br
.RI "Use for timerD timer interrupt handler to run critical FOC functions\&. "
.ti -1c
.RI "file \fBisr_timerGPTA\&.c\fP"
.br
.in -1c
