.TH "pac_foc/src/comm/uart_gui Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/comm/uart_gui Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBuart_gui\&.c\fP"
.br
.RI "Use for UART parameter write, checksum cal, message processing\&. "
.ti -1c
.RI "file \fBuart_gui\&.h\fP"
.br
.RI "Use for UART parameter write, checksum calculation, message processing\&. "
.in -1c
