.TH "pac_foc/src/mpos Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaligngo\fP"
.br
.ti -1c
.RI "directory \fBestimator\fP"
.br
.ti -1c
.RI "directory \fBhall\fP"
.br
.ti -1c
.RI "directory \fBqep\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmpos_funcs\&.h\fP"
.br
.RI "Use for mpos calculator function\&. "
.ti -1c
.RI "file \fBmpos_misc\&.h\fP"
.br
.RI "Use for mpos utility functions\&. "
.ti -1c
.RI "file \fBmpos_struct\&.h\fP"
.br
.RI "Use for mpos enums and structure\&. "
.in -1c
