.TH "pac_foc/src/comm/comm.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/comm/comm.h \- Use for communication initialization UART, PPM, Push Button\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'config_app\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'config_debug\&.h'\fP
.br
\fC#include 'uart_gui\&.h'\fP
.br
\fC#include 'ppm\&.h'\fP
.br
\fC#include 'push_button\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for communication initialization UART, PPM, Push Button\&. 


.PP
Definition in file \fBcomm\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
