.TH "pac_foc/src/control/control_1shunt_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/control_1shunt_funcs.h \- Use for single shunt control functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_timer\&.h'\fP
.br
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'control_1shunt_struct\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEQRD_FOC_I1\fP   AS0R0"
.br
.ti -1c
.RI "#define \fBSEQRD_FOC_I2\fP   AS1R0"
.br
.ti -1c
.RI "#define \fBSEQRD_FOC_VBUS\fP   AS1R1"
.br
.ti -1c
.RI "#define \fBSEQRD_FOC_IBUSAVG\fP   AS1R2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use for single shunt control functions\&. 


.PP
Definition in file \fBcontrol_1shunt_funcs\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define SEQRD_FOC_I1   AS0R0"

.PP
Definition at line 41 of file control_1shunt_funcs\&.h\&.
.SS "#define SEQRD_FOC_I2   AS1R0"

.PP
Definition at line 42 of file control_1shunt_funcs\&.h\&.
.SS "#define SEQRD_FOC_IBUSAVG   AS1R2"

.PP
Definition at line 47 of file control_1shunt_funcs\&.h\&.
.SS "#define SEQRD_FOC_VBUS   AS1R1"

.PP
Definition at line 44 of file control_1shunt_funcs\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
