.TH "pac_foc/src/control/control_sm.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/control_sm.h \- Use for FOC control state machine\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'config_options\&.h'\fP
.br
\fC#include 'board\&.h'\fP
.br
\fC#include 'config_app\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'mpos_funcs\&.h'\fP
.br
\fC#include 'control_funcs\&.h'\fP
.br
\fC#include 'foc\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for FOC control state machine\&. 


.PP
Definition in file \fBcontrol_sm\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
