.TH "pac_foc/src/control/control_3shunt_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/control_3shunt_funcs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_timer\&.h'\fP
.br
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
