.TH "pac_foc/src/control/control_power1_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/control_power1_funcs.h \- Use for control power calculation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'control_power1_struct\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for control power calculation\&. 


.PP
Definition in file \fBcontrol_power1_funcs\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
