pac_foc/src/control/control_funcs.h
NAME
pac_foc/src/control/control_funcs.h
SYNOPSIS
#include 'pac5xxx.h'
#include 'motor_struct.h'
#include 'utils.h'
#include 'control_3shunt_funcs.h'
Functions
void control_reset (Struct_Motor *motor_ptr)
This function use to reset FOC related variables.
void calculate_outerloop_scale_shift (fix16_t value_max, uint16_t *shift, uint32_t *outerloop_scale_q0)
This function use to calculate outer loop scale factor.
void config_control_dt (Struct_Motor *motor_ptr, int32_t dt_control_q26, uint32_t ctrl_divider)
Function Documentation
void calculate_outerloop_scale_shift (fix16_t value_max, uint16_t * shift, uint32_t * outerloop_scale_q0)
This function use to calculate outer loop scale factor.
Parameters
fix16_t value_max
uint16_t *shift
uint32_t *outerloop_scale_q0
Definition at line 96 of file control_funcs.c.
{
    fix16_t value_max_padded;
    // Absolute value
    if (value_max < 0)
        value_max = -value_max;
    // Cap max value at 16383 so that 2x does not overflow
    if (value_max > QCONST(16383.0f, Q16))
        value_max = QCONST(16383.0f, Q16);
    // Pad max value to 2x (to allow for overshoots and noise)
    value_max_padded = (value_max << 1);
    // Generate scaling shift applied to outer loop PI controller
    if (value_max_padded >= QCONST(16384, Q16))
        *shift = 15; // Shift=15, Res=0.5, Min=16384, Max=32768<
    else if (value_max_padded >= QCONST(8192, Q16))
        *shift = 14; // Shift=14, Res=0.25, Min=8192, Max=16384<
    else if (value_max_padded >= QCONST(4096, Q16))
        *shift = 13; // Shift=13, Res=0.125, Min=4096, Max=8192<
    else if (value_max_padded >= QCONST(2048, Q16))
        *shift = 12; // Shift=12, Res=0.0625, Min=2048, Max=4096<
    else if (value_max_padded >= QCONST(1024, Q16))
        *shift = 11; // Shift=11, Res=0.03125, Min=1024, Max=2048<
    else if (value_max_padded >= QCONST(512, Q16))
        *shift = 10; // Shift=10, Res=0.015625, Min=512, Max=1024<
    else if (value_max_padded >= QCONST(256, Q16))
        *shift = 9; // Shift=9, Res=0.0078125, Min=256, Max=512<
    else if (value_max_padded >= QCONST(128, Q16))
        *shift = 8; // Shift=8, Res=0.00390625, Min=128, Max=256<
    else if (value_max_padded >= QCONST(64, Q16))
        *shift = 7; // Shift=7, Res=0.001953125, Min=64, Max=128<
    else if (value_max_padded >= QCONST(32, Q16))
        *shift = 6; // Shift=6, Res=0.0009765625, Min=32, Max=64<
    else if (value_max_padded >= QCONST(16, Q16))
        *shift = 5; // Shift=5, Res=0.00048828125, Min=16, Max=32<
    else if (value_max_padded >= QCONST(8, Q16))
        *shift = 4; // Shift=4, Res=0.000244140625, Min=8, Max=16<
    else if (value_max_padded >= QCONST(4, Q16))
        *shift = 3; // Shift=3, Res=0.0001220703125, Min=4, Max=8<
    else if (value_max_padded >= QCONST(2, Q16))
        *shift = 2; // Shift=2, Res=0.00006103515625, Min=2, Max=4<
    else if (value_max_padded >= QCONST(1, Q16))
        *shift = 1; // Shift=1, Res=0.000030517578125, Min=1, Max=2<
    else // <= 0
        *shift = 0; // Shift=0, Res=0.0000152587890625, Min=0, Max=1<
    *outerloop_scale_q0 = (1 << *shift);
}
References Q16, and QCONST.
void config_control_dt (Struct_Motor * motor_ptr, int32_t dt_control_q26, uint32_t ctrl_divider)
Definition at line 149 of file control_funcs.c.
{
    motor_ptr->control.dt_control_q26 = dt_control_q26;
    motor_ptr->control.dt_control_1div_q6 = fix16_div(FIX16_1P0, dt_control_q26);
    motor_ptr->control.ctrl_divider = ctrl_divider;
}
References Struct_Motor::control, Struct_Control::ctrl_divider, Struct_Control::dt_control_1div_q6, Struct_Control::dt_control_q26, FIX16_1P0, and fix16_div().
Referenced by sm_mainsub_prestart().
void control_reset (Struct_Motor * motor_ptr)
This function use to reset FOC related variables.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 33 of file control_funcs.c.
{
    pid_reset(&(motor_ptr->control.outerloop_pid)); // Reset PID controller data
    // Reset duty cycle variables
    motor_ptr->control.u_duty_value = (motor_ptr->control.motor_period_ticks >> 1); // hold u duty in 16 bit sign short format
    motor_ptr->control.v_duty_value = (motor_ptr->control.motor_period_ticks >> 1); // hold v duty in 16 bit sign short format
    motor_ptr->control.w_duty_value = (motor_ptr->control.motor_period_ticks >> 1); // hold w duty in 16 bit sign short format
#if (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT) && (MODE_1SHUNT_SELECT == MODE_1SHUNT_ASYMMETRIC)
    motor_ptr->oneshunt.duty_u_up = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.duty_u_dn = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.duty_v_up = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.duty_v_dn = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.duty_w_up = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.duty_w_dn = (motor_ptr->control.motor_period_ticks >> 1);
#endif
#if (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT) && (MODE_1SHUNT_SELECT == MODE_1SHUNT_EXTENSION)
    motor_ptr->oneshunt.duty_comp_sign_1 = 1;
    motor_ptr->oneshunt.duty_comp_sign_2 = 1;
    motor_ptr->oneshunt.duty_comp_sign_3 = 1;
    motor_ptr->oneshunt.flag_current_valid = 1;
    motor_ptr->oneshunt.flag_current_valid_sreg = 1;
    motor_ptr->oneshunt.ss_sector = 2;
    motor_ptr->oneshunt.ss_sector_sreg = 2;
    motor_ptr->oneshunt.svm_sector_prev = 2;
    motor_ptr->oneshunt.taccr0_value = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.taccr1_value = (motor_ptr->control.motor_period_ticks >> 1);
#elif (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT) && (MODE_1SHUNT_SELECT == MODE_1SHUNT_ASYMMETRIC)
    motor_ptr->oneshunt.ss_sector = 2;
    motor_ptr->oneshunt.ss_sector_sreg = 2;
    motor_ptr->oneshunt.taccr0_value = (motor_ptr->control.motor_period_ticks >> 1);
    motor_ptr->oneshunt.taccr1_value = (motor_ptr->control.motor_period_ticks >> 1);
#endif
    motor_ptr->control.outerloop_ramp = 0;
    motor_ptr->control.outerloop_ramp_scaled_q14 = 0;
    motor_ptr->control.outerloop_fdbk_scaled_q14 = 0;
    motor_ptr->control.iqrefcl_target_f16 = motor_ptr->app.iqrefcl_cmd_f16;
    motor_ptr->control.idrefcl_target_f16 = motor_ptr->app.idrefcl_cmd_f16;
    #ifdef ENABLE_BOOTPROT
    motor_ptr->bootprot.bootprot_count1 = 0;
    motor_ptr->bootprot.bootprot_count2 = 0;
    motor_ptr->bootprot.bootprot_count3 = 0;
    #endif
#if defined(ENABLE_FIELD_WEAKENING)
    fw_reset(motor_ptr);
#endif
}
References Struct_Motor::app, Struct_Motor::control, Struct_OneShunt_Extn::duty_comp_sign_1, Struct_OneShunt_Extn::duty_comp_sign_2, Struct_OneShunt_Extn::duty_comp_sign_3, Struct_OneShunt_Extn::flag_current_valid, Struct_OneShunt_Extn::flag_current_valid_sreg, Struct_App::idrefcl_cmd_f16, Struct_Control::idrefcl_target_f16, Struct_App::iqrefcl_cmd_f16, Struct_Control::iqrefcl_target_f16, Struct_Control::motor_period_ticks, Struct_Motor::oneshunt, Struct_Control::outerloop_fdbk_scaled_q14, Struct_Control::outerloop_pid, Struct_Control::outerloop_ramp, Struct_Control::outerloop_ramp_scaled_q14, pid_reset(), Struct_OneShunt_Extn::ss_sector, Struct_OneShunt_Extn::ss_sector_sreg, Struct_OneShunt_Extn::svm_sector_prev, Struct_OneShunt_Extn::taccr0_value, Struct_OneShunt_Extn::taccr1_value, Struct_Control::u_duty_value, Struct_Control::v_duty_value, and Struct_Control::w_duty_value.
Referenced by motor_reset().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.