.TH "pac_foc/src/features/dcbus_check.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/dcbus_check.h
.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_dcbus_fault\fP (\fBStruct_Motor\fP *motor_ptr)"
.br
.RI "Use to check is DC bus is with-in min-max voltage range\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void check_dcbus_fault (\fBStruct_Motor\fP * motor_ptr)"

.PP
Use to check is DC bus is with-in min-max voltage range\&. 
.PP
\fBParameters\fP
.RS 4
\fIStruct_Motor*\fP motor_ptr 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
