.TH "pac_foc/src/features/dcbus_check.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/dcbus_check.c \- Use to check is DC bus is with-in min-max voltage range and post fault\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'dcbus_check\&.h'\fP
.br
\fC#include 'fault\&.h'\fP
.br
\fC#include 'app_funcs\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use to check is DC bus is with-in min-max voltage range and post fault\&. 


.PP
Definition in file \fBdcbus_check\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
