.TH "pac_foc/src/debug/debug_export.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/debug/debug_export.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBexport_variables\fP (\fBfix16_t\fP variable_num)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfix16_t\fP \fBgui_parameter_command\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBparameter_value1\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBparameter_value2\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBparameter_value3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void export_variables (\fBfix16_t\fP variable_num)"

.SH "Variable Documentation"
.PP 
.SS "\fBfix16_t\fP gui_parameter_command\fC [extern]\fP"

.SS "\fBfix16_t\fP parameter_value1\fC [extern]\fP"

.SS "\fBfix16_t\fP parameter_value2\fC [extern]\fP"

.SS "\fBfix16_t\fP parameter_value3\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
