pac_foc/src/app/driver_funcs.c
NAME
pac_foc/src/app/driver_funcs.c - Use to initialize PWM duty, port mode and enable disable motor, low side PWM.
SYNOPSIS
#include 'config_app.h'
#include 'pac5xxx.h'
#include 'motor_struct.h'
#include 'driver_funcs.h'
#include 'pac5xxx_driver_tile.h'
Functions
void m1_enable (void)
This function use to enable motor.
void m1_enable_with_duty (uint32_t duty_cycle)
This function use to set all three phases PWM duty cycle.
void m1_enable_no_duty (void)
This function use to enable PWM, GPIO and OutPut Enable.
void set_drivers_gpio (void)
This function use to set port to GPIO mode and set output to low.
void m1_disable (void)
This function use to disable motor.
void m1_LS_pwm_only_config (void)
This function use to configure low side PWM.
Detailed Description
Use to initialize PWM duty, port mode and enable disable motor, low side PWM.
Definition in file driver_funcs.c.
Function Documentation
void m1_disable (void)
This function use to disable motor.
Definition at line 107 of file driver_funcs.c.
{
    // Disable driver manager and verify active - need to enable even in PAC5210 to get ENHS pin to work
    pac5xxx_tile_register_write(ADDR_ENDRV, 0);
    // Set drivers to GPIO mode
    set_drivers_gpio();
    // Set duty cycles to 50%
    m1_u_set_duty(motor.control.motor_period_ticks >> 1);
    m1_v_set_duty(motor.control.motor_period_ticks >> 1);
    m1_w_set_duty(motor.control.motor_period_ticks >> 1);
}
References Struct_Motor::control, motor, Struct_Control::motor_period_ticks, and set_drivers_gpio().
Referenced by fault(), and statemachine_appmain().
void m1_enable (void)
This function use to enable motor.
Definition at line 30 of file driver_funcs.c.
{
    m1_enable_with_duty(motor.control.motor_period_ticks >> 1);
}
References Struct_Motor::control, m1_enable_with_duty(), motor, and Struct_Control::motor_period_ticks.
void m1_enable_no_duty (void)
This function use to enable PWM, GPIO and OutPut Enable.
Definition at line 68 of file driver_funcs.c.
{
    // Select PWM peripheral for Driver Port
    motor_psel_pwm();
   // Select GPIO mode for Driver Port
    motor_modesel_gpio();
    
    // Turn on output enables
    motor_outen_enable();
    // Enable driver manager and verify active - need to enable even in PAC5210 to get ENHS pin to work
#ifdef CAFE_ARCH3
    pac5xxx_tile_register_write(ADDR_ENDRV, 1 | (1 << 1));
#else
    pac5xxx_tile_register_write(ADDR_ENDRV, 1);
#endif
}
void m1_enable_with_duty (uint32_t duty_cycle)
This function use to set all three phases PWM duty cycle. Use to enable motor with duty cycle.
Parameters
duty_cycle
Definition at line 40 of file driver_funcs.c.
{
    // Set duty cycles to 50%
    m1_u_set_duty(duty_cycle);
    m1_v_set_duty(duty_cycle);
    m1_w_set_duty(duty_cycle);
    // Select PWM peripheral for Driver Port
    motor_psel_pwm();
    
   // Select GPIO mode for Driver Port
    motor_modesel_gpio();
    
    // Turn on output enables
    motor_outen_enable();
    // Enable driver manager and verify active - need to enable even in PAC5210 to get ENHS pin to work
#ifdef CAFE_ARCH3
    pac5xxx_tile_register_write(ADDR_ENDRV, 1 | (1 << 1));
#else
      pac5xxx_tile_register_write(ADDR_ENDRV, 1);
#endif
}
Referenced by m1_enable().
void m1_LS_pwm_only_config (void)
This function use to configure low side PWM.
Definition at line 125 of file driver_funcs.c.
{
    // Set IO state of all pins to 0
    motor_out_clear();
    // Select GPIO peripheral for Port A
    motor_psel_gpio();
    // Select PWM peripheral for Port A only low side
    motor_psel_pwm_LS();
    // Turn on output enables
    motor_outen_enable();
    // Enable driver manager
#ifdef CAFE_ARCH3
    pac5xxx_tile_register_write(ADDR_ENDRV, 1 | (1 << 1));
#else
    pac5xxx_tile_register_write(ADDR_ENDRV, 1);
#endif
}
void set_drivers_gpio (void)
This function use to set port to GPIO mode and set output to low.
Definition at line 91 of file driver_funcs.c.
{
    // Set IO state of all pins to 0
    motor_out_clear();
    // Select GPIO peripheral for Driver Port
    motor_psel_gpio();
    // Select GPIO mode for Driver Port
    motor_modesel_gpio();
    // Turn on output enables
    motor_outen_enable();
}
Referenced by m1_disable(), oc_reset(), and statemachine_appmain().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.