.TH "pac_foc/src/mpos/estimator/est_sim2est.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/estimator/est_sim2est.h \- Use for making system variables ready for SIM to EST transition\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'config_app\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'lbg1_funcs\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for making system variables ready for SIM to EST transition\&. 


.PP
Definition in file \fBest_sim2est\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
