.TH "pac_foc/src/mpos/estimator/estimator_build_info_keil.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/estimator/estimator_build_info_keil.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBESTIMATOR_BUILD_STR\fP   '20200813\&.185121'"
.br
.ti -1c
.RI "#define \fBESTIMATOR_BUILD_DATE_STR\fP   '20200813'"
.br
.ti -1c
.RI "#define \fBESTIMATOR_BUILD_DATE_NUM\fP   20200813"
.br
.ti -1c
.RI "#define \fBESTIMATOR_BUILD_TIME_STR\fP   '185121'"
.br
.ti -1c
.RI "#define \fBESTIMATOR_BUILD_TIME_NUM\fP   185121"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESTIMATOR_BUILD_DATE_NUM   20200813"

.PP
Definition at line 13 of file estimator_build_info_keil\&.h\&.
.SS "#define ESTIMATOR_BUILD_DATE_STR   '20200813'"

.PP
Definition at line 12 of file estimator_build_info_keil\&.h\&.
.SS "#define ESTIMATOR_BUILD_STR   '20200813\&.185121'"

.PP
Definition at line 11 of file estimator_build_info_keil\&.h\&.
.SS "#define ESTIMATOR_BUILD_TIME_NUM   185121"

.PP
Definition at line 15 of file estimator_build_info_keil\&.h\&.
.SS "#define ESTIMATOR_BUILD_TIME_STR   '185121'"

.PP
Definition at line 14 of file estimator_build_info_keil\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
