pac_foc/src/app/fault.h
NAME
pac_foc/src/app/fault.h
SYNOPSIS
#include 'motor_struct.h'
Functions
void oc_reset (void)
This function use to reset over current fault.
void fault (void)
This function use disable adc, motor disable and be in while loop.
void set_fault (uint32_t fault_mask)
This function use to set fault.
void clear_fault (uint32_t fault_mask)
This function use to clear fault.
void set_warning (uint32_t fault_mask)
This function use to set warning.
void clear_warning (uint32_t fault_mask)
This function use to clear warning.
int32_t pac5xxx_get_over_current_status (void)
int32_t pac5xxx_get_over_temperature_status (void)
int32_t pac5xxx_get_driver_fault (void)
Function Documentation
void clear_fault (uint32_t fault_mask)
This function use to clear fault.
Parameters
uint32_t fault_mask
Definition at line 153 of file fault.c.
{
    motor.fault.motor &= (~fault_mask);
}
References Struct_Motor::fault, motor, and Struct_Fault::motor.
Referenced by motor_reset().
void clear_warning (uint32_t fault_mask)
This function use to clear warning.
Parameters
uint32_t fault_mask
Definition at line 173 of file fault.c.
{
    motor.fault.motor &= ~fault_mask;
}
References Struct_Motor::fault, motor, and Struct_Fault::motor.
Referenced by check_pwm_sat(), est_anglediff_check(), and init_over_current_limit().
void fault (void)
This function use disable adc, motor disable and be in while loop.
Definition at line 31 of file fault.c.
{
    fix16_t delay_count; // Use this delay to blink LED during fault
    pac5xxx_adc_enable(0);
    // Disable motor if enter fault
    m1_disable();
    // Go into an infinite loop.
    while (1)
    {
        for (delay_count = 0; delay_count < 0x00010000; delay_count++)
        {
        }
    }
}
References m1_disable().
Referenced by Default_Handler(), fix16_div(), HardFault_Handler(), MemCtl_IRQHandler(), and NMI_Handler().
void oc_reset (void)
This function use to reset over current fault.
Definition at line 54 of file fault.c.
{
      uint16_t register_val;
    // Disable global interrupts until OC reset is complete
    __disable_irq();
    // Set drivers to GPIO mode
    set_drivers_gpio();
    // Clear int/fault flags
#ifdef CAFE_ARCH2
    register_val = pac5xxx_tile_register_read(ADDR_SIGINTF);
    while (register_val&0xA0)
    {
        register_val = pac5xxx_tile_register_read(ADDR_SIGINTF);
    }
    register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    while (register_val&0x80)
    {
        register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    }
    register_val = pac5xxx_tile_register_read(ADDR_SIGINTF);
    while (register_val&0x50)
    {
        register_val = pac5xxx_tile_register_read(ADDR_SIGINTF);
    }
    register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    while (register_val&0x08)
    {
        register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    }
    pac5xxx_tile_register_write(ADDR_PROTSTAT, 0xFF);
#endif
#ifdef CAFE_ARCH3
    register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    while (register_val & 0x11)
    {
        pac5xxx_tile_register_write(ADDR_PROTSTAT, 0x11);
        register_val = pac5xxx_tile_register_read(ADDR_PROTSTAT);
    }
    pac5xxx_tile_register_write(ADDR_PROTSTAT, 0x11);
#endif
    pac5xxx_tile_register_write(ADDR_PROTINTM, 0x00);
    while (pac5xxx_tile_register_read(ADDR_PROTSTAT));
    protint_enable();
    // Disable driver
    do
    {
        pac5xxx_tile_register_write(ADDR_ENDRV, 0);
        register_val = pac5xxx_tile_register_read(ADDR_ENDRV);
    } while ((register_val&0x1) != 0x0);
    // Enable driver
    do {
        pac5xxx_tile_register_write(ADDR_ENDRV, 1);
        register_val = pac5xxx_tile_register_read(ADDR_ENDRV);
    } while ((register_val&0x1) != 0x1);
    // Clear OC flag
    clear_fault(FAULT_CAFE_OC);
    // Enable global interrupts
    __enable_irq();
}
References set_drivers_gpio().
int32_t pac5xxx_get_driver_fault (void)
Referenced by GpioB_IRQHandler().
int32_t pac5xxx_get_over_current_status (void)
Referenced by GpioB_IRQHandler().
int32_t pac5xxx_get_over_temperature_status (void)
Referenced by GpioB_IRQHandler().
void set_fault (uint32_t fault_mask)
This function use to set fault.
Parameters
uint32_t fault_mask
Definition at line 129 of file fault.c.
{
    motor.fault.motor |= fault_mask;
    // Decide firmware response to fault
    if (fault_mask & FAULT_MAIN_GRP_STOP)
    {
        motor.fault.fault_stop_flag = 1;
    }
    else if (fault_mask & FAULT_MAIN_GRP_STATE)
    {
        motor.fault.fault_state_flag = 1;
    }
    else if (fault_mask & FAULT_MAIN_GRP_TERMINAL)
    {
        motor.fault.fault_terminal_flag = 1;
    }
}
References Struct_Motor::fault, FAULT_MAIN_GRP_STATE, FAULT_MAIN_GRP_STOP, FAULT_MAIN_GRP_TERMINAL, Struct_Fault::fault_state_flag, Struct_Fault::fault_stop_flag, Struct_Fault::fault_terminal_flag, motor, and Struct_Fault::motor.
Referenced by check_param_while_run(), est_anglediff_check(), GpioA_IRQHandler(), GpioB_IRQHandler(), hall_timer_isr(), lbg1_statemon(), sm_mainsub_prestart(), and systemvar_init().
void set_warning (uint32_t fault_mask)
This function use to set warning.
Parameters
uint32_t fault_mask
Definition at line 163 of file fault.c.
{
    motor.fault.motor |= fault_mask;
}
References Struct_Motor::fault, motor, and Struct_Fault::motor.
Referenced by check_pwm_sat(), est_anglediff_check(), GpioA_IRQHandler(), GpioB_IRQHandler(), init_over_current_limit(), picon_convert_gain(), and stack_test().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.