pac_foc/src/math/fix16.c
NAME
pac_foc/src/math/fix16.c - Fixed math library functions (fix16_t)
SYNOPSIS
#include 'fix16.h'
#include 'int64.h'
#include 'pac5xxx.h'
Macros
#define FIXMATH_NO_64BIT
#define FIXMATH_OPTIMIZE_8BIT
Functions
FIX16_RAMFUNC fix16_t fix16_mul (fix16_t inArg0, fix16_t inArg1)
Multiplies two fix16_t values.
FIX16_RAMFUNC uint32_t fix16_mul_uint (uint32_t inArg0, uint32_t inArg1)
Multiplies two integers and returns a fix16_t.
FIX16_RAMFUNC fix16_t fix16_div (fix16_t a, fix16_t b)
Divides two fix16_t numbers (a / b)
lfm_int64 int64_add (lfm_int64 x, lfm_int64 y)
Adds two 64-bit numbers.
lfm_int64 int64_sub (lfm_int64 x, lfm_int64 y)
Subtract two 64-bit numbers (x - y)
lfm_int64 int64_shift (lfm_int64 x, int8_t y)
Shift a 64-bit number by the given number of bits.
lfm_int64 int64_neg (lfm_int64 x)
Negate a 64-bit number.
lfm_int64 int64_mul_i32_i32 (int32_t x, int32_t y)
Multiply two 32-bit numbers into a 64-bit number.
lfm_int64 int64_mul_i64_i32 (lfm_int64 x, int32_t y)
Multiply a 64-bit and 32-bit number.
lfm_int64 int64_div_i64_i32 (lfm_int64 x, int32_t y)
Divide a 64-bit number by a 32-bit number (x / y)
Detailed Description
Fixed math library functions (fix16_t)
Definition in file fix16.c.
Macro Definition Documentation
#define FIXMATH_NO_64BIT
Definition at line 35 of file fix16.c.
#define FIXMATH_OPTIMIZE_8BIT
Definition at line 36 of file fix16.c.
Function Documentation
FIX16_RAMFUNC fix16_t fix16_div (fix16_t inArg0, fix16_t inArg1)
Divides two fix16_t numbers (a / b)
Parameters
a Value a
b Value b
Returns
Result (a / b)
Definition at line 653 of file fix16.c.
{
  // This uses the basic binary restoring division algorithm.
  // It appears to be faster to do the whole division manually than
  // trying to compose a 64-bit divide out of 32-bit divisions on
  // platforms without hardware divide.
  
  if (b == 0)
  {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
  }
  
  uint32_t remainder = (a >= 0) ? a : (-a);
  uint32_t divider = (b >= 0) ? b : (-b);
  uint32_t quotient = 0;
  uint32_t bit = 0x10000;
  
  // The algorithm requires D >= R
  while (divider < remainder)
  {
    divider <<= 1;
    bit <<= 1;
  }
  
  #ifndef FIXMATH_NO_OVERFLOW
  if (!bit)
  {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
  }
  #endif
  
  if (divider & 0x80000000)
  {
    // Perform one step manually to avoid overflows later.
    // We know that divider's bottom bit is 0 here.
    if (remainder >= divider)
    {
        quotient |= bit;
        remainder -= divider;
    }
    divider >>= 1;
    bit >>= 1;
  }
  
  // Main division loop
  while (bit && remainder)
  {
    if (remainder >= divider)
    {
        quotient |= bit;
        remainder -= divider;
    }
    
    remainder <<= 1;
    bit >>= 1;
  }
      
  #ifndef FIXMATH_NO_ROUNDING
  if (remainder >= divider)
  {
    quotient++;
  }
  #endif
  
  fix16_t result = quotient;
  
  // Figure out the sign of result
  if ((a ^ b) & 0x80000000)
  {
    #ifndef FIXMATH_NO_OVERFLOW
    if (result == fix16_min)
    {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
    }
    #endif
    
    result = -result;
  }
  
  return result;
}
References fault(), fix16_max, fix16_min, and fix16_overflow.
Referenced by cal_vm_const(), calc_vbus_internal(), config_control_dt(), foc_calc_pwmtimer(), foc_config(), foc_reset(), init_over_current_limit(), picon_convert_gain(), trig_arctan_90deg_q16(), and write_itotstart_target().
FIX16_RAMFUNC fix16_t fix16_mul (fix16_t inArg0, fix16_t inArg1)
Multiplies two fix16_t values.
Parameters
inArg0 Value a
inArg1 Value b
Returns
Result (a * b)
Definition at line 227 of file fix16.c.
{
  // Each argument is divided to 16-bit parts.
  // AB
  // * CD
  // -----------
  // BD 16 * 16 -> 32 bit products
  // CB
  // AD
  // AC
  // |----| 64 bit product
  int32_t A = (inArg0 >> 16), C = (inArg1 >> 16);
  uint32_t B = (inArg0 & 0xFFFF), D = (inArg1 & 0xFFFF);
  int32_t AC = A*C;
  int32_t AD_CB = A*D + C*B;
  uint32_t BD = B*D;
  int32_t product_hi = AC + (AD_CB >> 16);
  // Handle carry from lower 32 bits to upper part of result.
  uint32_t ad_cb_temp = AD_CB << 16;
  uint32_t product_lo = BD + ad_cb_temp;
  if (product_lo < BD)
    product_hi++;
#ifndef FIXMATH_NO_OVERFLOW
  // The upper 17 bits should all be the same (the sign).
  if (product_hi >> 31 != product_hi >> 15)
    return fix16_overflow;
#endif
#ifdef FIXMATH_NO_ROUNDING
  return (product_hi << 16) | (product_lo >> 16);
#else
  // Subtracting 0x8000 (= 0.5) and then using signed right shift
  // achieves proper rounding to result-1, except in the corner
  // case of negative numbers and lowest word = 0x8000.
  // To handle that, we also have to subtract 1 for negative numbers.
  uint32_t product_lo_tmp = product_lo;
  product_lo -= 0x8000;
  product_lo -= (uint32_t)product_hi >> 31;
  if (product_lo > product_lo_tmp)
    product_hi--;
  // Discard the lowest 16 bits. Note that this is not exactly the same
  // as dividing by 0x10000. For example if product = -1, result will
  // also be -1 and not 0. This is compensated by adding +1 to the result
  // and compensating this in turn in the rounding above.
  fix16_t result = (product_hi << 16) | (product_lo >> 16);
  result += 1;
  return result;
#endif
}
References fix16_overflow.
Referenced by calc_vbus_internal(), est_anglediff_check(), foc_calc_pwmtimer(), hall_param_write(), init_over_current_limit(), parameters_write_foc(), and picon_convert_gain().
FIX16_RAMFUNC uint32_t fix16_mul_uint (uint32_t inArg0, uint32_t inArg1)
Multiplies two integers and returns a fix16_t.
Parameters
inArg0 Value a
inArg1 Value b
Returns
Result (a * b) in fix16_t format
Definition at line 282 of file fix16.c.
{
  // Each argument is divided to 16-bit parts.
  // AB
  // * CD
  // -----------
  // BD 16 * 16 -> 32 bit products
  // CB
  // AD
  // AC
  // |----| 64 bit product
  uint32_t A = (inArg0 >> 16), C = (inArg1 >> 16);
  uint32_t B = (inArg0 & 0xFFFF), D = (inArg1 & 0xFFFF);
  uint32_t AC = A*C;
  uint32_t AD_CB = A*D + C*B;
  uint32_t BD = B*D;
  uint32_t product_hi = AC + (AD_CB >> 16);
  // Handle carry from lower 32 bits to upper part of result.
  uint32_t ad_cb_temp = AD_CB << 16;
  uint32_t product_lo = BD + ad_cb_temp;
  if (product_lo < BD)
    product_hi++;
  return (product_hi << 16) | (product_lo >> 16);
}
Referenced by picon_convert_gain().
lfm_int64 int64_add (lfm_int64 x, lfm_int64 y)
Adds two 64-bit numbers.
Parameters
x 64-bit number
y 64-bit number
Returns
64-bit sum
Definition at line 782 of file fix16.c.
{
        lfm_int64 ret;
        ret.hi = x.hi + y.hi;
        ret.lo = x.lo + y.lo;
        if((ret.lo < x.lo) || (ret.hi < y.hi))
                ret.hi++;
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
Referenced by int64_sub().
lfm_int64 int64_div_i64_i32 (lfm_int64 x, int32_t y)
Divide a 64-bit number by a 32-bit number (x / y)
Parameters
x 64-bit number
y 32-bit number
Returns
64-bit result (x / y)
Definition at line 859 of file fix16.c.
                                                    {
        int neg = ((x.hi ^ y) < 0);
        if(x.hi < 0)
                x = int64_neg(x);
        if(y < 0)
                y = -y;
        lfm_int64 ret = { (x.hi / y) , (x.lo / y) };
        x.hi = x.hi % y;
        x.lo = x.lo % y;
        lfm_int64 _y = int64_from_int32(y);
        lfm_int64 i;
        for(i = int64_from_int32(1); int64_cmp_lt(_y, x); _y = int64_shift(_y, 1), i = int64_shift(i, 1));
        while(x.hi) {
                _y = int64_shift(_y, -1);
                 i = int64_shift(i, -1);
                if(int64_cmp_ge(x, _y)) {
                        x = int64_sub(x, _y);
                        ret = int64_add(ret, i);
                }
        }
        ret = int64_add(ret, int64_from_int32(x.lo / y));
        return (neg ? int64_neg(ret) : ret);
}
References lfm_int64::hi, int64_neg(), and lfm_int64::lo.
lfm_int64 int64_mul_i32_i32 (int32_t x, int32_t y)
Multiply two 32-bit numbers into a 64-bit number.
Parameters
x 32-bit number
y 32-bit number
Returns
64-bit product
Definition at line 823 of file fix16.c.
                                                  {
         int16_t hi[2] = { (x >> 16), (y >> 16) };
        uint16_t lo[2] = { (x & 0xFFFF), (y & 0xFFFF) };
         int32_t r_hi = hi[0] * hi[1];
         int32_t r_md = (hi[0] * lo[1]) + (hi[1] * lo[0]);
        uint32_t r_lo = lo[0] * lo[1];
        r_hi += (r_md >> 16);
        r_lo += (r_md << 16);
        return (lfm_int64){ r_hi, r_lo };
}
lfm_int64 int64_mul_i64_i32 (lfm_int64 x, int32_t y)
Multiply a 64-bit and 32-bit number.
Parameters
x 64-bit number
y 32-bit number
Returns
64-bit product
Definition at line 837 of file fix16.c.
                                                    {
        int neg = ((x.hi ^ y) < 0);
        if(x.hi < 0)
                x = int64_neg(x);
        if(y < 0)
                y = -y;
        uint32_t _x[4] = { (x.hi >> 16), (x.hi & 0xFFFF), (x.lo >> 16), (x.lo & 0xFFFF) };
        uint32_t _y[2] = { (y >> 16), (y & 0xFFFF) };
        uint32_t r[4];
        r[0] = (_x[0] * _y[0]);
        r[1] = (_x[1] * _y[0]) + (_x[0] * _y[1]);
        r[2] = (_x[1] * _y[1]) + (_x[2] * _y[0]);
        r[3] = (_x[2] * _y[0]) + (_x[1] * _y[1]);
        lfm_int64 ret;
        ret.lo = r[0] + (r[1] << 16);
        ret.hi = (r[3] << 16) + r[2] + (r[1] >> 16);
        return (neg ? int64_neg(ret) : ret);
}
References lfm_int64::hi, int64_neg(), and lfm_int64::lo.
lfm_int64 int64_neg (lfm_int64 x)
Negate a 64-bit number.
Parameters
x 64-bit number
Returns
negated 64-bit number
Definition at line 814 of file fix16.c.
                                 {
        lfm_int64 ret;
        ret.hi = ~x.hi;
        ret.lo = ~x.lo + 1;
        if(ret.lo == 0)
                ret.hi++;
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
Referenced by int64_div_i64_i32(), int64_mul_i64_i32(), and int64_sub().
lfm_int64 int64_shift (lfm_int64 x, int8_t y)
Shift a 64-bit number by the given number of bits.
Parameters
x 64-bit number
y number of bits to shift
Returns
64-bit shifted number
Definition at line 797 of file fix16.c.
                                             {
        lfm_int64 ret;
        if(y > 0) {
                if(y >= 32)
                        return (lfm_int64){ 0, 0 };
                ret.hi = (x.hi << y) | (x.lo >> (32 - y));
                ret.lo = (x.lo << y);
        } else {
                y = -y;
                if(y >= 32)
                        return (lfm_int64){ 0, 0 };
                ret.lo = (x.lo >> y) | (x.hi << (32 - y));
                ret.hi = (x.hi >> y);
        }
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
lfm_int64 int64_sub (lfm_int64 x, lfm_int64 y)
Subtract two 64-bit numbers (x - y)
Parameters
x 64-bit number
y 64-bit number
Returns
64-bit difference (x - y )
Definition at line 792 of file fix16.c.
                                              {
        return int64_add(x, int64_neg(y));
}
References int64_add(), and int64_neg().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.