pac_foc/src/math/fix16.h
NAME
pac_foc/src/math/fix16.h - Fixed math library declarations (fix16_t)
SYNOPSIS
#include 'pac5xxx.h'
#include <stdint.h>
Macros
#define FIXMATH_FUNC_ATTRS
#define FIX16_RAMFUNC
#define FIXMATH_NO_OVERFLOW
#define FIXMATH_NO_ROUNDING
#define FOUR_DIV_PI 0x145F3
#define _FOUR_DIV_PI2 0xFFFF9840
#define X4_CORRECTION_COMPONENT 0x399A
#define PI_DIV_4 0x0000C90F
#define THREE_PI_DIV_4 0x00025B2F
#define fix16_max 0x7FFFFFFF
#define fix16_min 0x80000000
#define fix16_overflow 0x80000000
#define fix16_pi 205887
#define fix16_e 78145
#define FIX16_ONE 0x00010000
#define fix16_neg_one 0xFFFF0000
Typedefs
typedef int32_t fix16_t
Functions
FIX16_RAMFUNC fix16_t fix16_div (fix16_t inArg0, fix16_t inArg1) FIXMATH_FUNC_ATTRS
Divides two fix16_t numbers (a / b)
FIX16_RAMFUNC fix16_t fix16_lerp8 (fix16_t inArg0, fix16_t inArg1, uint8_t inFract) FIXMATH_FUNC_ATTRS
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
FIX16_RAMFUNC fix16_t fix16_lerp16 (fix16_t inArg0, fix16_t inArg1, uint16_t inFract) FIXMATH_FUNC_ATTRS
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
FIX16_RAMFUNC fix16_t fix16_lerp32 (fix16_t inArg0, fix16_t inArg1, uint32_t inFract) FIXMATH_FUNC_ATTRS
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
FIX16_RAMFUNC fix16_t fix16_sin_parabola (fix16_t inAngle) FIXMATH_FUNC_ATTRS
Returns the sine parabola of the given value.
FIX16_RAMFUNC fix16_t fix16_sin (fix16_t inAngle) FIXMATH_FUNC_ATTRS
Returns the sine of the given value.
FIX16_RAMFUNC fix16_t fix16_cos (fix16_t inAngle) FIXMATH_FUNC_ATTRS
Returns the cosine of the given value.
FIX16_RAMFUNC fix16_t fix16_tan (fix16_t inAngle) FIXMATH_FUNC_ATTRS
Returns the tangent of the given value.
FIX16_RAMFUNC fix16_t fix16_asin (fix16_t inValue) FIXMATH_FUNC_ATTRS
Returns the arc sine of the given value.
FIX16_RAMFUNC fix16_t fix16_acos (fix16_t inValue) FIXMATH_FUNC_ATTRS
Returns the arc cosine of the given value.
FIX16_RAMFUNC fix16_t fix16_atan (fix16_t inValue) FIXMATH_FUNC_ATTRS
Returns the arc tangent of the given value.
FIX16_RAMFUNC fix16_t fix16_atan2 (fix16_t inY, fix16_t inX) FIXMATH_FUNC_ATTRS
Returns the arc tangent 2 of the given value.
FIX16_RAMFUNC fix16_t fix16_sqrt (fix16_t inValue) FIXMATH_FUNC_ATTRS
Returns the square root of the given value.
FIX16_RAMFUNC fix16_t fix16_exp (fix16_t inValue) FIXMATH_FUNC_ATTRS
Returns the exponent (e^) of the given value.
FIX16_RAMFUNC fix16_t fix16_mul (fix16_t inArg0, fix16_t inArg1) FIXMATH_FUNC_ATTRS
Multiplies two fix16_t values.
FIX16_RAMFUNC uint32_t fix16_mul_uint (uint32_t inArg0, uint32_t inArg1) FIXMATH_FUNC_ATTRS
Multiplies two integers and returns a fix16_t.
Detailed Description
Fixed math library declarations (fix16_t)
Definition in file fix16.h.
Macro Definition Documentation
#define _FOUR_DIV_PI2 0xFFFF9840
Fix16 value of -4/PI²
Definition at line 68 of file fix16.h.
#define fix16_e 78145
fix16_t value of e
Definition at line 78 of file fix16.h.
#define fix16_max 0x7FFFFFFF
the maximum value of fix16_t
Definition at line 73 of file fix16.h.
#define fix16_min 0x80000000
the minimum value of fix16_t
Definition at line 74 of file fix16.h.
#define fix16_neg_one 0xFFFF0000
fix16_t value of -1
Definition at line 80 of file fix16.h.
#define FIX16_ONE 0x00010000
fix16_t value of 1
Definition at line 79 of file fix16.h.
#define fix16_overflow 0x80000000
the value used to indicate overflows when FIXMATH_NO_OVERFLOW is not specified
Definition at line 75 of file fix16.h.
#define fix16_pi 205887
fix16_t value of pi
Definition at line 77 of file fix16.h.
#define FIX16_RAMFUNC
Definition at line 57 of file fix16.h.
#define FIXMATH_FUNC_ATTRS
Definition at line 48 of file fix16.h.
#define FIXMATH_NO_OVERFLOW
Definition at line 62 of file fix16.h.
#define FIXMATH_NO_ROUNDING
Definition at line 63 of file fix16.h.
#define FOUR_DIV_PI 0x145F3
Fix16 value of 4/PI
Definition at line 67 of file fix16.h.
#define PI_DIV_4 0x0000C90F
Fix16 value of PI/4
Definition at line 70 of file fix16.h.
#define THREE_PI_DIV_4 0x00025B2F
Fix16 value of 3PI/4
Definition at line 71 of file fix16.h.
#define X4_CORRECTION_COMPONENT 0x399A
Fix16 value of 0.225
Definition at line 69 of file fix16.h.
Typedef Documentation
typedef int32_t fix16_t
Definition at line 65 of file fix16.h.
Function Documentation
FIX16_RAMFUNC fix16_t fix16_acos (fix16_t inValue)
Returns the arc cosine of the given value.
Parameters
inAngle input angle
Returns
arccos(inAngle)
FIX16_RAMFUNC fix16_t fix16_asin (fix16_t inValue)
Returns the arc sine of the given value.
Parameters
inAngle input angle
Returns
arcsin(inAngle)
FIX16_RAMFUNC fix16_t fix16_atan (fix16_t inValue)
Returns the arc tangent of the given value.
Parameters
inAngle input angle
Returns
arctan(inAngle)
FIX16_RAMFUNC fix16_t fix16_atan2 (fix16_t inY, fix16_t inX)
Returns the arc tangent 2 of the given value.
Parameters
inAngle input angle
Returns
arctan2(inAngle)
FIX16_RAMFUNC fix16_t fix16_cos (fix16_t inAngle)
Returns the cosine of the given value.
Parameters
inAngle input angle
Returns
Cos(inAngle)
FIX16_RAMFUNC fix16_t fix16_div (fix16_t inArg0, fix16_t inArg1)
Divides two fix16_t numbers (a / b)
Parameters
a Value a
b Value b
Returns
Result (a / b)
Definition at line 653 of file fix16.c.
{
  // This uses the basic binary restoring division algorithm.
  // It appears to be faster to do the whole division manually than
  // trying to compose a 64-bit divide out of 32-bit divisions on
  // platforms without hardware divide.
  
  if (b == 0)
  {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
  }
  
  uint32_t remainder = (a >= 0) ? a : (-a);
  uint32_t divider = (b >= 0) ? b : (-b);
  uint32_t quotient = 0;
  uint32_t bit = 0x10000;
  
  // The algorithm requires D >= R
  while (divider < remainder)
  {
    divider <<= 1;
    bit <<= 1;
  }
  
  #ifndef FIXMATH_NO_OVERFLOW
  if (!bit)
  {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
  }
  #endif
  
  if (divider & 0x80000000)
  {
    // Perform one step manually to avoid overflows later.
    // We know that divider's bottom bit is 0 here.
    if (remainder >= divider)
    {
        quotient |= bit;
        remainder -= divider;
    }
    divider >>= 1;
    bit >>= 1;
  }
  
  // Main division loop
  while (bit && remainder)
  {
    if (remainder >= divider)
    {
        quotient |= bit;
        remainder -= divider;
    }
    
    remainder <<= 1;
    bit >>= 1;
  }
      
  #ifndef FIXMATH_NO_ROUNDING
  if (remainder >= divider)
  {
    quotient++;
  }
  #endif
  
  fix16_t result = quotient;
  
  // Figure out the sign of result
  if ((a ^ b) & 0x80000000)
  {
    #ifndef FIXMATH_NO_OVERFLOW
    if (result == fix16_min)
    {
#ifdef FIX16_OVERFLOW_DETECT
    fault_mask |= FAULT_FIX16_OVERFLOW;
    fault(0);
    return fix16_overflow;
#else
    if ((a >= 0) == (b >= 0))
        return fix16_max;
    else
        return fix16_min;
#endif
    }
    #endif
    
    result = -result;
  }
  
  return result;
}
References fault(), fix16_max, fix16_min, and fix16_overflow.
Referenced by cal_vm_const(), calc_vbus_internal(), config_control_dt(), foc_calc_pwmtimer(), foc_config(), foc_reset(), init_over_current_limit(), picon_convert_gain(), trig_arctan_90deg_q16(), and write_itotstart_target().
FIX16_RAMFUNC fix16_t fix16_exp (fix16_t inValue)
Returns the exponent (e^) of the given value.
Parameters
inValue input value
Returns
e^inValue
FIX16_RAMFUNC fix16_t fix16_lerp16 (fix16_t inArg0, fix16_t inArg1, uint16_t inFract)
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
Parameters
inArg0 Value a
inArg1 Value b
inFract Fraction
Returns
Result
FIX16_RAMFUNC fix16_t fix16_lerp32 (fix16_t inArg0, fix16_t inArg1, uint32_t inFract)
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
Parameters
inArg0 Value a
inArg1 Value b
inFract Fraction
Returns
Result
FIX16_RAMFUNC fix16_t fix16_lerp8 (fix16_t inArg0, fix16_t inArg1, uint8_t inFract)
Returns the linear interpolation: (inArg0 * (1 - inFract)) + (inArg1 * inFract)
Parameters
inArg0 Value a
inArg1 Value b
inFract Fraction
Returns
Result
FIX16_RAMFUNC fix16_t fix16_mul (fix16_t inArg0, fix16_t inArg1)
Multiplies two fix16_t values.
Parameters
inArg0 Value a
inArg1 Value b
Returns
Result (a * b)
Definition at line 227 of file fix16.c.
{
  // Each argument is divided to 16-bit parts.
  // AB
  // * CD
  // -----------
  // BD 16 * 16 -> 32 bit products
  // CB
  // AD
  // AC
  // |----| 64 bit product
  int32_t A = (inArg0 >> 16), C = (inArg1 >> 16);
  uint32_t B = (inArg0 & 0xFFFF), D = (inArg1 & 0xFFFF);
  int32_t AC = A*C;
  int32_t AD_CB = A*D + C*B;
  uint32_t BD = B*D;
  int32_t product_hi = AC + (AD_CB >> 16);
  // Handle carry from lower 32 bits to upper part of result.
  uint32_t ad_cb_temp = AD_CB << 16;
  uint32_t product_lo = BD + ad_cb_temp;
  if (product_lo < BD)
    product_hi++;
#ifndef FIXMATH_NO_OVERFLOW
  // The upper 17 bits should all be the same (the sign).
  if (product_hi >> 31 != product_hi >> 15)
    return fix16_overflow;
#endif
#ifdef FIXMATH_NO_ROUNDING
  return (product_hi << 16) | (product_lo >> 16);
#else
  // Subtracting 0x8000 (= 0.5) and then using signed right shift
  // achieves proper rounding to result-1, except in the corner
  // case of negative numbers and lowest word = 0x8000.
  // To handle that, we also have to subtract 1 for negative numbers.
  uint32_t product_lo_tmp = product_lo;
  product_lo -= 0x8000;
  product_lo -= (uint32_t)product_hi >> 31;
  if (product_lo > product_lo_tmp)
    product_hi--;
  // Discard the lowest 16 bits. Note that this is not exactly the same
  // as dividing by 0x10000. For example if product = -1, result will
  // also be -1 and not 0. This is compensated by adding +1 to the result
  // and compensating this in turn in the rounding above.
  fix16_t result = (product_hi << 16) | (product_lo >> 16);
  result += 1;
  return result;
#endif
}
References fix16_overflow.
Referenced by calc_vbus_internal(), est_anglediff_check(), foc_calc_pwmtimer(), hall_param_write(), init_over_current_limit(), parameters_write_foc(), and picon_convert_gain().
FIX16_RAMFUNC uint32_t fix16_mul_uint (uint32_t inArg0, uint32_t inArg1)
Multiplies two integers and returns a fix16_t.
Parameters
inArg0 Value a
inArg1 Value b
Returns
Result (a * b) in fix16_t format
Definition at line 282 of file fix16.c.
{
  // Each argument is divided to 16-bit parts.
  // AB
  // * CD
  // -----------
  // BD 16 * 16 -> 32 bit products
  // CB
  // AD
  // AC
  // |----| 64 bit product
  uint32_t A = (inArg0 >> 16), C = (inArg1 >> 16);
  uint32_t B = (inArg0 & 0xFFFF), D = (inArg1 & 0xFFFF);
  uint32_t AC = A*C;
  uint32_t AD_CB = A*D + C*B;
  uint32_t BD = B*D;
  uint32_t product_hi = AC + (AD_CB >> 16);
  // Handle carry from lower 32 bits to upper part of result.
  uint32_t ad_cb_temp = AD_CB << 16;
  uint32_t product_lo = BD + ad_cb_temp;
  if (product_lo < BD)
    product_hi++;
  return (product_hi << 16) | (product_lo >> 16);
}
Referenced by picon_convert_gain().
FIX16_RAMFUNC fix16_t fix16_sin (fix16_t inAngle)
Returns the sine of the given value.
Parameters
inAngle input angle
Returns
Sin(inAngle)
FIX16_RAMFUNC fix16_t fix16_sin_parabola (fix16_t inAngle)
Returns the sine parabola of the given value.
Parameters
inAngle input angle
Returns
Sin(inAngle)
FIX16_RAMFUNC fix16_t fix16_sqrt (fix16_t inValue)
Returns the square root of the given value.
Parameters
inValue input value
Returns
sqrt(inValue)
Definition at line 42 of file fix16_sqrt.c.
                                    {
        int neg = (inValue < 0);
        if(neg)
                inValue = -inValue;
        #ifndef FIXMATH_NO_CACHE
        fix16_t tempIndex = (((inValue >> 16) ^ (inValue >> 4)) & 0x00000FFF);
        if(_fix16_sqrt_cache_index[tempIndex] == inValue)
                return (neg ? -_fix16_sqrt_cache_value[tempIndex] : _fix16_sqrt_cache_value[tempIndex]);
        #endif
        lfm_int64 tempOp = int64_const((inValue >> 16), (inValue << 16));
        lfm_int64 tempOut = int64_const(0, 0);
        lfm_int64 tempOne = int64_const(0x40000000UL, 0x00000000UL);
        while(int64_cmp_gt(tempOne, tempOp))
                tempOne = int64_shift(tempOne, -2);
        while(int64_cmp_ne(tempOne, int64_const(0, 0))) {
                if(int64_cmp_ge(tempOp, int64_add(tempOut, tempOne))) {
                        tempOp = int64_sub(tempOp, int64_add(tempOut, tempOne));
                        tempOut = int64_add(tempOut, int64_shift(tempOne, 1));
                }
                tempOut = int64_shift(tempOut, -1);
                tempOne = int64_shift(tempOne, -2);
        }
        #ifndef FIXMATH_NO_CACHE
        _fix16_sqrt_cache_index[tempIndex] = inValue;
        _fix16_sqrt_cache_value[tempIndex] = int64_lo(tempOut);
        #endif
        return (neg ? -int64_lo(tempOut) : int64_lo(tempOut));
}
FIX16_RAMFUNC fix16_t fix16_tan (fix16_t inAngle)
Returns the tangent of the given value.
Parameters
inAngle input angle
Returns
Tan(inAngle)
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.