pac_foc/src/control/foc_funcs.h
NAME
pac_foc/src/control/foc_funcs.h - Use for FOC utility functions, IdIq current filter, Id & Iq PI, vqmax.
SYNOPSIS
#include 'config_app.h'
#include 'config_features.h'
#include 'motor_struct.h'
#include 'satmon.h'
Functions
void foc_reset (Struct_Motor *motor_ptr)
This function use to reset FOC related variables.
void foc_systemvar_init (Struct_Motor *motor_ptr)
void foc_calc_pwmtimer (Struct_Motor *motor_ptr)
void foc_config (Struct_Motor *motor_ptr)
Detailed Description
Use for FOC utility functions, IdIq current filter, Id & Iq PI, vqmax.
Definition in file foc_funcs.h.
Function Documentation
void foc_calc_pwmtimer (Struct_Motor * motor_ptr)
Definition at line 89 of file foc_funcs.c.
{
    fix16_t pwm_counts, temp2;
    uint32_t temp1;
    // Calculate TimerA (PWM) ticks in up/down mode using Timer Clk frequency, foc_dt, and ctrl_divider
    temp1 = (TIMERCLK_FREQ_HZ >> 10); // clk_div1024 = clk / 1024 (q0 / q0 = q0)
    temp2 = fix16_div(motor_ptr->foc.dt_control_q26, motor_ptr->foc.ctrl_divider_foc); // pwm_dt_x1024 = dt_control_q26 / ctrl_divider
    temp2 = fix16_mul(temp2, temp1); // ticks = pwm_dt_x1024 * clk_div1024 (q16 * q0 = q16)
    temp2 = (temp2 >> 1); // ticks_updn = ticks / 2
    pwm_counts = ((temp2 + 0x8000) >> 16); // Round and shift from q16 to q0
    motor_ptr->foc.motor_period_ticks = pwm_counts;
}
References Struct_FOC::ctrl_divider_foc, Struct_FOC::dt_control_q26, fix16_div(), fix16_mul(), Struct_Motor::foc, and Struct_FOC::motor_period_ticks.
Referenced by parameters_write_foc().
void foc_config (Struct_Motor * motor_ptr)
Definition at line 126 of file foc_funcs.c.
{
    // Set PWM period to FOC
    motor_ptr->control.motor_period_ticks = motor_ptr->foc.motor_period_ticks;
    motor_ptr->control.motor_period_ticks_1div = fix16_div(FIX16_1P0, (motor_ptr->control.motor_period_ticks << 16));
    // Configure PWM timer for FOC
    configure_foc_timer();
    // Set PWM duty cycles to 50%
    m1_u_set_duty(motor_ptr->control.motor_period_ticks >> 1); // Set initial duty cycle to 50% (off)
    m1_v_set_duty(motor_ptr->control.motor_period_ticks >> 1); // Set initial duty cycle to 50% (off)
    m1_w_set_duty(motor_ptr->control.motor_period_ticks >> 1); // Set initial duty cycle to 50% (off)
    // Configure control loop for FOC mode
    config_control_timing_foc_inline();
    // Configure control divider for FOC
    config_control_dt(motor_ptr, motor_ptr->foc.dt_control_q26, motor_ptr->foc.ctrl_divider_foc);
    // Configure min/max duty
    foc_config_duty(motor_ptr);
#ifdef CONTROL_VDVQ_VECTOR_LIMIT
    config_vdvq_vector_limit(motor_ptr);
#endif
#ifdef ENABLE_MTPA
    // Unit: Degree, scaled
    motor_ptr->mtpa.mtpa_gain_q16 = fix16_mul(motor_ptr->mtpa.mtpa_gain_degpa_q16, motor_ptr->app.descale_current_factor);
#endif
#ifdef ENABLE_BOOTPROT
    fix16_t temp3;
    temp3 = BOOTPROT_TIME_LIMIT_SEC_x1024; //- motor_ptr->foc_dt;
    if (temp3 < 0)
        temp3 = 0;
    motor_ptr->bootprot.bootprot_max_counts = (fix16_mul(temp3, motor_ptr->control.dt_control_1div_q6) >> 16); // q0 = q16>>16
    motor_ptr->bootprot.bootprot_pwm_max_ticks = (fix16_mul((fix16_t)(motor_ptr->control.motor_period_ticks << 16), BOOTPROT_DUTY_MAX_PCT_Q16) >> 16);
#endif
}
References Struct_Motor::control, FIX16_1P0, fix16_div(), Struct_Motor::foc, Struct_Control::motor_period_ticks, Struct_FOC::motor_period_ticks, and Struct_Control::motor_period_ticks_1div.
Referenced by parameters_write_foc(), and sm_mainsub_post().
void foc_reset (Struct_Motor * motor_ptr)
This function use to reset FOC related variables.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 26 of file foc_funcs.c.
{
    pid_reset(&motor_ptr->foc.Id_pid); // Reset PID controller data
    pid_reset(&motor_ptr->foc.Iq_pid); // Reset PID controller data
    motor_ptr->foc.idref_ramp_q14 = 0;
    motor_ptr->foc.idref_ramp_f16 = 0;
    motor_ptr->foc.iqref_ramp_q14 = 0;
    motor_ptr->foc.iqref_ramp_f16 = 0;
    motor_ptr->foc.id_q14 = 0;
    motor_ptr->foc.iq_q14 = 0;
    motor_ptr->foc.vd_q14 = 0;
    motor_ptr->foc.vq_q14 = 0;
    motor_ptr->foc.flag_sat_logicor = 0; // Drive saturation flag implemented as logic "or" of control cycles in sampling window
    motor_ptr->foc.flag_sat_logicand = 0;
    motor_ptr->foc.svm_ta_q14 = 0;
    motor_ptr->foc.svm_tb_q14 = 0;
    motor_ptr->foc.svm_tc_q14 = 0;
    motor_ptr->foc.valpha_q14 = 0;
    motor_ptr->foc.vbeta_q14 = 0;
    
#ifdef ENABLE_DQ_DECOUPLING
    #if (SEL_DQ_DECOUPLING_METHOD == FEEDBACK_DECOUPLING)
    int32_t fc_temp_q16;
    fc_temp_q16 = fix16_div(motor_ptr->foc.Iq_pid.ka_q16 << 10, motor_ptr->mparam.lq_q26);
    // Convert from rad/s to Hz
    fc_temp_q16 = (fc_temp_q16 >> 10) * QCONST(0.159f, Q10);
    if (fc_temp_q16 > CURRENT_FILTER_CUTOFF_FREQ_Q16) fc_temp_q16 = CURRENT_FILTER_CUTOFF_FREQ_Q16;
    motor_ptr->foc.current_filter_coeff_q16 = calc_filter_alpha(fc_temp_q16, motor_ptr->control.dt_control_q26);
    motor_ptr->foc.id_dec_q14 = 0;
    motor_ptr->foc.iq_dec_q14 = 0;
    #endif
#endif
}
References fix16_div(), Struct_FOC::flag_sat_logicand, Struct_FOC::flag_sat_logicor, Struct_Motor::foc, Struct_FOC::Id_pid, Struct_FOC::id_q14, Struct_FOC::idref_ramp_f16, Struct_FOC::idref_ramp_q14, Struct_FOC::Iq_pid, Struct_FOC::iq_q14, Struct_FOC::iqref_ramp_f16, Struct_FOC::iqref_ramp_q14, PID_Data_Type::ka_q16, Struct_MParam::lq_q26, Struct_Motor::mparam, pid_reset(), Q10, QCONST, Struct_FOC::svm_ta_q14, Struct_FOC::svm_tb_q14, Struct_FOC::svm_tc_q14, Struct_FOC::valpha_q14, Struct_FOC::vbeta_q14, Struct_FOC::vd_q14, and Struct_FOC::vq_q14.
Referenced by motor_reset().
void foc_systemvar_init (Struct_Motor * motor_ptr)
Definition at line 66 of file foc_funcs.c.
{
    // default freq: 5 kHz
    motor_ptr->foc.dt_control_q26 = QCONST(0.0002f, Q26);
    motor_ptr->foc.ctrl_divider_foc = 3;
#if (CONFIG_SHUNT == CONFIG_SHUNT_3SHUNT)
#ifdef ENABLE_IPD
    motor_ptr->funcptr1 = (void (*)(void *)) &control_3shunt_adc_isr;
#endif
#elif (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT) && (MODE_1SHUNT_SELECT == MODE_1SHUNT_EXTENSION)
#ifdef ENABLE_IPD
    motor_ptr->funcptr1 = (void (*)(void *)) &control_1shunt_extn_adc_isr;
#endif
#elif (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT) && (MODE_1SHUNT_SELECT == MODE_1SHUNT_ASYMMETRIC)
#ifdef ENABLE_IPD
    motor_ptr->funcptr1 = (void (*)(void *)) &control_1shunt_asym_timerb_isr;
    motor_ptr->funcptr2 = (void (*)(void *)) &control_loop;
#endif
#endif
}
References Struct_FOC::ctrl_divider_foc, Struct_FOC::dt_control_q26, Struct_Motor::foc, Q26, and QCONST.
Referenced by systemvar_init().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.