.TH "pac_foc/src/mpos/hall/hall_sim2hall.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/mpos/hall/hall_sim2hall.h \- Use for hall port and interrupt initialization and utility function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'config_app\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for hall port and interrupt initialization and utility function\&. 


.PP
Definition in file \fBhall_sim2hall\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
