pac_foc/src/mpos/hall/hall_funcs.h
NAME
pac_foc/src/mpos/hall/hall_funcs.h - Use for hall FOC utility functions.
SYNOPSIS
#include 'pac5xxx.h'
#include 'config_app.h'
#include 'config_features.h'
#include 'driver_funcs.h'
#include 'fast_div.h'
#include 'fault.h'
#include 'motor_struct.h'
#include 'utils.h'
#include 'mpos_misc.h'
#include 'parameter_process.h'
#include 'hall_io_config.h'
#include 'hall_timer_config.h'
Macros
#define HALL2EST_ANGLEBLEND_TOTALCNT 100
#define HALL2EST_ANGLEBLEND_FACTOR_Q12 QCONST((1.0 / (float)HALL2EST_ANGLEBLEND_TOTALCNT), Q12)
#define HALL_SPEED_CAL_VALUE_Q0 QCONST(((1.0f * HCLK_FREQ_HZ_HALL) / (1.0f * HALL_CLK_DIVIDER)), 0)
#define HALL_TIMER_TICK_DT_Q26 QCONST(((1.0f * HALL_CLK_DIVIDER) / (1.0f * HCLK_FREQ_HZ_HALL)), Q26)
Functions
PAC5XXX_RAMFUNC void hall_process (Struct_Motor *motor_ptr)
This function use for hall processing.
void hall_init (Struct_Motor *motor_ptr)
Use for hall initialization.
void hall_reset (Struct_Motor *motor_ptr)
Use for reset FOC hall related variables, interrupt, ports.
void hall_timer_isr (void)
Use for processing hall timer ISR.
void hall_sort_create_next_state_array (int32_t *array_ptr_src, char *array_ptr_dest)
Use to sort and create next state table using source hall state array.
void hall_sort_create_prev_state_array (int32_t *array_ptr_src, char *array_ptr_dest)
Use to sort in descending order and create next state table using source hall state array.
void hall_create_sequence_array (Struct_Motor *motor_ptr)
Use to copy hall angle form snap angle to for, rev, next and prev state arrays.
void hall_param_write (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for processing hall FOC related parameters.
void hall_param_process (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for processing hall FOC forward and reverse snap angle.
Detailed Description
Use for hall FOC utility functions.
Definition in file hall_funcs.h.
Macro Definition Documentation
#define HALL2EST_ANGLEBLEND_FACTOR_Q12 QCONST((1.0 / (float)HALL2EST_ANGLEBLEND_TOTALCNT), Q12)
Definition at line 44 of file hall_funcs.h.
#define HALL2EST_ANGLEBLEND_TOTALCNT 100
Definition at line 43 of file hall_funcs.h.
#define HALL_SPEED_CAL_VALUE_Q0 QCONST(((1.0f * HCLK_FREQ_HZ_HALL) / (1.0f * HALL_CLK_DIVIDER)), 0)
Definition at line 78 of file hall_funcs.h.
#define HALL_TIMER_TICK_DT_Q26 QCONST(((1.0f * HALL_CLK_DIVIDER) / (1.0f * HCLK_FREQ_HZ_HALL)), Q26)
Definition at line 79 of file hall_funcs.h.
Function Documentation
void hall_create_sequence_array (Struct_Motor * motor_ptr)
Use to copy hall angle form snap angle to for, rev, next and prev state arrays.
Parameters
Struct_Motor* motor_ptr
Definition at line 416 of file hall_funcs.c.
{
    uint8_t count;
    // Reset forward and reverse next state table to zero
    for (count = 0; count < 8; count++)
    {
        motor_ptr->mpos.hall.hall_forward_next_state[count] = 0;
        motor_ptr->mpos.hall.hall_forward_prev_state[count] = 0;
        motor_ptr->mpos.hall.hall_reverse_next_state[count] = 0;
        motor_ptr->mpos.hall.hall_reverse_prev_state[count] = 0;
    }
    hall_sort_create_next_state_array(&motor_ptr->mpos.hall.hall_to_snapangle_forward[0],
            &motor_ptr->mpos.hall.hall_forward_next_state[0]);
    hall_sort_create_prev_state_array(&motor_ptr->mpos.hall.hall_to_snapangle_forward[0],
            &motor_ptr->mpos.hall.hall_forward_prev_state[0]);
    hall_sort_create_next_state_array(&motor_ptr->mpos.hall.hall_to_snapangle_reverse[0],
            &motor_ptr->mpos.hall.hall_reverse_next_state[0]);
    hall_sort_create_prev_state_array(&motor_ptr->mpos.hall.hall_to_snapangle_reverse[0],
            &motor_ptr->mpos.hall.hall_reverse_prev_state[0]);
}
References Struct_MPos::hall, Struct_Hall::hall_forward_next_state, Struct_Hall::hall_forward_prev_state, Struct_Hall::hall_reverse_next_state, Struct_Hall::hall_reverse_prev_state, hall_sort_create_next_state_array(), hall_sort_create_prev_state_array(), Struct_Hall::hall_to_snapangle_forward, Struct_Hall::hall_to_snapangle_reverse, and Struct_Motor::mpos.
Referenced by hall_param_process().
void hall_init (Struct_Motor * motor_ptr)
Use for hall initialization.
Definition at line 176 of file hall_funcs.c.
{
}
void hall_param_process (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for processing hall FOC forward and reverse snap angle.
Parameters
Struct_Motor* motor_ptr
ParameterCode param_code
int32_t rx_data
Definition at line 519 of file hall_funcs.c.
{
    switch(param_code)
    {
    case HallConfig_Snap_1_Fwd:
    case HallConfig_Snap_1_Rev:
    case HallConfig_Snap_2_Fwd:
    case HallConfig_Snap_2_Rev:
    case HallConfig_Snap_3_Fwd:
    case HallConfig_Snap_3_Rev:
    case HallConfig_Snap_4_Fwd:
    case HallConfig_Snap_4_Rev:
    case HallConfig_Snap_5_Fwd:
    case HallConfig_Snap_5_Rev:
    case HallConfig_Snap_6_Fwd:
    case HallConfig_Snap_6_Rev:
        hall_create_sequence_array(motor_ptr);
        break;
    default:
        break;
    }
}
References hall_create_sequence_array(), HallConfig_Snap_1_Fwd, HallConfig_Snap_1_Rev, HallConfig_Snap_2_Fwd, HallConfig_Snap_2_Rev, HallConfig_Snap_3_Fwd, HallConfig_Snap_3_Rev, HallConfig_Snap_4_Fwd, HallConfig_Snap_4_Rev, HallConfig_Snap_5_Fwd, HallConfig_Snap_5_Rev, HallConfig_Snap_6_Fwd, and HallConfig_Snap_6_Rev.
void hall_param_write (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for processing hall FOC related parameters.
Parameters
Struct_Motor* motor_ptr
ParameterCode param_code
int32_t rx_data
Definition at line 446 of file hall_funcs.c.
{
    switch(param_code)
    {
    case HallConfig_Istart:
        motor_ptr->startup.i_total_hall_gui = rx_data;
        break;
    case HallConfig_Gain_Fwd:
        motor_ptr->mpos.hall.angcorr_gain_fwd_q20 = rx_data;
        break;
    case HallConfig_Gain_Rev:
        motor_ptr->mpos.hall.angcorr_gain_rev_q20 = rx_data;
        break;
    case HallConfig_Offset_Fwd:
        motor_ptr->mpos.hall.angcorr_offset_fwd = rx_data;
        break;
    case HallConfig_Offset_Rev:
        motor_ptr->mpos.hall.angcorr_offset_rev = rx_data;
        break;
#if (MODULE_MPOS_HALL == ENABLED) && (MODULE_MPOS_LBG1 == ENABLED)
    case HallConfig_Speed:
        motor_ptr->mpos.hall.switchover_spd_lo2hi_radps = rx_data;
        motor_ptr->mpos.hall.switchover_spd_hi2lo_radps = fix16_mul(motor_ptr->mpos.hall.switchover_spd_lo2hi_radps, (Q16_1P0 - SWITCHOVER_SPD_HALLEST_HYST_PCT_Q16));
        break;
#endif
    case HallConfig_Snap_1_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[1] = rx_data;
        break;
    case HallConfig_Snap_1_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[1] = rx_data;
        break;
    case HallConfig_Snap_2_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[2] = rx_data;
        break;
    case HallConfig_Snap_2_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[2] = rx_data;
        break;
    case HallConfig_Snap_3_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[3] = rx_data;
        break;
    case HallConfig_Snap_3_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[3] = rx_data;
        break;
    case HallConfig_Snap_4_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[4] = rx_data;
        break;
    case HallConfig_Snap_4_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[4] = rx_data;
        break;
    case HallConfig_Snap_5_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[5] = rx_data;
        break;
    case HallConfig_Snap_5_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[5] = rx_data;
        break;
    case HallConfig_Snap_6_Fwd:
        motor_ptr->mpos.hall.hall_to_snapangle_forward[6] = rx_data;
        break;
    case HallConfig_Snap_6_Rev:
        motor_ptr->mpos.hall.hall_to_snapangle_reverse[6] = rx_data;
        break;
    default:
        break;
    }
}
References Struct_Hall::angcorr_gain_fwd_q20, Struct_Hall::angcorr_gain_rev_q20, Struct_Hall::angcorr_offset_fwd, Struct_Hall::angcorr_offset_rev, fix16_mul(), Struct_MPos::hall, Struct_Hall::hall_to_snapangle_forward, Struct_Hall::hall_to_snapangle_reverse, HallConfig_Gain_Fwd, HallConfig_Gain_Rev, HallConfig_Istart, HallConfig_Offset_Fwd, HallConfig_Offset_Rev, HallConfig_Snap_1_Fwd, HallConfig_Snap_1_Rev, HallConfig_Snap_2_Fwd, HallConfig_Snap_2_Rev, HallConfig_Snap_3_Fwd, HallConfig_Snap_3_Rev, HallConfig_Snap_4_Fwd, HallConfig_Snap_4_Rev, HallConfig_Snap_5_Fwd, HallConfig_Snap_5_Rev, HallConfig_Snap_6_Fwd, HallConfig_Snap_6_Rev, HallConfig_Speed, Struct_Motor::mpos, Q16_1P0, Struct_Motor::startup, Struct_Hall::switchover_spd_hi2lo_radps, and Struct_Hall::switchover_spd_lo2hi_radps.
PAC5XXX_RAMFUNC void hall_process (Struct_Motor * motor_ptr)
This function use for hall processing.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 38 of file hall_funcs.c.
{
    int32_t local_flag_hall_state_int = 0;
    __disable_irq();
    // Read hall interrupt flag atomically
    local_flag_hall_state_int = motor_ptr->mpos.hall.flag_hall_int;
    // Clear hall interrupt flag to signal hall ISR transition is processed
    motor_ptr->mpos.hall.flag_hall_int = FALSE;
    __enable_irq();
    // Check if hall transition has occurred after transition flag indicates that previous transition has been processed
    if (!motor_ptr->mpos.hall.transition_flag)
    {
        hall_check_hall_state_changed(motor_ptr);
    }
    // Process hall transition if state transition is detected and if hall interrupt has been detected
    if(motor_ptr->mpos.hall.transition_flag && local_flag_hall_state_int)
    {
        // Clear hall state transition flag
        motor_ptr->mpos.hall.transition_flag = FALSE;
        // Set external hall state transition flag
        motor_ptr->mpos.hall.transition_ext_flag = TRUE;
#if defined(ENABLE_HALL_SEQUENCE_CHECK) && !defined(ENABLE_HALL_TUNING)
        hall_check_sequence(motor_ptr);
#endif
        // Fault if read hall value is illegal
        hall_check_hall_state(motor_ptr);
        // Calculate hall angle
        hall_calc_motor_angle(motor_ptr);
        // Handle the case of kickback by decrementing the interpolation angle back to 0 to avoid a sudden jump in angle
        if (motor_ptr->mpos.hall.hall_ptr_prev_state[motor_ptr->mpos.hall.SensorStateLast] == motor_ptr->mpos.hall.SensorStateNew)
        {
            // Skip speed calculation for this transition
            motor_ptr->mpos.hall.do_speed_cal = FALSE;
            // Reset the transition counter to skip speed calculation on the first forward transition
            motor_ptr->mpos.hall.transition_counter = 0;
            // Set speed and speed filter to 0
            motor_ptr->mpos.hall.hall_spd_radps = 0;
            motor_ptr->mpos.hall.hall_spd_scaled_q14 = 0;
            motor_ptr->mpos.hall.hall_spd_scaled_q28 = 0;
            motor_ptr->mpos.hall.hall_spd_radps = 0;
            // Set interpolation to decrement interpolation angle from current value down to 0
            motor_ptr->mpos.hall.accumulate_degree_per_dt = -QCONST(0.026f, Q16);
        }
        // Handle the case of normal forward transition
        else
        {
            // Reset interpolation angle and let speed calculator determine interpolation increment
            motor_ptr->mpos.hall.accumulate_degree_value = 0;
            // Skip speed calculation on the first transition because speed reading is not valid
            if (motor_ptr->mpos.hall.transition_counter >= 1)
            {
                motor_ptr->mpos.hall.flag_speed_calc_enabled = TRUE;
                motor_ptr->mpos.hall.do_speed_cal = TRUE;
            }
            // Increment internal hall transition counter
            motor_ptr->mpos.hall.transition_counter++;
        }
#if defined(ENABLE_HALL_TUNING)
        halltune_store_transition_angle(motor_ptr);
#endif
#if defined(ENABLE_ANGLE_CORRECTION) || defined(ENABLE_MTPA)
        hall_angle_correction(motor_ptr);
#else
        motor_ptr->mpos.hall.hall_interpolated_angle = motor_ptr->mpos.hall.angle_fix16;
#endif
#if defined(ENABLE_HALL_TUNING)
        halltune_edgetuning(motor_ptr);
#endif
        // Store the last state
        motor_ptr->mpos.hall.SensorStateLast = motor_ptr->mpos.hall.SensorStateNew;
        __disable_irq();
        // Re-enable hall port interrupts
        hall_int_hallport_enable();
        __enable_irq();
    }
    else
    {
        // Calculate hall speed and interpolation increment
        if (motor_ptr->mpos.hall.do_speed_cal)
        {
            // Calculate speed only in the first cycle after hall state transition
            motor_ptr->mpos.hall.do_speed_cal = FALSE;
            // Calculate motor speed
            hall_calc_motor_speed(motor_ptr);
#if defined(ENABLE_HALL_TUNING)
            halltune_edge_pol_skew_tuning(motor_ptr);
#endif
        }
        // Clear external hall state transition flag
        motor_ptr->mpos.hall.transition_ext_flag = FALSE;
        // Interpolate angle between hall state transitions
        hall_angle_interpolate(motor_ptr);
    }
#if defined(ENABLE_HALL_ASSIST)
    hall_assist(motor_ptr);
#endif
#if 0
// debug_dac_1a = motor_ptr->mpos.hall.SensorStateNew << 13;
// debug_dac_1a = GET_HALL_VALUE << 11;
// debug_dac_1b = motor_ptr->mpos.hall.SensorStateNew << 11;
// debug_dac_1a = motor_ptr->mpos.hall.hall_spd_scaled_q14;
// debug_dac_2b = motor_ptr->mpos.hall.angle_fix16 >> 5;
// debug_dac_1c = motor_ptr->mpos.hall.hall_interpolated_angle >> 5;
// debug_dac_1a = motor_ptr->mpos.hall.accumulate_degree_per_dt;
// debug_dac_2c = motor_ptr->mpos.hall.accumulate_degree_value >> 5;
// debug_dac_2a = motor_ptr->mpos.hall.hall_angle >> 5;
// debug_dac_1a = motor_ptr->control.dt_control_q26;
#endif
}
References FALSE, Struct_Hall::flag_hall_int, Struct_MPos::hall, Struct_Motor::mpos, and Struct_Hall::transition_flag.
void hall_reset (Struct_Motor * motor_ptr)
Use for reset FOC hall related variables, interrupt, ports.
Parameters
Struct_Motor* motor_ptr
Definition at line 185 of file hall_funcs.c.
{
    // JAGTAG: Maybe move to hall_init()
    NVIC_EnableIRQ(Hall_Gpio_IRQn);
    // Set hall angle and next state array pointer according to motor direction
    if(motor_ptr->app.direction_reverse_cmd == 0)
    {
        motor_ptr->mpos.hall.hall_ptr_snapangle = &motor_ptr->mpos.hall.hall_to_snapangle_forward[0];
        motor_ptr->mpos.hall.ptr_angcorr_gain = &motor_ptr->mpos.hall.angcorr_gain_fwd_q20;
        motor_ptr->mpos.hall.ptr_angcorr_offset = &motor_ptr->mpos.hall.angcorr_offset_fwd;
        motor_ptr->mpos.hall.hall_ptr_next_state = &motor_ptr->mpos.hall.hall_forward_next_state[0];
        motor_ptr->mpos.hall.hall_ptr_prev_state = &motor_ptr->mpos.hall.hall_forward_prev_state[0];
    }
    else
    {
        motor_ptr->mpos.hall.hall_ptr_snapangle = &motor_ptr->mpos.hall.hall_to_snapangle_reverse[0];
        motor_ptr->mpos.hall.ptr_angcorr_gain = &motor_ptr->mpos.hall.angcorr_gain_rev_q20;
        motor_ptr->mpos.hall.ptr_angcorr_offset = &motor_ptr->mpos.hall.angcorr_offset_rev;
        motor_ptr->mpos.hall.hall_ptr_next_state = &motor_ptr->mpos.hall.hall_reverse_next_state[0];
        motor_ptr->mpos.hall.hall_ptr_prev_state = &motor_ptr->mpos.hall.hall_reverse_prev_state[0];
    }
    // Reset hall transition counter
    motor_ptr->mpos.hall.transition_counter = 0;
    // Reset hall speed and filter
    motor_ptr->mpos.hall.hall_spd_radps = 0;
    motor_ptr->mpos.hall.hall_spd_scaled_q14 = 0;
    motor_ptr->mpos.hall.hall_spd_scaled_q28 = 0;
    motor_ptr->mpos.hall.hall_spd_radps = 0;
    // Reset interpolation
    motor_ptr->mpos.hall.accumulate_degree_value = 0;
    motor_ptr->mpos.hall.accumulate_degree_per_dt = 0;
    // Reset state flags
    motor_ptr->mpos.hall.transition_flag = FALSE;
    motor_ptr->mpos.hall.transition_ext_flag = FALSE;
    motor_ptr->mpos.hall.do_speed_cal = FALSE;
    motor_ptr->mpos.hall.flag_speed_calc_enabled = FALSE;
    motor_ptr->mpos.hall.flag_hall_int = FALSE;
    motor_ptr->mpos.hall.flag_inithallspdfilt = TRUE;
    // Reset hall state to current state
    motor_ptr->mpos.hall.SensorStateLast = motor_ptr->mpos.hall.SensorStateNew = GET_HALL_VALUE;
    // Calculate hall angle for current state
    hall_calc_motor_angle(motor_ptr);
#ifdef ENABLE_ANGLE_CORRECTION
    // Angle Correction (only offset)
    motor_ptr->mpos.hall.hall_angle = motor_ptr->mpos.hall.angle_fix16 + *motor_ptr->mpos.hall.ptr_angcorr_offset;
#endif
    // Enable hall timer
    hall_timer_clear();
#if defined(FAMILY_52XX)
    // Configure the hall interrupt edge polarity depending on hall port input
    pac5xxx_gpio_int_polarity_hallport_bit_set_value(HALLA_PORT_BIT, PAC5XXX_GPIO_HALLA->IN.b & HALLA_PORT_BIT);
    pac5xxx_gpio_int_polarity_hallport_bit_set_value(HALLB_PORT_BIT, PAC5XXX_GPIO_HALLB->IN.b & HALLB_PORT_BIT);
    pac5xxx_gpio_int_polarity_hallport_bit_set_value(HALLC_PORT_BIT, PAC5XXX_GPIO_HALLC->IN.b & HALLC_PORT_BIT);
#endif
    // Reset diagnostics
    motor_ptr->mpos.hall.hall_check_error_code = 0;
    motor_ptr->mpos.hall.hall_check_error_state_new = 0;
    motor_ptr->mpos.hall.hall_check_error_state_prev = 0;
    // Reset observer hall angle correction
    motor_ptr->mpos.hall.hall_est_angle_corr = 0;
    __disable_irq();
    // Enable hall port interrupts
    hall_int_hallport_enable();
    __enable_irq();
}
References Struct_Hall::accumulate_degree_per_dt, Struct_Hall::accumulate_degree_value, Struct_Hall::angcorr_gain_fwd_q20, Struct_Hall::angcorr_gain_rev_q20, Struct_Hall::angcorr_offset_fwd, Struct_Hall::angcorr_offset_rev, Struct_Motor::app, Struct_App::direction_reverse_cmd, Struct_Hall::do_speed_cal, FALSE, Struct_Hall::flag_hall_int, Struct_Hall::flag_inithallspdfilt, Struct_Hall::flag_speed_calc_enabled, GET_HALL_VALUE, Struct_MPos::hall, Struct_Hall::hall_forward_next_state, Struct_Hall::hall_forward_prev_state, Struct_Hall::hall_ptr_next_state, Struct_Hall::hall_ptr_prev_state, Struct_Hall::hall_ptr_snapangle, Struct_Hall::hall_reverse_next_state, Struct_Hall::hall_reverse_prev_state, Struct_Hall::hall_spd_radps, Struct_Hall::hall_spd_scaled_q14, Struct_Hall::hall_spd_scaled_q28, Struct_Hall::hall_to_snapangle_forward, Struct_Hall::hall_to_snapangle_reverse, Struct_Motor::mpos, Struct_Hall::ptr_angcorr_gain, Struct_Hall::ptr_angcorr_offset, Struct_Hall::SensorStateLast, Struct_Hall::SensorStateNew, Struct_Hall::transition_counter, Struct_Hall::transition_ext_flag, Struct_Hall::transition_flag, and TRUE.
void hall_sort_create_next_state_array (int32_t * array_ptr_src, char * array_ptr_dest)
Use to sort and create next state table using source hall state array.
Parameters
int32_t* array_ptr_src
char* array_ptr_dest
Definition at line 332 of file hall_funcs.c.
{
#define START_INDEX_1 1
#define END_INDEX_1 7
    int32_t temp_angle_array[8] = {0,0,0,0,0,0,0,0};
    int32_t temp_index_array[8] = {0,0,0,0,0,0,0,0};
    volatile uint8_t count, count_element;
    // Copy angle info from 1D array to 1D array for sorting
    // Copy only data from index 1 to 6, indexes 0 and 7 are invalid
    for (count = START_INDEX_1; count < END_INDEX_1; count++)
        temp_angle_array[count] = array_ptr_src[count];
    // Sort array in ascending order for hall angles, smaller to bigger hall angle values and store in temporary 1D array
    // Sort function is a generic bubble sort also used in IPD
    bubble_sort_array(&temp_angle_array[START_INDEX_1], sizeof(temp_angle_array)/sizeof(temp_angle_array[0]) - 2);
    // Do a search and find hall states corresponding to hall angle values and save in temporary 1D array
    for (count = START_INDEX_1; count < END_INDEX_1; count++)
    {
        for (count_element = START_INDEX_1; count_element < END_INDEX_1; count_element++)
        {
            // Check if the hall angle value of sorted array matches the default hall angle array
            // If yes copy the array index for final hall angle, index array creation, use for next hall state calculation
            if(temp_angle_array[count] == array_ptr_src[count_element])
            {
                temp_index_array[count] = count_element;
                break;
            }
        }
    }
    // Call use to create next state table using hall state index information from ascending order angle table array
    hall_create_next_state_array(&temp_index_array[0], array_ptr_dest);
}
References bubble_sort_array(), END_INDEX_1, hall_create_next_state_array(), and START_INDEX_1.
Referenced by hall_create_sequence_array().
void hall_sort_create_prev_state_array (int32_t * array_ptr_src, char * array_ptr_dest)
Use to sort in descending order and create next state table using source hall state array.
Parameters
int32_t* array_ptr_src
char* array_ptr_dest
Definition at line 374 of file hall_funcs.c.
{
#define START_INDEX_1 1
#define END_INDEX_1 7
    int32_t temp_angle_array[8] = {0,0,0,0,0,0,0,0};
    int32_t temp_index_array[8] = {0,0,0,0,0,0,0,0};
    volatile uint8_t count, count_element;
    // Copy angle info from 1D array to 1D array for sorting
    // Copy only data from index 1 to 6, indexes 0 and 7 are invalid
    for (count = START_INDEX_1; count < END_INDEX_1; count++)
        temp_angle_array[count] = array_ptr_src[count];
    // Sort array in ascending order for hall angles, smaller to bigger hall angle values and store in temporary 1D array
    // Sort function is a generic bubble sort also used in IPD
    bubble_sort_array_descending(&temp_angle_array[START_INDEX_1], sizeof(temp_angle_array)/sizeof(temp_angle_array[0]) - 2);
    // Do a search and find hall states corresponding to hall angle values and save in temporary 1D array
    for (count = START_INDEX_1; count < END_INDEX_1; count++)
    {
        for (count_element = START_INDEX_1; count_element < END_INDEX_1; count_element++)
        {
            // Check if the hall angle value of sorted array matches the default hall angle array
            // If yes copy the array index for final hall angle, index array creation, use for next hall state calculation
            if(temp_angle_array[count] == array_ptr_src[count_element])
            {
                temp_index_array[count] = count_element;
                break;
            }
        }
    }
    // Call use to create next state table using hall state index information from ascending order angle table array
    hall_create_next_state_array(&temp_index_array[0], array_ptr_dest);
}
References bubble_sort_array_descending(), END_INDEX_1, hall_create_next_state_array(), and START_INDEX_1.
Referenced by hall_create_sequence_array().
void hall_timer_isr (void)
Use for processing hall timer ISR.
Definition at line 267 of file hall_funcs.c.
{
    static Struct_Motor* motor_ptr = &motor;
#if defined(CONFIG_HALL_TIMEOUT_MDISABLE)
    // Disable motor on hall timeout event
    if (motor_ptr->state.main == STATE_MAIN_RUN)
    {
        set_fault(FAULT_HALL_TIMEOUT);
    }
#else
    // Handle hall timeout by treating as 0 speed
    // Reset hall transition counter
    motor_ptr->mpos.hall.transition_counter = 0;
    // Set speed and speed filter to 0
    motor_ptr->mpos.hall.hall_spd_radps = 0;
    motor_ptr->mpos.hall.hall_spd_scaled_q14 = 0;
    motor_ptr->mpos.hall.hall_spd_scaled_q28 = 0;
    motor_ptr->mpos.hall.hall_spd_radps = 0;
    // Reset interpolation
    motor_ptr->mpos.hall.accumulate_degree_per_dt = 0;
#endif
#if defined(ENABLE_SIM)
    sim_halltimer_intflag_set(motor_ptr);
#endif
    // Clear interrupt bit
    hall_timer_clr_interrupt();
}
References Struct_Hall::accumulate_degree_per_dt, FAULT_HALL_TIMEOUT, Struct_MPos::hall, Struct_Hall::hall_spd_radps, Struct_Hall::hall_spd_scaled_q14, Struct_Hall::hall_spd_scaled_q28, Struct_State::main, motor, Struct_Motor::mpos, set_fault(), Struct_Motor::state, STATE_MAIN_RUN, and Struct_Hall::transition_counter.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.