.TH "pac_foc/src/control/harmonic_inj_libfuncs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/harmonic_inj_libfuncs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'calc_angle\&.h'\fP
.br
\fC#include 'sqrt\&.h'\fP
.br
\fC#include 'trig\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "PAC5XXX_RAMFUNC void \fBhinj_process\fP (\fBStruct_HarmonicInj\fP *harmonicinj_ptr, int32_t valpha_q14, int32_t vbeta_q14, int32_t *svm_ta_q14, int32_t *svm_tb_q14, int32_t *svm_tc_q14, int32_t angle_e)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "PAC5XXX_RAMFUNC void hinj_process (\fBStruct_HarmonicInj\fP * harmonicinj_ptr, int32_t valpha_q14, int32_t vbeta_q14, int32_t * svm_ta_q14, int32_t * svm_tb_q14, int32_t * svm_tc_q14, int32_t angle_e)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
