pac_foc/src/math/int64.h
NAME
pac_foc/src/math/int64.h - Definitions for 64-bit math functions.
SYNOPSIS
#include 'pac5xxx.h'
Data Structures
struct lfm_int64
Macros
#define FIXMATH_NO_64BIT
Functions
PAC5XXX_RAMFUNC lfm_int64 int64_add (lfm_int64 x, lfm_int64 y)
Adds two 64-bit numbers.
PAC5XXX_RAMFUNC lfm_int64 int64_neg (lfm_int64 x)
Negate a 64-bit number.
PAC5XXX_RAMFUNC lfm_int64 int64_sub (lfm_int64 x, lfm_int64 y)
Subtract two 64-bit numbers (x - y)
PAC5XXX_RAMFUNC lfm_int64 int64_shift (lfm_int64 x, int8_t y)
Shift a 64-bit number by the given number of bits.
PAC5XXX_RAMFUNC lfm_int64 int64_mul_i32_i32 (int32_t x, int32_t y)
Multiply two 32-bit numbers into a 64-bit number.
PAC5XXX_RAMFUNC lfm_int64 int64_mul_i64_i32 (lfm_int64 x, int32_t y)
Multiply a 64-bit and 32-bit number.
PAC5XXX_RAMFUNC lfm_int64 int64_div_i64_i32 (lfm_int64 x, int32_t y)
Divide a 64-bit number by a 32-bit number (x / y)
Detailed Description
Definitions for 64-bit math functions.
Definition in file int64.h.
Macro Definition Documentation
#define FIXMATH_NO_64BIT
Definition at line 40 of file int64.h.
Function Documentation
PAC5XXX_RAMFUNC lfm_int64 int64_add (lfm_int64 x, lfm_int64 y)
Adds two 64-bit numbers.
Parameters
x 64-bit number
y 64-bit number
Returns
64-bit sum
Definition at line 782 of file fix16.c.
{
        lfm_int64 ret;
        ret.hi = x.hi + y.hi;
        ret.lo = x.lo + y.lo;
        if((ret.lo < x.lo) || (ret.hi < y.hi))
                ret.hi++;
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
Referenced by int64_sub().
PAC5XXX_RAMFUNC lfm_int64 int64_div_i64_i32 (lfm_int64 x, int32_t y)
Divide a 64-bit number by a 32-bit number (x / y)
Parameters
x 64-bit number
y 32-bit number
Returns
64-bit result (x / y)
Definition at line 859 of file fix16.c.
                                                    {
        int neg = ((x.hi ^ y) < 0);
        if(x.hi < 0)
                x = int64_neg(x);
        if(y < 0)
                y = -y;
        lfm_int64 ret = { (x.hi / y) , (x.lo / y) };
        x.hi = x.hi % y;
        x.lo = x.lo % y;
        lfm_int64 _y = int64_from_int32(y);
        lfm_int64 i;
        for(i = int64_from_int32(1); int64_cmp_lt(_y, x); _y = int64_shift(_y, 1), i = int64_shift(i, 1));
        while(x.hi) {
                _y = int64_shift(_y, -1);
                 i = int64_shift(i, -1);
                if(int64_cmp_ge(x, _y)) {
                        x = int64_sub(x, _y);
                        ret = int64_add(ret, i);
                }
        }
        ret = int64_add(ret, int64_from_int32(x.lo / y));
        return (neg ? int64_neg(ret) : ret);
}
References lfm_int64::hi, int64_neg(), and lfm_int64::lo.
PAC5XXX_RAMFUNC lfm_int64 int64_mul_i32_i32 (int32_t x, int32_t y)
Multiply two 32-bit numbers into a 64-bit number.
Parameters
x 32-bit number
y 32-bit number
Returns
64-bit product
Definition at line 823 of file fix16.c.
                                                  {
         int16_t hi[2] = { (x >> 16), (y >> 16) };
        uint16_t lo[2] = { (x & 0xFFFF), (y & 0xFFFF) };
         int32_t r_hi = hi[0] * hi[1];
         int32_t r_md = (hi[0] * lo[1]) + (hi[1] * lo[0]);
        uint32_t r_lo = lo[0] * lo[1];
        r_hi += (r_md >> 16);
        r_lo += (r_md << 16);
        return (lfm_int64){ r_hi, r_lo };
}
PAC5XXX_RAMFUNC lfm_int64 int64_mul_i64_i32 (lfm_int64 x, int32_t y)
Multiply a 64-bit and 32-bit number.
Parameters
x 64-bit number
y 32-bit number
Returns
64-bit product
Definition at line 837 of file fix16.c.
                                                    {
        int neg = ((x.hi ^ y) < 0);
        if(x.hi < 0)
                x = int64_neg(x);
        if(y < 0)
                y = -y;
        uint32_t _x[4] = { (x.hi >> 16), (x.hi & 0xFFFF), (x.lo >> 16), (x.lo & 0xFFFF) };
        uint32_t _y[2] = { (y >> 16), (y & 0xFFFF) };
        uint32_t r[4];
        r[0] = (_x[0] * _y[0]);
        r[1] = (_x[1] * _y[0]) + (_x[0] * _y[1]);
        r[2] = (_x[1] * _y[1]) + (_x[2] * _y[0]);
        r[3] = (_x[2] * _y[0]) + (_x[1] * _y[1]);
        lfm_int64 ret;
        ret.lo = r[0] + (r[1] << 16);
        ret.hi = (r[3] << 16) + r[2] + (r[1] >> 16);
        return (neg ? int64_neg(ret) : ret);
}
References lfm_int64::hi, int64_neg(), and lfm_int64::lo.
PAC5XXX_RAMFUNC lfm_int64 int64_neg (lfm_int64 x)
Negate a 64-bit number.
Parameters
x 64-bit number
Returns
negated 64-bit number
Definition at line 814 of file fix16.c.
                                 {
        lfm_int64 ret;
        ret.hi = ~x.hi;
        ret.lo = ~x.lo + 1;
        if(ret.lo == 0)
                ret.hi++;
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
Referenced by int64_div_i64_i32(), int64_mul_i64_i32(), and int64_sub().
PAC5XXX_RAMFUNC lfm_int64 int64_shift (lfm_int64 x, int8_t y)
Shift a 64-bit number by the given number of bits.
Parameters
x 64-bit number
y number of bits to shift
Returns
64-bit shifted number
Definition at line 797 of file fix16.c.
                                             {
        lfm_int64 ret;
        if(y > 0) {
                if(y >= 32)
                        return (lfm_int64){ 0, 0 };
                ret.hi = (x.hi << y) | (x.lo >> (32 - y));
                ret.lo = (x.lo << y);
        } else {
                y = -y;
                if(y >= 32)
                        return (lfm_int64){ 0, 0 };
                ret.lo = (x.lo >> y) | (x.hi << (32 - y));
                ret.hi = (x.hi >> y);
        }
        return ret;
}
References lfm_int64::hi, and lfm_int64::lo.
PAC5XXX_RAMFUNC lfm_int64 int64_sub (lfm_int64 x, lfm_int64 y)
Subtract two 64-bit numbers (x - y)
Parameters
x 64-bit number
y 64-bit number
Returns
64-bit difference (x - y )
Definition at line 792 of file fix16.c.
                                              {
        return int64_add(x, int64_neg(y));
}
References int64_add(), and int64_neg().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.