pac_foc/src/isr/isr_gpioB.c
NAME
pac_foc/src/isr/isr_gpioB.c - Use for PortB ISR.
SYNOPSIS
#include 'motor_struct.h'
#include 'pac_init.h'
#include 'fault.h'
#include 'pac5xxx_driver_gpio.h'
#include 'pac5xxx_driver_tile.h'
Functions
void GpioB_IRQHandler (void)
Process GPIOB interrupts (CAFE interrupt on PB0)
Detailed Description
Use for PortB ISR.
Definition in file isr_gpioB.c.
Function Documentation
void GpioB_IRQHandler (void)
Process GPIOB interrupts (CAFE interrupt on PB0) Process GPIOB interrupts (CAFE interrupt on PB0) to handle over current
Definition at line 32 of file isr_gpioB.c.
{
    volatile uint8_t overcurrent_fault;
    volatile uint8_t temperature_fault;
    volatile uint8_t driver_fault;
    
#ifdef ENABLE_CBC_CURRENT_LIMIT
    volatile uint8_t cbc;
#endif
    // clear interrupt
    clear_oc_interrupt();
    
#ifdef ENABLE_CBC_CURRENT_LIMIT
    cbc = (pac5xxx_tile_register_read(ADDR_PROTSTAT) & 0x07);
    
    // Respond to CBC current condition
    if (cbc)
    {
        motor.stall.flag_cbc_triggered = 1;
        cbc_current_reset();
        set_warning(WARNING_CBC_OC);
    }
#endif
    driver_fault = pac5xxx_get_driver_fault();
    overcurrent_fault = pac5xxx_get_over_current_status();
    temperature_fault = pac5xxx_get_over_temperature_status();
    
    if (overcurrent_fault | temperature_fault | driver_fault)
    {
        // Set OC flag
        set_fault(FAULT_CAFE_OC);
    }
}
References FAULT_CAFE_OC, motor, pac5xxx_get_driver_fault(), pac5xxx_get_over_current_status(), pac5xxx_get_over_temperature_status(), set_fault(), set_warning(), and WARNING_CBC_OC.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.