pac_foc/src/isr/isr_stubs.c
NAME
pac_foc/src/isr/isr_stubs.c - Use for NMI, MemCtl, HardFault and Default ISR handlers.
SYNOPSIS
#include 'motor_struct.h'
#include 'fault.h'
Functions
void NMI_Handler (void)
Process interrupt for NMI_Handler.
void HardFault_Handler (void)
Process interrupt for HardFault_Handler.
void MemCtl_IRQHandler (void)
Process interrupt for MemCtl_IRQHandler.
void Default_Handler (void)
Process interrupt for Default_Handler.
Detailed Description
Use for NMI, MemCtl, HardFault and Default ISR handlers.
Definition in file isr_stubs.c.
Function Documentation
void Default_Handler (void)
Process interrupt for Default_Handler.
Definition at line 50 of file isr_stubs.c.
{
    // Go into an infinite loop.
    fault();
}
References fault().
void HardFault_Handler (void)
Process interrupt for HardFault_Handler.
Definition at line 34 of file isr_stubs.c.
{
    fault();
}
References fault().
void MemCtl_IRQHandler (void)
Process interrupt for MemCtl_IRQHandler.
Definition at line 42 of file isr_stubs.c.
{
    fault();
}
References fault().
void NMI_Handler (void)
Process interrupt for NMI_Handler.
Definition at line 26 of file isr_stubs.c.
{
    fault();
}
References fault().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.