.TH "pac_foc/src/isr/isr_gpioB.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/isr/isr_gpioB.c \- Use for PortB ISR\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'pac_init\&.h'\fP
.br
\fC#include 'fault\&.h'\fP
.br
\fC#include 'pac5xxx_driver_gpio\&.h'\fP
.br
\fC#include 'pac5xxx_driver_tile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGpioB_IRQHandler\fP (void)"
.br
.RI "Process GPIOB interrupts (CAFE interrupt on PB0) "
.in -1c
.SH "Detailed Description"
.PP 
Use for PortB ISR\&. 


.PP
Definition in file \fBisr_gpioB\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void GpioB_IRQHandler (void)"

.PP
Process GPIOB interrupts (CAFE interrupt on PB0) Process GPIOB interrupts (CAFE interrupt on PB0) to handle over current 
.PP
Definition at line 32 of file isr_gpioB\&.c\&.
.PP
.nf
33 {
34     volatile uint8_t overcurrent_fault;
35     volatile uint8_t temperature_fault;
36     volatile uint8_t driver_fault;
37     
38 #ifdef ENABLE_CBC_CURRENT_LIMIT
39     volatile uint8_t cbc;
40 #endif
41 
42     // clear interrupt
43     clear_oc_interrupt();
44     
45 #ifdef ENABLE_CBC_CURRENT_LIMIT
46     cbc = (pac5xxx_tile_register_read(ADDR_PROTSTAT) & 0x07);
47     
48     // Respond to CBC current condition
49     if (cbc)
50     {
51         motor\&.stall\&.flag_cbc_triggered = 1;
52         cbc_current_reset();
53         set_warning(WARNING_CBC_OC);
54     }
55 #endif
56 
57     driver_fault = pac5xxx_get_driver_fault();
58     overcurrent_fault = pac5xxx_get_over_current_status();
59     temperature_fault = pac5xxx_get_over_temperature_status();
60     
61     if (overcurrent_fault | temperature_fault | driver_fault)
62     {
63         // Set OC flag
64         set_fault(FAULT_CAFE_OC);
65     }       
66 }
.fi
.PP
References FAULT_CAFE_OC, motor, pac5xxx_get_driver_fault(), pac5xxx_get_over_current_status(), pac5xxx_get_over_temperature_status(), set_fault(), set_warning(), and WARNING_CBC_OC\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
