pac_foc/src/mpos/estimator/lbg1.h
NAME
pac_foc/src/mpos/estimator/lbg1.h - Estimator main functions.
SYNOPSIS
#include 'pac5xxx.h'
#include 'maths.h'
#include 'lbg1_struct.h'
Macros
#define LBG_GAIN_SCALER_Q06 QCONST(20000.0f, Q06)
#define LBG_KGAIN_START_PCT_F16 QCONST(0.2, Q16)
#define LBG_KGAIN_INC_PCT_F16 QCONST(0.10, Q16)
Functions
void lbg1_process_voltage_scale_lib (Struct_Est *est_ptr, fix16_t descale_voltage_factor)
void lbg1_update_state_lib (Struct_Est *est_ptr, fix16_t update_angle_q16, fix16_t update_speed_radps_q16, uint16_t speed_scale_shift, int32_t dt_control_q26)
void lbg1_check_transition_ready (Struct_Est *est_ptr)
void lbg1_calculate_coefficients_lib (Struct_Est *est_ptr, fix16_t dt_control_q26, fix16_t factor_current_descale, fix16_t motorparam_r, int32_t motorparam_l_x1024, uint16_t speed_scale_shift, int32_t gain_scaler_q06, int32_t nom_spd_q16)
void lbg1_switch2cl (Struct_Est *est_ptr)
void lbg1_statemon_lib (Struct_Est *est_ptr, int32_t lq_q26, int32_t rs_q16, int32_t dt_control_q26, int32_t descale_current_factor)
void lbg1_init (Struct_Est *est_ptr, int32_t lq_q26, int32_t rs_q16, int32_t dt_control_q26, int32_t descale_current_factor)
PAC5XXX_RAMFUNC void lbg1_estimator_lib (Struct_Est *est_ptr)
Detailed Description
Estimator main functions.
Definition in file lbg1.h.
Macro Definition Documentation
#define LBG_GAIN_SCALER_Q06 QCONST(20000.0f, Q06)
Definition at line 28 of file lbg1.h.
#define LBG_KGAIN_INC_PCT_F16 QCONST(0.10, Q16)
Definition at line 32 of file lbg1.h.
#define LBG_KGAIN_START_PCT_F16 QCONST(0.2, Q16)
Definition at line 31 of file lbg1.h.
Function Documentation
void lbg1_calculate_coefficients_lib (Struct_Est * est_ptr, fix16_t dt_control_q26, fix16_t factor_current_descale, fix16_t motorparam_r, int32_t motorparam_l_x1024, uint16_t speed_scale_shift, int32_t gain_scaler_q06, int32_t nom_spd_q16)
Referenced by lbg1_calculate_coefficients().
void lbg1_check_transition_ready (Struct_Est * est_ptr)
PAC5XXX_RAMFUNC void lbg1_estimator_lib (Struct_Est * est_ptr)
void lbg1_init (Struct_Est * est_ptr, int32_t lq_q26, int32_t rs_q16, int32_t dt_control_q26, int32_t descale_current_factor)
Referenced by lbg1_reset().
void lbg1_process_voltage_scale_lib (Struct_Est * est_ptr, fix16_t descale_voltage_factor)
Referenced by lbg1_process_voltage_scale().
void lbg1_statemon_lib (Struct_Est * est_ptr, int32_t lq_q26, int32_t rs_q16, int32_t dt_control_q26, int32_t descale_current_factor)
Referenced by lbg1_statemon().
void lbg1_switch2cl (Struct_Est * est_ptr)
void lbg1_update_state_lib (Struct_Est * est_ptr, fix16_t update_angle_q16, fix16_t update_speed_radps_q16, uint16_t speed_scale_shift, int32_t dt_control_q26)
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.