pac_foc/src/mpos/estimator/lbg1_funcs.c
NAME
pac_foc/src/mpos/estimator/lbg1_funcs.c - Estimator utility functions.
SYNOPSIS
#include 'config_app.h'
#include 'lbg1_funcs.h'
#include 'fault.h'
Functions
void lbg1_process_voltage_scale (Struct_Motor *motor_ptr)
Use for scaling estimator gs and kpe variables.
void lbg1_calculate_coefficients (Struct_Motor *motor_ptr)
Use for scaling estimator gs and kpe variables.
void lbg1_reset (Struct_Motor *motor_ptr)
Use to initialize and reset estimator variables.
void lbg1_statemon (Struct_Motor *motor_ptr)
Use for estimator variable ramps and ialpha, valpha calculation.
void lbg1_param_write (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for writing estimator parameters.
void lbg1_param_process (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for calculating estimator coefficients.
Detailed Description
Estimator utility functions.
Definition in file lbg1_funcs.c.
Function Documentation
void lbg1_calculate_coefficients (Struct_Motor * motor_ptr)
Use for scaling estimator gs and kpe variables.
Parameters
Struct_Motor* motor_ptr
Definition at line 41 of file lbg1_funcs.c.
{
    lbg1_calculate_coefficients_lib(&motor_ptr->mpos.est, motor_ptr->control.dt_control_q26, motor_ptr->app.descale_current_factor, motor_ptr->mparam.rs_q16,
            motor_ptr->mparam.lq_q26, motor_ptr->app.speed_scale_shift, LBG_GAIN_SCALER_Q06, motor_ptr->mparam.nom_spd_q16);
    // Set flag to indicate calculation is complete so that GUI can read it automatically
    set_status(FLAG_MPOS_UPDATE_CALC);
    // Set or clear warning for high estimator bandwidth
    if (motor_ptr->mpos.est.flag_estbw_high)
        set_warning(WARNING_ESTBW_HIGH);
    else
        clear_warning(WARNING_ESTBW_HIGH);
}
References Struct_Motor::app, Struct_Motor::control, Struct_App::descale_current_factor, Struct_Control::dt_control_q26, Struct_MPos::est, lbg1_calculate_coefficients_lib(), LBG_GAIN_SCALER_Q06, Struct_MParam::lq_q26, Struct_Motor::mparam, Struct_Motor::mpos, Struct_MParam::nom_spd_q16, Struct_MParam::rs_q16, and Struct_App::speed_scale_shift.
Referenced by lbg1_param_process().
void lbg1_param_process (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for calculating estimator coefficients.
Parameters
Struct_Motor* motor_ptr
ParameterCode param_code
int32_t rx_data
Definition at line 168 of file lbg1_funcs.c.
{
    // Parameter cases that require recalculation of estimator coefficients
    switch(param_code)
    {
    case dt:
    case diff_amp_gain:
    case Lq:
    case Ralpha:
    case NominalSpeed:
    case LBG1_BandWidth:
    case LBG1_DampingFactor:
    case LBG1_fc_speed:
        lbg1_calculate_coefficients(motor_ptr);
        break;
    default:
        break;
    }
}
References diff_amp_gain, dt, LBG1_BandWidth, lbg1_calculate_coefficients(), LBG1_DampingFactor, LBG1_fc_speed, Lq, NominalSpeed, and Ralpha.
void lbg1_param_write (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Use for writing estimator parameters.
Parameters
Struct_Motor* motor_ptr
ParameterCode param_code
int32_t rx_data
Definition at line 134 of file lbg1_funcs.c.
{
    // Parameter process handler
    switch(param_code)
    {
    case LBG1_BandWidth:
        motor_ptr->mpos.est.w0_q06 = rx_data >> 10;
        motor_ptr->mpos.est.w0_target_q06 = motor_ptr->mpos.est.w0_q06;
        break;
    case LBG1_DampingFactor:
        motor_ptr->mpos.est.dampfactor_q16 = rx_data;
        break;
    case LBG1_fc_speed:
        motor_ptr->mpos.est.filter_fc_speed_q16 = rx_data;
        break;
    case angle_correction_offset:
        motor_ptr->mpos.est.angcorr_offset = rx_data;
        break;
    case angle_correction_factor:
        // Value sent by GUI in Q20 format
        motor_ptr->mpos.est.angcorr_gain_q20 = rx_data;
        break;
    default:
        break;
    }
}
References Struct_Est::angcorr_gain_q20, Struct_Est::angcorr_offset, angle_correction_factor, angle_correction_offset, Struct_Est::dampfactor_q16, Struct_MPos::est, Struct_Est::filter_fc_speed_q16, LBG1_BandWidth, LBG1_DampingFactor, LBG1_fc_speed, Struct_Motor::mpos, Struct_Est::w0_q06, and Struct_Est::w0_target_q06.
void lbg1_process_voltage_scale (Struct_Motor * motor_ptr)
Use for scaling estimator gs and kpe variables.
Parameters
Struct_Motor* motor_ptr
Definition at line 31 of file lbg1_funcs.c.
{
    lbg1_process_voltage_scale_lib(&motor_ptr->mpos.est, motor_ptr->app.descale_voltage_factor);
}
References Struct_Motor::app, Struct_App::descale_voltage_factor, Struct_MPos::est, lbg1_process_voltage_scale_lib(), and Struct_Motor::mpos.
void lbg1_reset (Struct_Motor * motor_ptr)
Use to initialize and reset estimator variables.
Parameters
Struct_Motor* motor_ptr
Definition at line 61 of file lbg1_funcs.c.
{
    lbg1_init(&motor_ptr->mpos.est, motor_ptr->mparam.lq_q26, motor_ptr->mparam.rs_q16, motor_ptr->control.dt_control_q26, motor_ptr->app.descale_current_factor);
    motor_ptr->mpos.est.switchover_check_pass = 0; // flag set when we are ready to switch to close loop
    motor_ptr->mpos.est.angle_diff_timeout_counter = 0;
    motor_ptr->mpos.est.lbg_valid_fault_flag = 0;
    motor_ptr->mpos.est.lbg_valid_check_counter = 0;
}
References Struct_Est::angle_diff_timeout_counter, Struct_Motor::app, Struct_Motor::control, Struct_App::descale_current_factor, Struct_Control::dt_control_q26, Struct_MPos::est, lbg1_init(), Struct_Est::lbg_valid_check_counter, Struct_Est::lbg_valid_fault_flag, Struct_MParam::lq_q26, Struct_Motor::mparam, Struct_Motor::mpos, Struct_MParam::rs_q16, and Struct_Est::switchover_check_pass.
void lbg1_statemon (Struct_Motor * motor_ptr)
Use for estimator variable ramps and ialpha, valpha calculation.
Parameters
Struct_Motor* motor_ptr
Definition at line 77 of file lbg1_funcs.c.
{
    int32_t ialpha_sq_q28;
    int32_t valpha_sq_q28;
    lbg1_statemon_lib(&motor_ptr->mpos.est, motor_ptr->mparam.lq_q26, motor_ptr->mparam.rs_q16, motor_ptr->control.dt_control_q26, motor_ptr->app.descale_current_factor);
// debug_dac_1a = (motor_ptr->mpos.est.w0_target_q06 >> 6);
// debug_dac_1b = (motor_ptr->mpos.est.w0_ramp_q06 >> 6);
// debug_dac_2a = motor_ptr->mpos.est.kpe_const_q14;
// debug_dac_2b = motor_ptr->mpos.est.kpi_const_q14;
#if (MPOS_SELECT == MPOS_LBG1_START_ALIGNGO)
    if (motor_ptr->state.main == STATE_MAIN_RUN)
#elif (MPOS_SELECT == MPOS_LBG1_START_HALL)
    if (motor_ptr->mpos.mposmode == STATE_MPOSMODE_EST)
#endif
    {
        // Check that estimator inputs are valid
        ialpha_sq_q28 = ((motor_ptr->mpos.est.ialpha1_q14 * motor_ptr->mpos.est.ialpha1_q14) + (motor_ptr->mpos.est.ibeta1_q14 * motor_ptr->mpos.est.ibeta1_q14));
        valpha_sq_q28 = ((motor_ptr->mpos.est.valpha1_q14 * motor_ptr->mpos.est.valpha1_q14) + (motor_ptr->mpos.est.vbeta1_q14 * motor_ptr->mpos.est.vbeta1_q14));
        if ((ialpha_sq_q28 < LBG_CHK_THRESHOLD_CURRENT_SQ_Q28) && (valpha_sq_q28 < LBG_CHK_THRESHOLD_VOLTAGE_SQ_Q28))
        {
            if (motor_ptr->mpos.est.lbg_valid_check_counter++ > LBG_VALID_CHECK_COUNT_MAX)
            {
                motor_ptr->mpos.est.lbg_valid_fault_flag = 1;
                set_fault(FAULT_EST_INVALID_INPUT);
            }
        }
        else
        {
            if (motor_ptr->mpos.est.lbg_valid_check_counter-- < 0)
            {
                motor_ptr->mpos.est.lbg_valid_check_counter = 0;
                motor_ptr->mpos.est.lbg_valid_fault_flag = 0;
            }
        }
    }
// debug_var_1 = motor_ptr->mpos.est.lbg_valid_fault_flag << 16;
//
// debug_dac_1a = LBG_CHK_THRESHOLD_CURRENT_SQ_Q28 >> 14;
// debug_dac_1b = ialpha_sq_q28 >> 14;
// debug_dac_2a = LBG_CHK_THRESHOLD_VOLTAGE_SQ_Q28 >> 14;
// debug_dac_2b = valpha_sq_q28 >> 14;
}
References Struct_Motor::app, Struct_Motor::control, Struct_App::descale_current_factor, Struct_Control::dt_control_q26, Struct_MPos::est, FAULT_EST_INVALID_INPUT, Struct_Est::ialpha1_q14, Struct_Est::ibeta1_q14, lbg1_statemon_lib(), LBG_CHK_THRESHOLD_CURRENT_SQ_Q28, LBG_CHK_THRESHOLD_VOLTAGE_SQ_Q28, LBG_VALID_CHECK_COUNT_MAX, Struct_Est::lbg_valid_check_counter, Struct_Est::lbg_valid_fault_flag, Struct_MParam::lq_q26, Struct_State::main, Struct_Motor::mparam, Struct_Motor::mpos, Struct_MPos::mposmode, Struct_MParam::rs_q16, set_fault(), Struct_Motor::state, STATE_MAIN_RUN, STATE_MPOSMODE_EST, Struct_Est::valpha1_q14, and Struct_Est::vbeta1_q14.
Referenced by SysTick_Handler().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.