pac_foc/src/main.c
NAME
pac_foc/src/main.c - Use for motor control hardware and software initialization.
SYNOPSIS
#include 'motor_struct.h'
#include 'app_funcs.h'
#include 'pac_init.h'
#include 'fault.h'
#include 'pac5xxx_driver_adc.h'
Functions
int main (void)
This function use for initializing hardware and motor control FOC firmware.
Detailed Description
Use for motor control hardware and software initialization.
Definition in file main.c.
Function Documentation
int main (void)
This function use for initializing hardware and motor control FOC firmware.
Definition at line 29 of file main.c.
{
    // Disable global interrupts until initialization is complete
    __disable_irq();
     
    // Set pointers to data structure for current motor
    Struct_Motor* motor_ptr = &motor;
    
    // Initialize main - FOC state machines and system variables
    systemvar_init(motor_ptr);
    // Initialize all MCU peripherals
    peripheral_init();
    // Initialize CAFE
    cafe_init();
    // Start ADC sequencer
    pac5xxx_adc_start();
             
    // Enable global interrupts
    __enable_irq();
    // All the processing is interrupt driven
    while(1) {}
}
References cafe_init(), motor, peripheral_init(), and systemvar_init().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.