.TH "pac_foc/src/features/autotune/mid1_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/autotune/mid1_funcs.h \- Use for auto-tuning function definition in motor identification 1\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'driver_funcs\&.h'\fP
.br
\fC#include 'control_funcs\&.h'\fP
.br
\fC#include 'foc_math\&.h'\fP
.br
\fC#include 'atune_libfuncs\&.h'\fP
.br
\fC#include 'foc_funcs\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for auto-tuning function definition in motor identification 1\&. 


.PP
Definition in file \fBmid1_funcs\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
