.TH "pac_foc/src/features/autotune/mid1_funcs.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/autotune/mid1_funcs.c \- Use for auto-tuning function calls in motor identification 1\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mid1_funcs\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for auto-tuning function calls in motor identification 1\&. 


.PP
Definition in file \fBmid1_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
