.TH "pac_foc/src/control/mtpa_funcs.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/control/mtpa_funcs.c \- Use for FOC MTPA function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'maths\&.h'\fP
.br
\fC#include 'mtpa_funcs\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for FOC MTPA function\&. 


.PP
Definition in file \fBmtpa_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
