.TH "pac_foc/src/features/opd/opd_ol_config.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/opd/opd_ol_config.h \- Configuration for open-loop open phase detection\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOLOPD_STARTSAMPLEDELAY\fP   500"
.br
.ti -1c
.RI "#define \fBOLOPD_TOTALSAMPLES\fP   1024"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration for open-loop open phase detection\&. 


.PP
Definition in file \fBopd_ol_config\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define OLOPD_STARTSAMPLEDELAY   500"

.PP
Definition at line 22 of file opd_ol_config\&.h\&.
.SS "#define OLOPD_TOTALSAMPLES   1024"

.PP
Definition at line 23 of file opd_ol_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
