.TH "pac_foc/src/features/opd/opd_cl_funcs.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/opd/opd_cl_funcs.c \- Use for control functions in OPD\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'opd_cl_funcs\&.h'\fP
.br
\fC#include 'opd_cl_config\&.h'\fP
.br
\fC#include 'fault\&.h'\fP
.br
\fC#include 'debug\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for control functions in OPD\&. 


.PP
Definition in file \fBopd_cl_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
