pac_foc/src/features/flash_crc_test/pac5xxx_flash_test.h
NAME
pac_foc/src/features/flash_crc_test/pac5xxx_flash_test.h
SYNOPSIS
#include 'config_features.h'
Functions
void set_reset_flash_crc_test_results (int32_t value)
int32_t get_reset_flash_crc_test_results (void)
int32_t pac5xxx_flash_crc_test (uint8_t *p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a test of the flash using a 16-bit CRC.
int32_t pac5xxx_fast_flash_crc_test (uint16_t *p_table, uint8_t *p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a fast flash test using a CRC Table.
void make_crc16_table (uint16_t *p_crctable)
This function makes a 256 entry 16-bit CRC table on the fly in RAM.
int32_t pac5xxx_hw_flash_crc_test (uint8_t *p_start_addr, uint32_t size_bytes, uint16_t checksum)
uint16_t crc16_hw (uint16_t sum, uint8_t *p, uint32_t len)
int32_t get_initial_sp_addr (void)
Variables
uint16_t __crc16_checksum
Function Documentation
uint16_t crc16_hw (uint16_t sum, uint8_t * p, uint32_t len)
int32_t get_initial_sp_addr (void)
Definition at line 237 of file pac5xxx_flash_test.c.
{
    return 0;
}
int32_t get_reset_flash_crc_test_results (void)
void make_crc16_table (uint16_t * p_crctable)
This function makes a 256 entry 16-bit CRC table on the fly in RAM.
Parameters
p_crctable - pointer to the CRC table
Returns
none
Definition at line 215 of file pac5xxx_flash_test.c.
{
    int32_t value;
    int32_t i;
    int32_t j;
    for(i=0; i < 256; i++)
    {
        value = i << 8;
        for(j=0; j < 8; j++)
        {
           if(value & (1 << 15))
               value = (value << 1)^0x1021;
           else
               value = value << 1;
        }
        p_crctable[i]= value;
    }
}
Referenced by test_flash_crc().
int32_t pac5xxx_fast_flash_crc_test (uint16_t * p_table, uint8_t * p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a fast flash test using a CRC Table.
    The test computes a 16-bit CRC checksum over the contents of the
    flash used by the application. The CRC calculation makes use of
    a 256 entry CRC table to speed up the calculation. If the results
    don't match the checksum parameter passed in, then a 1 is returned.
Parameters
p_table - pointer to the CRC table
p_start_addr - starting address for the CRC calculation
size_bytes - size in bytes of the flash to be tested
checksum - CRC checksum to compare the test results against
Returns
int32_t 0= pass; 1=fail
Definition at line 101 of file pac5xxx_flash_test.c.
{
    uint16_t sum = 0;
    
    sum = crc16_table_256(sum, p_start_addr, size_bytes, p_table);
    if (sum != checksum)
        return 1;
    else
        return 0;
}
References crc16_table_256().
Referenced by test_flash_crc().
int32_t pac5xxx_flash_crc_test (uint8_t * p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a test of the flash using a 16-bit CRC.
    The test computes a 16-bit CRC checksum over the contents of the
    specified memory. If the results don't match the
    checksum parameter passed in, then a 1 is returned.
Parameters
p_start_addr - starting address for the CRC calculation
size_bytes - size in bytes of the flash to be tested
checksum - CRC checksum to compare the test results against
Returns
int32_t 0= pass; 1=fail
Definition at line 64 of file pac5xxx_flash_test.c.
{
    uint16_t sum=0;
    const uint32_t zero=0;
    
    //===== Calculate the CRC using the previous sum and the remainder of the bytes =====
    sum = crc16(sum, p_start_addr, size_bytes);
    //===== Push 16 more bits through to get the final sum =====
    sum = crc16(sum, (uint8_t *)&zero, 2);
    //===== Verify the final CRC against the stored CRC =====
    if (sum != checksum)
        return 1;
    else
        return 0;
}
References crc16().
int32_t pac5xxx_hw_flash_crc_test (uint8_t * p_start_addr, uint32_t size_bytes, uint16_t checksum)
Referenced by test_flash_crc().
void set_reset_flash_crc_test_results (int32_t value)
Variable Documentation
uint16_t __crc16_checksum [extern]
Referenced by test_flash_crc().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.