pac_foc/src/features/flash_crc_test/pac5xxx_flash_test.c
NAME
pac_foc/src/features/flash_crc_test/pac5xxx_flash_test.c
SYNOPSIS
#include 'config_app.h'
#include <stdint.h>
#include 'pac5xxx.h'
#include 'pac5xxx_driver_system.h'
#include 'pac5xxx_driver_memory.h'
#include 'pac5xxx_flash_test.h'
#include 'checksum.h'
Functions
void test_flash_crc (void)
int32_t pac5xxx_flash_crc_test (uint8_t *p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a test of the flash using a 16-bit CRC.
int32_t pac5xxx_fast_flash_crc_test (uint16_t *p_table, uint8_t *p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a fast flash test using a CRC Table.
void make_crc16_table (uint16_t *p_crctable)
This function makes a 256 entry 16-bit CRC table on the fly in RAM.
int32_t get_initial_sp_addr (void)
Function Documentation
int32_t get_initial_sp_addr (void)
Definition at line 237 of file pac5xxx_flash_test.c.
{
    return 0;
}
void make_crc16_table (uint16_t * p_crctable)
This function makes a 256 entry 16-bit CRC table on the fly in RAM.
Parameters
p_crctable - pointer to the CRC table
Returns
none
Definition at line 215 of file pac5xxx_flash_test.c.
{
    int32_t value;
    int32_t i;
    int32_t j;
    for(i=0; i < 256; i++)
    {
        value = i << 8;
        for(j=0; j < 8; j++)
        {
           if(value & (1 << 15))
               value = (value << 1)^0x1021;
           else
               value = value << 1;
        }
        p_crctable[i]= value;
    }
}
Referenced by test_flash_crc().
int32_t pac5xxx_fast_flash_crc_test (uint16_t * p_table, uint8_t * p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a fast flash test using a CRC Table.
    The test computes a 16-bit CRC checksum over the contents of the
    flash used by the application. The CRC calculation makes use of
    a 256 entry CRC table to speed up the calculation. If the results
    don't match the checksum parameter passed in, then a 1 is returned.
Parameters
p_table - pointer to the CRC table
p_start_addr - starting address for the CRC calculation
size_bytes - size in bytes of the flash to be tested
checksum - CRC checksum to compare the test results against
Returns
int32_t 0= pass; 1=fail
Definition at line 101 of file pac5xxx_flash_test.c.
{
    uint16_t sum = 0;
    
    sum = crc16_table_256(sum, p_start_addr, size_bytes, p_table);
    if (sum != checksum)
        return 1;
    else
        return 0;
}
References crc16_table_256().
Referenced by test_flash_crc().
int32_t pac5xxx_flash_crc_test (uint8_t * p_start_addr, uint32_t size_bytes, uint16_t checksum)
This function performs a test of the flash using a 16-bit CRC.
    The test computes a 16-bit CRC checksum over the contents of the
    specified memory. If the results don't match the
    checksum parameter passed in, then a 1 is returned.
Parameters
p_start_addr - starting address for the CRC calculation
size_bytes - size in bytes of the flash to be tested
checksum - CRC checksum to compare the test results against
Returns
int32_t 0= pass; 1=fail
Definition at line 64 of file pac5xxx_flash_test.c.
{
    uint16_t sum=0;
    const uint32_t zero=0;
    
    //===== Calculate the CRC using the previous sum and the remainder of the bytes =====
    sum = crc16(sum, p_start_addr, size_bytes);
    //===== Push 16 more bits through to get the final sum =====
    sum = crc16(sum, (uint8_t *)&zero, 2);
    //===== Verify the final CRC against the stored CRC =====
    if (sum != checksum)
        return 1;
    else
        return 0;
}
References crc16().
void test_flash_crc (void)
Definition at line 23 of file pac5xxx_flash_test.c.
{
    uint32_t ret;
#ifdef FAMILY_55XX
    // Call flash test using HW CRC Module
    ret = pac5xxx_hw_flash_crc_test( (uint8_t *) VECTOR_TABLE_ADDR, // Start Address
                                      (uint32_t) &__crc16_checksum - (uint32_t)VECTOR_TABLE_ADDR, // Size in bytes
                                      __crc16_checksum); // Expected CRC Value
#else
    // Create 16-bit crc16 table in RAM at RAM Base Address, The memory will be reclaimed by the application
    // Note: The stack pointer should be at the top of RAM so there is no conflict
    make_crc16_table(RAM_BASE_ADDRESS_PTR);
    // Call fast flash test using generated RAM table
    ret = pac5xxx_fast_flash_crc_test(RAM_BASE_ADDRESS_PTR, // Pointer to CRC Table
                                      (uint8_t *) VECTOR_TABLE_ADDR, // Start Address
                                      (uint32_t) &__crc16_checksum - (uint32_t)VECTOR_TABLE_ADDR, // Size in bytes
                                      __crc16_checksum); // Expected CRC Value
#endif // FAMILY_55XX
    // Store the results of the Flash CRC Test so the application can handle the CRC Failure
    uart_scratch_write(ret); // CRC Passed-ret=0; CRC Failed-ret=1 (i.e. non zero)
}
References __crc16_checksum, make_crc16_table(), pac5xxx_fast_flash_crc_test(), and pac5xxx_hw_flash_crc_test().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.