pac_foc/src/param/parameter_process.h
NAME
pac_foc/src/param/parameter_process.h - Use for parameter processing.
SYNOPSIS
#include 'param.h'
#include 'config_app.h'
Macros
#define VALUE_CFGAIO0 ((AIO10_MODE << 6) | (AIO0_OPT << 4) | (AIO0_POL << 3) | AIO0_MUX)
#define VALUE_CFGAIO1 ((AIO1_OPT << 4) | (AIO1_POL << 3) | AIO1_MUX)
#define VALUE_CFGAIO2 ((AIO32_MODE << 6) | (AIO2_OPT << 4) | (AIO2_POL << 3) | AIO2_MUX)
#define VALUE_CFGAIO3 ((AIO3_OPT << 4) | (AIO3_POL << 3) | AIO3_MUX)
#define VALUE_CFGAIO4 ((AIO54_MODE << 6) | (AIO4_OPT << 4) | (AIO4_POL << 3) | AIO4_MUX)
#define VALUE_CFGAIO5 ((AIO5_OPT << 4) | (AIO5_POL << 3) | AIO5_MUX)
#define VALUE_CFGAIO6 ((AIO6_MODE << 6) | (AIO6_OPT << 4) | (AIO6_POL << 3) | AIO6_MUX)
#define VALUE_CFGAIO7 ((AIO7_MODE << 6) | (AIO7_OPT << 4) | (AIO7_POL << 3) | AIO7_MUX)
#define VALUE_CFGAIO8 ((AIO8_MODE << 6) | (AIO8_OPT << 4) | (AIO8_POL << 3) | AIO8_MUX)
#define VALUE_CFGAIO9 ((AIO9_MODE << 6) | (AIO9_OPT << 4) | (AIO9_POL << 3) | AIO9_MUX)
Enumerations
enum ParameterCode { buffer = 0, status_motor, fault_warning, current_limit, dt, est_angle_offset, open_loop_align_hold_num_steps, open_loop_speed_slew_rate, open_loop_speed_setpoint, closed_loop_speed_slew_rate, closed_loop_speed_setpoint, id_ref, iq_ref, id_pi_filter_coeff, iq_pi_filter_coeff, id_fdbk, iq_fdbk, Vdc_gui, speed_pid_Kp, speed_pid_Ki, outerloop_pid_min, outerloop_pid_max, Id_pid_Kp, Id_pid_Ki, Id_pid_min, Id_pid_max, Iq_pid_Kp, Iq_pid_Ki, Iq_pid_min, Iq_pid_max, Ld, Lq, Ralpha, num_pole_pairs, Config_Ke, Confi_J, NominalSpeed, estimated_angle, estimated_speed, ideal_angle, measured_speed, motor_current, pwm_dac_selection, debug1, debug2, debug3, debug4, debug5, debug6, scale_factor1, scale_factor2, scale_factor3, debug1_index, debug2_index, debug3_index, debug1_min, debug1_max, debug2_min, debug2_max, debug3_min, debug3_max, id_ref_cl, idiq_ramp_rate, torque_scale, torque_offset, torque_angle_offset, descale_current_factor, est_lock_assist_vq, cl_mode_selection, iq_ref_cl, reverse_direction, cl_outerloop_setpoint_ramp, misc_fix16_1, misc_fix16_2, misc_fix16_3, misc_uint32_1, misc_uint32_2, misc_uint32_3, PWM_to_FOC_control_ratio, diff_amp_gain, Motor_BEMF_const, Stall_Detection_TimeOut, Auto_Mode_Open_Close_Loop, Clear_Fault_Flags, fw_id_sp, fw_vdrive_threshold, fw_speed_threshold_sp, param_read_command, param1, param2, param3, ipd_charge, ipd_discharge, ipd_num_periods_per_pulse, ipd_angle_offset_forward, ipd_angle_offset_reverse, ipd_same_pol_diff, ipd_max_min_diff, ipd_angle, sim_braking_align, sim_braking_ol_id_iq_ref_mul, sim_braking_ol_iq_ref_mul, min_cl_speed_limit, max_cl_speed_limit, sim_braking_timeout, sim_braking_diff_threshold, sim_current_track_gain, sim_bemf_amp_gain, close_loop_coast_timeout, pwm_dac_selection1, pwm_dac_selection2, pwm_dac_selection3, pwm_dac_selection4, scale_factor4, Phase_Rsense, OC_Rsense, Power_pid_Kp, Power_pid_Ki, Power_ramp_rate, Power_setpoint, Power_max_limit, SMO_KpI, SMO_Kangle, SMO_Kslide, SMO_Kslf, SMO_Kspeed, LBG1_Kpe, LBG1_Kpi, LBG1_BandWidth, LBG1_DampingFactor, LBG1_fc_speed, LBG2_KpI, LBG2_KpE, LBG2_Kspeed, angle_correction_offset, angle_correction_factor, firmware_options, calculated_power, Vdc_Rsense_ratio, Vphase_Rsense_ratio, Vdc_max_limit, AutoTune_Kpv, AutoTune_Kiv, ATune_Command, ATune_MID2_Istep, ATune_ATPI_Delta, AutoTune_Status, ATune_MID2_RunMode, AutoTune_Storage_ke_q26, AutoTune_Storage_j_q26, AutoTune_Storage_speed_ka_q16, AutoTune_Storage_speed_kb_q16, AutoTune_Storage_id_ka_q16, AutoTune_Storage_id_kb_q16, AutoTune_Storage_iq_ka_q16, AutoTune_Storage_iq_kb_q16, ATune_MID1_Start, ATune_MID1_RunMode, AutoTune_MID1_Storage_R_q16, AutoTune_MID1_Storage_Ld_q26, AutoTune_MID1_Storage_Lq_q26, ATune_MID1_AlignV1, ATune_MID1_AlignV2, ATune_MID1_Vinj, ATune_MID1_numlimit, ATune_MID1_ManCmd, ATune_MID1_PFactor, Commutation_Mode, HallConfig_Istart, HallConfig_Speed, HallConfig_Gain_Fwd, HallConfig_Gain_Rev, HallConfig_Offset_Fwd, HallConfig_Offset_Rev, HallConfig_Snap_1_Fwd, HallConfig_Snap_1_Rev, HallConfig_Snap_2_Fwd, HallConfig_Snap_2_Rev, HallConfig_Snap_3_Fwd, HallConfig_Snap_3_Rev, HallConfig_Snap_4_Fwd, HallConfig_Snap_4_Rev, HallConfig_Snap_5_Fwd, HallConfig_Snap_5_Rev, HallConfig_Snap_6_Fwd, HallConfig_Snap_6_Rev, HallTuning_Status, HallTuning_Command, HallTuning_Istart, HallTuning_Speed_Ramp, HallTuning_Target_Speed, HallTuning_State_1, HallTuning_Snap_1, HallTuning_State_2, HallTuning_Snap_2, HallTuning_State_3, HallTuning_Snap_3, HallTuning_State_4, HallTuning_Snap_4, HallTuning_State_5, HallTuning_Snap_5, HallTuning_State_6, HallTuning_Snap_6, QEP_Resolution, QEP_Offset_Angle_Fwd, QEP_Offset_Angle_Rev, QEP_Fc, mtpa_gain }
commands enum
Functions
void parameters_write_foc (ParameterCode param_code, fix16_t rx_data, Struct_Motor *motor_ptr)
Use to write FOC parameters as per function code.
void init_default_parameters (Struct_Motor *motor_ptr)
Use to initialize default FOC parameters.
void check_param_while_run (Struct_Motor *motor_ptr)
Use to check motor states before writing parameters, post error if not valid.
void write_itotstart_target (int32_t iref_q16, int32_t *itotref_target_q16, int32_t *itotref_target_1div_q16)
Use to write itotal current.
void init_diff_amp_gain (void)
Use to initialize diff amp.
void init_over_current_limit (uint32_t current_limit)
Use to initialize over current limit.
Detailed Description
Use for parameter processing.
Definition in file parameter_process.h.
Macro Definition Documentation
#define VALUE_CFGAIO0 ((AIO10_MODE << 6) | (AIO0_OPT << 4) | (AIO0_POL << 3) | AIO0_MUX)
Definition at line 27 of file parameter_process.h.
#define VALUE_CFGAIO1 ((AIO1_OPT << 4) | (AIO1_POL << 3) | AIO1_MUX)
Definition at line 28 of file parameter_process.h.
#define VALUE_CFGAIO2 ((AIO32_MODE << 6) | (AIO2_OPT << 4) | (AIO2_POL << 3) | AIO2_MUX)
Definition at line 39 of file parameter_process.h.
#define VALUE_CFGAIO3 ((AIO3_OPT << 4) | (AIO3_POL << 3) | AIO3_MUX)
Definition at line 40 of file parameter_process.h.
#define VALUE_CFGAIO4 ((AIO54_MODE << 6) | (AIO4_OPT << 4) | (AIO4_POL << 3) | AIO4_MUX)
Definition at line 51 of file parameter_process.h.
#define VALUE_CFGAIO5 ((AIO5_OPT << 4) | (AIO5_POL << 3) | AIO5_MUX)
Definition at line 52 of file parameter_process.h.
#define VALUE_CFGAIO6 ((AIO6_MODE << 6) | (AIO6_OPT << 4) | (AIO6_POL << 3) | AIO6_MUX)
Definition at line 64 of file parameter_process.h.
#define VALUE_CFGAIO7 ((AIO7_MODE << 6) | (AIO7_OPT << 4) | (AIO7_POL << 3) | AIO7_MUX)
Definition at line 70 of file parameter_process.h.
#define VALUE_CFGAIO8 ((AIO8_MODE << 6) | (AIO8_OPT << 4) | (AIO8_POL << 3) | AIO8_MUX)
Definition at line 76 of file parameter_process.h.
#define VALUE_CFGAIO9 ((AIO9_MODE << 6) | (AIO9_OPT << 4) | (AIO9_POL << 3) | AIO9_MUX)
Definition at line 82 of file parameter_process.h.
Enumeration Type Documentation
enum ParameterCode
commands enum
Enumerator
buffer
status_motor
fault_warning
current_limit
dt
est_angle_offset
open_loop_align_hold_num_steps
open_loop_speed_slew_rate
open_loop_speed_setpoint
closed_loop_speed_slew_rate
closed_loop_speed_setpoint
id_ref
iq_ref
id_pi_filter_coeff
iq_pi_filter_coeff
id_fdbk
iq_fdbk
Vdc_gui
speed_pid_Kp
speed_pid_Ki
outerloop_pid_min
outerloop_pid_max
Id_pid_Kp
Id_pid_Ki
Id_pid_min
Id_pid_max
Iq_pid_Kp
Iq_pid_Ki
Iq_pid_min
Iq_pid_max
Ld
Lq
Ralpha
num_pole_pairs
Config_Ke
Confi_J
NominalSpeed
estimated_angle
estimated_speed
ideal_angle
measured_speed
motor_current
pwm_dac_selection
debug1
debug2
debug3
debug4
debug5
debug6
scale_factor1
scale_factor2
scale_factor3
debug1_index
debug2_index
debug3_index
debug1_min
debug1_max
debug2_min
debug2_max
debug3_min
debug3_max
id_ref_cl
idiq_ramp_rate
torque_scale
torque_offset
torque_angle_offset
descale_current_factor
est_lock_assist_vq
cl_mode_selection
iq_ref_cl
reverse_direction
cl_outerloop_setpoint_ramp
misc_fix16_1
misc_fix16_2
misc_fix16_3
misc_uint32_1
misc_uint32_2
misc_uint32_3
PWM_to_FOC_control_ratio
diff_amp_gain
Motor_BEMF_const
Stall_Detection_TimeOut
Auto_Mode_Open_Close_Loop
Clear_Fault_Flags
fw_id_sp
fw_vdrive_threshold
fw_speed_threshold_sp
param_read_command
param1
param2
param3
ipd_charge
ipd_discharge
ipd_num_periods_per_pulse
ipd_angle_offset_forward
ipd_angle_offset_reverse
ipd_same_pol_diff
ipd_max_min_diff
ipd_angle
sim_braking_align
sim_braking_ol_id_iq_ref_mul
sim_braking_ol_iq_ref_mul
min_cl_speed_limit
max_cl_speed_limit
sim_braking_timeout
sim_braking_diff_threshold
sim_current_track_gain
sim_bemf_amp_gain
close_loop_coast_timeout
pwm_dac_selection1
pwm_dac_selection2
pwm_dac_selection3
pwm_dac_selection4
scale_factor4
Phase_Rsense
OC_Rsense
Power_pid_Kp
Power_pid_Ki
Power_ramp_rate
Power_setpoint
Power_max_limit
SMO_KpI
SMO_Kangle
SMO_Kslide
SMO_Kslf
SMO_Kspeed
LBG1_Kpe
LBG1_Kpi
LBG1_BandWidth
LBG1_DampingFactor
LBG1_fc_speed
LBG2_KpI
LBG2_KpE
LBG2_Kspeed
angle_correction_offset
angle_correction_factor
firmware_options
calculated_power
Vdc_Rsense_ratio
Vphase_Rsense_ratio
Vdc_max_limit
AutoTune_Kpv
AutoTune_Kiv
ATune_Command
ATune_MID2_Istep
ATune_ATPI_Delta
AutoTune_Status
ATune_MID2_RunMode
AutoTune_Storage_ke_q26
AutoTune_Storage_j_q26
AutoTune_Storage_speed_ka_q16
AutoTune_Storage_speed_kb_q16
AutoTune_Storage_id_ka_q16
AutoTune_Storage_id_kb_q16
AutoTune_Storage_iq_ka_q16
AutoTune_Storage_iq_kb_q16
ATune_MID1_Start
ATune_MID1_RunMode
AutoTune_MID1_Storage_R_q16
AutoTune_MID1_Storage_Ld_q26
AutoTune_MID1_Storage_Lq_q26
ATune_MID1_AlignV1
ATune_MID1_AlignV2
ATune_MID1_Vinj
ATune_MID1_numlimit
ATune_MID1_ManCmd
ATune_MID1_PFactor
Commutation_Mode
HallConfig_Istart
HallConfig_Speed
HallConfig_Gain_Fwd
HallConfig_Gain_Rev
HallConfig_Offset_Fwd
HallConfig_Offset_Rev
HallConfig_Snap_1_Fwd
HallConfig_Snap_1_Rev
HallConfig_Snap_2_Fwd
HallConfig_Snap_2_Rev
HallConfig_Snap_3_Fwd
HallConfig_Snap_3_Rev
HallConfig_Snap_4_Fwd
HallConfig_Snap_4_Rev
HallConfig_Snap_5_Fwd
HallConfig_Snap_5_Rev
HallConfig_Snap_6_Fwd
HallConfig_Snap_6_Rev
HallTuning_Status
HallTuning_Command
HallTuning_Istart
HallTuning_Speed_Ramp
HallTuning_Target_Speed
HallTuning_State_1
HallTuning_Snap_1
HallTuning_State_2
HallTuning_Snap_2
HallTuning_State_3
HallTuning_Snap_3
HallTuning_State_4
HallTuning_Snap_4
HallTuning_State_5
HallTuning_Snap_5
HallTuning_State_6
HallTuning_Snap_6
QEP_Resolution
QEP_Offset_Angle_Fwd
QEP_Offset_Angle_Rev
QEP_Fc
mtpa_gain
Definition at line 91 of file parameter_process.h.
{
    buffer = 0,
    status_motor,
    fault_warning,
    current_limit,
    dt,
    est_angle_offset,
    open_loop_align_hold_num_steps,
    open_loop_speed_slew_rate,
    open_loop_speed_setpoint,
    closed_loop_speed_slew_rate,
    closed_loop_speed_setpoint,
    id_ref,
    iq_ref,
    id_pi_filter_coeff,
    iq_pi_filter_coeff,
    id_fdbk,
    iq_fdbk,
    Vdc_gui,
    speed_pid_Kp,
    speed_pid_Ki,
    outerloop_pid_min,
    outerloop_pid_max,
    Id_pid_Kp,
    Id_pid_Ki,
    Id_pid_min,
    Id_pid_max,
    Iq_pid_Kp,
    Iq_pid_Ki,
    Iq_pid_min,
    Iq_pid_max,
    // Motor Configuration
    Ld,
    Lq,
    Ralpha,
    num_pole_pairs,
    Config_Ke,
    Confi_J,
    NominalSpeed,
    // Plot variables
    estimated_angle,
    estimated_speed,
    ideal_angle,
    measured_speed,
    motor_current,
    pwm_dac_selection,
    debug1,
    debug2,
    debug3,
    debug4,
    debug5,
    debug6,
    scale_factor1,
    scale_factor2,
    scale_factor3,
    debug1_index,
    debug2_index,
    debug3_index,
    debug1_min,
    debug1_max,
    debug2_min,
    debug2_max,
    debug3_min,
    debug3_max,
    id_ref_cl,
    idiq_ramp_rate,
    torque_scale,
    torque_offset,
    torque_angle_offset,
    descale_current_factor,
    est_lock_assist_vq,
    cl_mode_selection,
    iq_ref_cl,
    reverse_direction,
    cl_outerloop_setpoint_ramp,
    misc_fix16_1,
    misc_fix16_2,
    misc_fix16_3,
    misc_uint32_1,
    misc_uint32_2,
    misc_uint32_3,
    PWM_to_FOC_control_ratio,
    diff_amp_gain,
    Motor_BEMF_const,
    Stall_Detection_TimeOut,
    Auto_Mode_Open_Close_Loop,
    Clear_Fault_Flags,
    fw_id_sp,
    fw_vdrive_threshold,
    fw_speed_threshold_sp,
    param_read_command,
    param1,
    param2,
    param3,
    ipd_charge,
    ipd_discharge,
    ipd_num_periods_per_pulse,
    ipd_angle_offset_forward,
    ipd_angle_offset_reverse,
    ipd_same_pol_diff,
    ipd_max_min_diff,
    ipd_angle,
    sim_braking_align,
    sim_braking_ol_id_iq_ref_mul,
    sim_braking_ol_iq_ref_mul,
    min_cl_speed_limit, // JAGTAG: Consider eliminating min_cl_speed_limit parameter
    max_cl_speed_limit,
    sim_braking_timeout,
    sim_braking_diff_threshold,
    sim_current_track_gain,
    sim_bemf_amp_gain,
    close_loop_coast_timeout,
    pwm_dac_selection1,
    pwm_dac_selection2,
    pwm_dac_selection3,
    pwm_dac_selection4,
    scale_factor4,
    Phase_Rsense,
    OC_Rsense,
    Power_pid_Kp,
    Power_pid_Ki,
    Power_ramp_rate,
    Power_setpoint,
    Power_max_limit,
    SMO_KpI,
    SMO_Kangle,
    SMO_Kslide,
    SMO_Kslf,
    SMO_Kspeed,
    LBG1_Kpe,
    LBG1_Kpi,
    LBG1_BandWidth,
    LBG1_DampingFactor,
    LBG1_fc_speed,
    // JAGTAG: References to LBG2 need to be removed
    LBG2_KpI,
    LBG2_KpE,
    LBG2_Kspeed,
    angle_correction_offset,
    angle_correction_factor,
    firmware_options,
    calculated_power,
    Vdc_Rsense_ratio,
    Vphase_Rsense_ratio,
    Vdc_max_limit,
    // Auto Tune
    AutoTune_Kpv,
    AutoTune_Kiv,
    ATune_Command,
    ATune_MID2_Istep,
    ATune_ATPI_Delta,
    AutoTune_Status,
    ATune_MID2_RunMode,
    // Read AutoTune storage variables
    AutoTune_Storage_ke_q26,
    AutoTune_Storage_j_q26,
    AutoTune_Storage_speed_ka_q16,
    AutoTune_Storage_speed_kb_q16,
    AutoTune_Storage_id_ka_q16,
    AutoTune_Storage_id_kb_q16,
    AutoTune_Storage_iq_ka_q16,
    AutoTune_Storage_iq_kb_q16,
    // Read and write AutoTune storage variables and command for MID1
    ATune_MID1_Start,
    ATune_MID1_RunMode,
    AutoTune_MID1_Storage_R_q16,
    AutoTune_MID1_Storage_Ld_q26,
    AutoTune_MID1_Storage_Lq_q26,
    ATune_MID1_AlignV1,
    ATune_MID1_AlignV2,
    ATune_MID1_Vinj,
    ATune_MID1_numlimit,
    ATune_MID1_ManCmd,
    ATune_MID1_PFactor,
    // Commutation Mode
    Commutation_Mode,
    // Hall Sensor Configuration
    HallConfig_Istart,
    HallConfig_Speed,
    HallConfig_Gain_Fwd,
    HallConfig_Gain_Rev,
    HallConfig_Offset_Fwd,
    HallConfig_Offset_Rev,
    HallConfig_Snap_1_Fwd,
    HallConfig_Snap_1_Rev,
    HallConfig_Snap_2_Fwd,
    HallConfig_Snap_2_Rev,
    HallConfig_Snap_3_Fwd,
    HallConfig_Snap_3_Rev,
    HallConfig_Snap_4_Fwd,
    HallConfig_Snap_4_Rev,
    HallConfig_Snap_5_Fwd,
    HallConfig_Snap_5_Rev,
    HallConfig_Snap_6_Fwd,
    HallConfig_Snap_6_Rev,
    // Hall Tuning Configuration
    HallTuning_Status,
    HallTuning_Command,
    HallTuning_Istart,
    HallTuning_Speed_Ramp,
    HallTuning_Target_Speed,
    HallTuning_State_1,
    HallTuning_Snap_1,
    HallTuning_State_2,
    HallTuning_Snap_2,
    HallTuning_State_3,
    HallTuning_Snap_3,
    HallTuning_State_4,
    HallTuning_Snap_4,
    HallTuning_State_5,
    HallTuning_Snap_5,
    HallTuning_State_6,
    HallTuning_Snap_6,
    // QEP
    QEP_Resolution,
    QEP_Offset_Angle_Fwd,
    QEP_Offset_Angle_Rev,
    QEP_Fc,
    // MTPA
    mtpa_gain,
}ParameterCode;
Function Documentation
void check_param_while_run (Struct_Motor * motor_ptr)
Use to check motor states before writing parameters, post error if not valid.
Parameters
Struct_Motor* motor_ptr
Definition at line 598 of file parameter_process.c.
{
    if ((motor_ptr->state.main != STATE_MAIN_STOPPED) &&
            (motor_ptr->state.main != STATE_MAIN_RESET) &&
            (motor_ptr->state.main != STATE_MAIN_POST))
    {
        set_fault(FAULT_PARAM_WHILE_RUN);
    }
}
References FAULT_PARAM_WHILE_RUN, Struct_State::main, set_fault(), Struct_Motor::state, STATE_MAIN_POST, STATE_MAIN_RESET, and STATE_MAIN_STOPPED.
Referenced by parameters_write_foc().
void init_default_parameters (Struct_Motor * motor_ptr)
Use to initialize default FOC parameters.
Parameters
Struct_Motor* motor_ptr
Definition at line 212 of file parameter_process.c.
{
    uint32_t count, array_total_elements;
    array_total_elements = (sizeof(motor_parameters)/sizeof(motor_parameters[0]));
    for (count = 0; count < array_total_elements; count++)
    {
        parameters_write_foc(motor_parameters[count].enum_value, motor_parameters[count].value, motor_ptr);
    }
}
References motor_parameters, and parameters_write_foc().
Referenced by statemachine_appmain().
void init_diff_amp_gain (void)
Use to initialize diff amp.
void init_over_current_limit (uint32_t current_limit)
Use to initialize over current limit.
Parameters
uint32_t current_limit
Definition at line 617 of file parameter_process.c.
{
    Struct_Motor* motor_ptr = &motor;
    char lpdac_factor = 1;
    uint32_t lpdac_value = 0x00;
    lpdac_value = current_limit;
    switch (motor_ptr->app.iphase_amp_gain)
    {
        case 0:
            lpdac_factor = 1;
            break;
        case 1:
            lpdac_factor = 1;
            break;
        case 2:
            lpdac_factor = 2;
            break;
        case 3:
            lpdac_factor = 4;
            break;
        case 4:
            lpdac_factor = 8;
            break;
        case 5:
            lpdac_factor = 16;
            break;
        case 6:
            lpdac_factor = 32;
            break;
        case 7:
            lpdac_factor = 48;
            break;
        default:
            lpdac_factor = 1;
            break;
    }
    // Calculate current descale factor
    motor_ptr->app.descale_current_factor = fix16_div(CURRENT_SCALE_FACTOR_X1_Q16, (lpdac_factor << 16));
    // Set LPROT protection threshold
     // Handle LPDAC value calculation overflow
     if (lpdac_value > 0x3FF)
     {
         lpdac_value = 0x3FF;
         set_warning(WARNING_MAIN_OC_VALUE);
     }
     else
     {
         clear_warning(WARNING_MAIN_OC_VALUE);
     }
#ifdef CAFE_ARCH1
    pac5xxx_tile_register_write(ADDR_LPDAC0, (uint8_t)((lpdac_value >> 2) & 0xFF)); // HB: 8b MSB
    pac5xxx_tile_register_write(ADDR_LPDAC1, (uint8_t)((lpdac_value & 0x3))); // LB: 2b LSB
#endif
#ifdef CAFE_ARCH2
    pac5xxx_tile_register_write(ADDR_LPDACH, (uint8_t)((lpdac_value >> 2) & 0xFF)); // HB: 8b MSB
    pac5xxx_tile_register_write(ADDR_LPDACL, (uint8_t)((lpdac_value & 0x3))); // LB: 2b LSB
#endif
         
#ifdef CAFE_ARCH3
     if ((current_limit >> 6) > 15)
             lpdac_value = 15;
         else if ((current_limit >> 6) < 1)
                lpdac_value = 1;
         else
                lpdac_value = current_limit >> 6;
         pac5xxx_tile_register_write(ADDR_LPDACH, (uint8_t)(lpdac_value & 0x0F)); // 4bits scale from 10 bits
#endif
#ifdef CAFE_ARCH1
#ifdef ENABLE_CBC_CURRENT_LIMIT
    uint32_t hpdac_value = 0;
    // divide subtract 512 for current limit then des-scale it to fix16, divide it the amp gain in fix16,
    // scale it back divide it by 4 to fit for hpdac
    hpdac_value = (fix16_mul(fix16_div(((lpdac_value - 512) << 16), (fix16_t) (lpdac_factor << 16)), (fix16_t) (QCONST(HPDAC_OC_LIMIT_MULTIPLIER, 16))) >> 16) >> 2;
    if (hpdac_value > 255)
    {
        hpdac_value = 255;
        set_warning(WARNING_MAIN_OC_VALUE);
    }
    else
    {
        clear_warning(WARNING_MAIN_OC_VALUE);
    }
        pac5xxx_tile_register_write(ADDR_HPDAC, hpdac_value);
    #endif
#endif
#ifdef CAFE_ARCH2
    #ifdef ENABLE_CBC_CURRENT_LIMIT
        uint32_t hpdac_value = 0;
#if defined(PAC5532) || defined(PAC5232)
        hpdac_value = (fix16_mul((fix16_t) ((lpdac_value - 512) << 16), (fix16_t) (QCONST(HPDAC_OC_LIMIT_MULTIPLIER, 16))) >> 16);
        hpdac_value = hpdac_value + 512;
#else
        // Pre diff amp signal use for hpdac
        hpdac_value = (fix16_mul(fix16_div(((lpdac_value - 512) << 16), (fix16_t) (lpdac_factor << 16)), (fix16_t) (QCONST(HPDAC_OC_LIMIT_MULTIPLIER, 16))) >> 16);
#endif
#if (BOARD_SELECT == BOARD_PAC5256EVK1_REV_AB) || (BOARD_SELECT == BOARD_PAC5256EVK1_REV_AB_1SHUNT)
        hpdac_value = (fix16_mul((fix16_t) ((lpdac_value - 512) << 16), (fix16_t) (QCONST(HPDAC_OC_LIMIT_MULTIPLIER, 16))) >> 16);
        hpdac_value = hpdac_value + 512;
#endif
        if (hpdac_value > 1023)
        {
            hpdac_value = 1023;
            set_warning(WARNING_MAIN_OC_VALUE);
        }
        else
        {
            clear_warning(WARNING_MAIN_OC_VALUE);
        }
        pac5xxx_tile_register_write(ADDR_HPDACH, (uint8_t)((hpdac_value >> 2) & 0xFF)); // HB: 8b MSB
        pac5xxx_tile_register_write(ADDR_HPDACL, (uint8_t)((hpdac_value & 0x3))); // LB: 2b LSB
    #endif
#endif
}
References Struct_Motor::app, clear_warning(), current_limit, CURRENT_SCALE_FACTOR_X1_Q16, Struct_App::descale_current_factor, fix16_div(), fix16_mul(), Struct_App::iphase_amp_gain, motor, QCONST, set_warning(), and WARNING_MAIN_OC_VALUE.
Referenced by parameters_write_foc().
void parameters_write_foc (ParameterCode param_code, fix16_t rx_data, Struct_Motor * motor_ptr)
Use to write FOC parameters as per function code.
Parameters
ParameterCode param_code
fix16_t rx_data
Struct_Motor* motor_ptr
Definition at line 225 of file parameter_process.c.
{
// int32_t temp;
#if defined(ENABLE_AUTOTUNE_PI)
    atpi_paramchange_check(motor_ptr, param_code, rx_data);
#endif
    switch (param_code)
    {
// Motor Config
        case current_limit:
            motor_ptr->app.current_limit = rx_data;
            init_over_current_limit(motor_ptr->app.current_limit);
            break;
        case dt:
            check_param_while_run(motor_ptr);
            motor_ptr->foc.dt_control_q26 = rx_data;
            // Calculate PWM timer period ticks
            foc_calc_pwmtimer(motor_ptr);
            // Configure control loop for FOC mode
            foc_config(motor_ptr);
            // Update PI dt's
            motor_ptr->control.outerloop_pid.dt_q26 = fix16_mul(rx_data, fix16_from_int(SPEED_PI_LOOP_DIVIDER));
            picon_convert_gain(&motor_ptr->control.outerloop_pid, (motor_ptr->app.outerloop_scale_q0 << 16), motor_ptr->app.descale_current_factor);
            motor_ptr->foc.Id_pid.dt_q26 = rx_data;
            motor_ptr->foc.Iq_pid.dt_q26 = rx_data;
#if (COMMSEL_PPM == TRUE)
            // Convert into ADC ISR ticks count
            motor_ptr->ppm.pulse_timeout_in_sys_tick_isr_counts = (fix16_div((PPM_PULSE_VALID_CHECK_IN_SEC_FIX16), DT_SYSTICK_Q16)) >> 16;
            motor_ptr->ppm.motor_off_timeout_in_pulse_timeout_counts = (fix16_div((PPM_MOTOR_OFF_TIMEOUT_IN_SEC_FIX16), DT_SYSTICK_Q16)) >> 16;
            motor_ptr->ppm.motor_off_timeout_in_pulse_timeout_counts = (motor_ptr->ppm.motor_off_timeout_in_pulse_timeout_counts/motor_ptr->ppm.pulse_timeout_in_sys_tick_isr_counts);
#endif
#if defined(ENABLE_POWERMEASURE)
            power_calc_filter_alpha(motor_ptr, POWER_FILTER_FREQ_CUTOFF_HZ_Q16);
#endif
#if (INTERNAL_VMS == TRUE)
#if (CONFIG_SHUNT == CONFIG_SHUNT_3SHUNT)
            motor_ptr->u_duty_cycle_max_limit = (motor_ptr->control.motor_period_ticks * VMS_VALUE_EXCLUDE_BAND_LIMIT_3SHUNT) >> 16;
#endif
#endif
            break;
        case descale_current_factor:
            break;
        case diff_amp_gain:
            check_param_while_run(motor_ptr);
            if (motor_ptr->app.iphase_amp_gain != rx_data)
            {
#if defined(CAFE_ARCH3) && (DEVICE_SELECT == DEVICE_5285)
                motor_ptr->app.iphase_amp_gain = UVW_PHASE_RSENSE_GAIN_DEFAULT_VALUE_5285;
#else
                motor_ptr->app.iphase_amp_gain = rx_data;
#endif
                init_diff_amp_gain();
                init_over_current_limit(motor_ptr->app.current_limit);
#ifdef ENABLE_ADCCAL
                __disable_irq();
                motor_ptr->state.main = STATE_MAIN_POST;
                motor_ptr->state.post = STATE_POST_RESET;
                __enable_irq();
#endif
            }
#if defined(ENABLE_POWERMEASURE) && (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_1)
            power1_calc_param(motor_ptr);
#endif
            break;
        case cl_mode_selection:
            motor_ptr->app.speed_mode_flag = rx_data;
            break;
        case reverse_direction:
#ifndef ENABLE_NEGATIVE_IQ_COASTING
            check_param_while_run(motor_ptr);
#endif
            motor_ptr->app.direction_reverse_cmd = rx_data;
            break;
// Misc
         case Vdc_gui:
             break;
// Id & Iq
         case id_pi_filter_coeff:
             motor_ptr->foc.Id_filter_gain = rx_data;
             break;
         case iq_pi_filter_coeff:
             motor_ptr->foc.Iq_filter_gain = rx_data;
             break;
         case idiq_ramp_rate:
             motor_ptr->control.idiqref_rate_f16 = (rx_data);
             if (motor_ptr->control.idiqref_rate_f16 == 0)
                 motor_ptr->control.idiqref_rate_f16 = 1;
#ifdef ENABLE_NEGATIVE_IQ_COASTING
             motor_ptr->idiqref_rate_gui_f16 = motor_ptr->control.idiqref_rate_f16;
#endif
             break;
// Closed Loop
         case closed_loop_speed_slew_rate:
#if (OUTERLOOP_CONTROL_SELECT == OUTERLOOP_CONTROL_SPEED)
             motor_ptr->control.outerloop_rate_store = rx_data;
             motor_ptr->control.outerloop_rate = (motor_ptr->control.outerloop_rate_store * SPEED_PI_LOOP_DIVIDER) ; // Descaled f16
#endif
             break;
         case closed_loop_speed_setpoint:
#if (OUTERLOOP_CONTROL_SELECT == OUTERLOOP_CONTROL_SPEED)
             motor_ptr->control.outerloop_target = rx_data;
#endif
#ifdef ENABLE_CLSPEED_LIMIT_CHANGE_CHECK
             motor_ptr->debug.cl_speed_backup = rx_data;
#endif
             break;
         case id_ref_cl:
             motor_ptr->app.idrefcl_cmd_f16 = rx_data;
             motor_ptr->control.idrefcl_target_f16 = rx_data;
             break;
         case iq_ref_cl:
             motor_ptr->app.iqrefcl_cmd_f16 = rx_data;
#ifdef ENABLE_AUTOTUNE_REGULATE_IQREF
             if ((!motor_ptr->atune.flag_iqref_reg_active) || (motor_ptr->atune.flag_iqref_reg_active && (rx_data >= motor_ptr->control.iqrefcl_target_f16)))
             {
                 motor_ptr->control.iqrefcl_target_f16 = rx_data;
             }
#else
             motor_ptr->control.iqrefcl_target_f16 = rx_data;
#endif
             break;
         case max_cl_speed_limit:
             motor_ptr->app.speedrefcl_max = rx_data;
             calculate_outerloop_scale_shift(motor_ptr->app.speedrefcl_max, &motor_ptr->app.speed_scale_shift, &motor_ptr->app.outerloop_scale_q0);
#if (OUTERLOOP_CONTROL_SELECT == OUTERLOOP_CONTROL_SPEED)
             motor_ptr->control.outerloop_pi_scale_shift = motor_ptr->app.speed_scale_shift;
#endif
             break;
// Speed PID
#if (OUTERLOOP_CONTROL_SELECT == OUTERLOOP_CONTROL_SPEED)
         case speed_pid_Kp:
             motor_ptr->control.outerloop_pid.ka_q16 = rx_data;
             picon_convert_gain(&motor_ptr->control.outerloop_pid, (motor_ptr->app.outerloop_scale_q0 << 16), motor_ptr->app.descale_current_factor);
             break;
         case speed_pid_Ki:
             motor_ptr->control.outerloop_pid.kb_q16 = rx_data;
             picon_convert_gain(&motor_ptr->control.outerloop_pid, (motor_ptr->app.outerloop_scale_q0 << 16), motor_ptr->app.descale_current_factor);
             break;
#endif
         case outerloop_pid_min:
             motor_ptr->control.outerloop_pid.min_value = (rx_data >> 2);
             break;
         case outerloop_pid_max:
             motor_ptr->control.outerloop_pid.max_value = (rx_data >> 2);
             motor_ptr->control.imax_q16 = rx_data;
             motor_ptr->control.imax_1div_q16 = fix16_div(FIX16_ONE, motor_ptr->control.imax_q16);
             break;
// Id PID
         case Id_pid_Kp:
             motor_ptr->foc.Id_pid.ka_q16 = rx_data;
             break;
         case Id_pid_Ki:
             motor_ptr->foc.Id_pid.kb_q16 = rx_data;
             break;
         case Id_pid_min:
             motor_ptr->foc.Id_pid.min_value = (rx_data >> 2);
             break;
         case Id_pid_max:
             motor_ptr->foc.Id_pid.max_value = (rx_data >> 2);
             break;
// Iq PID
         case Iq_pid_Kp:
             motor_ptr->foc.Iq_pid.ka_q16 = rx_data;
             break;
         case Iq_pid_Ki:
             motor_ptr->foc.Iq_pid.kb_q16 = rx_data;
             break;
         case Iq_pid_min:
             motor_ptr->foc.Iq_pid.min_value = (rx_data >> 2);
             break;
         case Iq_pid_max:
             motor_ptr->foc.Iq_pid.max_value = (rx_data >> 2);
             break;
// Motor
         case Ld:
             motor_ptr->mparam.ld_q26 = rx_data;
             break;
         case Lq:
             motor_ptr->mparam.lq_q26 = rx_data;
             break;
         case Ralpha:
             motor_ptr->mparam.rs_q16 = rx_data;
             break;
         case num_pole_pairs:
             motor_ptr->mparam.pole_pairs = rx_data;
             break;
         case Config_Ke:
             motor_ptr->mparam.ke_q26 = rx_data;
             break;
         case Confi_J:
             motor_ptr->mparam.j_q26 = rx_data;
             break;
         case NominalSpeed:
             motor_ptr->mparam.nom_spd_q16 = rx_data;
             break;
         case PWM_to_FOC_control_ratio:
             check_param_while_run(motor_ptr);
             motor_ptr->foc.ctrl_divider_foc = rx_data;
             // Calculate PWM timer period ticks
             foc_calc_pwmtimer(motor_ptr);
             // Configure control loop for FOC mode
             foc_config(motor_ptr);
             break;
         case Auto_Mode_Open_Close_Loop:
             if (rx_data)
             {
                 motor_ptr->app.auto_close_loop_cmd = 1;
             }
             else
             {
                 motor_ptr->app.auto_close_loop_cmd = 0;
             }
             break;
         case Clear_Fault_Flags:
             clear_fault(FAULT_MAIN_GRP_CLEARCMD);
             break;
#ifdef ENABLE_IPD
         case ipd_charge:
             // Load new pwm_charge_ticks from rx_data; calculate new parameters
             motor_ptr->ipd.pwm_charge_ticks = rx_data;
             if (motor_ptr->ipd.pwm_charge_ticks <= IPD_ADC_TRIGGER_OFFSET_TICKS*motor_ptr->ipd.num_periods_per_pulse)
             {
                 motor_ptr->ipd.pwm_charge_ticks = (IPD_ADC_TRIGGER_OFFSET_TICKS+1)*motor_ptr->ipd.num_periods_per_pulse;
             }
             break;
         case ipd_discharge:
             // Load new pwm_discharge_percent from rx_data; calculate new parameters
             motor_ptr->ipd.pwm_discharge_percent = rx_data;
             break;
         case ipd_num_periods_per_pulse:
             motor_ptr->ipd.num_periods_per_pulse = rx_data;
             if (motor_ptr->ipd.pwm_charge_ticks <= IPD_ADC_TRIGGER_OFFSET_TICKS*motor_ptr->ipd.num_periods_per_pulse)
             {
                 motor_ptr->ipd.pwm_charge_ticks = (IPD_ADC_TRIGGER_OFFSET_TICKS+1)*motor_ptr->ipd.num_periods_per_pulse;
             }
             break;
         case ipd_angle_offset_forward:
             motor_ptr->ipd.ipd_angle_forward_offset = rx_data;
             break;
         case ipd_angle_offset_reverse:
             motor_ptr->ipd.ipd_angle_reverse_offset = rx_data;
             break;
#endif
         case close_loop_coast_timeout:
             motor_ptr->app.coast_timeout_target = rx_data;
             break;
#if (OUTERLOOP_CONTROL_SELECT == OUTERLOOP_CONTROL_POWER)
         case Power_pid_Kp:
             motor_ptr->control.outerloop_pid.ka_q16 = rx_data;
             picon_convert_gain(&motor_ptr->control.outerloop_pid, (motor_ptr->app.outerloop_scale_q0 << 16), motor_ptr->app.descale_current_factor);
             break;
         case Power_pid_Ki:
             motor_ptr->control.outerloop_pid.kb_q16 = rx_data;
             picon_convert_gain(&motor_ptr->control.outerloop_pid, (motor_ptr->app.outerloop_scale_q0 << 16), motor_ptr->app.descale_current_factor);
             break;
         case Power_ramp_rate:
             motor_ptr->control.outerloop_rate_store = rx_data;
             motor_ptr->control.outerloop_rate = (motor_ptr->control.outerloop_rate_store * SPEED_PI_LOOP_DIVIDER) ; // Descaled f16
             break;
         case Power_setpoint:
             motor_ptr->control.outerloop_target = rx_data;
             break;
         case Power_max_limit:
             motor_ptr->app.powerrefcl_max = rx_data;
             calculate_outerloop_scale_shift(motor_ptr->app.powerrefcl_max, &motor_ptr->control.outerloop_pi_scale_shift, &motor_ptr->app.outerloop_scale_q0);
             break;
#endif
        default:
            break;
    }
    // Parameter Write Functions Calls
#ifdef ENABLE_STALL_DETECT
    stalldet_param_write(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_ALIGNGO == ENABLED) && !defined(ENABLE_HALL_TUNING)
    aligngo_param_write(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_LBG1 == ENABLED)
    lbg1_param_write(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_AUTOTUNE_PI)
    at_param_write(motor_ptr, param_code, rx_data);
#endif
#ifdef ENABLE_SIM
    sim_param_write(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_HALL == ENABLED)
    hall_param_write(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_HALL_TUNING)
    halltune_param_write(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_QEP == ENABLED)
    qep_param_write(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_FIELD_WEAKENING)
    fw_param_write(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_MTPA)
    mtpa_param_write(motor_ptr, param_code, rx_data);
#endif
    // Parameter Process Functions Calls
    // Application parameter process function always needs to run first
    app_param_process(motor_ptr, param_code, rx_data);
#ifdef ENABLE_OPD_CL
    opdcl_param_process(motor_ptr, param_code, rx_data);
#endif
#ifdef ENABLE_STALL_DETECT
    stalldet_param_process(motor_ptr, param_code, rx_data);
#endif
#ifdef ENABLE_SIM
    sim_param_process(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_LBG1 == ENABLED)
    lbg1_param_process(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_AUTOTUNE_PI)
    at_param_process(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_HALL == ENABLED)
    hall_param_process(motor_ptr, param_code, rx_data);
#endif
#if (MODULE_MPOS_QEP == ENABLED)
    qep_param_process(motor_ptr, param_code, rx_data);
#endif
#if defined(ENABLE_FIELD_WEAKENING)
    fw_param_process(motor_ptr, param_code, rx_data);
#endif
}
References Struct_Motor::app, check_param_while_run(), Struct_Motor::control, Struct_App::current_limit, current_limit, dt, Struct_FOC::dt_control_q26, PID_Data_Type::dt_q26, fix16_mul(), Struct_Motor::foc, foc_calc_pwmtimer(), foc_config(), init_over_current_limit(), and Struct_Control::outerloop_pid.
Referenced by init_default_parameters().
void write_itotstart_target (int32_t iref_q16, int32_t * itotref_target_q16, int32_t * itotref_target_1div_q16)
Use to write itotal current.
Parameters
int32_t iref_q16
int32_t *itotref_target_q16
int32_t *itotref_target_1div_q16
Definition at line 609 of file parameter_process.c.
{
    // Copy startup itotal and calculate one over itotal
    *itotref_target_q16 = iref_q16;
    *itotref_target_1div_q16 = fix16_div(FIX16_ONE, iref_q16);
}
References fix16_div(), and FIX16_ONE.
Referenced by aligngo_param_write().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.