pac_foc/src/math/pid.c
NAME
pac_foc/src/math/pid.c - PID functions.
SYNOPSIS
#include 'pid.h'
#include 'fault.h'
Functions
void pid_reset (PID_Data_Type *pid_data)
Initializes the PID controller data.
void picon_convert_gain (PID_Data_Type *pid_data, uint32_t scale_in_q16, int32_t scale_out_q16)
Convert gain to PID data.
Detailed Description
PID functions.
Definition in file pid.c.
Function Documentation
void picon_convert_gain (PID_Data_Type * pid_data, uint32_t scale_in_q16, int32_t scale_out_q16)
Convert gain to PID data.
Parameters
pid_data pointer to PID data structure
scale_in_q16 input scale
scale_out_q16 output scale
Definition at line 41 of file pid.c.
{
    int32_t temp1_q16, temp2_q16;
    // Calculate Kp
    // Calculate Kp = ka * (scale_in/scale_out)
    // q16/q16 = q16, calculate 1/scale_out_q16
    temp1_q16 = fix16_div(FIX16_1P0, scale_out_q16);
    // q16 = q16 * q16, (fix16_1/scale_out_q16) * scale_in_q16
    temp1_q16 = fix16_mul_uint(temp1_q16, scale_in_q16);
    // q16 = q16 * q16
    temp1_q16 = fix16_mul(pid_data->ka_q16, temp1_q16);
    pid_data->kp_q11 = temp1_q16 >> 5;
    // Calculate Ki
    // Ki = Kb * Kp * Ts
    // q6 = q6 * q16
    temp2_q16 = fix16_mul(pid_data->kb_q16, temp1_q16);
    // q16 = q6 * q26
    pid_data->kidt_q16 = (fix16_mul(temp2_q16, pid_data->dt_q26) >> 10);
    // Check PI Gain Range
    if (pid_data->kp_q11 > QCONST(63, Q11)) // Kp max = 2^6=64 to overflow during q-math multiplication
    {
        pid_data->kp_q11 = QCONST(63, Q11);
        set_warning(WARNING_PIGAIN_RANGE);
    }
    if (pid_data->kidt_q16 > QCONST(1, Q16)) // kitd max = 1 to overflow during q-math multiplication
    {
        pid_data->kidt_q16 = QCONST(1, Q16);
        set_warning(WARNING_PIGAIN_RANGE);
    }
}
References PID_Data_Type::dt_q26, FIX16_1P0, fix16_div(), fix16_mul(), fix16_mul_uint(), PID_Data_Type::ka_q16, PID_Data_Type::kb_q16, PID_Data_Type::kidt_q16, PID_Data_Type::kp_q11, Q11, Q16, QCONST, set_warning(), and WARNING_PIGAIN_RANGE.
void pid_reset (PID_Data_Type * pid_data)
Initializes the PID controller data. Reset PID controller.
Parameters
pid_data Pointer to the PID controller data
Returns
none
Note
Note that the user must make sure that the pointer is valid and that the user-defined fields in the data structure are initialized properly (see the definition for the PID_Data_Type data structure).
Definition at line 33 of file pid.c.
{
    pid_data->I_prev = 0;
    pid_data->PI = 0;
    pid_data->PI_sat = 0;
}
References PID_Data_Type::I_prev, PID_Data_Type::PI, and PID_Data_Type::PI_sat.
Referenced by control_reset(), and foc_reset().
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.