pac_foc/src/mpos/qep/qep_funcs.h
NAME
pac_foc/src/mpos/qep/qep_funcs.h
SYNOPSIS
#include 'pac5xxx.h'
#include 'motor_struct.h'
#include 'parameter_process.h'
#include 'qep_io_config.h'
#include 'qep_timer_config.h'
#include 'utils.h'
#include 'mpos_misc.h'
#include 'calc_speed.h'
Functions
void qep_init (Struct_Motor *motor_ptr)
void qep_reset (Struct_Motor *motor_ptr)
void qep_param_calc (Struct_Motor *motor_ptr)
void qep_param_write (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
void qep_param_process (Struct_Motor *motor_ptr, ParameterCode param_code, int32_t rx_data)
void qep_isr (void)
Function Documentation
void qep_init (Struct_Motor * motor_ptr)
Definition at line 23 of file qep_funcs.c.
{
}
void qep_isr (void)
Definition at line 121 of file qep_funcs.c.
{
#if defined(FAMILY_55XX)
    static Struct_Motor* motor_ptr = &motor;
    if (qep_check_index_event_interrupt_flag())
    {
        motor_ptr->mpos.qep.index_counter++;
        NVIC_DisableIRQ(QEP_TIMER_IRQn);
    }
#endif
}
References Struct_QEP::index_counter, motor, Struct_Motor::mpos, and Struct_MPos::qep.
Referenced by QEPC_IRQHandler(), and QEPD_IRQHandler().
void qep_param_calc (Struct_Motor * motor_ptr)
Definition at line 60 of file qep_funcs.c.
{
    // Calculate speed filter alpha gain
    motor_ptr->mpos.qep.filter_alpha_speed_q16 = calc_filter_alpha(motor_ptr->mpos.qep.filter_fc_speed_q16, motor_ptr->control.dt_control_q26);
    // Calculate speed conversion factors
    calculate_speed_coefficients(motor_ptr->control.dt_control_q26, motor_ptr->app.speed_scale_shift, &motor_ptr->mpos.qep.kspd_radps_q6, &motor_ptr->mpos.qep.kspd_scaled_q14);
    // Calculate conversion factor from QEP counter to mechanical angle
#if defined(ENABLE_QEP_QUAD_MODE)
    motor_ptr->mpos.qep.conv_qep2mech_q24 = fix16_div((FIX16_2PI * motor_ptr->mparam.pole_pairs), (motor_ptr->mpos.qep.qep_resolution << (8 + 2))); // q24 = div(((q16*q0)=q16), (q0<<8)=q8)=q24
#else
    motor_ptr->mpos.qep.conv_qep2mech_q24 = fix16_div((FIX16_2PI * motor_ptr->mparam.pole_pairs), (motor_ptr->mpos.qep.qep_resolution << 8)); // q24 = div(((q16*q0)=q16), (q0<<8)=q8)=q24
#endif
#if defined(ENABLE_OLSPEED_ANGLEDIFF_TIMEOUT)
    // Calculate num of electrical cycles required for AngleDiff Timeout in QEP Mechanical Rotation terms
    motor_ptr->startup.qep_elec_angle_counts_threshold = motor_ptr->mparam.pole_pairs * NUM_QEP_MECH_ROTATION;
#endif
}
References Struct_QEP::filter_alpha_speed_q16, Struct_Motor::mpos, and Struct_MPos::qep.
Referenced by qep_param_process().
void qep_param_process (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Definition at line 104 of file qep_funcs.c.
{
    switch(param_code)
    {
    case dt:
    case num_pole_pairs:
    case max_cl_speed_limit:
    case QEP_Resolution:
    case QEP_Fc:
        qep_param_calc(motor_ptr);
        break;
    default:
        break;
    }
}
References dt, max_cl_speed_limit, num_pole_pairs, QEP_Fc, qep_param_calc(), and QEP_Resolution.
void qep_param_write (Struct_Motor * motor_ptr, ParameterCode param_code, int32_t rx_data)
Definition at line 82 of file qep_funcs.c.
{
    switch(param_code)
    {
    case QEP_Resolution:
        motor_ptr->mpos.qep.qep_resolution = rx_data;
        break;
    case QEP_Offset_Angle_Fwd:
        motor_ptr->mpos.qep.angcorr_offset_fwd = rx_data;
        break;
    case QEP_Offset_Angle_Rev:
        motor_ptr->mpos.qep.angcorr_offset_rev = rx_data;
        break;
    case QEP_Fc:
        motor_ptr->mpos.qep.filter_fc_speed_q16 = rx_data;
        break;
    default:
        break;
    }
}
References Struct_QEP::angcorr_offset_fwd, Struct_QEP::angcorr_offset_rev, Struct_QEP::filter_fc_speed_q16, Struct_Motor::mpos, Struct_MPos::qep, QEP_Fc, QEP_Offset_Angle_Fwd, QEP_Offset_Angle_Rev, Struct_QEP::qep_resolution, and QEP_Resolution.
void qep_reset (Struct_Motor * motor_ptr)
Definition at line 28 of file qep_funcs.c.
{
    // Status
    // Outputs
    motor_ptr->mpos.qep.qep_spd_radps = 0;
    motor_ptr->mpos.qep.qep_spd_scaled_q14 = 0;
    motor_ptr->mpos.qep.qep_spd_scaled_q28 = 0;
    motor_ptr->mpos.qep.qep_spd_prefilt_scaled_q14 = 0;
    motor_ptr->mpos.qep.qep_angle = 0;
    // Running Variables
    motor_ptr->mpos.qep.qep_calculated_angle = 0;
    motor_ptr->mpos.qep.qep_previous_angle = 0;
    motor_ptr->mpos.qep.counter_counts = 0;
    motor_ptr->mpos.qep.index_counter = 0;
    motor_ptr->startup.elec_angle_wrap_around_counts = 0;
    if(motor_ptr->app.direction_reverse_cmd == 0)
        motor_ptr->mpos.qep.ptr_angcorr_offset = &motor_ptr->mpos.qep.angcorr_offset_fwd;
    else
        motor_ptr->mpos.qep.ptr_angcorr_offset = &motor_ptr->mpos.qep.angcorr_offset_rev;
    // Enable QEP timer
#if defined(FAMILY_55XX)
    qep_timer_enabled();
    qep_index_event_clr_interrupt();
    NVIC_EnableIRQ(QEP_TIMER_IRQn);
#endif
}
References Struct_QEP::angcorr_offset_fwd, Struct_QEP::angcorr_offset_rev, Struct_Motor::app, Struct_QEP::counter_counts, Struct_App::direction_reverse_cmd, Struct_QEP::index_counter, Struct_Motor::mpos, Struct_QEP::ptr_angcorr_offset, Struct_MPos::qep, Struct_QEP::qep_angle, Struct_QEP::qep_calculated_angle, Struct_QEP::qep_previous_angle, Struct_QEP::qep_spd_prefilt_scaled_q14, Struct_QEP::qep_spd_radps, Struct_QEP::qep_spd_scaled_q14, Struct_QEP::qep_spd_scaled_q28, and Struct_Motor::startup.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.