.TH "pac_foc/src/features/sim/sim_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim/sim_funcs.h \- Contains generic SIM function definitions and includes all SIM functions for the selected SIM method\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'control_funcs\&.h'\fP
.br
\fC#include 'driver_funcs\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'parameter_process\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Contains generic SIM function definitions and includes all SIM functions for the selected SIM method\&. 


.PP
Definition in file \fBsim_funcs\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
