.TH "pac_foc/src/features/sim/sim_i_funcs.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim/sim_i_funcs.c \- I-SIM function definitions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'sim_funcs\&.h'\fP
.br
\fC#include 'foc_math\&.h'\fP
.br
\fC#include 'mpos_funcs\&.h'\fP
.br
\fC#include 'calc_speed\&.h'\fP
.br
\fC#include 'est_sim2est\&.h'\fP
.br
\fC#include 'hall_sim2hall\&.h'\fP
.br

.SH "Detailed Description"
.PP 
I-SIM function definitions\&. 


.PP
Definition in file \fBsim_i_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
