.TH "pac_foc/src/features/sim/sim_build_info_keil.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim/sim_build_info_keil.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIM_BUILD_STR\fP   '20200813\&.185128'"
.br
.ti -1c
.RI "#define \fBSIM_BUILD_DATE_STR\fP   '20200813'"
.br
.ti -1c
.RI "#define \fBSIM_BUILD_DATE_NUM\fP   20200813"
.br
.ti -1c
.RI "#define \fBSIM_BUILD_TIME_STR\fP   '185128'"
.br
.ti -1c
.RI "#define \fBSIM_BUILD_TIME_NUM\fP   185128"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIM_BUILD_DATE_NUM   20200813"

.PP
Definition at line 13 of file sim_build_info_keil\&.h\&.
.SS "#define SIM_BUILD_DATE_STR   '20200813'"

.PP
Definition at line 12 of file sim_build_info_keil\&.h\&.
.SS "#define SIM_BUILD_STR   '20200813\&.185128'"

.PP
Definition at line 11 of file sim_build_info_keil\&.h\&.
.SS "#define SIM_BUILD_TIME_NUM   185128"

.PP
Definition at line 15 of file sim_build_info_keil\&.h\&.
.SS "#define SIM_BUILD_TIME_STR   '185128'"

.PP
Definition at line 14 of file sim_build_info_keil\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
