.TH "pac_foc/src/features/sim/sim_i_struct.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim/sim_i_struct.h \- I-SIM structure definition\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'maths\&.h'\fP
.br
\fC#include 'pid\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStruct_SIM\fP"
.br
.RI "This structure used for Hall SIM\&. "
.in -1c
.SH "Detailed Description"
.PP 
I-SIM structure definition\&. 


.PP
Definition in file \fBsim_i_struct\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
