.TH "pac_foc/src/features/sim/sim_h_funcs.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/sim/sim_h_funcs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'sim_h_defs\&.h'\fP
.br
\fC#include 'control_funcs\&.h'\fP
.br
\fC#include 'driver_funcs\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'config_features\&.h'\fP
.br
\fC#include 'foc_math\&.h'\fP
.br
\fC#include 'hall_funcs\&.h'\fP
.br
\fC#include 'hall_sim2hall\&.h'\fP
.br
\fC#include 'foc_funcs\&.h'\fP
.br
\fC#include 'est_sim2est\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
