.TH "pac_foc/src/math/sin_table.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/math/sin_table.c \- Sine table\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'fix16\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBfoc_sin_tbl\fP [203]"
.br
.RI "Fixed point sine table for FOC controller\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sine table\&. 


.PP
Definition in file \fBsin_table\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const uint16_t foc_sin_tbl[203]"

.PP
Fixed point sine table for FOC controller\&. 360 degrees, from -1 to 1 
.PP
Definition at line 30 of file sin_table\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
