.TH "pac_foc/src/features/speed_check.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/speed_check.c \- Use for check speed min - max limit and generate speed fault\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'speed_check\&.h'\fP
.br
\fC#include 'fault\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for check speed min - max limit and generate speed fault\&. 


.PP
Definition in file \fBspeed_check\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
