.TH "pac_foc/src/features/stalldet/stalldet_config.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/stalldet/stalldet_config.h \- Use for stall detect configuration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTALL_EVENT_CNT_LIMIT\fP   10"
.br
.ti -1c
.RI "#define \fBSTALL_SPEED_ERROR_LIMIT_PCT\fP   \fBQCONST\fP(0\&.01, \fBQ28\fP)"
.br
.ti -1c
.RI "#define \fBSTALL_SPEED_FILTER_FC_Q16\fP   \fBQCONST\fP(0\&.1, \fBQ16\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use for stall detect configuration\&. 


.PP
Definition in file \fBstalldet_config\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define STALL_EVENT_CNT_LIMIT   10"

.PP
Definition at line 23 of file stalldet_config\&.h\&.
.SS "#define STALL_SPEED_ERROR_LIMIT_PCT   \fBQCONST\fP(0\&.01, \fBQ28\fP)"

.PP
Definition at line 24 of file stalldet_config\&.h\&.
.SS "#define STALL_SPEED_FILTER_FC_Q16   \fBQCONST\fP(0\&.1, \fBQ16\fP)"

.PP
Definition at line 25 of file stalldet_config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
