.TH "pac_foc/src/features/stalldet/stalldet_funcs.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/features/stalldet/stalldet_funcs.c \- Use for stall detect utility functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'motor_struct\&.h'\fP
.br
\fC#include 'stalldet_funcs\&.h'\fP
.br
\fC#include 'stalldet_config\&.h'\fP
.br
\fC#include 'maths\&.h'\fP
.br
\fC#include 'fault\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Use for stall detect utility functions\&. 


.PP
Definition in file \fBstalldet_funcs\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
