.TH "Struct_StartupAlignGo" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_StartupAlignGo \- eStateStartupAlignGo struct  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <startup_aligngo2est_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBeStateStartupAlignGo\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBStruct_AlignGo\fP \fBaligngo\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBidrefol_gui_q16\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBitotrefol_gui_q16\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
eStateStartupAlignGo struct 
.PP
Definition at line 41 of file startup_aligngo2est_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBStruct_AlignGo\fP Struct_StartupAlignGo::aligngo"

.PP
Definition at line 47 of file startup_aligngo2est_struct\&.h\&.
.PP
Referenced by aligngo_param_write(), app_param_process(), est_anglediff_check(), and sm_mainsub_prestart()\&.
.SS "\fBfix16_t\fP Struct_StartupAlignGo::idrefol_gui_q16"

.PP
Definition at line 50 of file startup_aligngo2est_struct\&.h\&.
.PP
Referenced by aligngo_param_write()\&.
.SS "\fBfix16_t\fP Struct_StartupAlignGo::itotrefol_gui_q16"

.PP
Definition at line 51 of file startup_aligngo2est_struct\&.h\&.
.PP
Referenced by aligngo_param_write()\&.
.SS "\fBeStateStartupAlignGo\fP Struct_StartupAlignGo::state"

.PP
Definition at line 44 of file startup_aligngo2est_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
