.TH "Struct_MParam" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_MParam
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mparam_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfix16_t\fP \fBld_q26\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBlq_q26\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBrs_q16\fP"
.br
.ti -1c
.RI "int32_t \fBke_q26\fP"
.br
.ti -1c
.RI "int32_t \fBj_q26\fP"
.br
.ti -1c
.RI "uint8_t \fBpole_pairs\fP"
.br
.ti -1c
.RI "int32_t \fBnom_spd_q16\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file mparam_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Struct_MParam::j_q26"

.PP
Definition at line 26 of file mparam_struct\&.h\&.
.SS "int32_t Struct_MParam::ke_q26"

.PP
Definition at line 25 of file mparam_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_MParam::ld_q26"

.PP
Definition at line 22 of file mparam_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_MParam::lq_q26"

.PP
Definition at line 23 of file mparam_struct\&.h\&.
.PP
Referenced by foc_reset(), lbg1_calculate_coefficients(), lbg1_reset(), and lbg1_statemon()\&.
.SS "int32_t Struct_MParam::nom_spd_q16"

.PP
Definition at line 28 of file mparam_struct\&.h\&.
.PP
Referenced by lbg1_calculate_coefficients()\&.
.SS "uint8_t Struct_MParam::pole_pairs"

.PP
Definition at line 27 of file mparam_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_MParam::rs_q16"

.PP
Definition at line 24 of file mparam_struct\&.h\&.
.PP
Referenced by lbg1_calculate_coefficients(), lbg1_reset(), and lbg1_statemon()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
