.TH "Struct_StartupHall" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_StartupHall \- \fBStruct_StartupHall\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <startup_hall_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBeStateHallStartMain\fP \fBstate_main\fP"
.br
.ti -1c
.RI "int32_t \fBi_total_hall_target_f16\fP"
.br
.ti -1c
.RI "int32_t \fBi_total_hall_target_1div_f16\fP"
.br
.ti -1c
.RI "int32_t \fBidrefstart_target_q16\fP"
.br
.ti -1c
.RI "int32_t \fBiqrefstart_target_q16\fP"
.br
.ti -1c
.RI "int32_t \fBi_total_hall_gui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBStruct_StartupHall\fP struct\&. 
.PP
Definition at line 38 of file startup_hall_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Struct_StartupHall::i_total_hall_gui"

.PP
Definition at line 50 of file startup_hall_struct\&.h\&.
.SS "int32_t Struct_StartupHall::i_total_hall_target_1div_f16"

.PP
Definition at line 45 of file startup_hall_struct\&.h\&.
.SS "int32_t Struct_StartupHall::i_total_hall_target_f16"

.PP
Definition at line 44 of file startup_hall_struct\&.h\&.
.SS "int32_t Struct_StartupHall::idrefstart_target_q16"

.PP
Definition at line 46 of file startup_hall_struct\&.h\&.
.SS "int32_t Struct_StartupHall::iqrefstart_target_q16"

.PP
Definition at line 47 of file startup_hall_struct\&.h\&.
.SS "\fBeStateHallStartMain\fP Struct_StartupHall::state_main"

.PP
Definition at line 41 of file startup_hall_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
