.TH "Struct_OneShunt_Asym" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_OneShunt_Asym
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_1shunt_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBtaccr0_value\fP"
.br
.ti -1c
.RI "int32_t \fBtaccr1_value\fP"
.br
.ti -1c
.RI "int32_t \fBss_sector\fP"
.br
.ti -1c
.RI "int32_t \fBss_sector_sreg\fP"
.br
.ti -1c
.RI "int32_t \fBphase_current1\fP"
.br
.ti -1c
.RI "int32_t \fBphase_current2\fP"
.br
.ti -1c
.RI "uint32_t \fBadc_offset_iphase_ss_q14\fP"
.br
.ti -1c
.RI "int32_t \fBduty_u_up\fP"
.br
.ti -1c
.RI "int32_t \fBduty_u_dn\fP"
.br
.ti -1c
.RI "int32_t \fBduty_u_dn_store\fP"
.br
.ti -1c
.RI "int32_t \fBduty_v_up\fP"
.br
.ti -1c
.RI "int32_t \fBduty_v_dn\fP"
.br
.ti -1c
.RI "int32_t \fBduty_v_dn_store\fP"
.br
.ti -1c
.RI "int32_t \fBduty_w_up\fP"
.br
.ti -1c
.RI "int32_t \fBduty_w_dn\fP"
.br
.ti -1c
.RI "int32_t \fBduty_w_dn_store\fP"
.br
.ti -1c
.RI "uint32_t \fBs1_min_gap\fP"
.br
.ti -1c
.RI "uint32_t \fBs1_sample_ticks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file control_1shunt_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t Struct_OneShunt_Asym::adc_offset_iphase_ss_q14"

.PP
Definition at line 60 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_u_dn"

.PP
Definition at line 62 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_u_dn_store"

.PP
Definition at line 63 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_u_up"

.PP
Definition at line 61 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_v_dn"

.PP
Definition at line 65 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_v_dn_store"

.PP
Definition at line 66 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_v_up"

.PP
Definition at line 64 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_w_dn"

.PP
Definition at line 68 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_w_dn_store"

.PP
Definition at line 69 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::duty_w_up"

.PP
Definition at line 67 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::phase_current1"

.PP
Definition at line 58 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::phase_current2"

.PP
Definition at line 59 of file control_1shunt_struct\&.h\&.
.SS "uint32_t Struct_OneShunt_Asym::s1_min_gap"

.PP
Definition at line 70 of file control_1shunt_struct\&.h\&.
.SS "uint32_t Struct_OneShunt_Asym::s1_sample_ticks"

.PP
Definition at line 71 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::ss_sector"

.PP
Definition at line 56 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::ss_sector_sreg"

.PP
Definition at line 57 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::taccr0_value"

.PP
Definition at line 54 of file control_1shunt_struct\&.h\&.
.SS "int32_t Struct_OneShunt_Asym::taccr1_value"

.PP
Definition at line 55 of file control_1shunt_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
