.TH "Struct_SIM" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_SIM \- This structure used for Hall SIM\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sim_h_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmotor_direction\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBsignal_detected\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBmotion_detected\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBmotion_notdetected\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBtransition_complete\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBflag_hall_timer_int\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBflag_hall_transition\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBtemp\fP: 25"
.br
.ti -1c
.RI "uint32_t \fBflag_hall_state_int\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBfreeInMotion_min_speed_limit\fP"
.br
.ti -1c
.RI "uint32_t \fBstate_sim\fP"
.br
.ti -1c
.RI "uint32_t \fBstatus_sim\fP"
.br
.ti -1c
.RI "uint32_t \fBstate_sim2cl\fP"
.br
.ti -1c
.RI "int \fBphase_u_adc\fP"
.br
.ti -1c
.RI "int \fBphase_v_adc\fP"
.br
.ti -1c
.RI "int \fBphase_w_adc\fP"
.br
.ti -1c
.RI "int32_t \fBphase_adc_threshold_q14\fP"
.br
.ti -1c
.RI "int32_t \fBcentertap_q14\fP"
.br
.ti -1c
.RI "int32_t \fBvphase_u_q14\fP"
.br
.ti -1c
.RI "int32_t \fBvphase_v_q14\fP"
.br
.ti -1c
.RI "int32_t \fBvphase_w_q14\fP"
.br
.ti -1c
.RI "int32_t \fBsim_alpha_q14\fP"
.br
.ti -1c
.RI "int32_t \fBsim_beta_q14\fP"
.br
.ti -1c
.RI "int32_t \fBsim_angle\fP"
.br
.ti -1c
.RI "int32_t \fBsim_angle_previous\fP"
.br
.ti -1c
.RI "int32_t \fBsim_spd_scaled_q28\fP"
.br
.ti -1c
.RI "int32_t \fBsim_spd_scaled_q14\fP"
.br
.ti -1c
.RI "int32_t \fBsim_spd_radps\fP"
.br
.ti -1c
.RI "int32_t \fBsim_spd_prefilt_scaled_q14\fP"
.br
.ti -1c
.RI "int32_t \fBmultp_conv_adc2volts_q16\fP"
.br
.ti -1c
.RI "int32_t \fBmultp_conv_adc2vscaled_q16\fP"
.br
.ti -1c
.RI "int32_t \fBdt_control_q26\fP"
.br
.ti -1c
.RI "int32_t \fBspeed_scale_shift\fP"
.br
.ti -1c
.RI "int32_t \fBkspd_scaled_q14\fP"
.br
.ti -1c
.RI "int32_t \fBkspd_radps_q16\fP"
.br
.ti -1c
.RI "int16_t \fBbraking_duty_cycle_q14\fP"
.br
.ti -1c
.RI "uint32_t \fBbraking_timeout_countmax\fP"
.br
.ti -1c
.RI "uint32_t \fBbraking_timeout_counter\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBalign_count_braking_timeout\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBOL_Id_ref_braking_mul\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBOL_Iq_ref_braking_mul\fP"
.br
.ti -1c
.RI "uint16_t \fBsim_counter\fP"
.br
.ti -1c
.RI "uint16_t \fBsim_detect2_countmax\fP"
.br
.ti -1c
.RI "uint16_t \fBbraking_duty_min_ticks\fP"
.br
.ti -1c
.RI "int16_t \fBbraking_duty_min_q14\fP"
.br
.ti -1c
.RI "int32_t \fBsim_duty_cycle_dec_q14\fP"
.br
.ti -1c
.RI "int32_t \fBbraking_duty_cycle_dec_q14\fP"
.br
.ti -1c
.RI "int32_t \fBangle_inc_q16\fP"
.br
.ti -1c
.RI "int32_t \fBangle_blend_cnt\fP"
.br
.ti -1c
.RI "int32_t \fBsim2cl_maxspd_radps_q16\fP"
.br
.ti -1c
.RI "int32_t \fBiphase_u_q14\fP"
.br
.ti -1c
.RI "int32_t \fBiphase_v_q14\fP"
.br
.ti -1c
.RI "int32_t \fBiphase_w_q14\fP"
.br
.ti -1c
.RI "int32_t \fBfilter_alpha_speed_q16\fP"
.br
.ti -1c
.RI "uint16_t \fBsim_mdetect_countmax\fP"
.br
.ti -1c
.RI "int32_t \fBmdetect_duty_cycle_dec_q14\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure used for Hall SIM\&. 

Structure holding V-SIM variables\&.
.PP
Structure holding I-SIM variables\&. 
.PP
Definition at line 29 of file sim_h_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBfix16_t\fP Struct_SIM::align_count_braking_timeout"

.PP
Definition at line 71 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::angle_blend_cnt"

.PP
Definition at line 82 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::angle_inc_q16"

.PP
Definition at line 81 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::braking_duty_cycle_dec_q14"

.PP
Definition at line 79 of file sim_h_struct\&.h\&.
.SS "int16_t Struct_SIM::braking_duty_cycle_q14"

.PP
Definition at line 68 of file sim_h_struct\&.h\&.
.SS "int16_t Struct_SIM::braking_duty_min_q14"

.PP
Definition at line 77 of file sim_h_struct\&.h\&.
.SS "uint16_t Struct_SIM::braking_duty_min_ticks"

.PP
Definition at line 76 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::braking_timeout_counter"

.PP
Definition at line 70 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::braking_timeout_countmax"

.PP
Definition at line 69 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::centertap_q14"

.PP
Definition at line 48 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::dt_control_q26"

.PP
Definition at line 63 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::filter_alpha_speed_q16"

.PP
Definition at line 64 of file sim_i_struct\&.h\&.
.SS "uint32_t Struct_SIM::flag_hall_state_int"

.PP
Definition at line 39 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::flag_hall_timer_int"

.PP
Definition at line 36 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::flag_hall_transition"

.PP
Definition at line 37 of file sim_h_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_SIM::freeInMotion_min_speed_limit"

.PP
Definition at line 40 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::iphase_u_q14"

.PP
Definition at line 46 of file sim_i_struct\&.h\&.
.SS "int32_t Struct_SIM::iphase_v_q14"

.PP
Definition at line 47 of file sim_i_struct\&.h\&.
.SS "int32_t Struct_SIM::iphase_w_q14"

.PP
Definition at line 48 of file sim_i_struct\&.h\&.
.SS "int32_t Struct_SIM::kspd_radps_q16"

.PP
Definition at line 66 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::kspd_scaled_q14"

.PP
Definition at line 65 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::mdetect_duty_cycle_dec_q14"

.PP
Definition at line 79 of file sim_i_struct\&.h\&.
.SS "uint32_t Struct_SIM::motion_detected"

.PP
Definition at line 33 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::motion_notdetected"

.PP
Definition at line 34 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::motor_direction"

.PP
Definition at line 31 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::multp_conv_adc2volts_q16"

.PP
Definition at line 60 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::multp_conv_adc2vscaled_q16"

.PP
Definition at line 61 of file sim_h_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_SIM::OL_Id_ref_braking_mul"

.PP
Definition at line 72 of file sim_h_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_SIM::OL_Iq_ref_braking_mul"

.PP
Definition at line 73 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::phase_adc_threshold_q14"

.PP
Definition at line 47 of file sim_h_struct\&.h\&.
.SS "int Struct_SIM::phase_u_adc"

.PP
Definition at line 44 of file sim_h_struct\&.h\&.
.SS "int Struct_SIM::phase_v_adc"

.PP
Definition at line 45 of file sim_h_struct\&.h\&.
.SS "int Struct_SIM::phase_w_adc"

.PP
Definition at line 46 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::signal_detected"

.PP
Definition at line 32 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim2cl_maxspd_radps_q16"

.PP
Definition at line 83 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_alpha_q14"

.PP
Definition at line 52 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_angle"

.PP
Definition at line 54 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_angle_previous"

.PP
Definition at line 55 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_beta_q14"

.PP
Definition at line 53 of file sim_h_struct\&.h\&.
.SS "uint16_t Struct_SIM::sim_counter"

.PP
Definition at line 74 of file sim_h_struct\&.h\&.
.SS "uint16_t Struct_SIM::sim_detect2_countmax"

.PP
Definition at line 75 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_duty_cycle_dec_q14"

.PP
Definition at line 78 of file sim_h_struct\&.h\&.
.SS "uint16_t Struct_SIM::sim_mdetect_countmax"

.PP
Definition at line 73 of file sim_i_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_spd_prefilt_scaled_q14"

.PP
Definition at line 59 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_spd_radps"

.PP
Definition at line 58 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_spd_scaled_q14"

.PP
Definition at line 57 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::sim_spd_scaled_q28"

.PP
Definition at line 56 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::speed_scale_shift"

.PP
Definition at line 64 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::state_sim"

.PP
Definition at line 41 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::state_sim2cl"

.PP
Definition at line 43 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::status_sim"

.PP
Definition at line 42 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::temp"

.PP
Definition at line 38 of file sim_h_struct\&.h\&.
.SS "uint32_t Struct_SIM::transition_complete"

.PP
Definition at line 35 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::vphase_u_q14"

.PP
Definition at line 49 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::vphase_v_q14"

.PP
Definition at line 50 of file sim_h_struct\&.h\&.
.SS "int32_t Struct_SIM::vphase_w_q14"

.PP
Definition at line 51 of file sim_h_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
