.TH "Struct_OPDOL" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_OPDOL
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opd_ol_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBstatus_opdol\fP"
.br
.ti -1c
.RI "uint8_t \fBstate_opdol_ctl\fP"
.br
.ti -1c
.RI "uint8_t \fBstate_opdol_main\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBopdol_Sum_Iw\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBopdol_Sum_Iv\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBopdol_Sum_Iu\fP"
.br
.ti -1c
.RI "uint32_t \fBolopd_start_sample_delay\fP"
.br
.ti -1c
.RI "uint32_t \fBolopd_total_samples\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file opd_ol_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t Struct_OPDOL::olopd_start_sample_delay"

.PP
Definition at line 32 of file opd_ol_struct\&.h\&.
.SS "uint32_t Struct_OPDOL::olopd_total_samples"

.PP
Definition at line 33 of file opd_ol_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_OPDOL::opdol_Sum_Iu"

.PP
Definition at line 31 of file opd_ol_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_OPDOL::opdol_Sum_Iv"

.PP
Definition at line 30 of file opd_ol_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_OPDOL::opdol_Sum_Iw"

.PP
Definition at line 29 of file opd_ol_struct\&.h\&.
.SS "uint8_t Struct_OPDOL::state_opdol_ctl"

.PP
Definition at line 27 of file opd_ol_struct\&.h\&.
.SS "uint8_t Struct_OPDOL::state_opdol_main"

.PP
Definition at line 28 of file opd_ol_struct\&.h\&.
.SS "uint8_t Struct_OPDOL::status_opdol"

.PP
Definition at line 26 of file opd_ol_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
