.TH "Struct_FW" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_FW \- field weakening structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fw_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfix16_t\fP \fBspd_threshold\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBid_sp\fP"
.br
.ti -1c
.RI "int32_t \fBflag_sat_logicand\fP"
.br
.ti -1c
.RI "int32_t \fBflag_sat_logicor\fP"
.br
.ti -1c
.RI "int32_t \fBfw_active_flag\fP"
.br
.ti -1c
.RI "\fBfix16_t\fP \fBflag_semaphore\fP"
.br
.ti -1c
.RI "int32_t \fBidrefcl_target_store_f16\fP"
.br
.ti -1c
.RI "int32_t \fBiqmax_q14\fP"
.br
.ti -1c
.RI "int32_t \fBiqmax_store_q14\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
field weakening structure 
.PP
Definition at line 28 of file fw_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Struct_FW::flag_sat_logicand"

.PP
Definition at line 35 of file fw_struct\&.h\&.
.SS "int32_t Struct_FW::flag_sat_logicor"

.PP
Definition at line 36 of file fw_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_FW::flag_semaphore"

.PP
Definition at line 38 of file fw_struct\&.h\&.
.SS "int32_t Struct_FW::fw_active_flag"

.PP
Definition at line 37 of file fw_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_FW::id_sp"

.PP
Definition at line 32 of file fw_struct\&.h\&.
.SS "int32_t Struct_FW::idrefcl_target_store_f16"

.PP
Definition at line 41 of file fw_struct\&.h\&.
.SS "int32_t Struct_FW::iqmax_q14"

.PP
Definition at line 42 of file fw_struct\&.h\&.
.SS "int32_t Struct_FW::iqmax_store_q14"

.PP
Definition at line 43 of file fw_struct\&.h\&.
.SS "\fBfix16_t\fP Struct_FW::spd_threshold"

.PP
Definition at line 31 of file fw_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
