.TH "Struct_Overmod" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_Overmod \- Over modulation structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <overmod_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBvalpha_premod_q14\fP"
.br
.ti -1c
.RI "int32_t \fBvbeta_premod_q14\fP"
.br
.ti -1c
.RI "int32_t \fBovermod_flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Over modulation structure\&. 
.PP
Definition at line 28 of file overmod_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int32_t Struct_Overmod::overmod_flag"

.PP
Definition at line 32 of file overmod_struct\&.h\&.
.PP
Referenced by check_overmod_status()\&.
.SS "int32_t Struct_Overmod::valpha_premod_q14"

.PP
Definition at line 30 of file overmod_struct\&.h\&.
.SS "int32_t Struct_Overmod::vbeta_premod_q14"

.PP
Definition at line 31 of file overmod_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
