.TH "Struct_PPM" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_PPM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ppm_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBppm_pulse_high\fP"
.br
.ti -1c
.RI "int32_t \fBppm_pulse_low\fP"
.br
.ti -1c
.RI "int32_t \fBppm_pulse_delta\fP"
.br
.ti -1c
.RI "uint32_t \fBpulse_time\fP"
.br
.ti -1c
.RI "uint32_t \fBvalid_pulse_counter_temp\fP"
.br
.ti -1c
.RI "uint32_t \fBpulse_detected\fP"
.br
.ti -1c
.RI "uint32_t \fBflag_cap_rising_first\fP"
.br
.ti -1c
.RI "uint32_t \fBmotor_powerup_flag\fP"
.br
.ti -1c
.RI "uint32_t \fBpulse_timeout_in_sys_tick_isr_counts\fP"
.br
.ti -1c
.RI "uint32_t \fBinvalid_pulse_detect_count\fP"
.br
.ti -1c
.RI "int32_t \fBvalid_motor_on_pulse_detect\fP"
.br
.ti -1c
.RI "uint32_t \fBmotor_off_timeout_in_pulse_timeout_counts\fP"
.br
.ti -1c
.RI "int32_t \fBppm_rise_ccr_value\fP"
.br
.ti -1c
.RI "uint32_t \fBtimer_counts\fP"
.br
.ti -1c
.RI "uint32_t \fBppm_slope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file ppm_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t Struct_PPM::flag_cap_rising_first"

.PP
Definition at line 28 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::invalid_pulse_detect_count"

.PP
Definition at line 31 of file ppm_struct\&.h\&.
.PP
Referenced by ppm_init()\&.
.SS "uint32_t Struct_PPM::motor_off_timeout_in_pulse_timeout_counts"

.PP
Definition at line 33 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::motor_powerup_flag"

.PP
Definition at line 29 of file ppm_struct\&.h\&.
.PP
Referenced by systemvar_init()\&.
.SS "int32_t Struct_PPM::ppm_pulse_delta"

.PP
Definition at line 24 of file ppm_struct\&.h\&.
.SS "int32_t Struct_PPM::ppm_pulse_high"

.PP
Definition at line 22 of file ppm_struct\&.h\&.
.SS "int32_t Struct_PPM::ppm_pulse_low"

.PP
Definition at line 23 of file ppm_struct\&.h\&.
.SS "int32_t Struct_PPM::ppm_rise_ccr_value"

.PP
Definition at line 34 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::ppm_slope"

.PP
Definition at line 36 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::pulse_detected"

.PP
Definition at line 27 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::pulse_time"

.PP
Definition at line 25 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::pulse_timeout_in_sys_tick_isr_counts"

.PP
Definition at line 30 of file ppm_struct\&.h\&.
.SS "uint32_t Struct_PPM::timer_counts"

.PP
Definition at line 35 of file ppm_struct\&.h\&.
.SS "int32_t Struct_PPM::valid_motor_on_pulse_detect"

.PP
Definition at line 32 of file ppm_struct\&.h\&.
.PP
Referenced by ppm_init()\&.
.SS "uint32_t Struct_PPM::valid_pulse_counter_temp"

.PP
Definition at line 26 of file ppm_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
