.TH "Struct_StartupAlignGo2QEP" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_StartupAlignGo2QEP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <startup_aligngo2qep_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBeStateStartupAlignGo2QEP\fP \fBstate\fP"
.br
.ti -1c
.RI "uint32_t \fBqep_ready\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBunused\fP: 31"
.br
.ti -1c
.RI "int32_t \fBqep_elec_angle_counts_threshold\fP"
.br
.ti -1c
.RI "int32_t \fBidrefol_gui_q16\fP"
.br
.ti -1c
.RI "int32_t \fBitotrefol_gui_q16\fP"
.br
.ti -1c
.RI "int32_t \fBelec_angle_wrap_around_counts\fP"
.br
.ti -1c
.RI "\fBStruct_AlignGo\fP \fBaligngo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file startup_aligngo2qep_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBStruct_AlignGo\fP Struct_StartupAlignGo2QEP::aligngo"

.PP
Definition at line 44 of file startup_aligngo2qep_struct\&.h\&.
.SS "int32_t Struct_StartupAlignGo2QEP::elec_angle_wrap_around_counts"

.PP
Definition at line 41 of file startup_aligngo2qep_struct\&.h\&.
.SS "int32_t Struct_StartupAlignGo2QEP::idrefol_gui_q16"

.PP
Definition at line 37 of file startup_aligngo2qep_struct\&.h\&.
.SS "int32_t Struct_StartupAlignGo2QEP::itotrefol_gui_q16"

.PP
Definition at line 38 of file startup_aligngo2qep_struct\&.h\&.
.SS "int32_t Struct_StartupAlignGo2QEP::qep_elec_angle_counts_threshold"

.PP
Definition at line 36 of file startup_aligngo2qep_struct\&.h\&.
.SS "uint32_t Struct_StartupAlignGo2QEP::qep_ready"

.PP
Definition at line 32 of file startup_aligngo2qep_struct\&.h\&.
.SS "\fBeStateStartupAlignGo2QEP\fP Struct_StartupAlignGo2QEP::state"

.PP
Definition at line 31 of file startup_aligngo2qep_struct\&.h\&.
.SS "uint32_t Struct_StartupAlignGo2QEP::unused"

.PP
Definition at line 33 of file startup_aligngo2qep_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
