.TH "Struct_BootProt" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct_BootProt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motor_struct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBbootprot_pwm_max_ticks\fP"
.br
.ti -1c
.RI "int8_t \fBbootprot_max_counts\fP"
.br
.ti -1c
.RI "int8_t \fBbootprot_count1\fP"
.br
.ti -1c
.RI "int8_t \fBbootprot_count2\fP"
.br
.ti -1c
.RI "int8_t \fBbootprot_count3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file motor_struct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int8_t Struct_BootProt::bootprot_count1"

.PP
Definition at line 108 of file motor_struct\&.h\&.
.SS "int8_t Struct_BootProt::bootprot_count2"

.PP
Definition at line 109 of file motor_struct\&.h\&.
.SS "int8_t Struct_BootProt::bootprot_count3"

.PP
Definition at line 110 of file motor_struct\&.h\&.
.SS "int8_t Struct_BootProt::bootprot_max_counts"

.PP
Definition at line 107 of file motor_struct\&.h\&.
.SS "int16_t Struct_BootProt::bootprot_pwm_max_ticks"

.PP
Definition at line 106 of file motor_struct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
