.TH "pac_foc/src/math/trig.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/src/math/trig.c \- Trigonometric support functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx\&.h'\fP
.br
\fC#include 'maths\&.h'\fP
.br
\fC#include 'trig\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBtrig_arctan_90deg_q16\fP (int32_t opposite_q16, int32_t adjacent_q16)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Trigonometric support functions\&. 


.PP
Definition in file \fBtrig\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int32_t trig_arctan_90deg_q16 (int32_t opposite_q16, int32_t adjacent_q16)"

.PP
Definition at line 25 of file trig\&.c\&.
.PP
.nf
26 {
27     int32_t result_q16;
28     int32_t arg_q16;
29 
30     if (opposite_q16 < adjacent_q16)
31     {
32         arg_q16 = fix16_div(opposite_q16, adjacent_q16);
33         result_q16 = foc_atan_tbl[arg_q16 >> 8];
34     }
35     else
36     {
37         arg_q16 = fix16_div(adjacent_q16, opposite_q16);
38         result_q16 = FIX16_PI_DIV_2 - foc_atan_tbl[arg_q16 >> 8];
39     }
40 
41     return result_q16;
42 }
.fi
.PP
References fix16_div(), FIX16_PI_DIV_2, and foc_atan_tbl\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-App from the source code\&.
