pac_foc/src/app/vbus_funcs.h
NAME
pac_foc/src/app/vbus_funcs.h - Use to calculate internal and external vbus and slope factor from flash and duty cycle execlusion.
SYNOPSIS
#include 'pac5xxx_driver_timer.h'
#include 'motor_struct.h'
#include 'fault.h'
#include 'control_funcs.h'
#include 'parameter_process.h'
Functions
void sample_dcbus (Struct_Motor *motor_ptr)
This function use to calculate average value of dc bus voltage.
fix16_t calc_vm (Struct_Motor *motor_ptr, unsigned int adc_counts)
void cal_vm_const (Struct_Motor *motor_ptr)
This function use to calculate vms constant.
Detailed Description
Use to calculate internal and external vbus and slope factor from flash and duty cycle execlusion.
Definition in file vbus_funcs.h.
Function Documentation
void cal_vm_const (Struct_Motor * motor_ptr)
This function use to calculate vms constant.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 149 of file vbus_funcs.c.
{
    // Convert VMS100 and VMS200 in mV to q16
    motor_ptr->vms_v100 = READ_UINT16(VMS100_ADDRESS) << 16;
    motor_ptr->vms_v200 = READ_UINT16(VMS200_ADDRESS) << 16;
    motor_ptr->one_div_vms200_minus_vms100 = fix16_div(FIX16_ONE, fix16_sub(motor_ptr->vms_v200, motor_ptr->vms_v100));
}
References fix16_div(), FIX16_ONE, Struct_Motor::one_div_vms200_minus_vms100, READ_UINT16, Struct_Motor::vms_v100, and Struct_Motor::vms_v200.
fix16_t calc_vm (Struct_Motor * motor_ptr, unsigned int adc_counts)
void sample_dcbus (Struct_Motor * motor_ptr)
This function use to calculate average value of dc bus voltage.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 164 of file vbus_funcs.c.
{
    long int vbus_vms;
#if (INTERNAL_VMS == TRUE)
    vbus_vms = calc_vbus_internal(motor_ptr, motor_ptr->vms_adc_vlaue);
#else
    vbus_vms = calc_vbus_external(motor_ptr, readseq_vbus());
#endif
    // Filter bus voltage
    filter_shift2(vbus_vms, &motor_ptr->app.dcbus_voltage, 2);
    // Calculate voltage factors
    vbus_calc_vfactors(motor_ptr);
}
References calc_vbus_external(), calc_vbus_internal(), and Struct_Motor::vms_adc_vlaue.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.