pac_foc/src/app/vbus_funcs.c
NAME
pac_foc/src/app/vbus_funcs.c - Use to calculate internal and external vbus and slope factor from flash.
SYNOPSIS
#include 'motor_struct.h'
#include 'vbus_funcs.h'
#include 'foc.h'
#include 'mpos_funcs.h'
#include 'param.h'
#include 'fault.h'
#include 'control_funcs.h'
#include 'foc_funcs.h'
#include 'comm.h'
Functions
fix16_t calc_vbus_external (Struct_Motor *motor_ptr, unsigned int adc_counts)
This function use to calculate vbus external.
fix16_t calc_vbus_internal (Struct_Motor *motor_ptr, unsigned int adc_counts)
This function use to calculate vbus internal.
void cal_vm_const (Struct_Motor *motor_ptr)
This function use to calculate vms constant.
void sample_dcbus (Struct_Motor *motor_ptr)
This function use to calculate average value of dc bus voltage.
Detailed Description
Use to calculate internal and external vbus and slope factor from flash.
Definition in file vbus_funcs.c.
Function Documentation
void cal_vm_const (Struct_Motor * motor_ptr)
This function use to calculate vms constant.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 149 of file vbus_funcs.c.
{
    // Convert VMS100 and VMS200 in mV to q16
    motor_ptr->vms_v100 = READ_UINT16(VMS100_ADDRESS) << 16;
    motor_ptr->vms_v200 = READ_UINT16(VMS200_ADDRESS) << 16;
    motor_ptr->one_div_vms200_minus_vms100 = fix16_div(FIX16_ONE, fix16_sub(motor_ptr->vms_v200, motor_ptr->vms_v100));
}
References fix16_div(), FIX16_ONE, Struct_Motor::one_div_vms200_minus_vms100, READ_UINT16, Struct_Motor::vms_v100, and Struct_Motor::vms_v200.
fix16_t calc_vbus_external (Struct_Motor * motor_ptr, unsigned int adc_counts)
This function use to calculate vbus external.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
unsigned int adc_counts
Definition at line 76 of file vbus_funcs.c.
{
    return (fix16_t) (adc_counts * (CONV_ADC2DCBUS_Q14 << 2)); // Q0 * (Q14 << 2) = Q16
}
References CONV_ADC2DCBUS_Q14.
Referenced by sample_dcbus().
fix16_t calc_vbus_internal (Struct_Motor * motor_ptr, unsigned int adc_counts)
This function use to calculate vbus internal.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
unsigned int adc_counts
Definition at line 92 of file vbus_funcs.c.
{
#if (INTERNAL_VMS == TRUE)
#if ((DEVICE_SELECT == DEVICE_5256) || (DEVICE_SELECT == DEVICE_5556))
//#define CAL_TECHNIQUE_1
#ifdef CAL_TECHNIQUE_1
    fix16_t vms100, vms200, vms_adc, temp1, vm;
#else
    fix16_t vms_adc, temp_vms, vm;
#endif
    //vms_adc = adc_counts * Q16_mV_PER_ADC_COUNT;
    vms_adc = adc_counts;
#ifdef CAL_TECHNIQUE_1
    // Convert VMS100 and VMS200 in mV to q16
    vms100 = READ_UINT16(VMS100_ADDRESS) << 16;
    vms200 = READ_UINT16(VMS200_ADDRESS) << 16;
    temp1 = fix16_div( (vms_adc - vms100), (vms200 - vms100));
    vm = fix16_mul(Q16_100, temp1) + Q16_100;
    return vm;
#else
    temp_vms = fix16_mul( (vms_adc - motor_ptr->vms_v100), motor_ptr->one_div_vms200_minus_vms100);
    vm = fix16_mul(Q16_100, temp_vms) + Q16_100;
    return vm;
#endif
#endif
#if (DEVICE_SELECT == DEVICE_5527) || (DEVICE_SELECT == DEVICE_5526)
#if (CONFIG_ADC_OFFSET_GAIN & VMS_INPUT)
    int32_t temp1;
    temp1 = ((readseq_vbus_vms() << 16)- motor_ptr->post.adc_offset_in_counts_q16) >> 13; // q16 >> 13 = q3
    temp1 = (temp1 * motor_ptr->post.adc_gain_in_counts_one_div_q16) >> 3; // q3 * q16 = q19>>3 = q16
    
#else
    return (fix16_t) ((readseq_vbus_vms() >> 2) * (CONV_ADC2DCBUS_Q14 << 2)); // Q0 * (Q14 << 2) = Q16
#endif
#endif
#else
    return 0;
#endif
}
References Struct_POST::adc_gain_in_counts_one_div_q16, Struct_POST::adc_offset_in_counts_q16, CONV_ADC2DCBUS_Q14, fix16_div(), fix16_mul(), Struct_Motor::one_div_vms200_minus_vms100, Struct_Motor::post, Q16_100, READ_UINT16, and Struct_Motor::vms_v100.
Referenced by sample_dcbus().
void sample_dcbus (Struct_Motor * motor_ptr)
This function use to calculate average value of dc bus voltage.
Parameters
Struct_Motor* motor_ptr pointer to motor structure
Definition at line 164 of file vbus_funcs.c.
{
    long int vbus_vms;
#if (INTERNAL_VMS == TRUE)
    vbus_vms = calc_vbus_internal(motor_ptr, motor_ptr->vms_adc_vlaue);
#else
    vbus_vms = calc_vbus_external(motor_ptr, readseq_vbus());
#endif
    // Filter bus voltage
    filter_shift2(vbus_vms, &motor_ptr->app.dcbus_voltage, 2);
    // Calculate voltage factors
    vbus_calc_vfactors(motor_ptr);
}
References calc_vbus_external(), calc_vbus_internal(), and Struct_Motor::vms_adc_vlaue.
Author
Generated automatically by Doxygen for FOC-4.1.2-App from the source code.