.TH "ADC_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Type \- Analog to Digital Converter (ADC)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEMUXCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEMUXDATA\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBADCCTL\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBADCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBADCINT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [11]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0S7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS0R7\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP [31]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1S7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAS1R7\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Analog to Digital Converter (ADC) 
.PP
Definition at line 452 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
