pac_foc/pac52xx/board/board_ep5285lvm1_1.c
NAME
pac_foc/pac52xx/board/board_ep5285lvm1_1.c
SYNOPSIS
#include 'motor_struct.h'
#include 'pac5xxx_driver_tile.h'
#include 'pac5xxx_driver_adc.h'
Functions
void init_diff_amp_gain (void)
void config_seq_foc (void)
void init_emux (void)
Function Documentation
void config_seq_foc (void)
Definition at line 33 of file board_ep5285lvm1_1.c.
{
    // Configure sequencers and ADC
    pac5xxx_adc_config(ADCCTL_ADSTART_AUTO_01_IND_TRIG, ADCCTL_ADCDIV_DIV4, 1); // Configure sequencers for AS0 chained triggers, /4 divider, repeat mode
    
    // AS0 configuration
    pac5xxx_adc_as0_config_pwm(ADCCTLX_AS1D_DEPTH1, ADCCTLX_TRIGEDGE_HITOLOW, ADCCTLX_TRIGPWM_PWMA0);
    pac5xxx_adc_as0_sequence_config(0, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AIO10), ASSEQ_DELAY_0); // Convert Vout, then change CAFE MUX to M1-Vu
#if (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_1) || !defined(ENABLE_POWERMEASURE)
    #ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    pac5xxx_adc_as1_config_pwm(ADCCTLX_AS1D_DEPTH4, ADCCTLX_TRIGEDGE_HITOLOW, ADCCTLX_TRIGPWM_PWMA1);
    pac5xxx_adc_as1_sequence_config(0, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AIO10), ASSEQ_DELAY_0); // Convert I2, then change CAFE MUX to Vbus
    pac5xxx_adc_as1_sequence_config(1, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AB13), ASSEQ_DELAY_0); // Convert Vbus, then change CAFE MUX to M1-Iu
    pac5xxx_adc_as1_sequence_config(2, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AB10), ASSEQ_DELAY_0); // Convert temperature, CAFE MUX to M1-Iu
    pac5xxx_adc_as1_sequence_config(3, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AIO10), ASSEQ_DELAY_0); // Convert I2, then change CAFE MUX to M1-Iu
    #else //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
    // AS1 configuration
    pac5xxx_adc_as1_config_pwm(ADCCTLX_AS1D_DEPTH4, ADCCTLX_TRIGEDGE_LOWTOHI, ADCCTLX_TRIGPWM_PWMA1);
    pac5xxx_adc_as1_sequence_config(0, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AIO10), ASSEQ_DELAY_0); // Convert I2, then change CAFE MUX to Vbus
    pac5xxx_adc_as1_sequence_config(1, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AB13), ASSEQ_DELAY_0); // Convert Vbus, then change CAFE MUX to M1-Iu
    pac5xxx_adc_as1_sequence_config(2, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AB10), ASSEQ_DELAY_0); // Convert temperature, CAFE MUX to M1-Iu
    pac5xxx_adc_as1_sequence_config(3, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_MSPI(SIGMGR_AIO10), ASSEQ_DELAY_0); // Convert I2, then change CAFE MUX to M1-Iu
   #endif //#ifndef SELECT_I2SAMPLE_MIDDLEPWM
#elif (POWER_MEASURE_SELECT == POWER_MEASURE_METHOD_2)
#error: POWER_MEASURE_METHOD_2 not supported BOARD_EP5285LVM1_1_1
#endif
}
References ADCCTL_ADCDIV_DIV4, ADCCTL_ADMUX_AD0, ADCCTL_ADSTART_AUTO_01_IND_TRIG, ADCCTLX_AS1D_DEPTH1, ADCCTLX_AS1D_DEPTH4, ADCCTLX_TRIGEDGE_HITOLOW, ADCCTLX_TRIGEDGE_LOWTOHI, ADCCTLX_TRIGPWM_PWMA0, ADCCTLX_TRIGPWM_PWMA1, ASSEQ_DELAY_0, ASSEQ_MSPI_AFTER_SH, pac5xxx_adc_as0_config_pwm(), pac5xxx_adc_as0_sequence_config(), pac5xxx_adc_as1_config_pwm(), pac5xxx_adc_as1_sequence_config(), and pac5xxx_adc_config().
void init_diff_amp_gain (void)
Definition at line 24 of file board_ep5285lvm1_1.c.
{
    pac5xxx_tile_register_write(ADDR_CFGAIO10, 0);
    // Enable Vref/2 offset, 1.5 usec HPCOMP blanking time
    pac5xxx_tile_register_write(ADDR_CFGAIO10, ((AIO50_OFFSET_ENABLED << 3) | 0x03));
    // Configure AIO6
    pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_IO << 6) | (AIO6789_OPT_INPUT << 4) | (AIO6789_POL_AH << 3) | AIO6789_MUX_DEFAULT)); // IO Mode
}
References AIO50_OFFSET_ENABLED, AIO6789_MODE_IO, AIO6789_MUX_DEFAULT, AIO6789_OPT_INPUT, AIO6789_POL_AH, and pac5xxx_tile_register_write().
void init_emux (void)
Definition at line 136 of file board_ep5285lvm1_1.c.
{
    // Manually set ADC EMUX so that first sequencer conversion is correct
// pac5xxx_tile_register_write(ADDR_ADCIN1, 0); // Set to EMUX to AIO10
}
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.