pac_foc/pac52xx/board/board_pac5256evk1.c
NAME
pac_foc/pac52xx/board/board_pac5256evk1.c
SYNOPSIS
#include 'motor_struct.h'
#include 'pac5xxx_tile_SignalManager.h'
#include 'pac5xxx_driver_tile.h'
#include 'pac5xxx_driver_adc.h'
Functions
void init_diff_amp_gain (void)
void config_seq_foc (void)
void init_emux (void)
Function Documentation
void config_seq_foc (void)
Definition at line 54 of file board_pac5256evk1.c.
{
    unsigned char value;
    // Configure sequencers and ADC
    pac5xxx_adc_config(ADCCTL_ADSTART_AUTO_01_CHAIN_TRIG, ADCCTL_ADCDIV_DIV4, 1); // Configure sequencers for AS0 chained triggers, /4 divider, repeat mode
    // AS0 configuration
    pac5xxx_adc_as0_config_pwm(ADCCTLX_AS1D_DEPTH3, ADCCTLX_TRIGEDGE_LOWTOHI, ADCCTLX_TRIGPWM_PWMA0);
    pac5xxx_adc_as0_sequence_config(0, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_AIO32 | SIGMGR_MSPI_SH_DIFFAMP, ASSEQ_DELAY_0); // Convert M1-Iu, then change CAFE MUX to M1-Iv
    pac5xxx_adc_as0_sequence_config(1, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_AIO54 | SIGMGR_MSPI_SH_DIFFAMP, ASSEQ_DELAY_0); // Convert M1-Iv, then change CAFE MUX to M1-Iw
    pac5xxx_adc_as0_sequence_config(2, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_AB11, ASSEQ_DELAY_0); // Convert M1-Iw, then change CAFE MUX to Vout=AB11
    // AS1 configuration
    pac5xxx_adc_as1_config_pwm(ADCCTLX_AS1D_DEPTH2, ADCCTLX_TRIGEDGE_LOWTOHI, ADCCTLX_TRIGPWM_PWMA0);
    pac5xxx_adc_as1_sequence_config(0, ADCCTL_ADMUX_AD0, ASSEQ_MSPI_AFTER_SH, SIGMGR_AB11, ASSEQ_DELAY_0); // Convert Vout, then change CAFE MUX to M1-Iu
    pac5xxx_adc_as1_sequence_config(1, ADCCTL_ADMUX_AD2, ASSEQ_MSPI_AFTER_SH, SIGMGR_AIO10, ASSEQ_DELAY_0);
    // Configure Power Mux so AB11 = Vout(Vbus)
    value = pac5xxx_tile_register_read(ADDR_PWRCTL);
    value = (value & 0xC7) | (0x05 << 3);
    pac5xxx_tile_register_write(ADDR_PWRCTL, value); // Select PWRMON Mux = Vbus
}
References ADCCTL_ADCDIV_DIV4, ADCCTL_ADMUX_AD0, ADCCTL_ADMUX_AD2, ADCCTL_ADSTART_AUTO_01_CHAIN_TRIG, ADCCTLX_AS1D_DEPTH2, ADCCTLX_AS1D_DEPTH3, ADCCTLX_TRIGEDGE_LOWTOHI, ADCCTLX_TRIGPWM_PWMA0, ASSEQ_DELAY_0, ASSEQ_MSPI_AFTER_SH, pac5xxx_adc_as0_config_pwm(), pac5xxx_adc_as0_sequence_config(), pac5xxx_adc_as1_config_pwm(), pac5xxx_adc_as1_sequence_config(), pac5xxx_adc_config(), pac5xxx_tile_register_read(), and pac5xxx_tile_register_write().
void init_diff_amp_gain (void)
Definition at line 21 of file board_pac5256evk1.c.
{
    Struct_Motor* motor_ptr = &motor;
    pac5xxx_tile_register_write(ADDR_CFGAIO0, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_HPROT_PR1 << 4) | (AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO1, ((AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO2, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_HPROT_PR1 << 4) | (AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO3, ((AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO4, ((((AIO50_MODE_DIFFAMP << 6) | (AIO50_GAIN_X1 << 3) | AIO50_LPCOMP_2US) & 0xC7) | (motor_ptr->app.iphase_amp_gain << 3)));
#ifdef ENABLE_CBC_CURRENT_LIMIT
    pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_HPROT_PR1 << 4) | (AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3) | AIO50_HPCOMP_1US));
#else
    pac5xxx_tile_register_write(ADDR_CFGAIO5, ((AIO50_LPROT_PR2 << 4) | (AIO50_OFFSET_ENABLED << 3)));
#endif
    pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_IO << 6) | (AIO6789_OPT_INPUT << 4) | (AIO6789_POL_AH << 3) | AIO6789_MUX_DEFAULT)); // IO Mode
    //pac5xxx_tile_register_write(ADDR_CFGAIO6, ((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT)); // Gain Mode
    pac5xxx_tile_register_write(ADDR_CFGAIO7, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO8, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
    pac5xxx_tile_register_write(ADDR_CFGAIO9, ((((AIO6789_MODE_GAIN << 6) | (AIO6789_GAIN_X1 << 3) | AIO6789_MUX_DEFAULT) & 0xC7) | (motor_ptr->app.vphase_amp_gain << 3)));
}
References AIO50_GAIN_X1, AIO50_HPCOMP_1US, AIO50_HPROT_PR1, AIO50_LPCOMP_2US, AIO50_LPROT_PR2, AIO50_MODE_DIFFAMP, AIO50_OFFSET_ENABLED, AIO6789_GAIN_X1, AIO6789_MODE_GAIN, AIO6789_MODE_IO, AIO6789_MUX_DEFAULT, AIO6789_OPT_INPUT, AIO6789_POL_AH, and pac5xxx_tile_register_write().
void init_emux (void)
Definition at line 156 of file board_pac5256evk1.c.
{
    // Manually set ADC EMUX so that first sequencer conversion is correct
    PAC5XXX_ADC->EMUXCTL.EMUXC = 0; // Set EMUX to manual mode
    PAC5XXX_ADC->EMUXDATA.VAL = SIGMGR_AIO10; // Set EMUX to AIO10
    PAC5XXX_ADC->EMUXCTL.EMUXC = 1; // Set EMUX to ADC DTSE mode
}
References PAC5XXX_ADC.
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.