.TH "pac_foc/pac52xx/device Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/device Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdebug_io\&.h\fP"
.br
.ti -1c
.RI "file \fBdevice_5220\&.h\fP"
.br
.RI "Use for 5220 device definition\&. "
.ti -1c
.RI "file \fBdevice_5222\&.h\fP"
.br
.RI "Use for 5222 device definition\&. "
.ti -1c
.RI "file \fBdevice_5223\&.h\fP"
.br
.RI "Use for 5223 device definition\&. "
.ti -1c
.RI "file \fBdevice_5232\&.h\fP"
.br
.RI "Use for 5232 device definition\&. "
.ti -1c
.RI "file \fBdevice_5250\&.h\fP"
.br
.RI "Use for 5250 device definition\&. "
.ti -1c
.RI "file \fBdevice_5253\&.h\fP"
.br
.RI "Use for 5253 device definition\&. "
.ti -1c
.RI "file \fBdevice_5256\&.h\fP"
.br
.RI "Use for 5256 device definition\&. "
.ti -1c
.RI "file \fBdevice_5285\&.h\fP"
.br
.RI "Use for 5285 device definition\&. "
.ti -1c
.RI "file \fBdevice_options\&.h\fP"
.br
.RI "Use for driver port definition\&. "
.ti -1c
.RI "file \fBfamily_52xx\&.c\fP"
.br
.RI "Use for 52xx family hardware resources initialization\&. "
.ti -1c
.RI "file \fBfamily_52xx\&.h\fP"
.br
.RI "Use for 52xx family hardware resources initialization\&. "
.in -1c
