.TH "pac_foc/pac52xx/pac5xxx_sdk Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBpac5xxx_boot_COIDE\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_boot_gcc\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_boot_IAR\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_boot_KEIL\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_device\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_drivers\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_peripheral\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpac5xxx_sdk_version\&.h\fP"
.br
.RI "SDK Version\&. "
.in -1c
