.TH "pac_foc/pac52xx/board Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/board Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBboard\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_custom_1\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_custom_1\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_ep5223lvm1_1\&.c\fP"
.br
.RI "EP5223LVM1-1 Board Configuration Functions\&. "
.ti -1c
.RI "file \fBboard_ep5223lvm1_1\&.h\fP"
.br
.RI "EP5223LVM1-1 Board Configuration Definitions\&. "
.ti -1c
.RI "file \fBboard_ep5223lvm1_1_1shunt\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_ep5223lvm1_1_1shunt\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_ep5223lvm1_1_1shunt_pwr2\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_ep5223lvm1_1_1shunt_pwr2\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_ep5250hphvm1_2\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_ep5250hphvm1_2\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_ep5250hphvm1_2_1shunt\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_ep5250hphvm1_2_1shunt\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_ep5285lvm1_1\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_ep5285lvm1_1\&.h\fP"
.br
.RI "EP5285LVM1-1 Board Configuration Definitions\&. "
.ti -1c
.RI "file \fBboard_options\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_pac5222evk1\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_pac5222evk1\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_pac5232evk1\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_pac5232evk1\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_pac5232evk1_1shunt\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_pac5232evk1_1shunt\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_pac5256evk1\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_pac5256evk1\&.h\fP"
.br
.ti -1c
.RI "file \fBboard_pac5256evk1_1shunt\&.c\fP"
.br
.ti -1c
.RI "file \fBboard_pac5256evk1_1shunt\&.h\fP"
.br
.ti -1c
.RI "file \fBconfig_board\&.h\fP"
.br
.RI "Use for selecting different motor control EVK's boards\&. "
.in -1c
