.TH "pac_foc/pac52xx Directory Reference" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBboard\fP"
.br
.ti -1c
.RI "directory \fBcmsis_core\fP"
.br
.ti -1c
.RI "directory \fBdevice\fP"
.br
.ti -1c
.RI "directory \fBeclipse_proj\fP"
.br
.ti -1c
.RI "directory \fBiar_proj\fP"
.br
.ti -1c
.RI "directory \fBkeil_proj\fP"
.br
.ti -1c
.RI "directory \fBpac5xxx_sdk\fP"
.br
.in -1c
