.TH "CMSIS_CM0_NVIC" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_CM0_NVIC \- CMSIS CM0 NVIC
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCMSIS CM0 SCB\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
memory mapped structure for Nested Vectored Interrupt Controller (NVIC) 
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
