.TH "CMSIS_CM0_Core_FunctionInterface" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_CM0_Core_FunctionInterface \- CMSIS CM0 Core Function Interface
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Core Function Interface containing:
.IP "\(bu" 2
Core NVIC Functions
.IP "\(bu" 2
Core SysTick Functions
.IP "\(bu" 2
Core Reset Functions 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
