.TH "pac_foc/pac52xx/cmsis_core/core_cm0.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/cmsis_core/core_cm0.h \- CMSIS Cortex-M0 Core Peripheral Access Layer Header File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.ti -1c
.RI "struct \fBSCB_Type\fP"
.br
.ti -1c
.RI "struct \fBSysTick_Type\fP"
.br
.ti -1c
.RI "struct \fBCoreDebug_Type\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CM0_CMSIS_VERSION_MAIN\fP   (0x01)"
.br
.ti -1c
.RI "#define \fB__CM0_CMSIS_VERSION_SUB\fP   (0x30)"
.br
.ti -1c
.RI "#define \fB__CM0_CMSIS_VERSION\fP   ((\fB__CM0_CMSIS_VERSION_MAIN\fP << 16) | \fB__CM0_CMSIS_VERSION_SUB\fP)"
.br
.ti -1c
.RI "#define \fB__CORTEX_M\fP   (0x00)"
.br
.ti -1c
.RI "#define \fB__NVIC_PRIO_BITS\fP   2"
.br
.ti -1c
.RI "#define \fB__I\fP   volatile const"
.br
.ti -1c
.RI "#define \fB__O\fP   volatile"
.br
.ti -1c
.RI "#define \fB__IO\fP   volatile"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Pos\fP   24"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_IMPLEMENTER_Msk\fP   (0xFFul << \fBSCB_CPUID_IMPLEMENTER_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Pos\fP   20"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_VARIANT_Msk\fP   (0xFul << \fBSCB_CPUID_VARIANT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_ARCHITECTURE_Msk\fP   (0xFul << \fBSCB_CPUID_ARCHITECTURE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Pos\fP   4"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_PARTNO_Msk\fP   (0xFFFul << \fBSCB_CPUID_PARTNO_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSCB_CPUID_REVISION_Msk\fP   (0xFul << \fBSCB_CPUID_REVISION_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_NMIPENDSET_Pos\fP   31"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_NMIPENDSET_Msk\fP   (1ul << \fBSCB_ICSR_NMIPENDSET_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Pos\fP   28"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVSET_Msk\fP   (1ul << \fBSCB_ICSR_PENDSVSET_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Pos\fP   27"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSVCLR_Msk\fP   (1ul << \fBSCB_ICSR_PENDSVCLR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Pos\fP   26"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTSET_Msk\fP   (1ul << \fBSCB_ICSR_PENDSTSET_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Pos\fP   25"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_PENDSTCLR_Msk\fP   (1ul << \fBSCB_ICSR_PENDSTCLR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Pos\fP   23"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPREEMPT_Msk\fP   (1ul << \fBSCB_ICSR_ISRPREEMPT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Pos\fP   22"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_ISRPENDING_Msk\fP   (1ul << \fBSCB_ICSR_ISRPENDING_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Pos\fP   12"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTPENDING_Msk\fP   (0x1FFul << \fBSCB_ICSR_VECTPENDING_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSCB_ICSR_VECTACTIVE_Msk\fP   (0x1FFul << \fBSCB_ICSR_VECTACTIVE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEY_Msk\fP   (0xFFFFul << \fBSCB_AIRCR_VECTKEY_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTKEYSTAT_Msk\fP   (0xFFFFul << \fBSCB_AIRCR_VECTKEYSTAT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Pos\fP   15"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_ENDIANESS_Msk\fP   (1ul << \fBSCB_AIRCR_ENDIANESS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_SYSRESETREQ_Msk\fP   (1ul << \fBSCB_AIRCR_SYSRESETREQ_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBSCB_AIRCR_VECTCLRACTIVE_Msk\fP   (1ul << \fBSCB_AIRCR_VECTCLRACTIVE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Pos\fP   4"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SEVONPEND_Msk\fP   (1ul << \fBSCB_SCR_SEVONPEND_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPDEEP_Msk\fP   (1ul << \fBSCB_SCR_SLEEPDEEP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBSCB_SCR_SLEEPONEXIT_Msk\fP   (1ul << \fBSCB_SCR_SLEEPONEXIT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKALIGN_Pos\fP   9"
.br
.ti -1c
.RI "#define \fBSCB_CCR_STKALIGN_Msk\fP   (1ul << \fBSCB_CCR_STKALIGN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Pos\fP   3"
.br
.ti -1c
.RI "#define \fBSCB_CCR_UNALIGN_TRP_Msk\fP   (1ul << \fBSCB_CCR_UNALIGN_TRP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Pos\fP   15"
.br
.ti -1c
.RI "#define \fBSCB_SHCSR_SVCALLPENDED_Msk\fP   (1ul << \fBSCB_SHCSR_SVCALLPENDED_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Pos\fP   4"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_EXTERNAL_Msk\fP   (1ul << \fBSCB_DFSR_EXTERNAL_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Pos\fP   3"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_VCATCH_Msk\fP   (1ul << \fBSCB_DFSR_VCATCH_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_DWTTRAP_Msk\fP   (1ul << \fBSCB_DFSR_DWTTRAP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_BKPT_Msk\fP   (1ul << \fBSCB_DFSR_BKPT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSCB_DFSR_HALTED_Msk\fP   (1ul << \fBSCB_DFSR_HALTED_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_COUNTFLAG_Msk\fP   (1ul << \fBSysTick_CTRL_COUNTFLAG_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_CLKSOURCE_Msk\fP   (1ul << \fBSysTick_CTRL_CLKSOURCE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_TICKINT_Msk\fP   (1ul << \fBSysTick_CTRL_TICKINT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSysTick_CTRL_ENABLE_Msk\fP   (1ul << \fBSysTick_CTRL_ENABLE_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSysTick_LOAD_RELOAD_Msk\fP   (0xFFFFFFul << \fBSysTick_LOAD_RELOAD_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSysTick_VAL_CURRENT_Msk\fP   (0xFFFFFFul << \fBSysTick_VAL_CURRENT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Pos\fP   31"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_NOREF_Msk\fP   (1ul << \fBSysTick_CALIB_NOREF_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Pos\fP   30"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_SKEW_Msk\fP   (1ul << \fBSysTick_CALIB_SKEW_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBSysTick_CALIB_TENMS_Msk\fP   (0xFFFFFFul << \fBSysTick_VAL_CURRENT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_DBGKEY_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_DBGKEY_Msk\fP   (0xFFFFul << \fBCoreDebug_DHCSR_DBGKEY_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESET_ST_Pos\fP   25"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RESET_ST_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_RESET_ST_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RETIRE_ST_Pos\fP   24"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_RETIRE_ST_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_RETIRE_ST_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_LOCKUP_Pos\fP   19"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_LOCKUP_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_LOCKUP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_SLEEP_Pos\fP   18"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_SLEEP_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_SLEEP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_HALT_Pos\fP   17"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_HALT_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_HALT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_REGRDY_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_S_REGRDY_Msk\fP   (1ul << \fBCoreDebug_DHCSR_S_REGRDY_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_MASKINTS_Pos\fP   3"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_MASKINTS_Msk\fP   (1ul << \fBCoreDebug_DHCSR_C_MASKINTS_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_STEP_Pos\fP   2"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_STEP_Msk\fP   (1ul << \fBCoreDebug_DHCSR_C_STEP_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_HALT_Pos\fP   1"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_HALT_Msk\fP   (1ul << \fBCoreDebug_DHCSR_C_HALT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_DEBUGEN_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBCoreDebug_DHCSR_C_DEBUGEN_Msk\fP   (1ul << \fBCoreDebug_DHCSR_C_DEBUGEN_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGWnR_Pos\fP   16"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGWnR_Msk\fP   (1ul << \fBCoreDebug_DCRSR_REGWnR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGSEL_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBCoreDebug_DCRSR_REGSEL_Msk\fP   (0x1Ful << \fBCoreDebug_DCRSR_REGSEL_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_DWTENA_Pos\fP   24"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_DWTENA_Msk\fP   (1ul << \fBCoreDebug_DEMCR_DWTENA_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_HARDERR_Pos\fP   10"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_HARDERR_Msk\fP   (1ul << \fBCoreDebug_DEMCR_VC_HARDERR_Pos\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CORERESET_Pos\fP   0"
.br
.ti -1c
.RI "#define \fBCoreDebug_DEMCR_VC_CORERESET_Msk\fP   (1ul << \fBCoreDebug_DEMCR_VC_CORERESET_Pos\fP)"
.br
.ti -1c
.RI "#define \fBSCS_BASE\fP   (0xE000E000)"
.br
.ti -1c
.RI "#define \fBCoreDebug_BASE\fP   (0xE000EDF0)"
.br
.ti -1c
.RI "#define \fBSysTick_BASE\fP   (\fBSCS_BASE\fP +  0x0010)"
.br
.ti -1c
.RI "#define \fBNVIC_BASE\fP   (\fBSCS_BASE\fP +  0x0100)"
.br
.ti -1c
.RI "#define \fBSCB_BASE\fP   (\fBSCS_BASE\fP +  0x0D00)"
.br
.ti -1c
.RI "#define \fBSCB\fP   ((\fBSCB_Type\fP *)           \fBSCB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBSysTick\fP   ((\fBSysTick_Type\fP *)       \fBSysTick_BASE\fP)"
.br
.ti -1c
.RI "#define \fBNVIC\fP   ((\fBNVIC_Type\fP *)          \fBNVIC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBCoreDebug\fP   ((\fBCoreDebug_Type\fP *)     \fBCoreDebug_BASE\fP)"
.br
.ti -1c
.RI "#define \fB_BIT_SHIFT\fP(\fBIRQn\fP)   (  (((uint32_t)(\fBIRQn\fP)       )    &  0x03) * 8 )"
.br
.ti -1c
.RI "#define \fB_SHP_IDX\fP(\fBIRQn\fP)   ( ((((uint32_t)(\fBIRQn\fP) & 0x0F)\-8) >>    2)     )"
.br
.ti -1c
.RI "#define \fB_IP_IDX\fP(\fBIRQn\fP)   (   ((uint32_t)(\fBIRQn\fP)            >>    2)     )"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M0 Core Peripheral Access Layer Header File\&. 


.PP
\fBVersion\fP
.RS 4
V1\&.30 
.RE
.PP
\fBDate\fP
.RS 4
30\&. October 2009
.RE
.PP
\fBNote\fP
.RS 4
Copyright (C) 2009 ARM Limited\&. All rights reserved\&.
.RE
.PP
\fB\fP
.RS 4
ARM Limited (ARM) is supplying this software for use with Cortex-M processor based microcontrollers\&. This file can be freely distributed within development tools that are supporting such ARM based processors\&.
.RE
.PP
\fB\fP
.RS 4
THIS SOFTWARE IS PROVIDED 'AS IS'\&. NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE\&. ARM SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER\&. 
.RE
.PP

.PP
Definition in file \fBcore_cm0\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
