.TH "pac_foc/pac52xx/device/device_options.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/device/device_options.h \- Use for driver port definition\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDRV_PA0\fP   0"
.br
.ti -1c
.RI "#define \fBDRV_PA1\fP   1"
.br
.ti -1c
.RI "#define \fBDRV_PA2\fP   2"
.br
.ti -1c
.RI "#define \fBDRV_PA3\fP   3"
.br
.ti -1c
.RI "#define \fBDRV_PA4\fP   4"
.br
.ti -1c
.RI "#define \fBDRV_PA5\fP   5"
.br
.ti -1c
.RI "#define \fBDRV_PA6\fP   6"
.br
.ti -1c
.RI "#define \fBDRV_PA7\fP   7"
.br
.ti -1c
.RI "#define \fBDRV_PD0\fP   (8 + 0)"
.br
.ti -1c
.RI "#define \fBDRV_PD1\fP   (8 + 1)"
.br
.ti -1c
.RI "#define \fBDRV_PD2\fP   (8 + 2)"
.br
.ti -1c
.RI "#define \fBDRV_PD3\fP   (8 + 3)"
.br
.ti -1c
.RI "#define \fBDRV_PD4\fP   (8 + 4)"
.br
.ti -1c
.RI "#define \fBDRV_PD5\fP   (8 + 5)"
.br
.ti -1c
.RI "#define \fBDRV_PD6\fP   (8 + 6)"
.br
.ti -1c
.RI "#define \fBDRV_PD7\fP   (8 + 7)"
.br
.ti -1c
.RI "#define \fBDRV_PB0\fP   (16 + 0)"
.br
.ti -1c
.RI "#define \fBDRV_PB1\fP   (16 + 1)"
.br
.ti -1c
.RI "#define \fBDRV_PB2\fP   (16 + 2)"
.br
.ti -1c
.RI "#define \fBDRV_PB3\fP   (16 + 3)"
.br
.ti -1c
.RI "#define \fBDRV_PB4\fP   (16 + 4)"
.br
.ti -1c
.RI "#define \fBDRV_PB5\fP   (16 + 5)"
.br
.ti -1c
.RI "#define \fBDRV_PB6\fP   (16 + 6)"
.br
.ti -1c
.RI "#define \fBDRV_PB7\fP   (16 + 7)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use for driver port definition\&. 


.PP
Definition in file \fBdevice_options\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DRV_PA0   0"

.PP
Definition at line 15 of file device_options\&.h\&.
.SS "#define DRV_PA1   1"

.PP
Definition at line 16 of file device_options\&.h\&.
.SS "#define DRV_PA2   2"

.PP
Definition at line 17 of file device_options\&.h\&.
.SS "#define DRV_PA3   3"

.PP
Definition at line 18 of file device_options\&.h\&.
.SS "#define DRV_PA4   4"

.PP
Definition at line 19 of file device_options\&.h\&.
.SS "#define DRV_PA5   5"

.PP
Definition at line 20 of file device_options\&.h\&.
.SS "#define DRV_PA6   6"

.PP
Definition at line 21 of file device_options\&.h\&.
.SS "#define DRV_PA7   7"

.PP
Definition at line 22 of file device_options\&.h\&.
.SS "#define DRV_PB0   (16 + 0)"

.PP
Definition at line 33 of file device_options\&.h\&.
.SS "#define DRV_PB1   (16 + 1)"

.PP
Definition at line 34 of file device_options\&.h\&.
.SS "#define DRV_PB2   (16 + 2)"

.PP
Definition at line 35 of file device_options\&.h\&.
.SS "#define DRV_PB3   (16 + 3)"

.PP
Definition at line 36 of file device_options\&.h\&.
.SS "#define DRV_PB4   (16 + 4)"

.PP
Definition at line 37 of file device_options\&.h\&.
.SS "#define DRV_PB5   (16 + 5)"

.PP
Definition at line 38 of file device_options\&.h\&.
.SS "#define DRV_PB6   (16 + 6)"

.PP
Definition at line 39 of file device_options\&.h\&.
.SS "#define DRV_PB7   (16 + 7)"

.PP
Definition at line 40 of file device_options\&.h\&.
.SS "#define DRV_PD0   (8 + 0)"

.PP
Definition at line 24 of file device_options\&.h\&.
.SS "#define DRV_PD1   (8 + 1)"

.PP
Definition at line 25 of file device_options\&.h\&.
.SS "#define DRV_PD2   (8 + 2)"

.PP
Definition at line 26 of file device_options\&.h\&.
.SS "#define DRV_PD3   (8 + 3)"

.PP
Definition at line 27 of file device_options\&.h\&.
.SS "#define DRV_PD4   (8 + 4)"

.PP
Definition at line 28 of file device_options\&.h\&.
.SS "#define DRV_PD5   (8 + 5)"

.PP
Definition at line 29 of file device_options\&.h\&.
.SS "#define DRV_PD6   (8 + 6)"

.PP
Definition at line 30 of file device_options\&.h\&.
.SS "#define DRV_PD7   (8 + 7)"

.PP
Definition at line 31 of file device_options\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
