pac_foc/pac52xx/device/family_52xx.h
NAME
pac_foc/pac52xx/device/family_52xx.h - Use for 52xx family hardware resources initialization.
SYNOPSIS
#include 'pac5xxx.h'
#include 'device_options.h'
#include 'pac5xxx_driver_gpio.h'
#include 'pac5xxx_driver_timer.h'
#include 'config_debug.h'
Macros
#define FAMILY_52XX
#define VMS100_ADDRESS 0x0010003C
#define VMS200_ADDRESS 0x0010003E
#define ADC_CHANNEL_MASK (1L << ADCCTL_ADMUX_AD0)
#define NIRQ1_PIN 0
#define NIRQ1_PIN_MASK (1 << NIRQ1_PIN)
Functions
void init_system (void)
init_system, use to setup PLL, system clock and flash wait state
void configure_cafe_fault_interrupt (void)
configure_cafe_fault_interrupt, configure over current interrupt from AFE
void configure_foc_timer (void)
configure_foc_timer, configure main FOC PWM timer
void configure_adc_emux_engine (void)
configure_adc_emux_engine, configure ADC EMUX for sending channel selection data
void configure_pwm_dac (void)
configure_pwm_dac, configure PWM timer for DAC outputs
void uart_scratch_write (int32_t value)
uart_scratch_write, function to write to UART scratch register
int32_t uart_scratch_read (void)
uart_scratch_read, function use to read data from UART scratch register
void initialize_foc_timer_seq_trigger_value (int32_t ccr_trig_value)
initialize_foc_timer_seq_trigger_value, use to initialize sequencer0 and 1 triggers
void initialize_foc_timer_seq_trigger_value_ccr0_ccr1 (int32_t ccr_trig_value)
initialize_foc_timer_seq_trigger_value_ccr0_ccr1, use to initialize sequencer0 and sequencer1 trigger
void initialize_socbridge_clk_divider (void)
initialize_socbridge_clk_divider, use to set clock divider of SOC bridge
Detailed Description
Use for 52xx family hardware resources initialization.
Definition in file family_52xx.h.
Macro Definition Documentation
#define ADC_CHANNEL_MASK (1L << ADCCTL_ADMUX_AD0)
Definition at line 36 of file family_52xx.h.
#define FAMILY_52XX
Definition at line 23 of file family_52xx.h.
#define NIRQ1_PIN 0
Definition at line 39 of file family_52xx.h.
#define NIRQ1_PIN_MASK (1 << NIRQ1_PIN)
Definition at line 40 of file family_52xx.h.
#define VMS100_ADDRESS 0x0010003C
Definition at line 32 of file family_52xx.h.
#define VMS200_ADDRESS 0x0010003E
Definition at line 33 of file family_52xx.h.
Function Documentation
void configure_adc_emux_engine (void)
configure_adc_emux_engine, configure ADC EMUX for sending channel selection data
Definition at line 128 of file family_52xx.c.
{
    // EMUX configuration
    // ADCEMUXCTRL DIVIDER is coming from config_app.h
    pac5xxx_adc_emux_config(ADCEMUXCTL_EMUXC_SEQ, ADCEMUXCTRL_EMUXDIV); // Configure EMUX to do conversions from ADC sequencer, /2 EMUX divider (HCLK=50MHz/2 = 25MHz)
    pac5xxx_adc_config_emux_io(); // Configure device IO for EMUX
    // ADC Configuration
    pac5xxx_adc_config_io(ADC_CHANNEL_MASK); // Configure device IO for ADC conversions (as Analog inputs)
}
References ADC_CHANNEL_MASK, ADCEMUXCTL_EMUXC_SEQ, pac5xxx_adc_config_emux_io(), pac5xxx_adc_config_io(), and pac5xxx_adc_emux_config().
void configure_cafe_fault_interrupt (void)
configure_cafe_fault_interrupt, configure over current interrupt from AFE
Definition at line 70 of file family_52xx.c.
{
    // Configure nIRQ1, CAFE fault interrupt, as digital input - active low
    pac5xxx_gpio_configure_interrupt_b(NIRQ1_PIN_MASK, 0);
    #ifdef ENABLE_CBC_CURRENT_LIMIT
        NVIC_SetPriority(GpioB_IRQn,0);
    #else
        NVIC_SetPriority(GpioB_IRQn,3);
    #endif
}
References NIRQ1_PIN_MASK, and pac5xxx_gpio_configure_interrupt_b().
void configure_foc_timer (void)
configure_foc_timer, configure main FOC PWM timer
Definition at line 84 of file family_52xx.c.
{
    pac5xxx_timer_a_clear_assert(); // Hold timer clear signal, so timer slaves do not count
    // Configure Timer A Base
    pac5xxx_timer_clock_config(TimerA, TxCTL_CS_ACLK, TxCTL_PS_DIV1); // Configure timer clock input for ACLK (50MHz), /1 divider
    PAC5XXX_TIMERA->CTL.PRDL = 1; // 07102015, Latch new TAPRD value when timerA counting down, TACTR value = 0x01
    pac5xxx_timer_base_config(TimerA, motor.control.motor_period_ticks, 0, TxCTL_MODE_UPDOWN, 0); // Enable base timer
   //Configure Dead Time Generators
    pac5xxx_dtg_config(DTGA0, MOTOR1_LED_TICKS, MOTOR1_TED_TICKS, 0, 0, 0, 0); // Configure DTGA0 for phase U
    pac5xxx_dtg_config(DTGA1, MOTOR1_LED_TICKS, MOTOR1_TED_TICKS, 0, 0, 0, 0); // Configure DTGA1 for phase V
    pac5xxx_dtg_config(DTGA2, MOTOR1_LED_TICKS, MOTOR1_TED_TICKS, 0, 0, 0, 0); // Configure DTGA2 for phase W
    pac5xxx_timer_a_clear_deassert(); // Release timer clear signal, all timers now in sync and start counting
    // Enable TACCR0 interrupt
#if 0
    pac5xxx_timer_cctrl_int_enable(TimerA, 0, 1); // Enable interrupts on TACCR0
#endif
}
void configure_pwm_dac (void)
configure_pwm_dac, configure PWM timer for DAC outputs
Definition at line 110 of file family_52xx.c.
{
#ifdef ENABLE_DEBUG_PWMDAC
    pac5xxx_timer_clock_config(TimerB, TxCTL_CS_ACLK, TxCTL_PS_DIV1); // Configure timer clock input for ACLK (100MHz), /1 divider
    pac5xxx_timer_clock_config(TimerC, TxCTL_CS_ACLK, TxCTL_PS_DIV1); // Configure timer clock input for ACLK (100MHz), /1 divider (must match timer B)
    pac5xxx_timer_clock_config(TimerD, TxCTL_CS_ACLK, TxCTL_PS_DIV1); // Configure timer clock input for ACLK (100MHz), /1 divider (must match timer B)
    pac5xxx_timer_base_config(TimerB, PWMDAC_PERIOD_TICKS, 0, TxCTL_MODE_UPDOWN, 1); // Configure Timer B as sync slave
    pac5xxx_timer_base_config(TimerC, PWMDAC_PERIOD_TICKS, 0, TxCTL_MODE_UPDOWN, 1); // Configure Timer C as sync slave
    pac5xxx_timer_base_config(TimerD, PWMDAC_PERIOD_TICKS, 0, TxCTL_MODE_UPDOWN, 1); // Configure Timer D as sync slave
    pwmdac_disable();
#endif
}
References pac5xxx_timer_base_config(), pac5xxx_timer_clock_config(), TimerB, TimerC, TimerD, TxCTL_CS_ACLK, TxCTL_MODE_UPDOWN, and TxCTL_PS_DIV1.
void init_system (void)
init_system, use to setup PLL, system clock and flash wait state
Definition at line 58 of file family_52xx.c.
{
    // PLL 50MHZ, FCLK: 50MHz, PLLCLK: 50MHz, ACLK: 50MHz (/1), HCLK: 50MHz (/1)
    // PLL CLK and FLASH wait state is coming from config_app.h
    pac5xxx_sys_pll_config(HCLK_FREQ_HZ/1000000);
    pac5xxx_sys_ccs_config(CCSCTL_CLKIN_CLKREF, CCSCTL_ACLKDIV_DIV1, CCSCTL_HCLKDIV_DIV1);
    pac5xxx_memctl_wait_state(FLASH_WAIT_STATE);
}
References CCSCTL_ACLKDIV_DIV1, CCSCTL_CLKIN_CLKREF, CCSCTL_HCLKDIV_DIV1, pac5xxx_memctl_wait_state(), pac5xxx_sys_ccs_config(), and pac5xxx_sys_pll_config().
void initialize_foc_timer_seq_trigger_value (int32_t ccr_trig_value)
initialize_foc_timer_seq_trigger_value, use to initialize sequencer0 and 1 triggers
Parameters
int32_t ccr_trig_value
Definition at line 274 of file family_52xx.c.
{
#if (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT)
    extern Struct_Motor motor;
#endif
#if (CONFIG_SHUNT == CONFIG_SHUNT_3SHUNT) || (CONFIG_SHUNT == CONFIG_SHUNT_2SHUNT)
    pac5xxx_timer_a_ccctr0_value_set(ccr_trig_value - 4); // Set value for AS0 trigger at triangle peak (PWM center)
#elif (CONFIG_SHUNT == CONFIG_SHUNT_1SHUNT)
    motor.oneshunt.taccr0_value = (ccr_trig_value >> 1);
    motor.oneshunt.taccr1_value = (ccr_trig_value >> 1);
    pac5xxx_timer_a_ccctr0_value_set(ccr_trig_value >> 1); // Set value for AS0 trigger at triangle peak (PWM center)
    pac5xxx_timer_a_ccctr1_value_set(ccr_trig_value >> 1); // Set value for AS0 trigger at triangle peak (PWM center)
#endif
}
void initialize_foc_timer_seq_trigger_value_ccr0_ccr1 (int32_t ccr_trig_value)
initialize_foc_timer_seq_trigger_value_ccr0_ccr1, use to initialize sequencer0 and sequencer1 trigger
Parameters
int32_t ccr_trig_value
Definition at line 294 of file family_52xx.c.
{
    pac5xxx_timer_a_ccctr0_value_set(ccr_trig_value); // Set value for AS0 trigger at triangle peak (PWM center)
    pac5xxx_timer_a_ccctr1_value_set(ccr_trig_value); // Set value for AS0 trigger at triangle peak (PWM center)
}
void initialize_socbridge_clk_divider (void)
initialize_socbridge_clk_divider, use to set clock divider of SOC bridge
Parameters
int32_t valuee
Definition at line 315 of file family_52xx.c.
{
    PAC5XXX_SOCBRIDGE->SOCBCLKDIV.VAL = SOC_BRIDGE_CLK_DIVIDER; // SPI CLK = 12.5 MHz = HCLK_FREQ_HZ/ ((CLKDIV + 1) * 2)
}
References PAC5XXX_SOCBRIDGE.
int32_t uart_scratch_read (void)
uart_scratch_read, function use to read data from UART scratch register
Returns
int32_t 32 bit data
Definition at line 255 of file family_52xx.c.
{
    // Return the value stored in the UART Scratch Pad Register
    return PAC5XXX_UART->SP.VAL;
}
References PAC5XXX_UART.
void uart_scratch_write (int32_t value)
uart_scratch_write, function to write to UART scratch register
Parameters
int32_t value
Definition at line 244 of file family_52xx.c.
{
    // Set the UART Scratch Pad Register value
    PAC5XXX_UART->SP.VAL = value; // CRC Passed-value=0; CRC Failed-value=1 (i.e. non zero)
}
References PAC5XXX_UART.
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.