.TH "GPIOA_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOA_Type \- General-Purpose Input-Output Port A (GPIOA)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnOE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnDS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnRUP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnRDN\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBGPIOnI\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnPSEL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTEN\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBGPIOnINT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General-Purpose Input-Output Port A (GPIOA) 
.PP
Definition at line 262 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
