.TH "GPIOC_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOC_Type \- General-Purpose Input-Output Port C (GPIOC)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnO\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnOE\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [3]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBGPIOnI\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnIE\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTEN\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBGPIOnINT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBGPIOnINTM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General-Purpose Input-Output Port C (GPIOC) 
.PP
Definition at line 287 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
