.TH "I2C_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Type \- I2C (I2C)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2CCFG\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBI2CINT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2CINTEN\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [9]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2CMACTL\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBI2CMARXDATA\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBI2CMATXDATA\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2CBAUD\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED2\fP [11]"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBI2CSLRXDATA\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBI2CSLTXDATA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBI2CSLADDR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C (I2C) 
.PP
Definition at line 506 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
