.TH "MEMCTL_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MEMCTL_Type \- FLASH Memory Controller (MEMCTL)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHLOCK\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHSTATUS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHPAGE\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHPERASE\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSWDACCESS\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHWSTATE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFLASHBWRITE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FLASH Memory Controller (MEMCTL) 
.PP
Definition at line 208 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
