.TH "NVIC_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NVIC_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm0\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISER\fP [1]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [31]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBICER\fP [1]"
.br
.ti -1c
.RI "uint32_t \fBRSERVED1\fP [31]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISPR\fP [1]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [31]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBICPR\fP [1]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [31]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [64]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIPR\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file core_cm0\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
