.TH "PAC52XX_Definitions" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC52XX_Definitions \- PAC52XX Definitions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDevice CMSIS Definitions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.br
.PP
This file defines all structures and symbols for PAC52XX:
.IP "\(bu" 2
registers and bitfields
.IP "\(bu" 2
peripheral base address
.IP "\(bu" 2
peripheral ID
.IP "\(bu" 2
Peripheral definitions 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
