.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_memory.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_memory.h \- Firmware driver for the PAC5XXX memory controller\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac52XX\&.h'\fP
.br
\fC#include 'pac5xxx_driver_config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAMFUNC_MEMORY\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_MEMORY\fP void \fBpac5xxx_memctl_flash_page_erase\fP (int page)"
.br
.RI "This function performs an erase of the given FLASH page\&. "
.ti -1c
.RI "\fBRAMFUNC_MEMORY\fP void \fBpac5xxx_memctl_flash_swr_enable_por\fP (int enabled)"
.br
.RI "This function configures SWR access during a power-on reset\&. "
.ti -1c
.RI "\fBRAMFUNC_MEMORY\fP void \fBpac5xxx_memctl_wait_state\fP (\fBMEMCTL_WaitState\fP wait_states)"
.br
.RI "This function configures the number of FLASH controller wait states\&. "
.ti -1c
.RI "\fBRAMFUNC_MEMORY\fP void \fBpac5xxx_memctl_buffered_write\fP (int segment, int address_offset, uint16_t data)"
.br
.RI "This function starts a buffered write operation with the given data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX memory controller\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_memory\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
