.TH "PAC5XXX_ADCRESULT_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_ADCRESULT_Type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_ADC\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__I\fP uint32_t \fBPAC5XXX_ADCRESULT_Type::s\fP: 16"
.br
.ti -1c
.RI "   uint32_t \fBPAC5XXX_ADCRESULT_Type::__pad0__\fP: 16"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__I\fP uint32_t \fBPAC5XXX_ADCRESULT_Type::b\fP: 8"
.br
.ti -1c
.RI "   uint32_t \fBPAC5XXX_ADCRESULT_Type::__pad0__\fP: 24"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fB__I\fP uint32_t \fBPAC5XXX_ADCRESULT_Type::VAL\fP: 10"
.br
.ti -1c
.RI "   uint32_t \fBPAC5XXX_ADCRESULT_Type::__pad0__\fP: 22"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file pac5xxx_ADC\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
