.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_ADC.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_ADC.h \- CMSIS Cortex-M Header File for the PAC5XXX ADC\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBPAC5XXX_ADCRESULT_Type\fP"
.br
.ti -1c
.RI "union \fBPAC5XXX_ADCSEQCTL_Type\fP"
.br
.ti -1c
.RI "struct \fBPAC5XXX_ADC_TypeDef\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBADC_EMUX_CTL_Type\fP { \fBADCEMUXCTL_EMUXC_MUXDATA\fP = 0, \fBADCEMUXCTL_EMUXC_SEQ\fP = 1 }"
.br
.ti -1c
.RI "enum \fBADC_EMUX_DIV_Type\fP { \fBADCEMUXCTL_EMUXDIV_DIV1\fP = 0, \fBADCEMUXCTL_EMUXDIV_DIV2\fP = 1, \fBADCEMUXCTL_EMUXDIV_DIV3\fP = 2, \fBADCEMUXCTL_EMUXDIV_DIV4\fP = 3, \fBADCEMUXCTL_EMUXDIV_DIV5\fP = 4, \fBADCEMUXCTL_EMUXDIV_DIV6\fP = 5, \fBADCEMUXCTL_EMUXDIV_DIV7\fP = 6, \fBADCEMUXCTL_EMUXDIV_DIV8\fP = 7 }"
.br
.ti -1c
.RI "enum \fBADCCTL_ADMODE_Type\fP { \fBADCCTL_ADSTART_SINGLE\fP = 0, \fBADCCTL_ADSTART_AUTO_0\fP = 1, \fBADCCTL_ADSTART_AUTO_1\fP = 2, \fBADCCTL_ADSTART_AUTO_01_CHAIN\fP = 3, \fBADCCTL_ADSTART_AUTO_0_TRIG\fP = 4, \fBADCCTL_ADSTART_AUTO_1_TRIG\fP = 5, \fBADCCTL_ADSTART_AUTO_01_CHAIN_TRIG\fP = 6, \fBADCCTL_ADSTART_AUTO_01_IND_TRIG\fP = 7 }"
.br
.ti -1c
.RI "enum \fBADCCTL_ADMUX_Type\fP { \fBADCCTL_ADMUX_AD0\fP = 0, \fBADCCTL_ADMUX_AD1\fP = 1, \fBADCCTL_ADMUX_AD2\fP = 2, \fBADCCTL_ADMUX_AD3\fP = 3, \fBADCCTL_ADMUX_AD4\fP = 4, \fBADCCTL_ADMUX_AD5\fP = 5, \fBADCCTL_ADMUX_VSSA\fP = 7 }"
.br
.ti -1c
.RI "enum \fBADCCTL_CLKDIV_Type\fP { \fBADCCTL_ADCDIV_DIV1\fP = 0, \fBADCCTL_ADCDIV_DIV2\fP = 1, \fBADCCTL_ADCDIV_DIV3\fP = 2, \fBADCCTL_ADCDIV_DIV4\fP = 3, \fBADCCTL_ADCDIV_DIV5\fP = 4, \fBADCCTL_ADCDIV_DIV6\fP = 5, \fBADCCTL_ADCDIV_DIV7\fP = 6, \fBADCCTL_ADCDIV_DIV8\fP = 7 }"
.br
.ti -1c
.RI "enum \fBADCCTLX_STRIG_Type\fP { \fBADCCTLX_ASTR_PWM\fP = 0, \fBADCCTLX_ASTR_TIMER\fP = 1 }"
.br
.ti -1c
.RI "enum \fBADCCTLX_SDEPTH_Type\fP { \fBADCCTLX_AS1D_DEPTH1\fP = 0, \fBADCCTLX_AS1D_DEPTH2\fP = 1, \fBADCCTLX_AS1D_DEPTH3\fP = 2, \fBADCCTLX_AS1D_DEPTH4\fP = 3, \fBADCCTLX_AS1D_DEPTH5\fP = 4, \fBADCCTLX_AS1D_DEPTH6\fP = 5, \fBADCCTLX_AS1D_DEPTH7\fP = 6, \fBADCCTLX_AS1D_DEPTH8\fP = 7 }"
.br
.ti -1c
.RI "enum \fBADCCTLX_TRIGEDGE_Type\fP { \fBADCCTLX_TRIGEDGE_LOWTOHI\fP = 0, \fBADCCTLX_TRIGEDGE_HITOLOW\fP = 1 }"
.br
.ti -1c
.RI "enum \fBADCCTLX_TRIGPWM_Type\fP { \fBADCCTLX_TRIGPWM_PWMA0\fP = 0, \fBADCCTLX_TRIGPWM_PWMA1\fP = 1, \fBADCCTLX_TRIGPWM_PWMA2\fP = 2, \fBADCCTLX_TRIGPWM_PWMA3\fP = 3, \fBADCCTLX_TRIGPWM_PWMA4\fP = 4, \fBADCCTLX_TRIGPWM_PWMA5\fP = 5, \fBADCCTLX_TRIGPWM_PWMA6\fP = 6, \fBADCCTLX_TRIGPWM_PWMA7\fP = 7, \fBADCCTLX_TRIGPWM_PWMB0\fP = 8, \fBADCCTLX_TRIGPWM_PWMB1\fP = 9, \fBADCCTLX_TRIGPWM_PWMC0\fP = 10, \fBADCCTLX_TRIGPWM_PWMC1\fP = 11, \fBADCCTLX_TRIGPWM_PWMD0\fP = 12, \fBADCCTLX_TRIGPWM_PWMD1\fP = 13 }"
.br
.ti -1c
.RI "enum \fBADCCTLX_TRIGTIMER_Type\fP { \fBADCCTLX_TRIGTIM_TIMERA\fP = 0, \fBADCCTLX_TRIGTIM_TIMERB\fP = 1, \fBADCCTLX_TRIGTIM_TIMERC\fP = 2, \fBADCCTLX_TRIGTIM_TIMERD\fP = 3 }"
.br
.ti -1c
.RI "enum \fBASSEQ_DELAY_Type\fP { \fBASSEQ_DELAY_0\fP = 0, \fBASSEQ_DELAY_4\fP = 1, \fBASSEQ_DELAY_8\fP = 2, \fBASSEQ_DELAY_16\fP = 3 }"
.br
.ti -1c
.RI "enum \fBASSEQ_MSPI_Type\fP { \fBASSEQ_MSPI_NOSEND\fP = 0, \fBASSEQ_MSPI_BEG\fP = 1, \fBASSEQ_MSPI_AFTER_SH\fP = 2 }"
.br
.ti -1c
.RI "enum \fBASCINT_SEQ_Type\fP { \fBASCINT_SEQ_0\fP = 1, \fBASCINT_SEQ_1\fP = 2 }"
.br
.ti -1c
.RI "enum \fBADCINT_BITS\fP { \fBADCINT_ADCINT\fP = 0x01, \fBADCINT_EMUXINT\fP = 0x02, \fBADCINT_AS0INT\fP = 0x04, \fBADCINT_AS1INT\fP = 0x08, \fBADCINT_ASCINT\fP = 0x10, \fBADCINT_ALL\fP = 0x1F }"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M Header File for the PAC5XXX ADC\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_ADC\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
