.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_timer_cctrl_int.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_timer_cctrl_int.c \- Firmware driver for the PAC5XXX capture/compare unit interrupt configuration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_TIMER\fP void \fBpac5xxx_timer_cctrl_int_enable\fP (\fBTimerInstance\fP timer, int ccr_num, int enable)"
.br
.RI "This function configures sets the interrupt enable state for the given timer and CCR unit\&. "
.ti -1c
.RI "\fBRAMFUNC_TIMER\fP int \fBpac5xxx_timer_cctrl_int\fP (\fBTimerInstance\fP timer, int ccr_num)"
.br
.RI "This function indicates if there is a pending interrupt on the given timer and CCR unit\&. "
.ti -1c
.RI "\fBRAMFUNC_TIMER\fP void \fBpac5xxx_timer_cctrl_int_clear\fP (\fBTimerInstance\fP timer, int ccr_num)"
.br
.RI "This function clears the interrupt flag for the given timer and CCR unit\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX capture/compare unit interrupt configuration\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_timer_cctrl_int\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
