.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_adc_config.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_adc_config.c \- Firmware driver for the PAC5XXX ADC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config\fP (\fBADCCTL_ADMODE_Type\fP adc_mode, \fBADCCTL_CLKDIV_Type\fP clock_divider, int repeat)"
.br
.RI "This function configures the ADC\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config_io\fP (unsigned char channel_mask)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX ADC\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_adc_config\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_config_io (unsigned char channel_mask)"

.PP
Definition at line 28 of file pac5xxx_driver_adc_config\&.c\&.
.PP
.nf
29 {
30   // Need to explictly disable OUTEN and INEN
31   PAC5XXX_GPIOC->OUTEN\&.b &= ~channel_mask;
32   PAC5XXX_GPIOC->INE\&.b &= ~channel_mask;
33  
34 }
.fi
.PP
References PAC5XXX_GPIOC\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
