.TH "PAC5XXX_PeripheralDecl" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_PeripheralDecl \- PAC5XXX Peripheral Declaration
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPAC5XXX_SYSCTL\fP   ((\fBPAC5XXX_SYSCLKCTL_TypeDef\fP *) \fBPAC5XXX_SYSCTL_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_MEMCTL\fP   ((\fBPAC5XXX_MEMCTL_TypeDef\fP *) \fBPAC5XXX_MEMCTL_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_WDT\fP   ((\fBPAC5XXX_WDT_TypeDef\fP *) \fBPAC5XXX_WDT_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_RTC\fP   ((\fBPAC5XXX_RTC_TypeDef\fP *) \fBPAC5XXX_RTC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOA\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOA_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOB\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOAB\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOAB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOC\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOD\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOD_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOCD\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOCD_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_GPIOE\fP   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOE_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_TIMERA\fP   ((\fBPAC5XXX_Timer8CC_TypeDef\fP *) \fBPAC5XXX_TIMERA_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_TIMERB\fP   ((\fBPAC5XXX_Timer4CC_TypeDef\fP *) \fBPAC5XXX_TIMERB_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_TIMERC\fP   ((\fBPAC5XXX_Timer2CC_TypeDef\fP *) \fBPAC5XXX_TIMERC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_TIMERD\fP   ((\fBPAC5XXX_Timer2CC_TypeDef\fP *) \fBPAC5XXX_TIMERD_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_ADC\fP   ((\fBPAC5XXX_ADC_TypeDef\fP *) \fBPAC5XXX_ADC_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_I2C\fP   ((\fBPAC5XXX_I2C_TypeDef\fP *) \fBPAC5XXX_I2C_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_UART\fP   ((\fBPAC5XXX_UART_TypeDef\fP *) \fBPAC5XXX_UART_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_SPI\fP   ((\fBPAC5XXX_SPI_TypeDef\fP *) \fBPAC5XXX_SPI_BASE\fP)"
.br
.ti -1c
.RI "#define \fBPAC5XXX_SOCBRIDGE\fP   ((\fBPAC5XXX_SocBridge_TypeDef\fP *) \fBPAC5XXX_SOCBRIDGE_BASE\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PAC5XXX_ADC   ((\fBPAC5XXX_ADC_TypeDef\fP *) \fBPAC5XXX_ADC_BASE\fP)"

.PP
Definition at line 2888 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOA   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOA_BASE\fP)"

.PP
Definition at line 2877 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOAB   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOAB_BASE\fP)"

.PP
Definition at line 2879 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOB   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOB_BASE\fP)"

.PP
Definition at line 2878 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOC   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOC_BASE\fP)"

.PP
Definition at line 2880 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOCD   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOCD_BASE\fP)"

.PP
Definition at line 2882 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOD   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOD_BASE\fP)"

.PP
Definition at line 2881 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_GPIOE   ((\fBPAC5XXX_GPIO_TypeDef\fP *) \fBPAC5XXX_GPIOE_BASE\fP)"

.PP
Definition at line 2883 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_I2C   ((\fBPAC5XXX_I2C_TypeDef\fP *) \fBPAC5XXX_I2C_BASE\fP)"

.PP
Definition at line 2889 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_MEMCTL   ((\fBPAC5XXX_MEMCTL_TypeDef\fP *) \fBPAC5XXX_MEMCTL_BASE\fP)"

.PP
Definition at line 2874 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_RTC   ((\fBPAC5XXX_RTC_TypeDef\fP *) \fBPAC5XXX_RTC_BASE\fP)"

.PP
Definition at line 2876 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_SOCBRIDGE   ((\fBPAC5XXX_SocBridge_TypeDef\fP *) \fBPAC5XXX_SOCBRIDGE_BASE\fP)"

.PP
Definition at line 2892 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_SPI   ((\fBPAC5XXX_SPI_TypeDef\fP *) \fBPAC5XXX_SPI_BASE\fP)"

.PP
Definition at line 2891 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_SYSCTL   ((\fBPAC5XXX_SYSCLKCTL_TypeDef\fP *) \fBPAC5XXX_SYSCTL_BASE\fP)"

.PP
Definition at line 2873 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_TIMERA   ((\fBPAC5XXX_Timer8CC_TypeDef\fP *) \fBPAC5XXX_TIMERA_BASE\fP)"

.PP
Definition at line 2884 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_TIMERB   ((\fBPAC5XXX_Timer4CC_TypeDef\fP *) \fBPAC5XXX_TIMERB_BASE\fP)"

.PP
Definition at line 2885 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_TIMERC   ((\fBPAC5XXX_Timer2CC_TypeDef\fP *) \fBPAC5XXX_TIMERC_BASE\fP)"

.PP
Definition at line 2886 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_TIMERD   ((\fBPAC5XXX_Timer2CC_TypeDef\fP *) \fBPAC5XXX_TIMERD_BASE\fP)"

.PP
Definition at line 2887 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_UART   ((\fBPAC5XXX_UART_TypeDef\fP *) \fBPAC5XXX_UART_BASE\fP)"

.PP
Definition at line 2890 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_WDT   ((\fBPAC5XXX_WDT_TypeDef\fP *) \fBPAC5XXX_WDT_BASE\fP)"

.PP
Definition at line 2875 of file pac52XX\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
