.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_device/pac5210.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_device/pac5210.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pac52XX\&.h'\fP
.br
\fC#include 'pac5xxx_tile_SignalManager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_SystemManager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_DriverManager\&.h'\fP
.br
\fC#include 'pac5xxx_tile_PowerManager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPAC5210\fP"
.br
.ti -1c
.RI "#define \fBCAFE_ARCH1\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAFE_ARCH1"

.PP
Definition at line 18 of file pac5210\&.h\&.
.SS "#define PAC5210"

.PP
Definition at line 17 of file pac5210\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
