.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_sdk_version.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_sdk_version.h \- SDK Version\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDK_VERSION_MAJOR\fP   2"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_MINOR\fP   7"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_BUGFIX\fP   0"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_RELEASE_STATE\fP   \fBPAC52XX_RELEASED\fP"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_RELEASE_NUM\fP   0"
.br
.ti -1c
.RI "#define \fBSDK_VERSION_STR\fP   'v2\&.7\&.0'"
.br
.in -1c
.SH "Detailed Description"
.PP 
SDK Version\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
\fB\fP
.RS 4
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.RE
.PP

.PP
Definition in file \fBpac5xxx_sdk_version\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define SDK_VERSION_BUGFIX   0"

.PP
Definition at line 24 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_MAJOR   2"

.PP
Definition at line 22 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_MINOR   7"

.PP
Definition at line 23 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_RELEASE_NUM   0"

.PP
Definition at line 26 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_RELEASE_STATE   \fBPAC52XX_RELEASED\fP"

.PP
Definition at line 25 of file pac5xxx_sdk_version\&.h\&.
.SS "#define SDK_VERSION_STR   'v2\&.7\&.0'"

.PP
Definition at line 27 of file pac5xxx_sdk_version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
