.TH "PAC52XX" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC52XX \- PAC52XX
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPAC52XX Definitions\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPAC5XXX_RAMFUNC\fP"
.br
.ti -1c
.RI "#define \fBPAC5XXX_OPTIMIZE_SPEED_ON\fP"
.br
.ti -1c
.RI "#define \fBPAC5XXX_OPTIMIZE_SPEED_OFF\fP"
.br
.ti -1c
.RI "#define \fBUNUSED_PARAM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PAC5XXX_OPTIMIZE_SPEED_OFF"

.PP
Definition at line 55 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_OPTIMIZE_SPEED_ON"

.PP
Definition at line 54 of file pac52XX\&.h\&.
.SS "#define PAC5XXX_RAMFUNC"

.PP
Definition at line 53 of file pac52XX\&.h\&.
.SS "#define UNUSED_PARAM"

.PP
Definition at line 56 of file pac52XX\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
