.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_UART.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_UART.h \- CMSIS Cortex-M Header File for the PAC5XXX UART Controller\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPAC5XXX_UART_TypeDef\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUART_IID_Type\fP { \fBUARTIIR_IID_MODEM_STATUS\fP = 0, \fBUARTIIR_IID_TX_HOLD_EMPTY\fP = 1, \fBUARTIIR_IID_RX_DATA_AVAIL\fP = 2, \fBUARTIIR_IID_RX_LINE_STATUS\fP = 3, \fBUARTIIR_IID_TIMEOUT\fP = 6 }"
.br
.ti -1c
.RI "enum \fBUART_FIFO_Depth_Type\fP { \fBUARTFCTL_RT_1B\fP = 0, \fBUARTFCTL_RT_4B\fP = 1, \fBUARTFCTL_RT_8B\fP = 2, \fBUARTFCTL_RT_14B\fP = 3 }"
.br
.ti -1c
.RI "enum \fBUART_BitsPerChar_Type\fP { \fBUART_BPC_5\fP = 0, \fBUART_BPC_6\fP = 1, \fBUART_BPC_7\fP = 2, \fBUART_BPC_8\fP = 3 }"
.br
.ti -1c
.RI "enum \fBUART_StopBits_Type\fP { \fBUART_STOP_BITS_1\fP = 0, \fBUART_STOP_BITS_2\fP = 1 }"
.br
.ti -1c
.RI "enum \fBUART_Parity_Type\fP { \fBUART_PARITY_ODD\fP = 0, \fBUART_PARITY_EVEN\fP = 1 }"
.br
.ti -1c
.RI "enum \fBUART_BreakControl_Type\fP { \fBUART_BRKCTL_NORMAL\fP = 0, \fBUART_BRKCTL_FORCE_0\fP = 1 }"
.br
.ti -1c
.RI "enum \fBUART_DivLatchAccess_Type\fP { \fBUART_DIVLACCESS_FIFO_IER\fP = 0, \fBUART_DIVLACCESS_DIV_LATCH\fP = 1 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M Header File for the PAC5XXX UART Controller\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_UART\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
