.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_Timers.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_peripheral/pac5xxx_Timers.h \- CMSIS Cortex-M Header File for the PAC5XXX Timers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBPAC5XXX_TIMERCC_TypeDef\fP"
.br
.ti -1c
.RI "union \fBPAC5XXX_DTGCTL_TypeDef\fP"
.br
.ti -1c
.RI "struct \fBPAC5XXX_Timer4CC_TypeDef\fP"
.br
.ti -1c
.RI "struct \fBPAC5XXX_Timer8CC_TypeDef\fP"
.br
.ti -1c
.RI "struct \fBPAC5XXX_Timer2CC_TypeDef\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTXCTRL_MODE_Type\fP { \fBTxCTL_MODE_DISABLED\fP = 0, \fBTxCTL_MODE_UP\fP = 1, \fBTxCTL_MODE_UPDOWN\fP = 2 }"
.br
.ti -1c
.RI "enum \fBTXCTRL_CLKIN_Type\fP { \fBTxCTL_CS_HCLK\fP = 0, \fBTxCTL_CS_ACLK\fP = 1 }"
.br
.ti -1c
.RI "enum \fBTXCTRL_PS_Type\fP { \fBTxCTL_PS_DIV1\fP = 0, \fBTxCTL_PS_DIV2\fP = 1, \fBTxCTL_PS_DIV4\fP = 2, \fBTxCTL_PS_DIV8\fP = 3, \fBTxCTL_PS_DIV16\fP = 4, \fBTxCTL_PS_DIV32\fP = 5, \fBTxCTL_PS_DIV64\fP = 6, \fBTxCTL_PS_DIV128\fP = 7 }"
.br
.ti -1c
.RI "enum \fBTXCCTRL_LATCH_Type\fP { \fBTxCTL_CLPRD_PRD\fP = 0, \fBTxCTL_CLPRD_0\fP = 1 }"
.br
.ti -1c
.RI "enum \fBTXCCTRL_CAPEDGE_Type\fP { \fBTxCCTL_CED_HIGHTOLOW\fP = 0, \fBTxCCTL_CED_LOWTOHIGH\fP = 1, \fBTxCCTL_CED_BOTH\fP = 2 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M Header File for the PAC5XXX Timers\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_Timers\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
