.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_uart_config.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_uart_config.c \- Firmware driver for the PAC5XXX UART\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_uart\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_LCR\fP (\fBUART_BitsPerChar_Type\fP bpc, \fBUART_StopBits_Type\fP stop_bits, int parity_enabled, \fBUART_Parity_Type\fP parity, int stick_parity, \fBUART_BreakControl_Type\fP break_control, \fBUART_DivLatchAccess_Type\fP div_latch_access)"
.br
.RI "This function configures the UART LCR (Line Control Register) "
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_MCR\fP (int DTR_asserted, int RTS_asserted, int BIT1_asserted, int BIT2_asserted, int loopback_mode)"
.br
.RI "This function configures the UART MCR (Modem Control Register) "
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_divisor_latch\fP (uint16_t latch_value)"
.br
.RI "This function configures the divisor latch\&. "
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_divisor_latch_remapped\fP (uint16_t latch_value)"
.br
.RI "This function configures the divisor latch using the remapped DL_L2 and DL_H2 registers\&. "
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_config_fractional_divisor\fP (unsigned char divisor_value)"
.br
.ti -1c
.RI "\fBRAMFUNC_UART\fP void \fBpac5xxx_uart_io_config\fP ()"
.br
.RI "This function configures IO for use with the UART peripheral\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX UART\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_uart_config\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBRAMFUNC_UART\fP void pac5xxx_uart_config_fractional_divisor (unsigned char divisor_value)"

.PP
Definition at line 62 of file pac5xxx_driver_uart_config\&.c\&.
.PP
.nf
63 {
64   PAC5XXX_UART->FD_F\&.VAL = divisor_value;
65 }
.fi
.PP
References PAC5XXX_UART\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
