.TH "PAC5XXX_Timer4CC" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_Timer4CC \- PAC5XXX Timer Capture/Compare/PWM outputs (TIMER4CC)
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPAC5XXX Timer Capture/Compare/PWM outputs (TIMER2CC)\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPAC5XXX_Timer4CC_TypeDef\fP"
.br
.ti -1c
.RI "struct \fBPAC5XXX_Timer8CC_TypeDef\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
