.TH "PAC5XXX_Tile_PowerManager" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_Tile_PowerManager \- PAC5XXX Power Manager Tile
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
