PAC5XXX_Driver_ADC
NAME
PAC5XXX_Driver_ADC - PAC5XXX ADC Driver Functions
SYNOPSIS
Macros
#define RAMFUNC_ADC
Functions
RAMFUNC_ADC void pac5xxx_adc_emux_config (ADC_EMUX_CTL_Type control_type, ADC_EMUX_DIV_Type divider)
This function configures the ADC's external MUX.
RAMFUNC_ADC void pac5xxx_adc_config (ADCCTL_ADMODE_Type adc_mode, ADCCTL_CLKDIV_Type clock_divider, int repeat)
This function configures the ADC.
RAMFUNC_ADC void pac5xxx_adc_config_io (uint8_t channel_mask)
This function configures the IO ports on the device for the given ADC channels.
RAMFUNC_ADC void pac5xxx_adc_config_emux_io (void)
This function configures the EMUX IO ports on the device for EMUX output.
RAMFUNC_ADC void pac5xxx_adc_as0_config_timer (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGTIMER_Type trig_timer_source)
This function configures the ASC0 unit for use with a timer trigger.
RAMFUNC_ADC void pac5xxx_adc_as0_config_pwm (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGEDGE_Type trig_edge, ADCCTLX_TRIGPWM_Type trig_pwm_source)
This function configures the ASC0 unit for use with a PWM trigger.
RAMFUNC_ADC void pac5xxx_adc_as1_config_timer (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGTIMER_Type trig_timer_source)
This function configures the ASC1 unit for use with a timer trigger.
RAMFUNC_ADC void pac5xxx_adc_as1_config_pwm (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGEDGE_Type trig_edge, ADCCTLX_TRIGPWM_Type trig_pwm_source)
This function configures the ASC1 unit for use with a PWM trigger.
RAMFUNC_ADC void pac5xxx_adc_as0_sequence_config (int seq_num, ADCCTL_ADMUX_Type mux_select, ASSEQ_MSPI_Type emux_control, uint8_t emux_data, ASSEQ_DELAY_Type seq_delay)
This function configures the given sequence number for the ASC0 unit.
RAMFUNC_ADC void pac5xxx_adc_as1_sequence_config (int seq_num, ADCCTL_ADMUX_Type mux_select, ASSEQ_MSPI_Type emux_control, uint8_t emux_data, ASSEQ_DELAY_Type seq_delay)
This function configures the given sequence number for the ASC1 unit.
RAMFUNC_ADC uint16_t pac5xxx_adc_as0_seq_get_result (int seq_num)
This function returns the ADC result for the given sequence number for the ASC0 unit.
RAMFUNC_ADC uint16_t pac5xxx_adc_as1_seq_get_result (int seq_num)
This function returns the ADC result for the given sequence number for the ASC1 unit.
Detailed Description
Macro Definition Documentation
#define RAMFUNC_ADC
Definition at line 31 of file pac5xxx_driver_adc.h.
Function Documentation
RAMFUNC_ADC void pac5xxx_adc_as0_config_pwm (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGEDGE_Type trig_edge, ADCCTLX_TRIGPWM_Type trig_pwm_source)
This function configures the ASC0 unit for use with a PWM trigger.
Parameters
sample_depth The sample depth from ADCCTLX_SDEPTH_Type
trig_edge The trigger edge for the sequence from ADCCTLX_TRIGEDGE_Type
trig_pwm_source The trigger source for the sequence when configured for PWM, from ADCCTLX_TRIGPWM_Type
Returns
none
Definition at line 29 of file pac5xxx_driver_adc_seq.c.
{
    PAC5XXX_ADC->ASCTL0.AS0TR = ADCCTLX_ASTR_PWM;
    PAC5XXX_ADC->ASCTL0.AS0D = sample_depth;
    PAC5XXX_ADC->ASCTL0.AS0TRE = trig_edge;
    PAC5XXX_ADC->ASCTL0.AS0TRPWM = trig_pwm_source;
    PAC5XXX_ADC->ASCTL0.AS0SEQEN = 1;
}
References ADCCTLX_ASTR_PWM, and PAC5XXX_ADC.
Referenced by config_seq_foc().
RAMFUNC_ADC void pac5xxx_adc_as0_config_timer (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGTIMER_Type trig_timer_source)
This function configures the ASC0 unit for use with a timer trigger.
Parameters
sample_depth The sample depth from ADCCTLX_SDEPTH_Type
trig_timer_source The trigger source for the sequence when configure for Timer, from ADCCTLX_TRIGTIMER_Type
Returns
none
Definition at line 20 of file pac5xxx_driver_adc_seq.c.
{
    PAC5XXX_ADC->ASCTL0.AS0TR = ADCCTLX_ASTR_TIMER;
    PAC5XXX_ADC->ASCTL0.AS0D = sample_depth;
    PAC5XXX_ADC->ASCTL0.AS0TRTMR = trig_timer_source;
    PAC5XXX_ADC->ASCTL0.AS0SEQEN = 1;
}
References ADCCTLX_ASTR_TIMER, and PAC5XXX_ADC.
RAMFUNC_ADC uint16_t pac5xxx_adc_as0_seq_get_result (int seq_num)
This function returns the ADC result for the given sequence number for the ASC0 unit.
Parameters
seq_num sequence number
Returns
ADC conversion result for seq_num
Definition at line 124 of file pac5xxx_driver_adc_seq.c.
{
    volatile PAC5XXX_ADCRESULT_Type* pSeq;
    
    if (seq_num == 0)
        pSeq = &PAC5XXX_ADC->AS0R0;
    else if (seq_num == 1)
        pSeq = &PAC5XXX_ADC->AS0R1;
    else if (seq_num == 2)
        pSeq = &PAC5XXX_ADC->AS0R2;
    else if (seq_num == 3)
        pSeq = &PAC5XXX_ADC->AS0R3;
    else if (seq_num == 4)
        pSeq = &PAC5XXX_ADC->AS0R4;
    else if (seq_num == 5)
        pSeq = &PAC5XXX_ADC->AS0R5;
    else if (seq_num == 6)
        pSeq = &PAC5XXX_ADC->AS0R6;
    else if (seq_num == 7)
        pSeq = &PAC5XXX_ADC->AS0R7;
    
    return pSeq->VAL;
}
References PAC5XXX_ADC, and PAC5XXX_ADCRESULT_Type::VAL.
RAMFUNC_ADC void pac5xxx_adc_as0_sequence_config (int seq_num, ADCCTL_ADMUX_Type mux_select, ASSEQ_MSPI_Type emux_control, uint8_t emux_data, ASSEQ_DELAY_Type seq_delay)
This function configures the given sequence number for the ASC0 unit.
Parameters
seq_num The sequence number to configure
mux_select The ADC MUX selection for the sequence from ADCCTL_ADMUX_Type
emux_control When to change the EMUX from the ASSEQ_MSPI_Type
emux_data The EMUX data to send for the given sequence
seq_delay The delay to apply for the given sequence from ADCCTLX_DELAY_Type
Returns
Non-zero if sequence complete
Referenced by config_seq_foc().
RAMFUNC_ADC void pac5xxx_adc_as1_config_pwm (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGEDGE_Type trig_edge, ADCCTLX_TRIGPWM_Type trig_pwm_source)
This function configures the ASC1 unit for use with a PWM trigger.
Parameters
sample_depth The sample depth from ADCCTLX_SDEPTH_Type
trig_edge The trigger edge for the sequence from ADCCTLX_TRIGEDGE_Type
trig_pwm_source The trigger source for the sequence when configured for PWM, from ADCCTLX_TRIGPWM_Type
Returns
none
Definition at line 50 of file pac5xxx_driver_adc_seq.c.
{
    PAC5XXX_ADC->ASCTL1.AS1TR = ADCCTLX_ASTR_PWM;
    PAC5XXX_ADC->ASCTL1.AS1D = sample_depth;
    PAC5XXX_ADC->ASCTL1.AS1TRE = trig_edge;
    PAC5XXX_ADC->ASCTL1.AS1TRPWM = trig_pwm_source;
    PAC5XXX_ADC->ASCTL1.AS1SEQEN = 1;
}
References ADCCTLX_ASTR_PWM, and PAC5XXX_ADC.
Referenced by config_seq_foc().
RAMFUNC_ADC void pac5xxx_adc_as1_config_timer (ADCCTLX_SDEPTH_Type sample_depth, ADCCTLX_TRIGTIMER_Type trig_timer_source)
This function configures the ASC1 unit for use with a timer trigger.
Parameters
sample_depth The sample depth from ADCCTLX_SDEPTH_Type
trig_timer_source The trigger source for the sequence when configure for Timer, from ADCCTLX_TRIGTIMER_Type
Returns
none
Definition at line 41 of file pac5xxx_driver_adc_seq.c.
{
    PAC5XXX_ADC->ASCTL1.AS1TR = ADCCTLX_ASTR_TIMER;
    PAC5XXX_ADC->ASCTL1.AS1D = sample_depth;
    PAC5XXX_ADC->ASCTL1.AS1TRTMR = trig_timer_source;
    PAC5XXX_ADC->ASCTL1.AS1SEQEN = 1;
}
References ADCCTLX_ASTR_TIMER, and PAC5XXX_ADC.
RAMFUNC_ADC uint16_t pac5xxx_adc_as1_seq_get_result (int seq_num)
This function returns the ADC result for the given sequence number for the ASC1 unit.
Parameters
seq_num sequence number
Returns
ADC conversion result for seq_num
Definition at line 148 of file pac5xxx_driver_adc_seq.c.
{
    volatile PAC5XXX_ADCRESULT_Type* pSeq;
    
    if (seq_num == 0)
        pSeq = &PAC5XXX_ADC->AS1R0;
    else if (seq_num == 1)
        pSeq = &PAC5XXX_ADC->AS1R1;
    else if (seq_num == 2)
        pSeq = &PAC5XXX_ADC->AS1R2;
    else if (seq_num == 3)
        pSeq = &PAC5XXX_ADC->AS1R3;
    else if (seq_num == 4)
        pSeq = &PAC5XXX_ADC->AS1R4;
    else if (seq_num == 5)
        pSeq = &PAC5XXX_ADC->AS1R5;
    else if (seq_num == 6)
        pSeq = &PAC5XXX_ADC->AS1R6;
    else if (seq_num == 7)
        pSeq = &PAC5XXX_ADC->AS1R7;
    
    return pSeq->VAL;
}
References PAC5XXX_ADC, and PAC5XXX_ADCRESULT_Type::VAL.
RAMFUNC_ADC void pac5xxx_adc_as1_sequence_config (int seq_num, ADCCTL_ADMUX_Type mux_select, ASSEQ_MSPI_Type emux_control, uint8_t emux_data, ASSEQ_DELAY_Type seq_delay)
This function configures the given sequence number for the ASC1 unit.
Parameters
seq_num The sequence number to configure
mux_select When to change the EMUX from the ASSEQ_MSPI_Type
emux_control The EMUX control to use for the given sequence from ADC_EMUX_CTL_Type
emux_data The EMUX data to send for the given sequence
seq_delay The delay to apply for the given sequence from ADCCTLX_DELAY_Type
Returns
Non-zero if sequence complete
Referenced by config_seq_foc().
RAMFUNC_ADC void pac5xxx_adc_config (ADCCTL_ADMODE_Type adc_mode, ADCCTL_CLKDIV_Type clock_divider, int repeat)
This function configures the ADC.
Parameters
adc_mode The ADC mode from ADCCTL_MODE
clock_divider Clock divider for the ADC clock
repeat Set to 1 to perform repeated conversions of the selected channel
Returns
none
Note
This function does not enable the ADC
Definition at line 20 of file pac5xxx_driver_adc_config.c.
{
    PAC5XXX_ADC->ADCCTL.ADCMODE = adc_mode;
    PAC5XXX_ADC->ADCCTL.ADCDIV = clock_divider;
    PAC5XXX_ADC->ADCCTL.ADCREPEAT = repeat;
}
References PAC5XXX_ADC.
Referenced by config_seq_foc().
RAMFUNC_ADC void pac5xxx_adc_config_emux_io (void)
This function configures the EMUX IO ports on the device for EMUX output.
Returns
none
Definition at line 26 of file pac5xxx_driver_adc_emux.c.
{
  PAC5XXX_GPIOB->PSEL.P5 = 1;
  PAC5XXX_GPIOB->PSEL.P6 = 1;
}
References PAC5XXX_GPIOB.
Referenced by configure_adc_emux_engine().
RAMFUNC_ADC void pac5xxx_adc_config_io (uint8_t channel_mask)
This function configures the IO ports on the device for the given ADC channels.
Parameters
channel_mask Bit-mask of the ADC channels to enable or disable IOs for
Returns
none
Referenced by configure_adc_emux_engine().
RAMFUNC_ADC void pac5xxx_adc_emux_config (ADC_EMUX_CTL_Type control_type, ADC_EMUX_DIV_Type divider)
This function configures the ADC's external MUX.
Parameters
control_type Type of external mux control
divider External MUX clock divider
Returns
none
Definition at line 20 of file pac5xxx_driver_adc_emux.c.
{
    PAC5XXX_ADC->EMUXCTL.EMUXC = control_type;
    PAC5XXX_ADC->EMUXCTL.EMUXDIV = divider;
}
References PAC5XXX_ADC.
Referenced by configure_adc_emux_engine().
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.