.TH "PAC5XXX_Timer2CC_TypeDef" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_Timer2CC_TypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_Timers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::s\fP: 16"
.br
.ti -1c
.RI "      uint32_t \fBPAC5XXX_Timer2CC_TypeDef::__pad0__\fP: 16"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::b\fP: 8"
.br
.ti -1c
.RI "      uint32_t \fBPAC5XXX_Timer2CC_TypeDef::__pad0__\fP: 24"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::PRDL\fP: 1"
.br
.ti -1c
.RI "      uint32_t \fBPAC5XXX_Timer2CC_TypeDef::__pad0__\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::CLR\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::SS\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::INT\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::INTEN\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::CLKDIV\fP: 3"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::CLK\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::MODE\fP: 2"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::SYNC\fP: 1"
.br
.ti -1c
.RI "      \fB__IO\fP uint32_t \fBPAC5XXX_Timer2CC_TypeDef::DTGCLKDIVEN\fP: 1"
.br
.ti -1c
.RI "      uint32_t \fBPAC5XXX_Timer2CC_TypeDef::__pad1__\fP: 18"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "} \fBCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPRD\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBCTR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [13]"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_TIMERCC_TypeDef\fP \fBCCTRL0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTR0\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_TIMERCC_TypeDef\fP \fBCCTRL1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCTR1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [20]"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_DTGCTL_TypeDef\fP \fBDTGCTL0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGLED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGTED0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 231 of file pac5xxx_Timers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
