.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_adc_emux.c" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_adc_emux.c \- Firmware driver for the PAC5XXX ADC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac5xxx_driver_adc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_emux_config\fP (\fBADC_EMUX_CTL_Type\fP control_type, \fBADC_EMUX_DIV_Type\fP divider)"
.br
.RI "This function configures the ADC's external MUX\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config_emux_io\fP ()"
.br
.RI "This function configures the EMUX IO ports on the device for EMUX output\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX ADC\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_adc_emux\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
