PAC5XXX_Driver_SocBridge
NAME
PAC5XXX_Driver_SocBridge - PAC5XXX SOC Bridge Peripheral Driver Functions
SYNOPSIS
Macros
#define RAMFUNC_SOCBRIDGE
Functions
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config (int enable, int int_enable)
This function configures and enables the SOC bridge.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config_chip_select (uint8_t cs_setup, uint8_t cs_hold, uint8_t cs_wait)
This function configures the behavior of the SOC bridge chip select signal.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config_io (void)
This function configures the IO ports on the device for SOC bridge operation.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable (int enable)
This function configures SOC Bridge interrupts to the given state.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_RDOFL (int enable)
This function configures the state of the Read Buffer Overflow (RDOFL) interrupt.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_CYC_DONE (int enable)
This function configures the state of the Cycle Done (CYC_DONE) interrupt.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_WRUFL (int enable)
This function configures the state of the Write Buffer Underflow (WRUFL) interupt.
RAMFUNC_SOCBRIDGE uint8_t pac5xxx_socbridge_data_read_8b (uint8_t tx_data)
This function reads 8b of data from the SOC Bridge receive register.
Detailed Description
Macro Definition Documentation
#define RAMFUNC_SOCBRIDGE
Definition at line 32 of file pac5xxx_driver_socbridge.h.
Function Documentation
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config (int enable, int int_enable)
This function configures and enables the SOC bridge. @paramn enable Set to 1 to enable SOC Bridge, 0 to disable
Parameters
int_enable Set to 1 to enable interrupts, 0 to disable interrupts
Returns
none
Definition at line 20 of file pac5xxx_driver_socbridge_config.c.
{
    PAC5XXX_SOCBRIDGE->SOCBCTL.SETTO3 = 3; // Need to set these bits to 3 for SOCBCTL write
    PAC5XXX_SOCBRIDGE->SOCBCTL.SIE = int_enable; // Interrupts enabled
    PAC5XXX_SOCBRIDGE->SOCBCFG.SETTO3 = 3; // Need to set these bits to 3 for SOCBCFG write
    PAC5XXX_SOCBRIDGE->SOCBCFG.SETTO0 = 0; // Need to set this bit to 0 for SOCBCFG write
    PAC5XXX_SOCBRIDGE->SOCBCFG.WL = 1; // Set Word Length to 16 bits.
    PAC5XXX_SOCBRIDGE->SOCBCLKDIV.VAL = 1; // SPI CLK = 12.5 MHz = 50 MHz/ ((CLKDIV + 1) * 2)
    PAC5XXX_SOCBRIDGE->SOCBINT_EN.w = 0; // Clear interrupt enables
    PAC5XXX_SOCBRIDGE->SOCBCTL.SSEN = enable; // enable peripheral
}
References PAC5XXX_SOCBRIDGE.
Referenced by pac5xxx_tile_socbridge_config().
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config_chip_select (uint8_t cs_setup, uint8_t cs_hold, uint8_t cs_wait)
This function configures the behavior of the SOC bridge chip select signal.
Parameters
cs_setup This value is the minimum number of clock periods to wait from the assertion of the chip select to the first clock transition.
cs_hold This value is the minimum number of clock periods to wait from the last clock transition to de-assertion of the chip select signal.
cs_wait This value determines the minimum number of clock periods to wait between the de-assertion of the chip select and the re-assertion of the chip select signal.
Returns
none
Referenced by pac5xxx_tile_socbridge_config().
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_config_io (void)
This function configures the IO ports on the device for SOC bridge operation.
Returns
none
Definition at line 20 of file pac5xxx_driver_socbridge_config_io.c.
{
  //
  // CS0: GPIOBSEL1 = 01b (PB1 - output)
  // CLK: GPIOBSEL4 = 01b (PB4 - output)
  // MOSI: GPIOBSEL2 = 01b (PB2 - output)
  // MISO: GPIOBSEL3 = 01b (PB3 - input)
  //
  
  PAC5XXX_GPIOB->PSEL.P1 = 1; // CS0
  PAC5XXX_GPIOB->OUTEN.P1 = 1; // output
  PAC5XXX_GPIOB->PSEL.P4 = 1; // CLK
  PAC5XXX_GPIOB->OUTEN.P4 = 1; // output
  PAC5XXX_GPIOB->PSEL.P2 = 1; // MOSI
  PAC5XXX_GPIOB->OUTEN.P2 = 1; // output
  PAC5XXX_GPIOB->PSEL.P3 = 1; // MISO, input by default
}
References PAC5XXX_GPIOB.
Referenced by pac5xxx_tile_socbridge_config().
RAMFUNC_SOCBRIDGE uint8_t pac5xxx_socbridge_data_read_8b (uint8_t tx_data)
This function reads 8b of data from the SOC Bridge receive register.
Parameters
Data to write on MOSI during read operation
Returns
Data read from the receive register
Definition at line 19 of file pac5xxx_driver_socbridge_data.c.
{
    uint8_t data;
    PAC5XXX_SOCBRIDGE->SOCBD.b = tx_data;
    // Wait for transmission to be complete
    while (!pac5xxx_socbridge_stat_CYC_DONE());
    PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE = 0x1;
    data = PAC5XXX_SOCBRIDGE->SOCBD.b;
    return data;
}
References PAC5XXX_SOCBRIDGE.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable (int enable)
This function configures SOC Bridge interrupts to the given state. Interrupts and status
Parameters
enable When set to 1, enables interrupts. When set to 0, disables interrupts.
Returns
none
Note
This function must be used to enable any interrupts. This must be used in conjunction with another function that enables specific interrupts. This function does not enable interrupts in the Cortex NVIC. That must be done explictly using the CMSIS API functions for the NVIC.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_CYC_DONE (int enable)
This function configures the state of the Cycle Done (CYC_DONE) interrupt.
Parameters
enable When set to 1, enables this interrupt. When set to 0, disables this interrupt.
Returns
none
Note
This function must be used in conjunction with the pac5xxx_socbridge_int_enable() function to enable this interrupt.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_RDOFL (int enable)
This function configures the state of the Read Buffer Overflow (RDOFL) interrupt.
Parameters
enable When set to 1, enables this interrupts. When set to 0, disables this interrupt.
Returns
none
Note
This function must be used in conjunction with the pac5xxx_socbridge_int_enable() function to enable this interrupt.
RAMFUNC_SOCBRIDGE void pac5xxx_socbridge_int_enable_WRUFL (int enable)
This function configures the state of the Write Buffer Underflow (WRUFL) interupt.
Parameters
enable When set to 1, enables this interrupts. When set to 0, disables this interrupt.
Returns
none
Note
This function must be used in conjunction with the pac5xxx_socbridge_int_enable() function to enable this interrupt.
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.