.TH "PAC5XXX_Driver_ADC" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_Driver_ADC \- PAC5XXX ADC Driver Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAMFUNC_ADC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_emux_config\fP (\fBADC_EMUX_CTL_Type\fP control_type, \fBADC_EMUX_DIV_Type\fP divider)"
.br
.RI "This function configures the ADC's external MUX\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config\fP (\fBADCCTL_ADMODE_Type\fP adc_mode, \fBADCCTL_CLKDIV_Type\fP clock_divider, int repeat)"
.br
.RI "This function configures the ADC\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config_io\fP (uint8_t channel_mask)"
.br
.RI "This function configures the IO ports on the device for the given ADC channels\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_config_emux_io\fP (void)"
.br
.RI "This function configures the EMUX IO ports on the device for EMUX output\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as0_config_timer\fP (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGTIMER_Type\fP trig_timer_source)"
.br
.RI "This function configures the ASC0 unit for use with a timer trigger\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as0_config_pwm\fP (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGEDGE_Type\fP trig_edge, \fBADCCTLX_TRIGPWM_Type\fP trig_pwm_source)"
.br
.RI "This function configures the ASC0 unit for use with a PWM trigger\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as1_config_timer\fP (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGTIMER_Type\fP trig_timer_source)"
.br
.RI "This function configures the ASC1 unit for use with a timer trigger\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as1_config_pwm\fP (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGEDGE_Type\fP trig_edge, \fBADCCTLX_TRIGPWM_Type\fP trig_pwm_source)"
.br
.RI "This function configures the ASC1 unit for use with a PWM trigger\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as0_sequence_config\fP (int seq_num, \fBADCCTL_ADMUX_Type\fP mux_select, \fBASSEQ_MSPI_Type\fP emux_control, uint8_t emux_data, \fBASSEQ_DELAY_Type\fP seq_delay)"
.br
.RI "This function configures the given sequence number for the ASC0 unit\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP void \fBpac5xxx_adc_as1_sequence_config\fP (int seq_num, \fBADCCTL_ADMUX_Type\fP mux_select, \fBASSEQ_MSPI_Type\fP emux_control, uint8_t emux_data, \fBASSEQ_DELAY_Type\fP seq_delay)"
.br
.RI "This function configures the given sequence number for the ASC1 unit\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP uint16_t \fBpac5xxx_adc_as0_seq_get_result\fP (int seq_num)"
.br
.RI "This function returns the ADC result for the given sequence number for the ASC0 unit\&. "
.ti -1c
.RI "\fBRAMFUNC_ADC\fP uint16_t \fBpac5xxx_adc_as1_seq_get_result\fP (int seq_num)"
.br
.RI "This function returns the ADC result for the given sequence number for the ASC1 unit\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RAMFUNC_ADC"

.PP
Definition at line 31 of file pac5xxx_driver_adc\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as0_config_pwm (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGEDGE_Type\fP trig_edge, \fBADCCTLX_TRIGPWM_Type\fP trig_pwm_source)"

.PP
This function configures the ASC0 unit for use with a PWM trigger\&. 
.PP
\fBParameters\fP
.RS 4
\fIsample_depth\fP The sample depth from \fIADCCTLX_SDEPTH_Type\fP 
.br
\fItrig_edge\fP The trigger edge for the sequence from \fIADCCTLX_TRIGEDGE_Type\fP 
.br
\fItrig_pwm_source\fP The trigger source for the sequence when configured for PWM, from \fIADCCTLX_TRIGPWM_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 29 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
32 {
33     PAC5XXX_ADC->ASCTL0\&.AS0TR = ADCCTLX_ASTR_PWM;
34     PAC5XXX_ADC->ASCTL0\&.AS0D = sample_depth;
35     PAC5XXX_ADC->ASCTL0\&.AS0TRE = trig_edge;
36     PAC5XXX_ADC->ASCTL0\&.AS0TRPWM = trig_pwm_source;
37     PAC5XXX_ADC->ASCTL0\&.AS0SEQEN = 1;
38 }
.fi
.PP
References ADCCTLX_ASTR_PWM, and PAC5XXX_ADC\&.
.PP
Referenced by config_seq_foc()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as0_config_timer (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGTIMER_Type\fP trig_timer_source)"

.PP
This function configures the ASC0 unit for use with a timer trigger\&. 
.PP
\fBParameters\fP
.RS 4
\fIsample_depth\fP The sample depth from \fIADCCTLX_SDEPTH_Type\fP 
.br
\fItrig_timer_source\fP The trigger source for the sequence when configure for Timer, from \fIADCCTLX_TRIGTIMER_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 20 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
22 {
23     PAC5XXX_ADC->ASCTL0\&.AS0TR = ADCCTLX_ASTR_TIMER;
24     PAC5XXX_ADC->ASCTL0\&.AS0D = sample_depth;
25     PAC5XXX_ADC->ASCTL0\&.AS0TRTMR = trig_timer_source;
26     PAC5XXX_ADC->ASCTL0\&.AS0SEQEN = 1;
27 }
.fi
.PP
References ADCCTLX_ASTR_TIMER, and PAC5XXX_ADC\&.
.SS "\fBRAMFUNC_ADC\fP uint16_t pac5xxx_adc_as0_seq_get_result (int seq_num)"

.PP
This function returns the ADC result for the given sequence number for the ASC0 unit\&. 
.PP
\fBParameters\fP
.RS 4
\fIseq_num\fP sequence number 
.RE
.PP
\fBReturns\fP
.RS 4
ADC conversion result for \fIseq_num\fP 
.RE
.PP

.PP
Definition at line 124 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
125 {
126     volatile PAC5XXX_ADCRESULT_Type* pSeq;
127     
128     if (seq_num == 0)
129         pSeq = &PAC5XXX_ADC->AS0R0;
130     else if (seq_num == 1)
131         pSeq = &PAC5XXX_ADC->AS0R1;
132     else if (seq_num == 2)
133         pSeq = &PAC5XXX_ADC->AS0R2;
134     else if (seq_num == 3)
135         pSeq = &PAC5XXX_ADC->AS0R3;
136     else if (seq_num == 4)
137         pSeq = &PAC5XXX_ADC->AS0R4;
138     else if (seq_num == 5)
139         pSeq = &PAC5XXX_ADC->AS0R5;
140     else if (seq_num == 6)
141         pSeq = &PAC5XXX_ADC->AS0R6;
142     else if (seq_num == 7)
143         pSeq = &PAC5XXX_ADC->AS0R7;
144     
145     return pSeq->VAL;
146 }
.fi
.PP
References PAC5XXX_ADC, and PAC5XXX_ADCRESULT_Type::VAL\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as0_sequence_config (int seq_num, \fBADCCTL_ADMUX_Type\fP mux_select, \fBASSEQ_MSPI_Type\fP emux_control, uint8_t emux_data, \fBASSEQ_DELAY_Type\fP seq_delay)"

.PP
This function configures the given sequence number for the ASC0 unit\&. 
.PP
\fBParameters\fP
.RS 4
\fIseq_num\fP The sequence number to configure 
.br
\fImux_select\fP The ADC MUX selection for the sequence from \fIADCCTL_ADMUX_Type\fP 
.br
\fIemux_control\fP When to change the EMUX from the \fIASSEQ_MSPI_Type\fP 
.br
\fIemux_data\fP The EMUX data to send for the given sequence 
.br
\fIseq_delay\fP The delay to apply for the given sequence from \fIADCCTLX_DELAY_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Non-zero if sequence complete 
.RE
.PP

.PP
Referenced by config_seq_foc()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as1_config_pwm (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGEDGE_Type\fP trig_edge, \fBADCCTLX_TRIGPWM_Type\fP trig_pwm_source)"

.PP
This function configures the ASC1 unit for use with a PWM trigger\&. 
.PP
\fBParameters\fP
.RS 4
\fIsample_depth\fP The sample depth from \fIADCCTLX_SDEPTH_Type\fP 
.br
\fItrig_edge\fP The trigger edge for the sequence from \fIADCCTLX_TRIGEDGE_Type\fP 
.br
\fItrig_pwm_source\fP The trigger source for the sequence when configured for PWM, from \fIADCCTLX_TRIGPWM_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 50 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
53 {
54     PAC5XXX_ADC->ASCTL1\&.AS1TR = ADCCTLX_ASTR_PWM;
55     PAC5XXX_ADC->ASCTL1\&.AS1D = sample_depth;
56     PAC5XXX_ADC->ASCTL1\&.AS1TRE = trig_edge;
57     PAC5XXX_ADC->ASCTL1\&.AS1TRPWM = trig_pwm_source;
58     PAC5XXX_ADC->ASCTL1\&.AS1SEQEN = 1;
59 }
.fi
.PP
References ADCCTLX_ASTR_PWM, and PAC5XXX_ADC\&.
.PP
Referenced by config_seq_foc()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as1_config_timer (\fBADCCTLX_SDEPTH_Type\fP sample_depth, \fBADCCTLX_TRIGTIMER_Type\fP trig_timer_source)"

.PP
This function configures the ASC1 unit for use with a timer trigger\&. 
.PP
\fBParameters\fP
.RS 4
\fIsample_depth\fP The sample depth from \fIADCCTLX_SDEPTH_Type\fP 
.br
\fItrig_timer_source\fP The trigger source for the sequence when configure for Timer, from \fIADCCTLX_TRIGTIMER_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 41 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
43 {
44     PAC5XXX_ADC->ASCTL1\&.AS1TR = ADCCTLX_ASTR_TIMER;
45     PAC5XXX_ADC->ASCTL1\&.AS1D = sample_depth;
46     PAC5XXX_ADC->ASCTL1\&.AS1TRTMR = trig_timer_source;
47     PAC5XXX_ADC->ASCTL1\&.AS1SEQEN = 1;
48 }
.fi
.PP
References ADCCTLX_ASTR_TIMER, and PAC5XXX_ADC\&.
.SS "\fBRAMFUNC_ADC\fP uint16_t pac5xxx_adc_as1_seq_get_result (int seq_num)"

.PP
This function returns the ADC result for the given sequence number for the ASC1 unit\&. 
.PP
\fBParameters\fP
.RS 4
\fIseq_num\fP sequence number 
.RE
.PP
\fBReturns\fP
.RS 4
ADC conversion result for \fIseq_num\fP 
.RE
.PP

.PP
Definition at line 148 of file pac5xxx_driver_adc_seq\&.c\&.
.PP
.nf
149 {
150     volatile PAC5XXX_ADCRESULT_Type* pSeq;
151     
152     if (seq_num == 0)
153         pSeq = &PAC5XXX_ADC->AS1R0;
154     else if (seq_num == 1)
155         pSeq = &PAC5XXX_ADC->AS1R1;
156     else if (seq_num == 2)
157         pSeq = &PAC5XXX_ADC->AS1R2;
158     else if (seq_num == 3)
159         pSeq = &PAC5XXX_ADC->AS1R3;
160     else if (seq_num == 4)
161         pSeq = &PAC5XXX_ADC->AS1R4;
162     else if (seq_num == 5)
163         pSeq = &PAC5XXX_ADC->AS1R5;
164     else if (seq_num == 6)
165         pSeq = &PAC5XXX_ADC->AS1R6;
166     else if (seq_num == 7)
167         pSeq = &PAC5XXX_ADC->AS1R7;
168     
169     return pSeq->VAL;
170 }
.fi
.PP
References PAC5XXX_ADC, and PAC5XXX_ADCRESULT_Type::VAL\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_as1_sequence_config (int seq_num, \fBADCCTL_ADMUX_Type\fP mux_select, \fBASSEQ_MSPI_Type\fP emux_control, uint8_t emux_data, \fBASSEQ_DELAY_Type\fP seq_delay)"

.PP
This function configures the given sequence number for the ASC1 unit\&. 
.PP
\fBParameters\fP
.RS 4
\fIseq_num\fP The sequence number to configure 
.br
\fImux_select\fP When to change the EMUX from the \fIASSEQ_MSPI_Type\fP 
.br
\fIemux_control\fP The EMUX control to use for the given sequence from \fIADC_EMUX_CTL_Type\fP 
.br
\fIemux_data\fP The EMUX data to send for the given sequence 
.br
\fIseq_delay\fP The delay to apply for the given sequence from \fIADCCTLX_DELAY_Type\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Non-zero if sequence complete 
.RE
.PP

.PP
Referenced by config_seq_foc()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_config (\fBADCCTL_ADMODE_Type\fP adc_mode, \fBADCCTL_CLKDIV_Type\fP clock_divider, int repeat)"

.PP
This function configures the ADC\&. 
.PP
\fBParameters\fP
.RS 4
\fIadc_mode\fP The ADC mode from \fIADCCTL_MODE\fP 
.br
\fIclock_divider\fP Clock divider for the ADC clock 
.br
\fIrepeat\fP Set to 1 to perform repeated conversions of the selected channel 
.RE
.PP
\fBReturns\fP
.RS 4
none
.RE
.PP
\fBNote\fP
.RS 4
This function does not enable the ADC 
.RE
.PP

.PP
Definition at line 20 of file pac5xxx_driver_adc_config\&.c\&.
.PP
.nf
21 {
22     PAC5XXX_ADC->ADCCTL\&.ADCMODE = adc_mode;
23     PAC5XXX_ADC->ADCCTL\&.ADCDIV = clock_divider;
24     PAC5XXX_ADC->ADCCTL\&.ADCREPEAT = repeat;
25 }
.fi
.PP
References PAC5XXX_ADC\&.
.PP
Referenced by config_seq_foc()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_config_emux_io (void)"

.PP
This function configures the EMUX IO ports on the device for EMUX output\&. 
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 26 of file pac5xxx_driver_adc_emux\&.c\&.
.PP
.nf
27 {
28   PAC5XXX_GPIOB->PSEL\&.P5 = 1;
29   PAC5XXX_GPIOB->PSEL\&.P6 = 1;
30 }
.fi
.PP
References PAC5XXX_GPIOB\&.
.PP
Referenced by configure_adc_emux_engine()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_config_io (uint8_t channel_mask)"

.PP
This function configures the IO ports on the device for the given ADC channels\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel_mask\fP Bit-mask of the ADC channels to enable or disable IOs for 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Referenced by configure_adc_emux_engine()\&.
.SS "\fBRAMFUNC_ADC\fP void pac5xxx_adc_emux_config (\fBADC_EMUX_CTL_Type\fP control_type, \fBADC_EMUX_DIV_Type\fP divider)"

.PP
This function configures the ADC's external MUX\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrol_type\fP Type of external mux control 
.br
\fIdivider\fP External MUX clock divider 
.RE
.PP
\fBReturns\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 20 of file pac5xxx_driver_adc_emux\&.c\&.
.PP
.nf
21 {
22     PAC5XXX_ADC->EMUXCTL\&.EMUXC = control_type;
23     PAC5XXX_ADC->EMUXCTL\&.EMUXDIV = divider;
24 }
.fi
.PP
References PAC5XXX_ADC\&.
.PP
Referenced by configure_adc_emux_engine()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
