PAC5XXX_Driver_System
NAME
PAC5XXX_Driver_System - PAC5XXX System and Clock Controller Driver Functions
SYNOPSIS
Macros
#define RAMFUNC_SYSTEM
Functions
RAMFUNC_SYSTEM void pac5xxx_sys_ccs_config (CCSCTL_CLKIN_Type clock_select, CCSCTL_ACLKDIV_Type aclk_div, CCSCTL_HCLKDIV_Type fclk_div)
This function configures the PAC5XXX clock control system.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config_dividers (uint8_t input_div, uint16_t feedback_div, uint8_t output_div)
This function configures the PAC5XXX PLL dividers.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_enable (int delay)
This function enables the PAC5XXX PLL.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config_100mhz (CCSCTL_HCLKDIV_Type fclk_div, CCSCTL_ACLKDIV_Type aclk_div)
This function configures and enables the PLL for a 100MHz output.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config (int frequency_mhz)
This function configures and enables the PLL with the given frequency output.
void pac_recovery (void)
void pac_delay_asm (uint32_t counts)
Detailed Description
Macro Definition Documentation
#define RAMFUNC_SYSTEM
Definition at line 32 of file pac5xxx_driver_system.h.
Function Documentation
RAMFUNC_SYSTEM void pac5xxx_sys_ccs_config (CCSCTL_CLKIN_Type clock_select, CCSCTL_ACLKDIV_Type aclk_div, CCSCTL_HCLKDIV_Type fclk_div)
This function configures the PAC5XXX clock control system.
Parameters
clock_select The input clock select for FRCLK
aclk_div The ACLK divider
fclk_div The FCLK divider
Returns
none
Definition at line 20 of file pac5xxx_driver_system_ccs_config.c.
{
    PAC5XXX_SYSCTL->CCSCTL.CLKIN = clock_select;
    PAC5XXX_SYSCTL->CCSCTL.ACLKDIV = aclk_div;
    PAC5XXX_SYSCTL->CCSCTL.HCLKDIV = fclk_div;
}
References PAC5XXX_SYSCTL.
Referenced by init_system().
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config (int frequency_mhz)
This function configures and enables the PLL with the given frequency output.
Parameters
frequency_mhz Output frequency in MHz
Note
This function configures and enables the PLL from the internal reference (CLKREF). After the 500us wait time (for the PLL to lock), the FCLK output is switched from CLKREF to the PLL output.
Definition at line 21 of file pac5xxx_driver_system_pll_config_mhz.c.
{
    // Switch to the CLKREF input from internal oscillator, Configure FCLK /2, ACLK /1
    PAC5XXX_SYSCTL->CCSCTL.CLKIN = CCSCTL_CLKIN_CLKREF;
    // Turn off internal oscillator, we don't need it anymore
    pac5xxx_sys_osc_disable();
    // Enable PLL (carefully)
    //
    // PLLOUT = PLLIN * (PLLFD / (PLLID * PLLOD * 2))
    // Constraints:
    // - PLLFD: 2-514
    // - PLLID: 2-34
    // - PLLOD: 0-16
    //
    // Configure PLL dividers: IN /2 [min], FDBK 100, OUT /1 [min]
    // should be PLLOUT at 100MHz: 4MHz * (100 / (2 * 100 * 2))
    pac5xxx_sys_pll_config_dividers(PLLCTL_INPUT_DIV(2), PLLCTL_FDBK_DIV(frequency_mhz), PLLCTL_OUTPUT_DIV(1));
    // SysTick is configured to use the reference clock (FRCLK)
    // The STCLK is CLKREF / 3, or 4MHz / 3 = 1.333MHz or 0.75us/tick. So to get a delay of 500us,
    // you need a count value of 500 / 0.75 = 666
    pac5xxx_sys_pll_enable(666);
    // Now we can switch to the PLLCLK for the ACLK and FCLK divider input
    pac5xxx_sys_ccs_pll_select();
}
References CCSCTL_CLKIN_CLKREF, and PAC5XXX_SYSCTL.
Referenced by init_system().
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config_100mhz (CCSCTL_HCLKDIV_Type fclk_div, CCSCTL_ACLKDIV_Type aclk_div)
This function configures and enables the PLL for a 100MHz output.
Parameters
fclk_div HCLK output divider after PLL stage
aclk_div ACLK output divider after PLL stage
Note
This function configures and enables the PLL from the internal reference (CLKREF), with the given HCLK and FCLK dividers. After the 500us wait time (for the PLL to lock), the FCLK output is switched from CLKREF to the PLL output.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_config_dividers (uint8_t input_div, uint16_t feedback_div, uint8_t output_div)
This function configures the PAC5XXX PLL dividers.
Parameters
input_div Input clock divider
feedback_div Feedback divider
output_div Output divider
Returns
none
Definition at line 20 of file pac5xxx_driver_system_pll_config.c.
{
    PAC5XXX_SYSCTL->PLLCTL.PLLINDIV = input_div;
    PAC5XXX_SYSCTL->PLLCTL.PLLFBDIV = feedback_div;
    PAC5XXX_SYSCTL->PLLCTL.PLLOUTDIV = output_div;
}
References PAC5XXX_SYSCTL.
RAMFUNC_SYSTEM void pac5xxx_sys_pll_enable (int delay)
This function enables the PAC5XXX PLL.
Parameters
delay The number of SysTick clocks to delay
Returns
none
Note
The user should make sure that PLL bypass is active, by calling the function: pac5xxx_sys_pll_bypass_enable() before calling this function.
There is a mandatory 500us delay after the PLL is enabled before it is stable and ready to use. This function will enforce the passed in delay after it enables the PLL before it returns control to the user. At that point, the user may remove the PLL bypass by calling pac5xxx_sys_pll_bypass_disable(). This time delay is enforced by polling the SysTick timer.
Definition at line 27 of file pac5xxx_driver_system_pll_config.c.
{
  
  // Configure SysTick the number of SysTick clock ticks passed into this function.
  SysTick->LOAD = delay;
  SysTick->VAL = 0;
    
  // Enable PLL
  PAC5XXX_SYSCTL->PLLCTL.PLLEN = 1;
  
  // Enable SysTick timer countdown and set the clock to reference clock
  SysTick->CTRL |= SysTick_CTRL_ENABLE_Msk;
  
  // Wait until it reaches 0 and then return
  while ((SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk) == 0);
  
  
}
References PAC5XXX_SYSCTL, SysTick, SysTick_CTRL_COUNTFLAG_Msk, and SysTick_CTRL_ENABLE_Msk.
void pac_delay_asm (uint32_t counts)
Referenced by pac_recovery().
void pac_recovery (void)
Definition at line 42 of file pac5xxx_driver_system_ccs_config.c.
{
    volatile uint32_t i;
    uint32_t perform_delay = 1;
    // PE2 is already an input, just need to Enable Pull Up
    PAC5XXX_GPIOE->PU.P2 = 1; // Enable Pull Up
    // If PE2 is high a delay is not needed
    // Must check over the length of a full UART packet at 115kbps (78uS) in case UART is talking and making PE2 low for short durations
    for (i=0; i < 12; i++) // Value of 12 = at least 140 uS, which is enough for 1 UART packet
    {
        // If PE2 is high at any time, then a delay is not needed
        if (PAC5XXX_GPIOE->IN.P2 == 1)
        {
            perform_delay = 0;
        }
    }
    // If PE2 was low, delay required, add 6 second delay
    if(perform_delay)
    {
        pac_delay_asm(1400000);
    }
    // Restore PE2 to reset state
    PAC5XXX_GPIOE->PU.P2 = 0; // Disable Pull Up
}
References PAC5XXX_GPIOE, and pac_delay_asm().
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.