.TH "PAC5XXX_GPIO_TypeDef" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAC5XXX_GPIO_TypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac5xxx_GPIO\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBOUT\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBOUTEN\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBDS\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBPU\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBPD\fP"
.br
.ti -1c
.RI "\fB__I\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBIN\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBINE\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PSEL_TypeDef\fP \fBPSEL\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBINTP\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBINTE\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBINTF\fP"
.br
.ti -1c
.RI "\fB__IO\fP \fBPAC5XXX_GPIO_PINS_TypeDef\fP \fBINTM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 116 of file pac5xxx_GPIO\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
