PAC5XXX_Driver_Tile
NAME
PAC5XXX_Driver_Tile - PAC5XXX Tile Driver Functions
SYNOPSIS
Macros
#define RAMFUNC_TILE
Functions
RAMFUNC_TILE void pac5xxx_tile_socbridge_config (int enable, int int_enable)
This function configures the device for configuration with the Analog tiles via SOC Bridge.
RAMFUNC_TILE void pac5xxx_tile_register_write (uint8_t address, uint8_t data)
This function writes a tile register.
RAMFUNC_TILE uint8_t pac5xxx_tile_register_read (uint8_t address)
This function reads a tile register via polling.
RAMFUNC_TILE int pac5xxx_tile_register_write_validate (uint8_t address, uint8_t data)
This function writes the given data to the given tile address register, and then reads back the value.
RAMFUNC_TILE void pac5xxx_tile_register_write_burst (uint8_t start_address, int num_bytes, uint8_t *data)
This function writes a burst of data to the given register addresses via polling.
RAMFUNC_TILE int pac5xxx_tile_register_read_burst (uint8_t start_address, int num_bytes, uint8_t *data)
This function reads a burst of data starting from the given register address via polling.
Detailed Description
Macro Definition Documentation
#define RAMFUNC_TILE
Definition at line 31 of file pac5xxx_driver_tile.h.
Function Documentation
RAMFUNC_TILE uint8_t pac5xxx_tile_register_read (uint8_t address)
This function reads a tile register via polling.
Parameters
address Register address to read from
Returns
Data read from register
Definition at line 35 of file pac5xxx_driver_tile_socbridge.c.
{
    uint8_t data;
    // Write the Address to be read; R/W =0 and data is don't care
    // Format: Addr(15:9) | R/W(8) | Data(7:0)
    PAC5XXX_SOCBRIDGE->SOCBD.w = address << 9;
    // Wait for transmission to be complete
    while (!PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE);
    PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE = 0x1;
    // Read the data
    data = PAC5XXX_SOCBRIDGE->SOCBD.w;
    // Return read data
    return data;
}
References PAC5XXX_SOCBRIDGE.
Referenced by config_seq_foc(), and pac5xxx_tile_register_write_validate().
RAMFUNC_TILE int pac5xxx_tile_register_read_burst (uint8_t start_address, int num_bytes, uint8_t * data)
This function reads a burst of data starting from the given register address via polling.
Parameters
start_address Starting address to read from
num_bytes Number of register reads to perform
data Pointer to returned read data
Returns
0: success; non-zero: failure
Definition at line 40 of file pac5xxx_driver_tile_socbridge_burst.c.
{
    int i;
    int addr = start_address;
    uint8_t *pData = data;
    for (i = 0; i < num_bytes; i++, addr++, pData++)
    {
        // Write the Address to be read; R/W =0 and data is don't care
        // Format: Addr(15:9) | R/W(8) | Data(7:0)
        PAC5XXX_SOCBRIDGE->SOCBD.w = addr << 9;
        // Wait for transmission to be complete
        while (!PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE);
        PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE = 0x1;
        // Read the data
        *pData = PAC5XXX_SOCBRIDGE->SOCBD.w;
    }
    // Return read data
    return 1;
}
References PAC5XXX_SOCBRIDGE.
RAMFUNC_TILE void pac5xxx_tile_register_write (uint8_t address, uint8_t data)
This function writes a tile register.
Parameters
address Register address to write
data Data to write
Returns
0: success, non-zero: failure
Note
The user must configure interrupts for the SOC Bridge interface after calling this function and is responsible for registering the Cortex interrupts and providing the interrupt handlers.
Definition at line 22 of file pac5xxx_driver_tile_socbridge.c.
{
    // Write 16-bits containing Addr, R/W=1, Data
    // Format: Addr(15:9) | R/W(8) | Data(7:0)
    PAC5XXX_SOCBRIDGE->SOCBD.w = (address << 9) | (1 << 8) | data;
    // Wait for transmission to be complete
    while (!PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE);
    PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE = 0x1;
}
References PAC5XXX_SOCBRIDGE.
Referenced by config_seq_foc(), init_diff_amp_gain(), init_emux(), and pac5xxx_tile_register_write_validate().
RAMFUNC_TILE void pac5xxx_tile_register_write_burst (uint8_t start_address, int num_bytes, uint8_t * data)
This function writes a burst of data to the given register addresses via polling.
Parameters
start_address Address to start writing from
num_bytes Number of register writes to perform
data Pointer to array of data to write to each register
Returns
0: success; non-zero: failure
Definition at line 21 of file pac5xxx_driver_tile_socbridge_burst.c.
{
    int i;
    int addr = start_address;
    uint8_t *pData = data;
    for (i = 0; i < num_bytes; i++, addr++, pData++)
    {
        // Write 16-bits containing Addr, R/W=1, Data
        // Format: Addr(15:9) | R/W(8) | Data(7:0)
        PAC5XXX_SOCBRIDGE->SOCBD.w = (addr << 9) | (1 << 8) | *pData;
        // Wait for transmission to be complete
        while (!PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE);
        PAC5XXX_SOCBRIDGE->SOCBSTAT.CYC_DONE = 0x1;
    }
}
References PAC5XXX_SOCBRIDGE.
RAMFUNC_TILE int pac5xxx_tile_register_write_validate (uint8_t address, uint8_t data)
This function writes the given data to the given tile address register, and then reads back the value.
Parameters
address Register address to write to
data 8b register data to write
Returns
returns zero if read-back matches write data, non-zero if mis-match
Definition at line 21 of file pac5xxx_driver_tile_socbridge_validate.c.
{
    pac5xxx_tile_register_write(address, data);
    if (pac5xxx_tile_register_read(address) != data)
        return 1;
    return 0;
}
References pac5xxx_tile_register_read(), and pac5xxx_tile_register_write().
RAMFUNC_TILE void pac5xxx_tile_socbridge_config (int enable, int int_enable)
This function configures the device for configuration with the Analog tiles via SOC Bridge.
Parameters
enable Set to 1 to enable SOC Bridge
int_enable Set to 1 to enable interrupts for SOC bridge
Returns
none
Definition at line 21 of file pac5xxx_driver_tile_socbridge_config.c.
{
      // Configure SOC Bridge
      pac5xxx_socbridge_config(enable, int_enable); // Enabled
      pac5xxx_socbridge_config_chip_select(1, // CS setup time (clock cycles from assertion of chip select to first assertion of clock)
                                           1, // CS hold time (clock cycles from last assertion of clock to de-assertion of chip select)
                                           5); // CS wait time (clock cycles between back to back transfers of data)
      pac5xxx_socbridge_config_io(); // Enable SPI IOs
}
References pac5xxx_socbridge_config(), pac5xxx_socbridge_config_chip_select(), and pac5xxx_socbridge_config_io().
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.