.TH "pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_socbridge.h" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_drivers/pac5xxx_driver_socbridge.h \- Firmware driver for the PAC5XXX SOC Bridge\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pac52XX\&.h'\fP
.br
\fC#include 'pac5xxx_driver_config\&.h'\fP
.br
\fC#include 'pac5xxx_driver_gpio\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAMFUNC_SOCBRIDGE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config\fP (int enable, int int_enable)"
.br
.RI "This function configures and enables the SOC bridge\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config_chip_select\fP (uint8_t cs_setup, uint8_t cs_hold, uint8_t cs_wait)"
.br
.RI "This function configures the behavior of the SOC bridge chip select signal\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_config_io\fP (void)"
.br
.RI "This function configures the IO ports on the device for SOC bridge operation\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_int_enable\fP (int enable)"
.br
.RI "This function configures SOC Bridge interrupts to the given state\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_int_enable_RDOFL\fP (int enable)"
.br
.RI "This function configures the state of the Read Buffer Overflow (RDOFL) interrupt\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_int_enable_CYC_DONE\fP (int enable)"
.br
.RI "This function configures the state of the Cycle Done (CYC_DONE) interrupt\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP void \fBpac5xxx_socbridge_int_enable_WRUFL\fP (int enable)"
.br
.RI "This function configures the state of the Write Buffer Underflow (WRUFL) interupt\&. "
.ti -1c
.RI "\fBRAMFUNC_SOCBRIDGE\fP uint8_t \fBpac5xxx_socbridge_data_read_8b\fP (uint8_t tx_data)"
.br
.RI "This function reads 8b of data from the SOC Bridge receive register\&. "
.in -1c
.SH "Detailed Description"
.PP 
Firmware driver for the PAC5XXX SOC Bridge\&. 


.PP
\fBNote\fP
.RS 4
Copyright (C) 2015-2019, Qorvo, Inc\&.
.RE
.PP
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC\&.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC\&. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS\&. 
.PP
Definition in file \fBpac5xxx_driver_socbridge\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
