.TH "pac_foc/pac52xx/iar_proj/readme_IMPORTANT_IAR_update.txt" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pac_foc/pac52xx/iar_proj/readme_IMPORTANT_IAR_update.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "The PAC FOC IAR \fBproject\fP can be opened in IAR v8 x as is \fBBut\fP"
.br
.ti -1c
.RI "The PAC FOC IAR \fBproject\fP can be opened in IAR v8 x as is IAR v7 x must be updated with new PAC devices To update any version of IAR v7 or \fBnewer\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "The PAC FOC IAR \fBproject\fP can be opened in IAR v8 x as is But"

.PP
Definition at line 1 of file readme_IMPORTANT_IAR_update\&.txt\&.
.SS "The PAC FOC IAR \fBproject\fP can be opened in IAR v8 x as is IAR v7 x must be updated with new PAC devices To update any version of IAR v7 or newer"

.PP
Definition at line 4 of file readme_IMPORTANT_IAR_update\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
