.TH "RTC_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Type \- Real-Time Clock (RTC)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint32_t \fBRTCCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRTCCDV\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRTCCTR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Real-Time Clock (RTC) 
.PP
Definition at line 246 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
