.TH "sdk_drivers" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdk_drivers \- PAC52xx SDK Driver Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPAC5XXX ADC Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Driver Config\fP"
.br
.ti -1c
.RI "\fBPAC5XXX GPIO Peripheral Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX I2C Peripheral Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Memory Controller Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Real\-Time Clock Driver Functions`\fP"
.br
.ti -1c
.RI "\fBPAC5XXX SOC Bridge Peripheral Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX SPI Peripheral Drviers\fP"
.br
.ti -1c
.RI "\fBPAC5XXX System and Clock Controller Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Tile Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Analog Timer and DTG Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX UART Driver Functions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Watchdog Timer Driver Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
