.TH "sdk_headers" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdk_headers \- PAC2xx SDK Peripheral Headers
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPAC52XX Definitions\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Memory Mapping\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Peripheral Declaration\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Analog to Digital Converter (ADC)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX General\-Purpose IO (GPIO)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX I2C Controller (I2C)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX FLASH Memory Controller (MEMCTL)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Real\-Time Clock (RTC)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX SOC Bridge\fP"
.br
.ti -1c
.RI "\fBPAC5XXX SPI Controller (SPI)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX System and Clock Controller (SYSCLKCTL)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Driver Manager Tile\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Power Manager Tile\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Signal Manager Tile\fP"
.br
.ti -1c
.RI "\fBPAC5XXX System Manager Tile\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Timer Capture/Compare/PWM outputs (TIMER8CC)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Timer Capture/Compare/PWM outputs (TIMER4CC)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Timer Capture/Compare/PWM outputs (TIMER2CC)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX UART Controller (UART)\fP"
.br
.ti -1c
.RI "\fBPAC5XXX Watchdog Timer (WDT)\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
