.TH "SOCB_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOCB_Type \- SOC Bus Bridge (SOCB)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__O\fP uint32_t \fBSOCBCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOCBCFG\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [3]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOCBSTAT\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOCBD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSOCBINT_EN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SOC Bus Bridge (SOCB) 
.PP
Definition at line 560 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
