.TH "SPI_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Type \- SPI (SPI)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__O\fP uint32_t \fBSPICTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPICFG\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPICLKDIV\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [2]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPISTAT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPICSSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPID\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSPIINT_EN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SPI (SPI) 
.PP
Definition at line 582 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
