pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_boot_COIDE/startup_pac5xxx_CooCox.c
NAME
pac_foc/pac52xx/pac5xxx_sdk/pac5xxx_boot_COIDE/startup_pac5xxx_CooCox.c - PAC5XXX startup code for CooCox IDE (CoIde)
SYNOPSIS
#include 'pac52XX.h'
#include 'system_pac5xxx.h'
Macros
#define STACK_SIZE 0x000000B0
#define WEAK __attribute__ ((weak))
Functions
void pac_recovery (void)
__attribute__ ((section('.co_stack')))
The minimal vector table for a Cortex M0. Note that the proper constructs must be placed on this to ensure that it ends up at physical address 0x00000000.
 "
void Default_Reset_Handler (void)
This is the code that gets called when the processor first starts execution following a reset event. Only the absolutely necessary set is performed, after which the application supplied main() routine is called.
__attribute__ ((noinline))
Detailed Description
PAC5XXX startup code for CooCox IDE (CoIde)
Note
Copyright (C) 2015-2019, Qorvo, Inc.
THIS SOFTWARE IS SUBJECT TO A SOURCE CODE LICENSE AGREEMENT WHICH PROVIDES, AMONG OTHER THINGS: (i) THAT IT CAN BE USED ONLY TO ADAPT THE LICENSEE'S APPLICATION TO PAC PROCESSORS SUPPLIED BY QORVO, INC.; (ii) THAT IT IS PROVIDED 'AS IS' WITHOUT WARRANTY; (iii) THAT QORVO, INC. IS NOT LIABLE FOR ANY INDIRECT DAMAGES OR FOR DIRECT DAMAGES EXCEEDING US$1,500; AND (iv) THAT IT CAN BE DISCLOSED TO AND USED ONLY BY CERTAIN AUTHORIZED PERSONS.
Definition in file startup_pac5xxx_CooCox.c.
Macro Definition Documentation
#define STACK_SIZE 0x000000B0
Stack size (in Words)
Definition at line 21 of file startup_pac5xxx_CooCox.c.
#define WEAK __attribute__ ((weak))
Function Documentation
__attribute__ ((noinline))
Definition at line 214 of file startup_pac5xxx_CooCox.c.
{
    __ASM
    (
        " push {r1} \n\t"
        " movs r1, #1 \n\t"
        "delay_loop1: \n\t"
        " sub r0,r0,r1 \n\t" // Decrement r0=counts by r1=decrement value
        " bne delay_loop1 \n\t" // Keep looping until counts == 0
        " pop {r1} \n\t"
    );
}
__attribute__ ((section('.co_stack')))
The minimal vector table for a Cortex M0. Note that the proper constructs must be placed on this to ensure that it ends up at physical address 0x00000000.
 < The initial stack pointer
< The reset handler
< The NMI handler
< The hard fault handler
< Reserved
< SVCall handler
< Reserved
< The PendSV handler
< The SysTick handler
< Memory controller handler
< unused
< WDT handler
< GPIOA handler
< GPIOB handler
< GPIOC handler
< GPIOD handler
< GPIOE handler
< Timer A handler
< Timer A Extended handler
< Timer B handler
< Timer C handler
< Timer D handler
< ADC handler
< SocBridge handler
< SPI-B handler
< UART handler
< I2C handler
< ADC EMUX handler
< RTC handler
Definition at line 22 of file startup_pac5xxx_CooCox.c.
{
  /*----------Core Exceptions------------------------------------------------ */
  (void *)&pulStack[STACK_SIZE],
  Reset_Handler,
  NMI_Handler,
  HardFault_Handler,
  0,0,0,0,0,0,0,
  SVC_Handler,
  0, 0,
  PendSV_Handler,
  SysTick_Handler,
  /*----------External Exceptions---------------------------------------------*/
  MemCtl_IRQHandler,
  SysClk_IRQHandler,
  Wdt_IRQHandler,
  GpioA_IRQHandler,
  GpioB_IRQHandler,
  GpioC_IRQHandler,
  GpioD_IRQHandler,
  GpioE_IRQHandler,
  TimerA_IRQHandler,
  TimerAExt_IRQHandler,
  TimerB_IRQHandler,
  TimerC_IRQHandler,
  TimerD_IRQHandler,
  ADC_IRQHandler,
  SocBridge_IRQHandler,
  SPIB_IRQHandler,
  UART_IRQHandler,
  I2C_IRQHandler,
  EMUX_IRQHandler,
  RTC_IRQHandler
};
void Default_Reset_Handler (void)
This is the code that gets called when the processor first starts execution following a reset event. Only the absolutely necessary set is performed, after which the application supplied main() routine is called.
Parameters
None
Return values
None
Definition at line 128 of file startup_pac5xxx_CooCox.c.
{
  // Call pac_recovery function to allow recovery of mis-configured device
  pac_recovery();
  /* Initialize data and bss */
  unsigned long *pulSrc, *pulDest;
  /* Copy the data segment initializers from flash to SRAM */
  pulSrc = &_sidata;
  for(pulDest = &_sdata; pulDest < &_edata; )
  {
    *(pulDest++) = *(pulSrc++);
  }
  
  /* Zero fill the bss segment. */
  for(pulDest = &_sbss; pulDest < &_ebss; )
  {
    *(pulDest++) = 0;
  }
    
  /* Call SystemInit for device initialization before letting user have control */
  SystemInit();
  /* Call the application's entry point.*/
  main();
}
References pac_recovery(), and SystemInit().
void pac_recovery (void)
Definition at line 42 of file pac5xxx_driver_system_ccs_config.c.
{
    volatile uint32_t i;
    uint32_t perform_delay = 1;
    // PE2 is already an input, just need to Enable Pull Up
    PAC5XXX_GPIOE->PU.P2 = 1; // Enable Pull Up
    // If PE2 is high a delay is not needed
    // Must check over the length of a full UART packet at 115kbps (78uS) in case UART is talking and making PE2 low for short durations
    for (i=0; i < 12; i++) // Value of 12 = at least 140 uS, which is enough for 1 UART packet
    {
        // If PE2 is high at any time, then a delay is not needed
        if (PAC5XXX_GPIOE->IN.P2 == 1)
        {
            perform_delay = 0;
        }
    }
    // If PE2 was low, delay required, add 6 second delay
    if(perform_delay)
    {
        pac_delay_asm(1400000);
    }
    // Restore PE2 to reset state
    PAC5XXX_GPIOE->PU.P2 = 0; // Disable Pull Up
}
Referenced by Default_Reset_Handler().
Author
Generated automatically by Doxygen for FOC-4.1.2-PAC52XX from the source code.