.TH "TIMERD_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMERD_Type \- Timer D Peripheral (TIMERD)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxPRD\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBTxCTR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [13]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC0CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC0CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC1CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC1CTR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP [20]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGD0CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGD0LED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGD0TED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer D Peripheral (TIMERD) 
.PP
Definition at line 425 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
