.TH "TIMERA_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMERA_Type \- Timer A Peripheral (TIMERA)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxPRD\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBTxCTR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED\fP [13]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC0CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC0CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC1CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC1CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC2CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC2CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC3CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC3CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC4CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC4CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC5CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC5CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC6CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC6CTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC7CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTxCC7CTR\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED1\fP [8]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA0CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA0LED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA0TED\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA1CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA1LED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA1TED\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA2CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA2LED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA2TED\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA3CTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA3LED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDTGA3TED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer A Peripheral (TIMERA) 
.PP
Definition at line 310 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
