.TH "WDT_Type" 3 "Wed Sep 23 2020" "Version 4.1.2" "FOC-4.1.2-PAC52XX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WDT_Type \- Watchdog Timer (WDT)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pac52XX\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__I\fP uint32_t \fBWDTCTL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWDTCDV\fP"
.br
.ti -1c
.RI "\fB__I\fP uint32_t \fBWDTCTR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Watchdog Timer (WDT) 
.PP
Definition at line 230 of file pac52XX\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FOC-4\&.1\&.2-PAC52XX from the source code\&.
